{
 "title": "XTDB Monitoring Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "xtdbnode", "label": "XTDB Node", "query": { "query": "label_values(node_id)" } }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_committed_bytes{area=\"heap\", node_id=\"$xtdbnode\"})",
     "legendFormat": "JVM Heap Used"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{area=\"heap\", node_id=\"$xtdbnode\"})",
     "legendFormat": "JVM Heap Max"
    }
   ]
  },
  { "title": "XTDB - Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Transactions - Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "tx_op_timer_seconds_count{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Transactions - Timer (Max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "tx_op_timer_seconds_max{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Transactions - Timer (Quantiles)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "tx_op_timer_seconds{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} - {{quantile}} quantile"
    }
   ]
  },
  { "title": "XTDB - Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Query - Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "query_timer_seconds_count{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Query - Timer (Max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "query_timer_seconds_max{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Query - Timer",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "query_timer_seconds{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} - {{quantile}} quantile"
    }
   ]
  },
  { "title": "XTDB - JVM Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "JVM - Heap Usage (Average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by(node_id) (jvm_memory_committed_bytes{node_id=\"$xtdbnode\"})",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "JVM - Heap Usage (Max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by(node_id) (jvm_memory_committed_bytes{node_id=\"$xtdbnode\"})",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "JVM - Buffer Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(node_id) (jvm_buffer_memory_used_bytes{node_id=\"$xtdbnode\"})",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "JVM - Live Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "JVM - Thread States",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "jvm_threads_states_threads{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} - {{state}}"
    }
   ]
  },
  { "title": "XTDB - Direct Allocated Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "XTDB - Buffer Pool Allocated Memory",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "memorycache_evictableBytes_bytes{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} evictable bytes"
    },
    {
     "expr": "memorycache_freeBytes_bytes{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} free bytes"
    },
    {
     "expr": "memorycache_pinnedBytes_bytes{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} pinned bytes"
    }
   ]
  },
  {
   "title": "XTDB - Compactor Allocated Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "compactor_allocator_allocated_memory_bytes{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "XTDB - Indexer Allocated Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "indexer_allocator_allocated_memory_bytes{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "XTDB - Live Index Allocated Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "live_index_allocator_allocated_memory_bytes{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "XTDB - Log Watcher Allocated Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "watcher_allocator_allocated_memory_bytes{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  }
 ]
}