#!/bin/bash -ex

DOCKER_REPO=${DOCKER_REPO}
NAMESPACE=${NAMESPACE:-juxt}
STUB_DEP_VERSION=${STUB_DEP_VERSION:-0}
BUILD_VERSION=${BUILD_VERSION:-0}
CONTAINER=${DOCKER_REPO}${NAMESPACE}
LATEST=${1:false}
BUILDS=("standalone-demo-with-volume")
