---
title: XTQL Transactions (Clojure)
---

Transactions in XTDB are submitted to the link:/ops/config/log[log], to be processed asynchronously.
They each consist of an array of link:#tx-ops[operations].

This document provides examples for EDN transaction operations, to be submitted to link:/drivers/clojure/codox/xtdb.api.html#var-execute-tx[`xt/execute-tx`] or link:/drivers/clojure/codox/xtdb.api.html#var-submit-tx[`xt/submit-tx`].

[#tx-ops]
== Transaction operations

=== `put-docs`

Upserts documents into the given table, optionally during the given valid time period.

[source,clojure]
----
[:put-docs
 ;; -- required

 ;; options map
 ;; * can just provide `<table>` rather than a map if there are
 ;;   no other options
 {;; -- required

  ;; table to put docs into (keyword)
  :into <table>

  ;; --optional

  ;; valid-from, valid-to can be `java.util.Date`, `java.time.Instant`
  ;; or `java.time.ZonedDateTime`
  :valid-from #inst "..."
  :valid-to #inst "..."
  }

 ;; -- required
 ;; documents to submit (variadic, 0..n)
 ;; * each must contain `:xt/id`
 & <docs>
 ]
----

==== Examples

* single document
+
[source,clojure]
----
[:put-docs :my-table {:xt/id :foo}]
----
* with options
+
[source,clojure]
----
[:put-docs {:into :my-table, :valid-from #inst "2024-01-01"}
 {:xt/id :foo, ...}
 {:xt/id :bar, ...}]
----
* dynamically generated
+
[source,clojure]
----
(into [:put-docs {:into :my-table, ...}]
      (->> (range 100)
           (map (fn [n]
                  {:xt/id n, :n-str (str n)}))))
----

=== `patch-docs`

Upserts documents into the given table, merging them with any existing documents, optionally during the given valid time period.

Documents are currently merged at the granularity of individual keys - e.g. if a key is present in the patch document, it will override the same key in the database document; if a key is absent or null, the key from the document already in the database will be preserved.

[source,clojure]
----
[:patch-docs
 ;; -- required

 ;; options map
 ;; * can just provide `<table>` rather than a map if there are
 ;;   no other options
 {;; -- required

  ;; table to patch docs into (keyword)
  :into <table>

  ;; --optional

  ;; valid-from, valid-to can be `java.util.Date`, `java.time.Instant`
  ;; or `java.time.ZonedDateTime`
  :valid-from #inst "..."
  :valid-to #inst "..."
  }

 ;; -- required
 ;; documents to submit (variadic, 0..n)
 ;; * each must contain `:xt/id`
 & <docs>
 ]
----

==== Examples

* single document
+
[source,clojure]
----
[:put-docs :my-table {:xt/id :foo, :a 1}]
[:patch-docs :my-table {:xt/id :foo, :b 2}]

;; => {:xt/id :foo, :a 1, :b 2}
----
* with options
+
[source,clojure]
----
[:patch-docs {:into :my-table, :valid-from #inst "2024-01-01"}
 {:xt/id :foo, ...}
 {:xt/id :bar, ...}]
----
* dynamically generated
+
[source,clojure]
----
(into [:patch-docs {:into :my-table, ...}]
      (->> (range 100)
           (map (fn [n]
                  {:xt/id n, :n-str (str n)}))))
----

[#delete-docs]
=== `delete-docs`

Deletes documents from the given table, optionally during the given valid time period.
The default valid time behaviour is the same as link:#_put_docs[put], above.

[source,clojure]
----
[:delete-docs
 ;; -- required

 ;; options map
 ;; * can just provide `<table>` rather than a map if there are no other options
 {;; -- required

  ;; table to delete docs from
  :from <table>

  ;; --optional

  ;; valid-from, valid-to can be `java.util.Date`, `java.time.Instant` or `java.time.ZonedDateTime`
  :valid-from #inst "..."
  :valid-to #inst "..."
  }

 ;; -- required
 ;; document ids to delete (variadic, 0..n)
 & <ids>
 ]
----

Examples:

* single document
+
[source,clojure]
----
[:delete-docs :my-table :foo]
----
* with options
+
[source,clojure]
----
[:delete-docs {:from :my-table, :valid-from #inst "2024-01-01"}
 :foo :bar ...]
----
* dynamically generated
+
[source,clojure]
----
(into [:delete-docs {:from :my-table, ...}]
      (range 100))
----


[#erase-docs]
=== `erase-docs`

Irrevocably erases documents from the given table (including through system time), for all valid-time.

[source,clojure]
----
[:erase-docs
 ;; -- required

 ;; table to erase documents from
 <table>

 ;; document ids to erase (variadic, 0..n)
 & <ids>
 ]
----

Examples:

* single document
+
[source,clojure]
----
[:erase-docs :my-table :foo]
----
* dynamically generated
+
[source,clojure]
----
(into [:erase-docs :my-table] (range 100))
----

== Transaction options

Transaction options are an optional map of the following keys:

[source,clojure]
----
{;; -- optional
 :system-time #inst "2024-01-01"
 :default-tz #xt/zone "America/Los_Angeles"}
----
