---
title: XTQL Transactions
---
:examples: ../src/test/resources/docs/xtql_dml_json_examples.yaml
:clojure: /drivers/clojure/txs
:kotlin: /drivers/kotlin/kdoc/xtdb-api/xtdb.api.tx
:icon: /images/icons

Transactions in XTDB are submitted to the link:/config/tx-log[transaction log], to be processed asynchronously.
They each consist of an array of link:#tx-ops[operations].

[.lang-icons.right]
image:{icon}/clojure.svg[Clojure,link={clojure}]
image:{icon}/kotlin.svg[Kotlin,link=/drivers/kotlin/kdoc/xtdb-api/xtdb.api/-i-xtdb/submit-tx.html]

For details about how transactions are submitted, see your individual client language documentation:


[#tx-ops]
== Transaction operations

[.lang-icons.right]
image:{icon}/clojure.svg[Clojure,link={clojure}#_put_docs]
image:{icon}/kotlin.svg[Kotlin,link={kotlin}/-tx-ops/put-docs.html]

=== `putDocs`

Upserts documents into the given table, optionally during the given valid time period.

[source,json]
----
include::{examples}[tags=put-docs-json,indent=0]
----

[.lang-icons.right]
image:{icon}/clojure.svg[Clojure,link={clojure}#delete-docs]
image:{icon}/kotlin.svg[Kotlin,link={kotlin}/-tx-ops/delete-docs.html]

[#delete-docs]
=== `deleteDocs`

Deletes documents from the given table, optionally during the given valid time period.
The default valid time behaviour is the same as link:#_put_docs[put], above.

[source,json]
----
include::{examples}[tags=delete-docs-json,indent=0]
----

[.lang-icons.right]
image:{icon}/clojure.svg[Clojure,link={clojure}#erase-docs]
image:{icon}/kotlin.svg[Kotlin,link={kotlin}/-tx-ops/erase-docs.html]

[#erase-docs]
=== `eraseDocs`


Irrevocably erases documents from the given table (including through system time), for all valid-time.

[source,json]
----
include::{examples}[tags=erase-docs-json,indent=0]
----

[.lang-icons.right]
image:{icon}/clojure.svg[Clojure,link={clojure}#_insert_into]
image:{icon}/kotlin.svg[Kotlin,link={kotlin}/-tx-ops/insert.html]

=== `insertInto`

Inserts documents into a table from the given link:./queries[query].

[source,json]
----
include::{examples}[tags=insert-into-json,indent=0]
----

Example:

* copy from another table:
+
[source,sql]
----
INSERT INTO users
SELECT _id, first_name AS given_name, last_name AS family_name FROM old_users
----
+
[source,json]
----
include::{examples}[tags=insert-into-json-ex1,indent=0]
----

[.lang-icons.right]
image:{icon}/clojure.svg[Clojure,link={clojure}#_update]
image:{icon}/kotlin.svg[Kotlin,link={kotlin}/-tx-ops/update.html]

=== `update`


Updates documents in a given table based on the provided query.

[source,json]
----
include::{examples}[tags=update-json,indent=0]
----

Example:

* Increment a version for a user account, by email:
+
[source,sql]
----
UPDATE users
SET version = version + 1
WHERE email = ?

-- with argument 'james@example.com'
----
+
[source,json]
----
include::{examples}[tags=update-json-ex1,indent=0]
----

See also:

* link:./queries#_temporal_filter[Temporal filters]
* link:./queries#_binding_specs[Binding specs]
* link:./queries#_expressions[Expressions]
* link:./queries#_unify[Unify]
* link:./queries#_argument_specs[Argument specs]


[.lang-icons.right]
image:{icon}/clojure.svg[Clojure,link={clojure}#_delete]
image:{icon}/kotlin.svg[Kotlin,link={kotlin}/-tx-ops/delete.html]

=== `delete`


Deletes documents from the given table, based on the provided query.

[source,json]
----
include::{examples}[tags=delete-json,indent=0]
----

See also:

* link:./queries#_temporal_filter[Temporal filters]
* link:./queries#_binding_specs[Binding specs]
* link:./queries#_expressions[Expressions]
* link:./queries#_unify[Unify]
* link:./queries#_argument_specs[Argument specs]

Examples:

* `DELETE FROM users WHERE email = 'james@example.com'`
+
--
[source,json]
----
include::{examples}[tags=delete-json-ex1,indent=0]
----
--
+
* Deleting using a sub-query
+
--
[source,sql]
----
DELETE FROM users
WHERE author_id IN (SELECT author_id FROM authors WHERE email = 'james@example.com'
----

[source,json]
----
include::{examples}[tags=delete-json-ex2,indent=0]
----
--

[.lang-icons.right]
image:{icon}/clojure.svg[Clojure,link={clojure}#_erase]
image:{icon}/kotlin.svg[Kotlin,link={kotlin}/-tx-ops/erase.html]

=== `erase`

Irrevocably erase the document from the given table (for all valid-time, for all system-time), based on the provided query.

[source,json]
----
include::{examples}[tags=erase-json,indent=0]
----

See also:

* link:./queries#_binding_specs[Binding specs]
* link:./queries#_expressions[Expressions]
* link:./queries#_unify[Unify]
* link:./queries#_argument_specs[Argument specs]

Examples:

* erase by email:
+
[source,sql]
----
ERASE FROM users WHERE email = ?

-- 'james@example.com' supplied separately as an argument
----
+
--
[source,json]
----
include::{examples}[tags=erase-json-ex1,indent=0]
----
--
+
* erasing using a sub-query:
+
--
[source,sql]
----
ERASE FROM users
WHERE author_id IN (SELECT author_id FROM authors WHERE email = ?)

-- 'james@example.com' supplied separately as an argument
----

[source,json]
----
include::{examples}[tags=erase-json-ex2,indent=0]
----
--

[.lang-icons.right]
image:{icon}/clojure.svg[Clojure,link={clojure}#asserts]
image:{icon}/kotlin.svg[Kotlin,link={kotlin}/-tx-ops/assert-exists.html]

[#asserts]
=== Asserts: `assertExists`, `assertNotExists`

Within a transaction, `assertExists`/`assertNotExists` operations assert that the given query returns at least one row/no rows respectively - if not, the transaction will roll back.

[source,json]
----
include::{examples}[tags=assert-json,indent=0]
----

[.lang-icons.right]
image:{icon}/clojure.svg[Clojure,link={clojure}#_call]
image:{icon}/kotlin.svg[Kotlin,link={kotlin}/-tx-ops/call.html]

=== `call`

Call a transaction function.

[source,json]
----
{
  // -- required
  // function to call
  fnId: "fn-id",

  // -- optional
  // list of arguments to the function
  // args: [ ... ]
}
----

Transaction functions can currently only be defined in link:/config/clojure/txs.adoc#_call[Clojure].


[.lang-icons.right]
image:{icon}/clojure.svg[Clojure,link={clojure}#_transaction_options]
image:{icon}/kotlin.svg[Kotlin,link={kotlin}/-tx-options/index.html]

== Transaction options

Transaction options are an optional map of the following keys:

[source,json]
----
{
  // -- optional

  // overrides system-time for the transaction
  // * mustn't be earlier than any previous system time
  "systemTime": "2024-01-01T00:00:00Z",

  // overrides the default time zone for operations in the transaction.
  // default: "UTC"
  "defaultTz": "America/Los_Angeles",

  // whether to default to "all valid-time" if not explicitly specified in the query
  // default: false
  "defaultAllValidTime": false,
}
----
