= SQL Transactions

XTDB 2.x is a schemaless document database.
There is no DDL and you can add any record without static table definitions.


[#gotchas]
== Gotchas

Before discussing basic transactions, it's worth reading about XTDB 2.x's
xref:getting-started::gotchas.adoc["gotchas"].


[#insert]
== INSERT / UPSERT

For now, `INSERT` behaves like `UPSERT`.
You are permitted to run the following statement twice in a row and the second will not be rejected.
By default, `SELECT` will query across all of `VALID_TIME`, so you will see two rows returned as well.

[source,sql]
----
INSERT INTO users (xt$id, name) VALUES (1234, 'Matt');
----

NOTE: If `INSERT` is altered to prevent repeated execution against the same `id`, a true `UPSERT` statement may be added to duplicate this behaviour. However, `UPSERT` (and `REPLACE`) are not a part of the SQL Specification.

=== Async

The result of `INSERT` statement might be surprising:

[source,sh]
----
INSERT 0 0
----

This is because XTDB is asynchronous.
Your data has reached the Transaction Log but isn't fully committed to the Object Store yet.

=== Time-Travel

By default, an `INSERT` occurs "as of now".
Inserted data can be forced to live in the past or future by setting `xt$valid_from` and/or `xt$valid_to`:

[source,sql]
----
INSERT INTO users (xt$id, name, xt$valid_from)
  VALUES (5678, 'Kath', DATE '2027-01-06');
----


[#update]
== UPDATE

By default, updates only affect an entity on the `SYSTEM_TIME` and `VALID_TIME` timelines from the point in time when the `UPDATE` statement occurred.

[source,sh]
----
UPDATE users SET name='James' WHERE users.id=1234;
----

Be aware that the `WHERE` clause requires fully-qualified columns, like `SELECT`.

////
Updates can be forced to occur in the past or future by setting `XT$VALID_FROM` and/or `XT$VALID_TO`:
[source,sh]
----
UPDATE users SET name='James', xt$valid_from=DATE '1998-01-05' WHERE users.id=1234;
----
////


[#delete]
== DELETE

[source,sh]
----
DELETE FROM users WHERE users.id=1234;
----


[#erase]
== ERASE

Because XTDB is immutable, it requires a method of _erasure_.
Unlike `DELETE`, when a record is erased it is not just hidden from that point in the timeline, onward.
And erased record is completely removed from disk.
`ERASE` should be used sparingly, to comply with international laws like
the EU's https://gdpr.eu/[GDPR] and Canada's
https://laws-lois.justice.gc.ca/eng/acts/P-8.6/[PIPEDA].

[source,sh]
----
ERASE FROM users WHERE users.id=1234;
----


[#readwrite-mode]
== `READ WRITE` Mode

XTDB is an asynchronous database.
By default, XTDB is in `READ ONLY` mode.
To commit a transaction, it must enter `READ WRITE` mode:

[source,sql]
----
START TRANSACTION READ WRITE;
-- your DML here
COMMIT;
----

DML statements (`INSERT`, `UPDATE`, etc.),
will be wrapped in a `READ WRITE` transaction automatically.


[#objectsandarrays]
== Objects and Arrays

Nested data is supported in the form of objects and arrays.

=== Objects

Construct an Object with `OBJECT`:

[source,sql]
----
INSERT INTO posts (xt$id, text, social)
  VALUES (444, 'XTDB has nested data!',
          OBJECT ('twitter': '@xtdb_com', 'visible': true));
SELECT posts.social FROM posts;
----

For convenience, `OBJECT` has a shorthand literal syntax:

[source,sql]
----
INSERT INTO posts (xt$id, text, social)
  VALUES (555, 'XTDB has object literals!',
          {'twitter': '@xtdb_com', 'visible': true});
SELECT posts.social FROM posts;
----

=== Arrays

Construct an Array with `ARRAY`:

[source,sql]
----
INSERT INTO toots (xt$id, text, likes)
  VALUES (777, 'Did you know XTDB has arrays?',
          ARRAY ['Kath', 'Joe', 'Holly']);
SELECT toots.likes from toots;
----

For convenience, the `ARRAY` keyword can be elided for the shorthand literal syntax:

[source,sql]
----
INSERT INTO toots (xt$id, text, likes)
  VALUES (888, 'Did you know XTDB has array literals?',
          ['Kath', 'Joe', 'Holly']);
SELECT toots.likes[1] from toots;
----

=== Deep Nesting

Deeper nesting is permitted. Arrays and Objects can be combined. For example:

[source,sql]
----
INSERT INTO toots_deep (xt$id, text, likes)
  VALUES (999, 'Did you know XTDB supports deep nesting?',
          [{'name': 'Kath', 'count': 5},
           {'name': 'Joe', 'count': 10},
           {'name': 'Holly', 'count': 3}]);
SELECT toots_deep.likes from toots_deep;
----
