= SQL Queries

[#gotchas]
== Gotchas

Before discussing basic queries, it's worth reading about XTDB 2.x's
xref:getting-started::gotchas.adoc["gotchas"].


[#select]
== Basic SELECT

Columns must be fully qualified, such as `users.name`:

[source,sql]
----
INSERT INTO users (id, name) VALUES (1234, 'Matt');
SELECT users.name FROM users;
----

returns:

[source,text]
----
 name
-------
 "Matt"
(1 row)
----


[#joins]
== Joins

Joins in XTDB are ad-hoc.
Foreign keys are not required and any table can join on any other table, as long as their columns contain the same value.

[source,sql]
----
INSERT INTO posts (id, user_id, text)
  VALUES (1234, 5678, 'Hello World!');
INSERT INTO posts (id, user_id, text)
  VALUES (2345, 5678, 'Summer Reading: George Copeland');

INSERT INTO people (id, name, friends)
  VALUES (5678, 'Sarah',
          [{'user': 'Dan'},
           {'user': 'Kath'}]);

SELECT posts.text, people.name
  FROM posts JOIN people ON posts.user_id = people.id;
----


[#arrowtable]
== ARROW_TABLE

Queries can access correctly-formatted Apache Arrow files directly from the web.

[source,sql]
----
INSERT INTO users (id, post_id, name) VALUES (555, 'foo1', 'Jamie');

SELECT more_posts.id, more_posts.text, users.name
  FROM ARROW_TABLE('https://xtdb.com/more_posts.arrow')
  AS more_posts JOIN users ON more_posts.id = users.post_id;
----

NOTE: `ARROW_TABLE` is not permitted in DML (`INSERT`, `UPDATE`, etc.)
because transactions in XTDB must be deterministic.
Determinism is broken if the contents of the external `.arrow` file change.


[#typeequality]
== Type Equality

=== Numeric Types

For now, numerics are equal if they are equal in Clojure.
See https://github.com/xtdb/core2/issues/214[Issue #214] for an example of an exception to this rule.

=== Strings and Byte Arrays

Equality cannot be compared between a String and a Byte Array.

=== Dates and Timestamps

Dates/Timestamps are equal as per the SQL:2011 specification.
Dates/Timestamps without a TZ are assumed to be the TZ of the session before being compared.

If you have a copy of the ISO/ANSI SQL:2011 specification
(_Information technology — Database languages — SQL — Part 2: Foundation (SQL/Foundation)_),
you will find a helpful table on Page 37 (_Table 3 — Datetime data type conversions_).

NOTE: For simplicity, we _highly_ recommend writing date/time data as Timestamps with a UTC Timezone whenever possible.


== Type Casts

=== Numeric Types

Most numeric types will cast as expected

Type casts are a work-in-progress, but most numeric-to-numeric casts will work as expected.
Casts between numerics and non-numeric types may not work yet.

[source,sql]
----
INSERT INTO t1 (id) VALUES (1);
SELECT (2 + CAST(3.0 AS INT)) FROM t1; -- returns 5
SELECT (2 + CAST("3" AS INT)) FROM t1; -- fails as of 2022-09-16
----

=== Dates and Timestamps

Similar to date/time type equality, Dates/Timestamps without a TZ are assumed to be the TZ of the session before being compared.


== 3-Value Logic

In SQL, `UNKNOWN` is a legal value for `BOOLEAN` data types, which results in "3-value logic".
The other two values available are, naturally, `TRUE`, and `FALSE`.

Booleans can be combined with the `AND`, `OR`, `NOT`, and `IS` keywords. Rather than equality checks,
SQL booleans are compared with `IS`:

[source,sql]
----
SELECT t1.a FROM t1 WHERE t1.a IS NOT NULL;
----


== Math

=== Overflow

Overflow is strictly checked. Internally, this is implemented with
https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Math.html[`*Exact()` methods from `java.lang.Math`].

=== BigDecimal

`BigDecimal` is not yet supported.
