= SQL Time Queries

In addition to this documentation, there are a number of
https://github.com/xtdb/core2-playground/blob/main/bitemporal/snodgrass-99.sql[examples in the `core2-playground` repo].

[#enhancedsql2011]
== Enhanced SQL:2011

XTDB defaults to SQL:2011 behaviour but alternative temporal defaults are offered.
The following command will switch XTDB's Application Time semantics to "as of now",
which will feel more natural to most users.

[source,sql]
----
SET APPLICATION_TIME_DEFAULTS TO AS_OF_NOW;
----

With "as of now" Application Time semantics, the following inserted record is only visible
when time-travelling (`FOR APPLICATION_TIME AS OF`) to the year 2027 or when viewing the
entire timeline at once (`FOR ALL APPLICATION_TIME`):

[source,sql]
----
INSERT INTO posts (xt$id, user_id, text, application_time_start)
  VALUES (9012, 5678, 'Happy 2027!', DATE '2027-01-01');

-- data from 2027 is not visible by default
SELECT posts.text FROM posts;

SELECT posts.text FROM posts
  FOR APPLICATION_TIME AS OF DATE '2027-01-02';

-- data from 2027 becomes visible when viewing the entire timeline
SELECT posts.text FROM posts
  FOR ALL APPLICATION_TIME;
----


[#isosql2011]
== ISO SQL:2011

Although XTDB defaults to SQL:2011 behaviour, you can explicitly set this behaviour
to switch away from the "as of now" defaults, if you've set them:

[source,sql]
----
SET APPLICATION_TIME_DEFAULTS TO ISO_STANDARD;
----

When XTDB is in ISO Standard mode, queries will return records visible to all of Application Time by default:

[source,sql]
----
INSERT INTO posts (xt$id, user_id, text, application_time_start)
  VALUES (9012, 5678, 'Happy 2027!', DATE '2027-01-01');

-- data from 2027 is visible by default
SELECT posts.text FROM posts;
----


[#troubleshooting]
== Troubleshooting

Particularly while using ISO Standard mode, it is often helpful to orient oneself
by querying all 4 built-in time columns:

[source,sql]
----
SELECT posts.text,
       posts.system_time_start,
       posts.system_time_end,
       posts.application_time_start,
       posts.application_time_end FROM posts;
----


== Table Period Specification Grammar
railroad::query_system_time_period_specification.html[]


[#timecolumns]
== Time Columns

All tables in XTDB contain the two logical temporal columns.
These "columns" are not real and cannot be queried directly.
Instead, they are `PERIOD`s, comprised of two `TIMESTAMP` columns each.
These four timestamp columns _can_ be inserted into and queried directly.

_System Time_ represents the immutable timeline of data, as it is recorded.
_Application Time_ represents the validity (sometimes called "effectivity") of data
-- it is what allows users to correct data in the past or insert data into the future.

* `SYSTEM_TIME` is comprised of:
** system_time_start
** system_time_end
* `APPLICATION_TIME` is comprised of:
** application_time_start
** application_time_end

[#timetravel]
== Time Travel

XTDB permits point-in-time queries across both timelines.
To time travel, specify an `AS OF` clause with a `DATE` or `TIMESTAMP` suffix.

=== `FOR SYSTEM_TIME AS OF`

For point-in-time queries on the System Timeline:

[source,sql]
----
INSERT INTO posts (xt$id,title)
  VALUES (99,'That Time I Attended RubyConf 2005');

SELECT posts.title FROM posts
  FOR SYSTEM_TIME AS OF DATE '2022-09-20';
----

=== `FOR APPLICATION_TIME AS OF`

For point-in-time queries on the Application Timeline:

[source,sql]
----
INSERT INTO posts (xt$id,title,application_time_start)
  VALUES (199,'That Time I Attended Strange Loop 2022',
          DATE '2025-09-21');

SELECT posts.title FROM posts
  FOR APPLICATION_TIME AS OF DATE '2025-09-21';
----


[#ignoringtime]
== Ignoring Time

You can temporarily suspend point-in-time queries by querying the entire timeline at once:

=== `FOR ALL SYSTEM_TIME`

[source,sql]
----
SELECT posts.title FROM posts
  FOR ALL SYSTEM_TIME;
----

=== `FOR ALL APPLICATION_TIME`

[source,sql]
----
SELECT posts.title FROM posts
  FOR ALL APPLICATION_TIME;
----

=== Ignore the entire timeplane

[source,sql]
----
SELECT posts.title FROM posts
  FOR ALL SYSTEM_TIME
  FOR ALL APPLICATION_TIME;
----


[#periods]
== Periods

A period is not a reified data type -- in the sense that you cannot insert it into a column -- but
periods are essential for _Temporal Predicates_. To create a `PERIOD`:

[source,sql]
----
PERIOD(start_time, end_time)
----

SQL Periods have _closed-open semantics_.
The `start_time` is inclusive.
The `end_time` includes all time up-to-but-not-including that time.


[#temporalpredicates]
== Temporal Predicates

Records on the System Timeline and Application Timeline exist as time ranges.
_Temporal Predicates_ are SQL:2011 operators which bear close resemblance to
https://en.wikipedia.org/wiki/Allen%27s_interval_algebra#Relations[Allens' Interval Relations].

=== `CONTAINS`

`x CONTAINS y` returns `TRUE` if x contains every time point in y,
i.e., if xs ≤ ys and xe ≥ ye.

In the case where `y` is a DateTime value expression (`DATE` or `TIMESTAMP`),
`x CONTAINS y` returns `TRUE` if x contains y, i.e., if xs ≤ y and xe > y.

[source,sql]
----
INSERT INTO posts (xt$id,title)
  VALUES (99,'That Time I Attended RubyConf 2005');

SELECT posts.title FROM posts
  WHERE posts.SYSTEM_TIME
  CONTAINS PERIOD(DATE '2027-01-01', DATE '2028-01-01');
----

=== `OVERLAPS`

`x OVERLAPS y` returns `TRUE` if the two periods have at least one time point in common,
i.e, if xs < ye and xe > ys.

[source,sql]
----
INSERT INTO posts (xt$id,title,application_time_start)
  VALUES (299,'Overlapping',DATE '2027-01-01');

SELECT posts.title FROM posts
  WHERE posts.APPLICATION_TIME
  OVERLAPS PERIOD(DATE '2026-01-01', DATE '2027-01-02');
----

=== `EQUALS`

`x EQUALS y` returns `TRUE` if the two periods have every time point in common,
i.e., if `xs = ys` and `xe = ye`.

[source,sql]
----
INSERT INTO posts (xt$id,title,application_time_start,application_time_end)
  VALUES (399,'Equals?',DATE '2027-01-01',DATE '2027-01-02');

SELECT posts.title FROM posts
  WHERE posts.APPLICATION_TIME
  EQUALS PERIOD(DATE '2027-01-01', DATE '2027-01-02');
----

=== `PRECEDES`

`x PRECEDES y` returns `TRUE` if the end value of x is less than or equal to the start value of y,
i.e., if xe ≤ ys.

[source,sql]
----
INSERT INTO posts (xt$id,title,application_time_start,application_time_end)
  VALUES (499,'Precedes?',DATE '2007-01-01',DATE '2007-01-02');

SELECT posts.title FROM posts
  WHERE posts.APPLICATION_TIME
  PRECEDES PERIOD(DATE '2007-01-03', DATE '2026-12-31');
----

=== `SUCCEEDS`

`x SUCCEEDS y` returns `TRUE` if the start value of x is greater than or equal to the end value of y,
i.e., if xs ≥ ye.

[source,sql]
----
INSERT INTO posts (xt$id,title,application_time_start,application_time_end)
  VALUES (599,'Succeeds?',DATE '2037-01-01',DATE '2037-01-02');

SELECT posts.title FROM posts
  WHERE posts.APPLICATION_TIME
  SUCCEEDS PERIOD(DATE '2036-12-30', DATE '2036-12-31');
----

=== `IMMEDIATELY PRECEDES`

`x IMMEDIATELY PRECEDES y` returns `TRUE` if the end value of x is equal to the start value
of y, i.e., if xe = ys.

[source,sql]
----
INSERT INTO posts (xt$id,title,application_time_start,application_time_end)
  VALUES (699,'Immediately Precedes?',DATE '2007-01-01',
          TIMESTAMP '2007-01-02 12:34:56');

SELECT posts.title FROM posts
  WHERE posts.APPLICATION_TIME
  IMMEDIATELY PRECEDES PERIOD(TIMESTAMP '2007-01-02 12:34:56', DATE '2026-12-31');
----

=== `IMMEDIATELY SUCCEEDS`

`x IMMEDIATELY SUCCEEDS y` returns `TRUE` if the start value of x is equal to the end value
of y, i.e., if xs = ye.

[source,sql]
----
INSERT INTO posts (xt$id,title,application_time_start,application_time_end)
  VALUES (799,'Immediately Succeeds?',TIMESTAMP '2036-12-31 12:34:56',
          DATE '2037-01-02');

SELECT posts.title FROM posts
  WHERE posts.APPLICATION_TIME
  IMMEDIATELY SUCCEEDS PERIOD(DATE '2036-12-30',
                              TIMESTAMP '2036-12-31 12:34:56');
----


[#automaticsplitting]
== Automatic (Application) Time Period Splitting

Whenever an `UPDATE` or `DELETE` operation is performed on an existing record,
the old Application Time is "split".

[source,sql]
----
INSERT INTO posts (xt$id,title,application_time_start)
  VALUES (899,'Will I be split?',DATE '1997-02-02');

UPDATE posts
  FOR PORTION OF APPLICATION_TIME
  FROM DATE '1998-01-20' TO DATE '1999-01-30'
  SET title='Split!';

SELECT posts.title,
       posts.system_time_start,
       posts.system_time_end,
       posts.application_time_start,
       posts.application_time_end
       FROM posts
       FOR ALL APPLICATION_TIME;
----


[#endoftime]
== End of Time

For convenience, XTDB adds the reserved word `END_OF_TIME` which can be used in place of
a hard-coded end-of-time value. It can be used like so:

[source,sql]
----
INSERT INTO posts (xt$id,title,application_time_start)
  VALUES (999,'Delete from 1995 to the end of time?',DATE '1990-02-02');

DELETE FROM posts
  FOR PORTION OF APPLICATION_TIME
  FROM DATE '1995-01-01' TO END_OF_TIME
  WHERE posts.xt$id= 999;

SELECT posts.title,
       posts.system_time_start,
       posts.system_time_end,
       posts.application_time_start,
       posts.application_time_end
       FROM posts
       FOR ALL APPLICATION_TIME;
----


[#inspectthetimeline]
== Inspect The Timeline

Whether you are in `AS_OF_NOW` or `ISO_STANDARD` mode, you can inspect the entire timeline.

To inspect all of System Time:

[source,sql]
----
SELECT posts.title,
       posts.system_time_start,
       posts.system_time_end,
       posts.application_time_start,
       posts.application_time_end
       FROM posts
       FOR ALL SYSTEM_TIME;
----

To inspect all of Application Time:

[source,sql]
----
SELECT posts.title,
       posts.system_time_start,
       posts.system_time_end,
       posts.application_time_start,
       posts.application_time_end
       FROM posts
       FOR ALL APPLICATION_TIME;
----

These two clauses can be combined to inspect the entire time plane (both timelines):

[source,sql]
----
SELECT posts.title,
       posts.system_time_start,
       posts.system_time_end,
       posts.application_time_start,
       posts.application_time_end
       FROM posts
       FOR ALL SYSTEM_TIME
       FOR ALL APPLICATION_TIME;
----


[#patterns]
== Temporal Data Patterns

=== Move a record into the past/future

To retroactively "move" a record into the past or future, use the "upsert" functionality of the `INSERT` statement:

[source,sql]
----
INSERT INTO products (xt$id,name,application_time_start)
  VALUES (1,'iPhone',DATE '2009-01-01');
SELECT products.name,products.application_time_start
  FROM products; -- returns 2009

INSERT INTO products (xt$id,name,application_time_start)
  VALUES (1,'iPhone',DATE '2007-06-29');
SELECT products.name,products.application_time_start
  FROM products; -- returns correct 2007 date
----

It is not possible to use an `UPDATE` statement to change a record's `APPLICATION_TIME`.

=== Change a record for a portion of (its) time

`UPDATE ... FOR PORTION OF APPLICATION_TIME` can be used for exactly this purpose:

[source,sql]
----
INSERT INTO employee (xt$id, name, title, application_time_start)
  VALUES (4, 'Deepa', 'Developer', DATE '2013-07-31');

UPDATE employee FOR PORTION OF APPLICATION_TIME
  FROM DATE '2018-01-01' TO DATE '2021-01-01'
  SET title = 'CEO'
  WHERE employee.xt$id= 4;

SELECT employee.title, employee.application_time_start
  FROM employee FOR ALL APPLICATION_TIME
  WHERE employee.id=4;
----
