[#about]
= About Crux

[#about-team]
== Team

See our https://github.com/juxt/crux/graphs/contributors[contributors].

[#about-support]
== Support

Please contact us if you would like to discuss your support requirements: crux@juxt.pro

[#about-hosting]
=== Managed Hosting

JUXT offers a Managed Hosting service for Crux to accelerate your
development and provide you with a secure and reliable service.

[#about-software]
=== Software

JUXT currently offers bespoke support packages for Crux with SLAs that can be customised to meet your requirements.

[#about-reseller]
=== Reseller

Are you looking to implement Crux as part of a solution for your client(s)? JUXT can provide Software Support and Managed Hosting on your behalf. Please consider joining our reseller program.

[#about-deployment]
=== Deployment

Engage JUXT for Deployment Services Support if you need help with the initial process of installing and configuring Crux in your environment.

[#about-contributing]
== Contributing

include::contributing.adoc[leveloffset=+1]

[#about-releases]
=== Releases

For technical changes, see the https://github.com/juxt/crux/blob/master/CHANGELOG.md[Changelog].

include::faq.adoc[leveloffset=+1]
