= About Crux
:toc: macro

toc::[]

[#team]
== Team

See our https://github.com/juxt/crux/graphs/contributors[contributors].

[#support]
== Support

Please contact us if you would like to discuss your support requirements: crux@juxt.pro

[#hosting]
=== Managed Hosting

JUXT offers a Managed Hosting service for Crux to accelerate your
development and provide you with a secure and reliable service.

[#software]
=== Software

JUXT currently offers bespoke support packages for Crux with SLAs that can be customised to meet your requirements.

[#reseller]
=== Reseller

Are you looking to implement Crux as part of a solution for your client(s)? JUXT can provide Software Support and Managed Hosting on your behalf. Please consider joining our reseller program.

[#about-deployment]
=== Deployment

Engage JUXT for Deployment Services Support if you need help with the initial process of installing and configuring Crux in your environment.

[#contributing]
== Contributing

include::contributing.adoc[leveloffset=+1]

[#releases]
== Releases

For technical changes, see the https://github.com/juxt/crux/blob/master/CHANGELOG.md[Changelog].

[#faqs]
include::faq.adoc[leveloffset=+1]
