AWSTemplateFormatVersion: '2010-09-09'

Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: 'crux-soak'

Outputs:
  FargateContainerSecurityGroup:
    Value: !Ref 'ECRRepository'
