/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.8.1/userguide/building_java_projects.html
 */

group = "juxt"
version = "0.1.0-SNAPSHOT"

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    id("dev.clojurephant.clojure") version "0.6.0-beta.1"
}

repositories {
    // Use JCenter for resolving dependencies.
    jcenter()
    maven { name = "Clojars"; url = uri("https://repo.clojars.org") }
}

dependencies {
    implementation("org.clojure", "clojure", "1.10.2")
    implementation("org.clojure", "tools.logging", "1.1.0")
    implementation("org.apache.arrow", "arrow-vector", "3.0.0")
    implementation("org.apache.arrow", "arrow-memory-netty", "3.0.0")
    implementation("org.roaringbitmap", "RoaringBitmap", "0.9.3")

    testImplementation("org.clojure", "data.csv", "1.0.0")

    devImplementation("nrepl", "nrepl", "0.6.0")
    devImplementation("cider:cider-nrepl:0.25.2")
}

sourceSets {
    main {
        resources.srcDir("src")
        resources.srcDir("data")
    }
    test {
        resources.srcDir("test")
    }
}

tasks.test {
    // Use junit platform for unit tests.
    useJUnitPlatform()
}

tasks.clojureRepl {
    handler.set("cider.nrepl/cider-nrepl-handler")
}
