= XTDB "core2" Research

== Prerequisites

You will need either JDK 11 or 17 installed.


== Installing

For now, "installation" consists of creating a very tiny Clojure
program and requiring `core2` as a dependency. You will need to
create a directory with a structure like the following:

[source]
----
.
├── deps.edn
└── src
    └── xtexample.clj
----

`deps.edn` defines your server's dependency on `core2` and allows
you to execute your tiny Clojure program. `src/xtexample.clj` is
explained under _Running_.

[source,clojure,title='deps.edn']
----
{:aliases
 {:run {:exec-fn xtexample/run
        ;; needed on JDK16+ to allow Netty/Arrow access DirectBuffer internals:
        :jvm-opts ["--add-opens=java.base/java.nio=ALL-UNNAMED"
                   "-Dio.netty.tryReflectionSetAccessible=true"]}}

 :deps
 {com.xtdb.labs/core2-core
  {:git/url "ssh://git@github.com/xtdb/core2"
   ;; update this to the latest SHA:
   :git/sha "28ea1ee464101aa49432a57a222f58baf46c76ad"
   :deps/root "core"}}}

;; duplicate for other modules, setting their `:deps/root`.
;; S3/JDBC/Kafka etc are under `"modules/*"`
----

* Run `clojure -X:deps prep` in your directory
* When you bump the version (sha), re-run it with
  `clojure -X:deps prep :force true`


== Running

`src/xtexample.clj` creates an in-memory core2 node, exposes a Postgres
wire protocol endpoint, and adds a few sample records for you to query.

[source,clojure,title='src/xtexample.clj']
----
(ns xtexample
  (:require [core2.api :as c2]
            [core2.node :as node]
            [core2.sql.pgwire :as pgwire]))

(def node (node/start-node {}))

(def server (pgwire/serve node))

;; TODO: remove this when we have basic DML
(defn add-sample-txs []
  (let [tx (c2/submit-tx node [[:put {:id (random-uuid) :name "James"}]
                               [:put {:id (random-uuid) :name "Matt"}]
                               [:put {:id (random-uuid) :name "Dan"}]])]
    (println "Sample transaction sent:\n\n" (deref tx))))

(defn run [opts]
  (println "XTDB started.")
  (add-sample-txs)
  (read-line))
----

[source,sh]
----
clj -X:run
----


== Developing Core2

Core2 is a mono-repo -- we develop it from the root directory of the git repository.

* First time: `./bin/prep.sh`
* `./bin/re-prep.sh` to re-run `javac` if you change Java classes
* Start and connect to a REPL at the top-level of the project - this starts a REPL with all of the modules available.
+
For Emacs/CIDER:
* grab the `:lib/kaocha` and `:repl/cider-refactor` aliases from https://github.com/practicalli/clojure-deps-edn/blob/live/deps.edn[John's deps.edn]
* then `./bin/cider.sh`, and `cider-connect-clj` (`, s c j` in Spacemacs)

* `(dev)`
* `(go)`
* `node` is then bound to a started node, using `dev/dev-node` as a persistent data directory

Linting:
* `clojure -Xlint` - runs clojure-lsp's `diagnostics`.
* `clojure -Xlint :namespace '[core2.foo]'` - same, for given namespaces.

=== Links

* https://github.com/xtdb/core2/projects/1[Kanban board]
* https://app.circleci.com/pipelines/github/xtdb/core2[Continuous Integration (CircleCI)]
* link:bibliography.org[bibliography.org] - a list of light bedtime reading.

=== Testing

* Test all with `clj -X:core2:test`; `clj -X:core2:integration-test` for longer tests
* Some tests have external dependencies which require `docker-compose`:
  * `docker-compose up` (`docker-compose up <postgres|kafka>` etc for individual containers),
  * `clojure -X:jdbc-test` / `clojure -X:kafka-test`
  * `docker-compose down`

=== Profiling

To attach YourKit:

* Install YourKit (it's on the AUR, for Arch folks)
* Add an alias to `~/.clojure/deps.edn`:
+
[source,clojure]
----
{:aliases {:yourkit {:jvm-opts ["-agentpath:/opt/yourkit/bin/linux-x86-64/libyjpagent.so"]}}}
----
* `clj -A:yourkit -M:repl/cider`


== Building / Deploying

=== CircleCI

. Fork this repo
. 'Follow' the project on your https://app.circleci.com/dashboard[CircleCI dashboard]

At the moment (until #295), you'll need to create a `slack-bot` context:

. Your dashboard -> org settings (for your 'personal org') -> contexts -> create context `slack-bot`
. add env var `SLACK_ACCESS_TOKEN`: `<ask James>`

I regret using contexts - this is a pain.
In my defense, I thought a context could be shared between forks, but apparently it can only be shared between projects in the same org.

=== Maven Central

TODO: migrate from Lein

Core2 artifacts are deployed to Maven Central.

* To deploy a `dev-SNAPSHOT` release, `./lein-sub deploy`
* To deploy a release, `CORE2_VERSION=<version> ./lein-sub do install, deploy`, then head to the https://oss.sonatype.org/[Nexus UI] to close/release it.

=== Uberjar

* `clojure -Xuberjar` => `target/core2-standalone.jar`
* `java -jar target/core2-standalone.jar [--help]`

=== Docker

==== Building a local image for testing

* Make sure your Docker daemon is running
* `./bin/docker-build.sh [--clean]` will build and tag as `core2:latest`, and load it into your images list. The `--clean` flag can be used to ensure the core2 uberjar is rebuilt.
* To run: `docker run -p 5432:5432 core2` (with no `xtdb/` organization prefix)

==== Building and pushing a multi-arch image to dockerhub

Pushing core2 images requires a login to docker with permission to push to the xtdb docker hub org, ask @refset or @jarohen if you do not have this.

* install https://github.com/docker/buildx[buildx] if it is not already (docker desktop, recent docker versions have it bundled). This will enable multi-arch builds support.
* `docker buildx install` to https://github.com/docker/buildx#set-buildx-as-the-default-builder[set buildx as your default Docker builder]
* `./bin/docker-build-and-push.sh [--clean] [--latest]` will build and push the image as `xtdb/core2:"$sha"` as well as `xtdb/core2:latest` if `--latest` is supplied.

As with a local build, the `--clean` flag can ensure a the core2 uberjar is built afresh.

==== Troubleshooting

If you get an error on build like this:

[source,text]
----
error: multiple platforms feature is currently not supported for docker driver. Please switch to a different driver (eg. "docker buildx create --use")
----

You may have to create and switch to a builder using the `docker-container` buildx driver:

[source,shell]
----
# you only need to run this once to configure buildx:
docker buildx create --name mybuilder --driver=docker-container --use
# then re-run:
./bin/docker-build-and-push.sh --clean --latest
----

See also this https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/[blog from docker] and https://cloudolife.com/2022/03/05/Infrastructure-as-Code-IaC/Container/Docker/Docker-buildx-support-multiple-architectures-images/[this tutorial] for more details on multi-arch builds with buildx.

If you try to push to Docker Hub without credentials configured, you will see:

[source,text]
----
error: failed to solve: server message: insufficient_scope: authorization failed
----

* Make sure you have an account on https://hub.docker.com
* Ask @refset or @jarohen to add your account to the `xtdb` organization
* Log in with `docker login` (interactive) to save your credentials locally


== Arrow Fork

We maintain a fork of [Arrow](https://github.com/apache/arrow) to fix a couple of issues in `DenseUnionVector` - see [this diff](https://github.com/apache/arrow/compare/master...juxt:master) for more details.

To upgrade Arrow:

* Usual bump in `project.clj`
* Clone the [Arrow repo](https://github.com/apache/arrow), add the [JUXT fork](https://github.com/juxt/arrow) as a remote.
* Rebase `juxt/master` on the upstream tag.
* In Core2, `./bin/rebuild-forked-arrow-files.sh`
* Test
* Push (`--force-with-lease`) to JUXT fork, and commit to Core2.
