= XTDB "core2" Research

== Prerequisites

You will need either JDK 11 or 17 installed.


== Installing

For now, "installation" consists of creating a very tiny Clojure
program and requiring `core2` as a dependency. You will need to
create a directory with a structure like the following:

[source]
----
.
├── deps.edn
└── src
    └── xtexample.clj
----

`deps.edn` defines your server's dependency on `core2` and allows
you to execute your tiny Clojure program. `src/xtexample.clj` is
explained under _Running_.

[source,clojure,title='deps.edn']
----
{:aliases
 {:run {:exec-fn xtexample/run
        ;; needed on JDK16+ to allow Netty/Arrow access DirectBuffer internals:
        :jvm-opts ["--add-opens=java.base/java.nio=ALL-UNNAMED"
                   "-Dio.netty.tryReflectionSetAccessible=true"]}}

 :deps
 {com.xtdb.labs/core2-core
  {:git/url "ssh://git@github.com/xtdb/core2"
   ;; update this to the latest SHA:
   :git/sha "28ea1ee464101aa49432a57a222f58baf46c76ad"
   :deps/root "core"}

  ;; TODO: users shouldn't have to specify this manually
  com.widdindustries/time-literals {:mvn/version "0.1.6"}}}

;; duplicate for other modules, setting their `:deps/root`.
;; S3/JDBC/Kafka etc are under `"modules/*"`
----

* Run `clojure -X:deps prep` in your directory
* When you bump the version (sha), re-run it with
  `clojure -X:deps prep :force true`


== Running

`src/xtexample.clj` creates an in-memory core2 node, exposes a Postgres
wire protocol endpoint, and adds a few sample records for you to query.

[source,clojure,title='src/xtexample.clj']
----
(ns xtexample
  (:require [core2.api :as c2]
            [core2.local-node :as local-node]
            [core2.sql.pgwire :as pgwire]))

(def node (local-node/start-node {}))

(def server (pgwire/serve node))

;; TODO: remove this when we have basic DML
(defn add-sample-txs []
  (let [tx (c2/submit-tx node [[:put {:_id (random-uuid) :name "James"}]
                               [:put {:_id (random-uuid) :name "Matt"}]
                               [:put {:_id (random-uuid) :name "Dan"}]])]
    (println "Sample transaction sent:\n\n" (deref tx))))

(defn run [opts]
  (println "XTDB started.")
  (add-sample-txs)
  (read-line))
----

[source,sh]
----
clj -X:run
----


== Developing Core2

Core2 is a mono-repo -- we develop it from the root directory of the git repository.

* First time: `./bin/prep.sh`
* `./bin/re-prep.sh` to re-run `javac` if you change Java classes
* Start and connect to a REPL at the top-level of the project - this starts a REPL with all of the modules available.
+
For Emacs/CIDER:
* grab the `:lib/kaocha` and `:repl/cider-refactor` aliases from https://github.com/practicalli/clojure-deps-edn/blob/live/deps.edn[John's deps.edn]
* then `./bin/cider.sh`, and `cider-connect-clj` (`, s c j` in Spacemacs)

* `(dev)`
* `(go)`
* `node` is then bound to a started node, using `dev/dev-node` as a persistent data directory

Linting:
* `clojure -Xlint` - runs clojure-lsp's `diagnostics`.
* `clojure -Xlint :namespace '[core2.foo]'` - same, for given namespaces.

=== Links

* https://github.com/xtdb/core2/projects/1[Kanban board]
* https://app.circleci.com/pipelines/github/xtdb/core2[Continuous Integration (CircleCI)]
* link:bibliography.org[bibliography.org] - a list of light bedtime reading.

=== Testing

* Test all with `clj -X:core2:test`; `clj -X:core2:integration-test` for longer tests
* Some tests have external dependencies which require `docker-compose`:
  * `docker-compose up` (`docker-compose up <postgres|kafka>` etc for individual containers),
  * `clojure -X:jdbc-test` / `clojure -X:kafka-test`
  * `docker-compose down`

=== Profiling

To attach YourKit:

* Install YourKit (it's on the AUR, for Arch folks)
* Add an alias to `~/.clojure/deps.edn`:
+
[source,clojure]
----
{:aliases {:yourkit {:jvm-opts ["-agentpath:/opt/yourkit/bin/linux-x86-64/libyjpagent.so"]}}}
----
* `clj -A:yourkit -M:repl/cider`


== Building / Deploying

=== Maven Central

TODO: migrate from Lein

Core2 artifacts are deployed to Maven Central.

* To deploy a `dev-SNAPSHOT` release, `./lein-sub deploy`
* To deploy a release, `CORE2_VERSION=<version> ./lein-sub do install, deploy`, then head to the https://oss.sonatype.org/[Nexus UI] to close/release it.

=== Uberjar

* `clojure -Xuberjar` => `target/core2-standalone.jar`
* `java -jar target/core2-standalone.jar [--help]`

=== Docker

Requires a login to docker with push perms to the xtdb org.

* `./bin/build-docker.sh [--clean]` will build and tag as `xtdb/core2:latest`
* `docker push
* `CORE2_VERSION=<version> ./bin/build-docker.sh` to tag as a different version.

== Arrow Fork

We maintain a fork of [Arrow](https://github.com/apache/arrow) to fix a couple of issues in `DenseUnionVector` - see [this diff](https://github.com/apache/arrow/compare/master...juxt:master) for more details.

To upgrade Arrow:

* Usual bump in `project.clj`
* Clone the [Arrow repo](https://github.com/apache/arrow), add the [JUXT fork](https://github.com/juxt/arrow) as a remote.
* Rebase `juxt/master` on the upstream tag.
* In Core2, `./bin/rebuild-forked-arrow-files.sh`
* Test
* Push (`--force-with-lease`) to JUXT fork, and commit to Core2.
