= core2

== Install

[source,clojure]
----
;; deps.edn
{:deps {com.xtdb.labs/core2-core
        {:git/url "ssh://git@github.com/xtdb/core2",
         :git/sha "<sha>"
         :deps/root "core"}}}

;; duplicate for other modules, setting their `:deps/root`.
;; S3/JDBC/Kafka etc are under `"modules/*"`
----

* First time: `clojure -X:deps prep`
* When you bump the version: `clojure -X:deps prep :force true`

==  Usage - differences to XTDB 1.x

=== Architecture

Where XTDB 1.x has a transaction log, document store and query indices, Core2 has a transaction log and an object store.

* XTDB 1.x transactions are split up into 'tx-events' and documents, with the former going on the tx-log and the latter to the doc-store.
  In Core2, the transaction log doesn't need to have infinite retention, so we no longer need this split - transactions go straight on to the log, and the document store is obsolete.
* Rather than each node having its own query indices, Core2 shares these between nodes in a cluster via the object store.
  The object store is hence _the_ golden store, thanks to the transience of the transaction log.
* The files stored in the object store are in https://arrow.apache.org/[Apache Arrow] format, the structure of which Core2 takes responsibility for maintaining - we no longer require a KV store.

[cols="1,2*^"]
|===
| | Transaction Log | Object Store

| AWS S3 | | ✓
| Azure Blobs | | (soon)
| Google Cloud Storage | | (soon)
| FileSystem | ✓ | ✓
| Kafka | ✓ | ✗
| JDBC | (soon) | ✓
| In-memory | ✓ | ✓
| LMDB (KV) | ✗ | ✗
| RocksDB (KV) | ✗ | ✗
|===


=== Setup

Main require: `[core2.api :as c2]`

Configuration uses https://github.com/weavejester/integrant[Integrant].

You can still start a completely in-memory node using `(core2.local-node/start-node {})`.
For a Kafka/JDBC node:

[source,clojure]
----
(with-open [node (node/start-node {:core2.kafka/log {:bootstrap-servers "localhost:9092"}

                                   :core2.jdbc.postgres/dialect {}
                                   :core2.jdbc/default-pool {:db-spec {:user "postgres"
                                                                       :password "postgres"
                                                                       :database "core2test"}}
                                   :core2.jdbc/object-store {}})]
  ;; ...
  )
----

The CLI parameters, and EDN/JSON configuration file formats are the same as XTDB 1.x.

=== Transactions

Transactions are slightly different to XTDB 1.x:

- `[:xtdb.api/put <doc>]` -> `[:put <doc>]`. Put and delete supported thus far.
- `:xt/id` -> `:_id`. Valid ID types currently strings, numbers, dates.
- `c2/submit-tx` returns `CompletableFuture`, deref it to get the transaction details.

=== Datalog Queries
In a similar manner to `next.jdbc`[https://github.com/seancorfield/next-jdbc], execute Datalog queries in Core2 using `c2/plan-datalog-query`.
This returns a reducible sequence that you can pass to (say) `reduce`, `into` or `run!`.
When finalised (by `reduce`) this will ensure the query results are adequately closed.

[source,clojure]
----
(with-open [node (node/start-node {})]
  (->> (c2/plan-datalog-query node
                              '{:find [?e ?name]
                                :where [[?e :name ?name]]})
       (into [])))
----

These queries currently return a vector of maps `[{:e ..., :name ...}, {...}]`, although this is only because it's what was closest to what we had available at the time.

=== SQL queries

Same as Datalog, but use `plan-sql-query` instead.

[source,clojure]
----
(with-open [node (node/start-node {})]
  (->> (c2/plan-sql-query node "SELECT u.name FROM users u")
       (into [])))
----


=== Bases

Core2 doesn't have the concept of DBs - instead, we pass the node and (optionally) a 'basis' to queries.
In Core2, the upper bound for the tx-time is applied per-source; the default upper bound for VT is applied at the query level - this is because each data source has their own tx-time timeline, but VT is assumed to be a single timeline, consistent across data sources.

[source,clojure]
----
;; simple case - use the latest tx the node has available:
(->> (c2/plan-datalog-query node '{...})
     (into []))

;; or, to read your own writes (timeout optional):
;; `plan-datalog-query` will await the transaction
(->> (c2/plan-datalog-query node
                            (-> '{:find ..., :where ...}
                                (assoc :basis {:tx tx}
                                       :basis-timeout (Duration/ofSeconds 1))))
     (into []))
----

The `plan-datalog-query` functions take the node, the query, and then a variable number of params.

[source,clojure]
----
(->> (c2/plan-datalog-query tu/*node*
                            (-> '{:find [?e]
                                  :in [?first-name ?last-name]
                                  :where [[?e :first-name ?first-name]
                                          [?e :last-name ?last-name]]}
                                (assoc :basis {:tx tx}))
                            "Ivan" "Ivanov")
     (into #{}))
----

Unlike Datomic, `$` shouldn't be included in `:in` - if/when we reinstate multiple sources to Datalog queries, I propose we include them as a named map in the basis-opts:

[source,clojure]
----
;; something like this, anyway.
(->> (c2/plan-datalog-query node
                            (-> '{:find [...]
                                  :where [[$db1 ...], [$db2 ...]]}
                                (assoc :basis {'$db1 {:tx tx}
                                               '$db2 {:tx tx}}
                                       :basis-timeout (Duration/ofSeconds 1))))
     (into []))
----

`plan-datalog-query-async` is the same, except it runs entirely asynchronously and returns a `CompletableFuture` of the query plan.
(In fact, `plan-datalog-query` just calls `plan-datalog-query-async` and deref's it.)

The basis map can also contain a `:default-valid-time` option, which applies to any entities that don't specify other valid-time constraints.
This is for repeatable queries - it defaults to 'now' if not provided.

[source,clojure]
----
(->> (c2/plan-datalog-query node
                            (-> '{:find [?e ?name]
                                  :where [[?e :name ?name]]}
                                (assoc :basis {:default-valid-time #inst "..."})))
     (into []))
----

There is also `op/query-ra` which accepts a lower-level relational algebra query - have a look in `core2.logical-plan` for what can go into these plans, and `core2.tpch-queries` for examples.

SQL queries do not currently support bases.

== Developing Core2

Core2 is a mono-repo - we develop it from the root directory of the git repository.

* First time: `./bin/prep.sh`
* `./bin/re-prep.sh` to re-run `javac` if you change Java classes
* Start and connect to a REPL at the top-level of the project - this starts a REPL with all of the modules available.
+
For Emacs/CIDER:
* grab the `:lib/kaocha` and `:repl/cider-refactor` aliases from https://github.com/practicalli/clojure-deps-edn/blob/live/deps.edn[John's deps.edn]
* then `./bin/cider.sh`, and `cider-connect-clj` (`, s c j` in Spacemacs)

* `(dev)`
* `(go)`
* `node` is then bound to a started node, using `dev/dev-node` as a persistent data directory

Linting:
* `clojure -Xlint` - runs clojure-lsp's `diagnostics`.
* `clojure -Xlint :namespace '[core2.foo]'` - same, for given namespaces.

=== Links

* https://github.com/xtdb/core2/projects/1[Kanban board]
* https://app.circleci.com/pipelines/github/xtdb/core2[Continuous Integration (CircleCI)]
* link:bibliography.org[bibliography.org] - a list of light bedtime reading.

=== Testing

* Test all with `clj -X:core2:test`; `clj -X:core2:integration-test` for longer tests
* Some tests have external dependencies which require `docker-compose`:
  * `docker-compose up` (`docker-compose up <postgres|kafka>` etc for individual containers),
  * `clojure -X:jdbc-test` / `clojure -X:kafka-test`
  * `docker-compose down`

=== Profiling

To attach YourKit:

* Install YourKit (it's on the AUR, for Arch folks)
* Add an alias to `~/.clojure/deps.edn`:
+
[source,clojure]
----
{:aliases {:yourkit {:jvm-opts ["-agentpath:/opt/yourkit/bin/linux-x86-64/libyjpagent.so"]}}}
----
* `clj -A:yourkit -M:repl/cider`

=== Building Core2

==== Maven Central

TODO: migrate from Lein

Core2 artifacts are deployed to Maven Central.

* To deploy a `dev-SNAPSHOT` release, `./lein-sub deploy`
* To deploy a release, `CORE2_VERSION=<version> ./lein-sub do install, deploy`, then head to the https://oss.sonatype.org/[Nexus UI] to close/release it.

==== Uberjar

* `clojure -Xuberjar` => `target/core2-standalone.jar`
* `java -jar target/core2-standalone.jar [--help]`

==== Docker

* `./bin/build-docker.sh [--clean]` => `juxt.xtdb-labs/core2:latest`
* `CORE2_VERSION=<version> ./bin/build-docker.sh` to tag as a different version.

== Arrow Fork

We maintain a fork of [Arrow](https://github.com/apache/arrow) to fix a couple of issues in `DenseUnionVector` - see [this diff](https://github.com/apache/arrow/compare/master...juxt:master) for more details.

To upgrade Arrow:

* Usual bump in `project.clj`
* Clone the [Arrow repo](https://github.com/apache/arrow), add the [JUXT fork](https://github.com/juxt/arrow) as a remote.
* Rebase `juxt/master` on the upstream tag.
* In Core2, `./bin/rebuild-forked-arrow-files.sh`
* Test
* Push (`--force-with-lease`) to JUXT fork, and commit to Core2.

== Copyright & License

The MIT License (MIT)

Copyright © 2021-2022 JUXT LTD.

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
