#!/usr/bin/env bash

set -e

(
  cd $(dirname $0)

  if [ "$1" == "-s" ]; then
      MODULES=$(echo $2 | tr ":" "\n" )
      shift 2;
  else
      MODULES="crux-core
labs/crux-rdf
crux-metrics
crux-rocksdb
crux-lmdb
crux-jdbc
crux-http-client
crux-http-server
crux-kafka-embedded
crux-kafka-connect
crux-kafka
crux-sql
crux-lucene
crux-test
crux-s3
crux-azure-blobs
crux-google-cloud-storage
crux-bench"
  fi

  for MODULE in $MODULES; do
      (
          echo --$MODULE
          cd $MODULE > /dev/null
          lein $@
      )
  done
)
