#!/usr/bin/env bash

set -e

(
  cd "$(dirname "$0")"

  if [ "$1" == "-s" ]; then
      MODULES=$(echo "$2" | tr ":" "\n" )
      shift 2;
  else
      MODULES="core
labs/rdf
modules/metrics
modules/rocksdb
modules/lmdb
modules/jdbc
modules/http-client
modules/http-server
modules/http-health-check
modules/kafka-embedded
modules/kafka-connect
modules/kafka
modules/sql
modules/lucene
test
modules/s3
modules/azure-blobs
modules/google-cloud-storage
modules/replicator
bench"
  fi

  for MODULE in $MODULES; do
      (
          echo --"$MODULE"
          cd "$MODULE" > /dev/null
          lein "$@"
      )
  done
)
