#!/usr/bin/env bash

set -e

(
  cd "$(dirname "$0")"

  if [ "$1" == "-s" ]; then
      MODULES=$(echo "$2" | tr ":" "\n" )
      shift 2;
  else
      MODULES="
api
core
modules/datasets
modules/s3
modules/kafka
modules/jdbc
modules/bench"
  fi

  for MODULE in $MODULES; do
      (
          echo --"$MODULE"
          cd "$MODULE" > /dev/null
          lein "$@"
      )
  done
)
