= core2

== Install

[source,clojure]
----
;; project.clj
[pro.juxt.crux-labs/core2-core "dev-SNAPSHOT"]
[pro.juxt.crux-labs/core2-kafka "dev-SNAPSHOT"]
[pro.juxt.crux-labs/core2-jdbc "dev-SNAPSHOT"]
[pro.juxt.crux-labs/core2-s3 "dev-SNAPSHOT"]


;; deps.edn
{pro.juxt.crux-labs/core2-core {:mvn/version "dev-SNAPSHOT"}
 pro.juxt.crux-labs/core2-kafka {:mvn/version "dev-SNAPSHOT"}
 pro.juxt.crux-labs/core2-jdbc {:mvn/version "dev-SNAPSHOT"}
 pro.juxt.crux-labs/core2-s3 {:mvn/version "dev-SNAPSHOT"}}
----

==  Usage - differences to Classic

=== Architecture

Where Classic has a transaction log, document store and query indices, Core2 has a transaction log and an object store.

* Classic transactions are split up into 'tx-events' and documents, with the former going on the tx-log and the latter to the doc-store.
  In Core2, the transaction log doesn't need to have infinite retention, so we no longer need this split - transactions go straight on to the log, and the document store is obsolete.
* Rather than each node having its own query indices, Core2 shares these between nodes in a cluster via the object store.
  The object store is hence _the_ golden store, thanks to the transience of the transaction log.
* The files stored in the object store are in https://arrow.apache.org/[Apache Arrow] format, the structure of which Core2 takes responsibility for maintaining - we no longer require a KV store.

[cols="1,2*^"]
|===
| | Transaction Log | Object Store

| AWS S3 | | ✓
| Azure Blobs | | (soon)
| Google Cloud Storage | | (soon)
| FileSystem | ✓ | ✓
| Kafka | ✓ | ✗
| JDBC | (soon) | ✓
| In-memory | ✓ | ✓
| LMDB (KV) | ✗ | ✗
| RocksDB (KV) | ✗ | ✗
|===


=== Setup

Main require: `[core2.api :as c2]`

Configuration uses https://github.com/weavejester/integrant[Integrant].

You can still start a completely in-memory node using `(core2.local-node/start-node {})`.
For a Kafka/JDBC node:

[source,clojure]
----
(with-open [node (node/start-node {:core2.kafka/log {:bootstrap-servers "localhost:9092"}

                                   :core2.jdbc.postgres/dialect {}
                                   :core2.jdbc/default-pool {:db-spec {:user "postgres"
                                                                       :password "postgres"
                                                                       :database "core2test"}}
                                   :core2.jdbc/object-store {}})]
  ;; ...
  )
----

The CLI parameters, and EDN/JSON configuration file formats are the same as Classic.

=== Transactions

Transactions are slightly different to Classic:

- `[:crux.tx/put <doc>]` -> `[:put <doc>]`. Put and delete supported thus far.
- `:crux.db/id` -> `:_id`. Valid ID types currently strings, numbers, dates.
- `c2/submit-tx` returns `CompletableFuture`, deref it to get the transaction details.

=== Queries
In a similar manner to `next.jdbc`[https://github.com/seancorfield/next-jdbc], execute Datalog queries in Core2 using `c2/plan-query`.
This returns a reducible sequence that you can pass to (say) `reduce`, `into` or `run!`.
When finalised (by `reduce`) this will ensure the query results are adequately closed.

[source,clojure]
----
(with-open [node (node/start-node {})]
  (->> (c2/plan-query node
                      '{:find [?e ?name]
                        :where [[?e :name ?name]]})
       (into [])))
----

These queries currently return a vector of maps `[{:e ..., :name ...}, {...}]`, although this is only because it's what was closest to what we had available at the time.

=== Bases
Core2 doesn't have the concept of DBs - instead, we pass the node and (optionally) a 'basis' to queries.
In Core2, the upper bound for the tx-time is applied per-source; the default upper bound for VT is applied at the query level - this is because each data source has their own tx-time timeline, but VT is assumed to be a single timeline, consistent across data sources.

[source,clojure]
----
;; simple case - use the latest tx the node has available:
(->> (c2/plan-query node '{...})
     (into []))

;; or, to read your own writes (timeout optional):
;; `plan-query` will await the transaction
(->> (c2/plan-query node
                    (-> '{:find ..., :where ...}
                        (assoc :basis {:tx tx}
                                 :basis-timeout (Duration/ofSeconds 1))))
     (into []))
----

The `plan-query` functions take the node, the query, and then a variable number of params.

[source,clojure]
----
(->> (c2/plan-query tu/*node*
                    (-> '{:find [?e]
                          :in [?first-name ?last-name]
                          :where [[?e :first-name ?first-name]
                                  [?e :last-name ?last-name]]}
                        (assoc :basis {:tx tx}))
                    "Ivan" "Ivanov")
     (into #{}))
----

Unlike Datomic, `$` shouldn't be included in `:in` - if/when we reinstate multiple sources to Datalog queries, I propose we include them as a named map in the basis-opts:

[source,clojure]
----
;; something like this, anyway.
(->> (c2/plan-query node
                    (-> '{:find [...]
                          :where [[$db1 ...], [$db2 ...]]}
                        (assoc :basis {'$db1 {:tx tx}
                                       '$db2 {:tx tx}}
                               :basis-timeout (Duration/ofSeconds 1))))
     (into []))
----

`plan-query-async` is the same, except it runs entirely asynchronously and returns a `CompletableFuture` of the query plan.
(In fact, `plan-query` just calls `plan-query-async` and deref's it.)

The basis map can also contain a `:default-valid-time` option, which applies to any entities that don't specify other valid-time constraints.
This is for repeatable queries - it defaults to 'now' if not provided.

[source,clojure]
----
(->> (c2/plan-query node
                    (-> '{:find [?e ?name]
                          :where [[?e :name ?name]]}
                        (assoc :basis {:default-valid-time #inst "..."})))
     (into []))
----

There is also `op/plan-ra` which accepts a lower-level relational algebra query - have a look in `core2.logical-plan` for what can go into these plans, and `core2.tpch-queries` for examples.

== Developing Core2

First time:
- `./lein-sub install`

- Start and connect to your REPL in the usual fashion
- `(dev)`
- `(go)`
- `node` is then bound to a started node, using `dev/dev-node` as a persistent data directory

=== Links

- https://github.com/juxt/crux-rnd/projects/1[Kanban board]
- https://app.circleci.com/pipelines/github/juxt/crux-rnd[Continuous Integration (CircleCI)]
- link:bibliography.org[bibliography.org] - a list of light bedtime reading.

=== Testing

* Can test individual modules by `lein test`
* Test all with `./lein-sub test`; `./lein-sub test :integration` for longer tests
* Some tests have external dependencies which require `docker-compose`:
  * `docker-compose up` (`docker-compose up <postgres|kafka>` etc for individual containers),
  * `lein test :with-docker` / `./lein-sub test :with-docker`
  * `docker-compose down`

=== Profiling

To attach YourKit, `lein run with-profile +attach-yourkit repl :headless` (assumes YourKit in `/opt/yourkit` as installed by the AUR)

=== Building Core2

==== Maven Central

Core2 artifacts are deployed to Maven Central.

* To deploy a `dev-SNAPSHOT` release, `./lein-sub deploy`
* To deploy a release, `CORE2_VERSION=<version> ./lein-sub do install, deploy`, then head to the https://oss.sonatype.org/[Nexus UI] to close/release it.

==== Uberjar

* `./lein-sub do clean, install`
* `lein uberjar` => `target/core2-standalone.jar`

* `java -jar target/core2-standalone [--help]`

==== Docker

* `./bin/build-docker.sh [--clean]` => `juxt.crux-labs/core2:latest`
* `CORE2_VERSION=<version> ./bin/build-docker.sh` to tag as a different version.


== Copyright & License

The MIT License (MIT)

Copyright © 2021 JUXT LTD.

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
