= XTDB "Core 2"

== WARNING!

This is **not production code.**
Do not run anything in this repository expecting it to work.
The modules in this repository are _experiments_ which may or may not be used in the upcoming 2.x series of XTDB.

If you are looking for the stable, production-quality XTDB source code, you will always find it here: https://github.com/xtdb/xtdb

==  What is this?

XTDB is an immutable, (optionally) bitemporal, HTAP document database.
(Stable XTDB releases found here: https://docs.xtdb.com/administration/installing/)
This repository represents a number of _experiments_ intended to explore and expand on the original design of XTDB.

We are not yet certain how these experiments will be used in XTDB.
Some may be used verbatim, as they appear in this repository.
Some may be used in parts.
Some may be limited to providing inspiration.

== XTDB 2.x Vision

XTDB 2.x isn't a repository.
It is an extension of the pillars which make XTDB appealing to so many people.
Those pillars -- and the XTDB 2.x vision for those pillars -- are documented in the https://xtdb.com/vision-doc.pdf[Vision Document] (PDF).

== FAQ

Please read the https://github.com/xtdb/core2/blob/readme_new/FAQ.adoc[Frequently Asked Questions] to see if we have already answered a question you have.

== Developers

See https://github.com/xtdb/core2/blob/readme_new/HACKING.adoc[HACKING].
