= Crux Kotlin DSL

A Kotlin DSL for Crux which enables pretty transactions and queries

== Quickstart

```bash
git clone git@github.com:crux-labs/crux-kotlin-dsl.git
cd crux-kotlin-dsl
./gradlew build
cp build/libs/crux-kotlin-dsl-0.0.1-SNAPSHOT.jar {your-project-deps-directory}
```

== Status

Pre-Alpha: This library is experimental. If you need a stable Java/Kotlin API, use the https://crux-doc.s3.eu-west-2.amazonaws.com/crux-javadoc/master/index.html[Crux Core Java API] directly for now.

== References

* https://www.juxt.pro/drafts/crux-kotlin (TODO: replace with real blog post)
* https://github.com/AlistairONeill/crux-kotlin-dsl

== Copyright & License

The MIT License (MIT)

Copyright © 2020-2021 JUXT LTD.

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
