= XTDB "Core2" Research

Welcome to the XTDB research repository.

XTDB Core2 is an experimental, SQL-first, immutable database concept.


== Vision

The technical aim is to layer on temporal query capability on top of a immutable, columnar data storage.

Core2 will support the SQL:2011 specification whilst aiming for a schemaless document model,
and will embrace a separate-storage-from-compute architecture.
Core2 uses Apache Arrow as the data-format, and the engine allows for querying across nested document data.

Read more about Core2 in our https://xtdb.com/pdfs/vision-doc.pdf[Vision Document] (PDF).


== SQL:2011

XTDB not only supports the SQL:2011 standard, it makes SQL:2011 accessible.
All data is bitemporal.
Document records remove the need for awkward bitemporal schema migrations.

SQL:2011 queries enable querying _across_ time.
For example, the following query asks "Which employees and contractors worked for the company at the same time?"

[source,sql]
----
SELECT employee.name, contractor.name
FROM employee, contractor
WHERE employee.application_time OVERLAPS contractor.application_time
----


== Warning

This is an experimental project.

If you are looking for an existing immutable document database with bitemporal query, we will continue to develop
and support XTDB 1.x here: https://github.com/xtdb/xtdb

Stable XTDB releases found here: https://docs.xtdb.com/administration/installing/


== Hows does this differ from XTDB 1.x?

XTDB 1.x is a mature product offering, used in production, with on-going development focusing on continued hardening and performance.
XTDB 1.x is a Datalog-first, in-process embeddable database, offering advanced 'peer-like' functionality such as transaction-functions,
speculative transactions, programmatic Datalog rules, and more.

XTDB Core2 has a different goal of bringing immutability, schemaless documents, and temporal query to a mainstream SQL audience.

[cols=3*]
|===
| | XTDB 1.x Series | XTDB "Core2" Research Series
| Status | Stable | Experimental (pre-alpha)
| Initial Stable Release | 2019 | 2023* (planned)
| Primary Interface | Java + 'edn Datalog' | SQL (JDBC, native drivers, etc.)
| Secondary Interface | OpenAPI, Calcite SQL (read-only) | Datalog* (planned)
| Execution Model | Tuple-at-a-Time Sort-Merge Joins | Vectorized Relational Algebra
| Storage & Compute | Coupled (nodes are full replicas) | Separated (cost-effective scale out)
| Primary Storage Format | Custom Key-Value encodings | Columnar Apache Arrow
| Bitemporal Querying | Timeslice only ('as-of') | Full SQL:2011
| Relational Decorrelation | No | Yes
| Analytical Querying | No | Yes
| Single-partition Transaction Log | Infinite Retention | Ephemeral
| Index Upgrades | Full log replay | Online
| - | - | -
| Immutable Semantics | Yes | Yes
| Online Transactions (ACID, linearizable consistency) | Yes | Yes
| Always-On Bitemporality | Yes | Yes
| Dynamism (graph joins, union typing, schemaless, etc.) | Yes | Yes
|===


== License and Copyright

The Affero GNU Public License, Version 3.

Copyright © 2018-2022 JUXT Ltd.
