= Datalog Queries
:page-aliases: reference::queries.adoc

[#intro]
== Introduction

XTDB is a schemaless document database that provides you with a comprehensive means of traversing and querying across all of your documents.
XTDB automatically indexes the top-level fields in all documents, supporting efficient ad-hoc joins and retrievals.
XTDB is both _immutable_ and _bitemporal_, which are both required characteristics for a safe schemaless database.

XTDB is also a graph database.
The central characteristic of a graph database is that it can support arbitrary-depth graph queries (recursive traversals) very efficiently by default, without any need for schema-level optimisations.
Graph queries are possible through the XTDB dialect of the Datalog query language.

=== EDN Datalog

Extensible Data Notation (edn) is a simple data format that is used to describe XTDB Datalog queries.
To understand how edn works, read the brief description at http://edn-format.org/[http://edn-format.org].

To learn about Datalog queries and get familiar with the concepts, read the xref:tutorials::learn-datalog.adoc[Learn XTDB Datalog Today] tutorial.

////
Can we remove these 3 paragraphs? -sd

A Datalog query consists of a set of variables and a set of clauses.
The result of running a query is a result set of the possible combinations of values that
satisfy all of the clauses at the same time.
These combinations of values are referred to as "tuples".

The possible values within the result tuples are derived from your database of
documents. The documents themselves are represented in the database indexes as
"entity–attribute–value" (EAV) facts. For example, a single document
`{:xt/id :myid :color "blue" :age 12}` is transformed into two facts
`[[:myid :color "blue"][:myid :age 12]]`.

In the most basic case, a Datalog query works by searching for "subgraphs" in
the database that match the pattern defined by the clauses. The values within
these subgraphs are then returned according to the list of return variables
requested in the `:find` vector within the query.
////

[#structure]
=== Basic Structure

A query in XTDB is performed by calling `xt/q` on an XTDB database snapshot with a quoted map and, optionally, additional arguments.

[source,clojure]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=anatomy,indent=0]
----
<1> Database value. Usually the snapshot view comes from calling `xt/db` on an XTDB node
<2> Query map or vector (ex. `[:find ...etc... ]`, as found in other Datalog databases)
<3> Argument(s) supplied to the `:in` relations

The query map accepts the following Keywords

.Query Keys
[cols="3,3,8"]
|===
|Key|Type|Purpose

|<<#find,`:find`>>|Vector|Specify values to be returned
|<<#where,`:where`>>|Vector|Restrict the results of the query
|<<#in,`:in`>>|Vector|Specify external arguments
|<<#ordering-and-pagination,`:order-by`>>|Vector|Control the result order
|<<#ordering-and-pagination,`:limit`>>|Int|Specify how many results to return
|<<#ordering-and-pagination,`:offset`>>|Int|Specify how many results to discard
|<<#rules,`:rules`>>|Vector|Define powerful statements for use in `:where` clauses
|<<#timeout,`:timeout`>>|Int|Specify maximum query run time in ms
|===

[#find]
== Find

The find clause of a query specifies what values to be returned. These will be returned as a vector.

[#find-logic-variable]
=== Logic Variable

You can specify logic variables within your query without first declaring them elsewhere.
Logic variables are commonly prefix with a `?` (question mark) as a stylistic convention but it is not necessary and can simply be considered part of the variable's identifier. For example, `foo` or `?foo` can be used equivalently, but they are not equal and will be treated as independent logic variables.

The following will return all last names bound to the logic variable `n`.

[source,clojure]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=triple,indent=0]
----

[#find-expressions]
=== Expressions

You can use basic Clojure-like expressions within a `:find` parameter.

[source,clojure]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=find-expr,indent=0]
----

* `let`, and other macros are unsupported - you can create and call fully-qualified Clojure functions for more advanced use cases.
* Function calls are guarded by xref:administration::configuring.adoc#fn-allowlist[`:fn-allow-list`], if it was specified in the node configuration.

[#find-aggregate]
=== Aggregates

You can specify an aggregate function to apply to at most one logic variable.

.Built-in Aggregate Functions
[cols="3,.^8"]
|===
|Usage|Description
|`(sum <expr>)`| Accumulates as a single value via the Clojure https://clojuredocs.org/clojure.core/+[`&#43;`] function
|`(min <expr>)` .2+| Return a single value via the Clojure https://clojuredocs.org/clojure.core/compare[`compare`] function which may operate on many types (integers, strings, collections etc.)
|`(max <expr>)`
|`(count <expr>)`| Return a single count of all values including any duplicates (note: this always performs a scan - no statistics or other stateful materializations are used)
|`(avg <expr>)`| Return a single value equivalent to `sum / count`
|`(median <expr>)` .3+| Return a single value corresponding to the statistical definition
|`(variance <expr>)`
|`(stddev <expr>)`
|`(rand N <expr>)`| Return a vector of exactly N values, where some values may be duplicates if N is larger than the range
|`(sample N <expr>)`| Return a vector of at-most N distinct values
|`(distinct <expr>)`| Return a set of distinct values
|===

* Aggregates cannot be nested within another - e.g. `(sum (count ?x))` is disallowed.
* Results are implicitly grouped by all logic variables referred to outside of aggregations (even if the same variables are also referred to within aggregations).
  For example, in the following example, the results are grouped by `?a` and `?b`:
+
[source,clojure]
----
{:find [?a (/ ?b (sum (+ ?b ?c)))], ...}
----

==== Example:

[source,clojure]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=query-aggregates,indent=0]

;; =>
include::example$test/xtdb/docs/examples/query_test.clj[tags=query-aggregates-r,indent=0]
----

=== Custom Aggregates

Custom (user-defined) aggregates are supported by adding a new method (via Clojure `defmethod`) for `xtdb.query/aggregate`.
This method takes a single (ignored) parameter and returns a multi-arity function which accepts zero parameters, an accumulator, or an accumulator and a single entity.
For example:

[source,clojure]
----
(defmethod xtdb.query/aggregate 'sort-reverse [_]
  (fn
    ([] [])
    ([acc] (vec (reverse (sort acc))))
    ([acc x] (conj acc x))))
----

[#pull]
=== Pull

XTDB queries support a `pull` syntax, allowing you to decouple specifying which entities you want from what data you'd like about those entities in your queries.
XTDB's support is based on the excellent https://edn-query-language.org/eql/1.0.0/what-is-eql.html[EDN Query Language (EQL)^] library.

To specify what data you'd like about each entity, include a `(pull ?logic-var projection-spec)` entry in the `:find` clause of your query:

[source,clojure]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=pull-query-1,indent=0]
include::example$test/xtdb/docs/examples/query_test.clj[tags=pull-query-1-r,indent=0]

include::example$test/xtdb/docs/examples/query_test.clj[tags=pull-query-2,indent=0]
include::example$test/xtdb/docs/examples/query_test.clj[tags=pull-query-2-r,indent=0]
----

You can quickly grab the whole document by specifying `*` in the projection spec:

[source,clojure]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=pull-query-6,indent=0]
include::example$test/xtdb/docs/examples/query_test.clj[tags=pull-query-6-r,indent=0]
----

If you have the entity id(s) in hand, you can call `pull` or `pull-many` directly:

[source,clojure]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=pull-many-query-1]
include::example$test/xtdb/docs/examples/query_test.clj[tags=pull-many-query-1-r]
include::example$test/xtdb/docs/examples/query_test.clj[tags=pull-many-query-2]
include::example$test/xtdb/docs/examples/query_test.clj[tags=pull-many-query-2-r]
----

We can navigate to other entities (and hence build up nested results) using joins.
Joins are specified in `{}` braces in the projection-spec - each one maps one join key to its nested spec:

[source,clojure]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=pull-query-3,indent=0]
include::example$test/xtdb/docs/examples/query_test.clj[tags=pull-query-3-r,indent=0]

include::example$test/xtdb/docs/examples/query_test.clj[tags=pull-query-4,indent=0]
include::example$test/xtdb/docs/examples/query_test.clj[tags=pull-query-4-r,indent=0]
----

We can also navigate in the reverse direction, looking for entities that refer to this one, by prepending `_` to the attribute name:

[source,clojure]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=pull-query-5,indent=0]
include::example$test/xtdb/docs/examples/query_test.clj[tags=pull-query-5-r,indent=0]
----

==== Attribute parameters

XTDB `pull` syntax supports a handful of custom https://edn-query-language.org/eql/1.0.0/specification.html#_parameters[EQL parameters], specified by wrapping the `:attribute` key in a pair: `(:attribute {:param :value, ...})`.

* `:as` - to rename attributes in the result, wrap the attribute in `(:source-attribute {:as :output-name})`:
+
[source,clojure]
----
{:find [(pull ?profession [:profession/name
                           {(:user/_profession {:as :users}) [:user/id :user/name]}])]
 :where [[?profession :profession/name]]}

;; => [{:profession/name "Doctor",
;;      :users [{:user/id 1, :user/name "Ivan"},
;;              {:user/id 3, :user/name "Petr"}]},
;;     {:profession/name "Lawyer",
;;      :users [{:user/id 2, :user/name "Sergei"}]}]
----
* `:limit` - limit the amount of values returned under the given property/join: `(:attribute {:limit 5})`
* `:default` - specify a default value if the matched document doesn't contain the given attribute: `(:attribute {:default "default"})`
* `:into` - specify the collection to pour the results into: `(:attribute {:into #{}})`
+
[source,clojure]
----
{:find [(pull ?profession [:profession/name
                           {(:user/_profession {:as :users, :into #{}})
                           [:user/id :user/name]}])]
 :where [[?profession :profession/name]]}

;; => [{:profession/name "Doctor",
;;      :users #{{:user/id 1, :user/name "Ivan"},
;;               {:user/id 3, :user/name "Petr"}}},
;;     {:profession/name "Lawyer",
;;      :users #{{:user/id 2, :user/name "Sergei"}}}]
----
* `:cardinality` (reverse joins) - by default, reverse joins put their values in a collection - for many-to-one/one-to-one reverse joins, specify `{:cardinality :one}` to return a single value.

For full details on what's supported in the projection-spec, see the https://edn-query-language.org/eql/1.0.0/specification.html[EQL specification^]

[#return-maps]
=== Returning maps
To return maps rather than tuples, supply the map keys under `:keys` for keywords, `:syms` for symbols, or `:strs` for strings:

[source,clojure]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=return-maps,indent=0]
include::example$test/xtdb/docs/examples/query_test.clj[tags=return-maps-r,indent=0]
----

[#where]
== Where

The `:where` section of a query limits the combinations of possible results by satisfying all clauses and rules in the supplied vector against the database (and any `:in` relations).

.Valid Clauses
[cols="1,4"]
|===
|Name|Description
|<<#clause-triple, triple clause>>| Restrict using EAV indexes
|<<#clause-pred, predicate>>| Restrict with any predicate
|<<#clause-range, range predicate>>| Restrict with any of `<` `+<=+` `>=` `>` `=`
|<<#clause-unification, unification predicate>>| Unify two distinct logic variables with `!=` or `==`
|<<#clause-not, not rule>>| Negate a list of clauses
|<<#clause-not-join, not-join rule>>| Not rule with its own scope
|<<#clause-or, or rule>>| Restrict on at least one matching clause
|<<#clause-or-join, or-join rule>>| Or with its own scope
|<<#clause-rule, defined rule>>| Restrict with a user-defined rule
|===

[#clause-inputs]
=== Clause Inputs

Clauses may refer to combinations of literal values and logic variables as inputs.
Identical logic variables used across multiple clauses unify automatically (with the exception of `or-join` or `not-join` scoping).

A literal set containing literal values (e.g. `#{"val-1" "val-2"}`) will be interpreted as an input relation of distinct values, and can be used in place of any literal input (e.g. a set of entity IDs in the first position of a triple clause).

[#clause-triple]
=== Triple

A triple clause is a vector of (1) a literal entity ID or a logic variable, (2) a hard-coded attribute keyword (top-level key in a document), and (3) optionally, a value which can be a literal or a logic variable.

It restricts results by matching EAV facts

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=double,indent=0]

include::example$test/xtdb/docs/examples/query_test.clj[tags=triple-2,indent=0]

include::example$test/xtdb/docs/examples/query_test.clj[tags=triple-3,indent=0]
----
<1> This matches all entities, `p`, which have a `:name` field.
<2> This matches all entities, `p`, which have a `:name` of `"Ivan"`.
<3> This matches all entities, `p`, which have a `:name` which match the `:last-name` of `q`.

Note that the keyword attribute must always be specified and therefore you cannot use a logic variable in the attribute position.
You can however enumerate combinations of known attributes using rules, or execute independent queries efficiently using `openDB` (`open-db`).
A list of all known attributes is available via the `attributeStats` (`attribute-stats`) API.

Where fine-grained query join ordering control is desired, and in particularly the `e` should always be resolved before the `v`, the built-in (see https://github.com/xtdb/xtdb/blob/e2f51ed99fc2716faa8ad254c0b18166c937b134/test/test/xtdb/query_test.clj#L1054[`get-attr`]) lookup function may be a useful substitute to consider instead of a triple clause.

[#clause-pred]
=== Predicates

Any fully qualified Clojure function that returns a boolean can be used as a "filter" predicate clause.

Predicate clauses must be placed in a clause, i.e. with a surrounding vector.

[source,clojure]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=query-with-pred-1,indent=0]
----

This matches all entities, `p` which have an odd `:age`.

[#where-subqueries]
=== Subqueries

You can nest a subquery with a `:where` clause to bind the result for further use in the query.

==== Binding results as a scalar

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=sub-query-example-1,indent=0]
----

In the above query, we perform a subquery doing some arithmetic operations and returning the result - and bind the resulting relation as a scalar.

Result set:

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=sub-query-example-1-r,indent=0]
----

==== Binding results as a tuple

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=sub-query-example-2,indent=0]
----

Similar to the previous query, except we bind the resulting relation as a tuple.

Result set:

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=sub-query-example-2-r,indent=0]
----

In this example, we bind the results of a subquery and use them to return another result.

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=sub-query-example-3,indent=0]
----

Result set:

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=sub-query-example-3-r,indent=0]
----

Any fully qualified Clojure function can also be used to return relation bindings in this way, by returning a list, set or vector.

[#clause-range]
=== Range Predicate

A `range predicate` is a vector containing a list of a range operator and then two logic variables or literals.

Allowed range operators are `<`, `+<=+`, `>=`, `>`, and `=`.

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=range-1,indent=0]

include::example$test/xtdb/docs/examples/query_test.clj[tags=range-2,indent=0]

include::example$test/xtdb/docs/examples/query_test.clj[tags=range-3,indent=0]
----
<1> Finds any entity, `p`, with an `:age` which is greater than 18
<2> Finds any entity, `p`, with an `:age` which is greater than the `:age` of any entity
<3> Finds any entity, `p`, for which 18 is greater than `:age` of `p`

[#clause-unification]
=== Unification Predicate

Use a unification predicate, either `==` or `!=`, to constrain two independent logic variables. Literals (and sets of literals) can also be used in place of one of the logic variables.

[source,clj]
----
;; Find all pairs of people with the same age:

[[p :age a]
 [p2 :age a2]
 [(== a a2)]]

;; ...is approximately equivalent to...

[[p :age a]
 [p2 :age a]]

;; Find all pairs of people with different ages:

[[p :age a]
 [p2 :age a2]
 [(!= a a2)]]

;; ...is approximately equivalent to...

[[p :age a]
 [p2 :age a2]
 (not [(= a a2]])]
----

[#clause-not]
=== Not

The `not` clause rejects a graph if all the clauses within it are true.

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=not-data,indent=0]

include::example$test/xtdb/docs/examples/query_test.clj[tags=not-2,indent=0]

include::example$test/xtdb/docs/examples/query_test.clj[tags=not-2-r,indent=0]
----
<1> Data
<2> Query
<3> Result

This will match any document which does not have a `:name` of "Ivan" _and_ a `:last-name` of "Ivanov".

[#clause-not-join]
=== Not Join

The `not-join` rule allows you to restrict the possibilities for logic variables by asserting that there does not exist a match for a given sequence of clauses.

You declare which logic variables from outside the `not-join` scope are to be used in the join.

Any other logic variables within the not-join are scoped only for the join.

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=not-join-data,indent=0]

include::example$test/xtdb/docs/examples/query_test.clj[tags=not-join,indent=0]

include::example$test/xtdb/docs/examples/query_test.clj[tags=not-join-r,indent=0]
----
<1> Data
<2> Declaration of which logic variables need to unify with the rest of the query
<3> Clauses
<4> Result

This will match any entity, `p`, which has different values for the `:name` and `:last-name` field.

Importantly, the logic variable `n` is unbound outside the `not-join` clause.

[#clause-or]
=== Or

An `or` clause is satisfied if any of its legs are satisfied.

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=or-data,indent=0]

include::example$test/xtdb/docs/examples/query_test.clj[tags=or-1,indent=0]

include::example$test/xtdb/docs/examples/query_test.clj[tags=or-1-r,indent=0]
----
<1> Data
<2> Query
<3> Result

This will match any document, `p`, which has a `:last-name` of "Ivanov" or "Ivannotov".

When within an `or` rule, you can use `and` to group clauses into a single leg (which must all be true).

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=or-2,indent=0]
----

Whenever the query engine complains that each leg in the `or` or `or-join` clause requires the "same logic variables", you can add a no-op predicate clause like `[(any? e)]` within `and` clauses for each of the missing variables in the various legs.
You need to add such no-op predicates until each leg contains the same set of variables.

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=or-3,indent=0]
----

Hypothetically, XTDB could automatically detect these cases and insert no-op predicates on the user's behalf, but that would be a deviation from the essential semantics of Datalog.
Note that `clojure.core/any?` is a function that always returns `true`.

[#clause-or-join]
=== Or Join

The `or-join` clause is satisfied if any of its legs are satisfied.

You declare which logic variables from outside the `or-join` scope are to be used in the join.

Any other logic variables within the `or-join` are scoped only for the join.

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=or-join-data,indent=0]

include::example$test/xtdb/docs/examples/query_test.clj[tags=or-join,indent=0]

include::example$test/xtdb/docs/examples/query_test.clj[tags=or-join-r,indent=0]
----
<1> Data
<2> Declaration of which logic variables need to unify with the rest of the query
<3> Clauses
<4> Result

This will match any document, `p` which has an `:age` greater than or equal to 18 _or_ has a `:name` of "Ivan".

Importantly, the logic variable `a` is unbound outside the `or-join` clauses.

[#clause-rule]
=== Rules

<<#rules, See Rules>>

[#in]
== In

XTDB queries can take a set of additional arguments, binding them to variables under the `:in` key within the query.

`:in` supports various kinds of binding.

=== Scalar binding

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=query-with-arguments1,indent=0]
----

In the above query, we parameterize the `first-name` symbol, and pass in "Ivan" as our input, binding "Ivan" to `first-name` in the query.

Result Set:
[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=query-with-arguments1-r,indent=0]
----

=== Collection binding

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=query-with-arguments2,indent=0]
----

This query shows binding to a collection of inputs - in this case, binding `first-name` to all of the different values in a collection of first-names.

Result Set:
[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=query-with-arguments2-r,indent=0]
----

=== Tuple binding

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=query-with-arguments3,indent=0]
----

In this query we are binding a set of variables to a single value each, passing in a collection as our input. In this case, we are passing a collection with a `first-name` followed by a `last-name`.

Result Set:
[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=query-with-arguments3-r,indent=0]
----

=== Relation binding

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=query-with-arguments4,indent=0]
----

Here we see how we can extend the parameterisation to match using multiple fields at once by passing and destructuring a relation containing multiple tuples.

Result Set:
[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=query-with-arguments4-r,indent=0]
----

[#ordering-and-pagination]
== Ordering and Pagination

A Datalog query naturally returns a result set of tuples, however, the tuples
can also be consumed as a sequence and therefore you will always have an
implicit order available. Ordinarily this implicit order is undefined (i.e. not
meaningful), because the join order and result order are unlikely to correlate.

The `:order-by` option is available for use in the query map to explicitly
control the result order.

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=order-and-pagination-1,indent=0]
----

Use of `:order-by` will require that results are fully-realised by the query
engine, however this happens transparently and it will automatically spill to
disk when sorting large numbers of results.

Basic `:offset` and `:limit` options are supported however typical pagination
use-cases will need a more comprehensive approach because `:offset` will
naively scroll through the initial result set each time.

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=order-and-pagination-2,indent=0]
----

Ordered results are returned as bags, not sets, so you may want to deduplicate
consecutive identical result tuples (e.g. using `clojure.core/dedupe` or
similar).

`:limit` may be used in isolation, without `:order-by`, and will also return a
bag of results that can contain duplicates. This will process exactly the
required number of results from the underlying streaming query to satisfy the
limit, which can be useful for minimizing unnecessary processing.

To use `:order-by` with an aggregate, simply restate the aggregate element exactly as it is written in your `:find` vector.

More powerful ordering and pagination features may be provided in the future.
Feel free to open an issue or get in touch to discuss your ordering
requirements, e.g. see https://github.com/xtdb/xtdb/discussions/1514[#1514]

[#rules]
== Rules
Rules are defined by a rule head and then clauses as you would find in a `:where` statement.

They can be used as a shorthand for when you would otherwise be repeating the same restrictions in your `:where` statement.

[source,clojure]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=rules-1,indent=0]
----
<1> Rule usage clause (i.e. invocation)
<2> Rule head (i.e. signature)
<3> Rule body containing one or more clauses

The above defines the rule named `adult?` which checks that the supplied entity has an `:age` which is `>=` 18

Multiple rule bodies may be defined for a single rule name (i.e. using matching rule heads) which works in a similar fashion to an `or-join`.

The clauses within Rules can also be further Rule invocation clauses. This allows for the recursive traversal of entities and more.

[source,clojure]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=rules-2,indent=0]
----

This example finds all entities that the entity with `:name` "Smith" is connected to via `:follow`, even if the connection is via intermediaries.

=== Bound arguments

To improve the performance of a rule you can specify that certain arguments in the rule head must be "bound" logic variables (i.e. there must be known values for each argument at the point of evaluation) by enclosing them in a vector in the first argument position. Any remaining arguments will be treated as regular "free" logic variables.

As an analogy, bound variables are input arguments to a function, and free variables are the destructured return values from that function.

Changes are only necessary in the rule head(s) - no changes are required in the body or the usage clauses. Rule heads must always match.

For example, the following query and rule set will work and return the correct results.

[source,clojure]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=rules-3,indent=0]
----

However, specifying that the `p` variable should be bound before the rule can be evaluated will improve the evalution time by many orders-of-magnitude for large data sets.

[source,clojure]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=rules-4,indent=0]
----

[#timeout]
== Timeout

`:timeout` sets the maximum run time of the query (in milliseconds).

If the query has not completed by this time, a `java.util.concurrent.TimeoutException` is thrown.

[#valid-time-travel]
== Valid Time travel

When performing a query, `xt/q` is called on a database snapshot.

To query based on a different Valid Time, create this snapshot by specifying the desired Valid Time when we call `db` on the node.

[source,clojure]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=query-at-t-d1,indent=0]

include::example$test/xtdb/docs/examples/query_test.clj[tags=query-at-t-d2,indent=0]
----

Here, we have `put` different documents in XTDB with different Valid Times.

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=query-at-t-q1,indent=0]
----

Here, we have defined a query, `q` to find all entities with a `:name` of "Malcolma" and `:last-name` of "Sparks"

We can run the query at different Valid Times as follows

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=query-at-t-q1-q,indent=0]

include::example$test/xtdb/docs/examples/query_test.clj[tags=query-at-t-q2-q,indent=0]
----

The first query will return an empty result set (`#{}`) because there isn't a document with the `:name` "Malcolma" valid at `#inst "1986-10-23"`

The second query will return `#{[:malcolm]}` because the document with `:name` "Malcolma" _is_ valid at the current time.
This will be the case so long as there are no newer versions (in the valid time axis) of the document that affect the current valid time version.

[#joins]
== Joins

=== Query: "Join across entities on a single attribute"

Given the following documents in the database
[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=join-d,indent=0]
----

We can run a query to return a set of tuples that satisfy the join on the attribute `:name`
[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=join-q,indent=0]
----

Result Set:
[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=join-r,indent=0]
----

Note that every person joins once, plus 2 more matches.

=== Query: "Join with two attributes, including a multi-valued attribute"

Given the following documents in the database
[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=join2-d,indent=0]
----

We can run a query to return a set of entities that `:follows` the set of entities with the `:name` value of `"Ivan"`
[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=join2-q,indent=0]
----

Result Set:
[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=join2-r,indent=0]
----

Note that because XTDB is schemaless there is no need to have elsewhere declared that the `:follows` attribute may take a value of edn type `set`.

[#streaming-queries]
== Streaming Queries

Query results can also be streamed, which is particularly useful for advanced
scenarios where complete results may not fit into memory.
`xtdb.api/open-q` returns a `Closeable` sequence. Note that
results are returned as bags, not sets, so you may wish to deduplicate
consecutive identical result tuples (e.g. using `clojure.core/dedupe` or
similar).

We recommend using `with-open` to ensure that the sequence is closed properly.

WARNING: Ensure that the sequence is eagerly consumed (as much of it as you
need) within the `with-open` block - attempting to consume the sequence from
outside the block (either explicitly, or by accidentally returning a lazy
sequence from the `with-open` block) will result in undefined behaviour (e.g. a
JVM segfault crash when using RocksDB). Lazy work can be realized (and therefore avoided) using
`doall`/`dorun`/`doseq` or similar.

[source,clj,indent=0]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=streaming-query,indent=0]
----

[#history-api]
== History API

[#history-full-document-history]
=== Full Entity History
XTDB allows you to retrieve all versions of a given entity:
[source,clj]
----
include::example$test/xtdb/docs/examples_test.clj[tags=history-full,indent=0]
----

=== Retrieving previous documents
When retrieving the previous versions of an entity, you have the option to additionally return the documents associated with those versions (by using `:with-docs?` in the additional options map)
[source,clj]
----
include::example$test/xtdb/docs/examples_test.clj[tags=history-with-docs,indent=0]
----

[#history-document-history-range]
=== Document History Range
Retrievable entity versions can be bounded by four time coordinates:

* valid-time-start
* tx-time-start
* valid-time-end
* tx-time-end

All coordinates are inclusive. All coordinates can be null. The specified sort-order direction will be relative to the actual order of the start/end times provided.

The returned order is always sorted by valid-time first, and then tx-time second as the tie-break (e.g. when `with-corrections? true` is specified).

[source,clj]
----
include::example$test/xtdb/docs/examples_test.clj[tags=history-range,indent=0]
----

=== Lazy Iteration
See the `open-entity-history` (Clojure) and `openEntityHistory` (Java) APIs.

=== History predicates
There also exists the predicates `get-start-valid-time` and `get-end-valid-time` to access
the history of an entity inside a query. These allow to get the start `valid-time` and
`end-valid` time of an entity with respect to the snapshot view of the given db.

[source,clj]
----
include::example$test/xtdb/docs/examples_test.clj[tags=history-predicates,indent=0]
----

[#clojure-tips]
== Clojure Tips

=== Quoting

Logic variables used in queries must always be quoted in the `:find` and
`:where` clauses, which in the most minimal case could look like the following:

[source,clj]
----
(xt/q db
  {:find ['?e]
   :where [['?e :event/employee-code '?code]]}))
----

However it is often convenient to quote entire clauses or even the entire query
map rather than each individual use of every logic variable, for instance:

[source,clj]
----
(xt/q db
  '{:find [?e]
    :where [[?e :event/employee-code ?code]]}))
----

Note that use of Clojure's syntax quoting may cause confusion and is therefore not recommended. This is because Datalog built-ins like range predicates, unification predicates and rules (`or`, `not` etc.) will be mistakenly coerced into corresponding Clojure core functions (`clojure.core/or`, `clojure.core/==` etc.) and produce invalid queries.

=== Maps and Vectors in data

Say you have a document like so and you want to add it to an XTDB db:
[source,clj]
----
{:xt/id :me
 :list ["carrots" "peas" "shampoo"]
 :pockets {:left ["lint" "change"]
           :right ["phone"]}}
----
XTDB decomposes top-level sets and vectors as a collection of into triples
(which are fully indexed) so the query engine is able see all elements on the
base level. As a result of this the query engine is not required to traverse any
structures or any other types of search algorithm which would slow the query
down. The same thing should apply for maps so instead of doing `:pocket {:left
thing :right thing}` you should put them under a namespace, instead structuring
the data as `:pocket/left thing :pocket/right thing` to put the data all on the
base level. Like so:

[source,clj]
----
(xt/submit-tx
  node
  [[::xt/put
    {:xt/id :me
     :list ["carrots" "peas" "shampoo"]
     :pockets/left ["lint" "change"]
     :pockets/right ["phone"]}]
   [::xt/put
    {:xt/id :you
     :list ["carrots" "tomatoes" "wig"]
     :pockets/left ["wallet" "watch"]
     :pockets/right ["spectacles"]}]])
----

To query inside these vectors the code would be:

[source,clj]
----
(xt/q (xt/db node) '{:find [e l]
                     :where [[e :list l]]
                     :in [l]}
                   "carrots")
;; => #{[:you "carrots"] [:me "carrots"]}

(xt/q (xt/db node) '{:find [e p]
                     :where [[e :pockets/left p]]
                     :in [p]}
                   "watch")
;; => #{[:you "watch"]}
----

Note that `l` and `p` is returned as a single element as XTDB decomposes the
vector

[#datascript-differences]
== DataScript Differences

This list is not necessarily exhaustive and is based on the partial re-usage of
DataScript's query test suite within XTDB's query tests.

XTDB does not support:

- vars in the attribute position, such as `[e ?a "Ivan"]` or `[e _ "Ivan"]`

XTDB does _not yet_ support:

- `ground` (you can use alternatively use `identity`)
- `get-else` (see https://github.com/xtdb/xtdb/blob/e2f51ed99fc2716faa8ad254c0b18166c937b134/test/test/xtdb/query_test.clj#L1054[`get-attr`] which returns a relation instead)
- `get-some`
- `missing?` (however, instead of `[(missing? $ ?e :height)]` you can use `(not-join [?e] [?e :height])`)
- reverse attribute syntax in triple clauses (i.e. `[?child :example/_child ?parent]`), however reverse attribute joins (like `:example/_child`) are supported in `pull`

[#custom-functions]
== Custom Functions and Advanced Examples

Many advanced query requirements can be addressed using custom predicate function calls since you can reference any function that is loaded (and available on the classpath) by using its fully qualified name in a Datalog clause, e.g. `[(clojure.core/+ x y) z)]`.
These custom functions can be passed the `db` query context using the `$` argument convention for sophisticated nesting of queries and other lookups. Destructuring the results of a function as a relation is also supported, similarly to `:in` bindings.
The suite of functions in the `clojure.core` namespace may be referred to without the fully qualified prefix, including `clojure.core/eval`, however an xref:administration::configuring.adoc#fn-allowlist[allowlist feature] is available to help maintain security (particularly relevant when the HTTP server is being used).

These functions can be used, for example, to access data that is deeply nested with a given top-level value.

[source,clojure]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=get-in-data,indent=0]

include::example$test/xtdb/docs/examples/query_test.clj[tags=get-in,indent=0]

include::example$test/xtdb/docs/examples/query_test.clj[tags=get-in-2,indent=0]

include::example$test/xtdb/docs/examples/query_test.clj[tags=get-in-r,indent=0]
----
<1> Data
<2> Usage of `clojure.core/get-in` function with literal vector of keys
<3> Usage of `clojure.core/vector` function to construct intermediate vector value
<4> Result

Be aware during development that query compilation internalizes function definitions and this means that subsequent re-definitions of your custom functions may not be reflected until the query is modified and therefore re-compiled. During development, you can introduce a dummy predicate clause like `[(any? 1)]` (which always evaluates to `true` and has no effect on the query) and increment the integer when needed to bypass the effects of query caching.

The full range of XTDB APIs are available:

[source,clojure]
----
(defn get-vt-created [db eid]
  (with-open [h (xt/open-entity-history db eid :asc)]
    (-> (iterator-seq h)
        first
        ::xt/valid-time)))

(defn get-vt-last-updated [db eid]
  (with-open [h (xt/open-entity-history db eid :desc)]
    (-> (iterator-seq h)
        first
        ::xt/valid-time)))

(xt/q (xt/db my-node)
      '{:find [e vt-created vt-last-updated]
        :limit 1
        :where [[e :xt/id]
                [(dev/get-vt-created $ e) vt-created]
                [(dev/get-vt-last-updated $ e) vt-last-updated]]})

;;=> [[-219 #inst "2021-10-15T12:01:06.289-00:00" #inst "2021-10-15T12:15:11.020-00:00"]]
----

Many examples of advanced queries are showcased across the https://github.com/xtdb/xtdb/blob/main/test/test/xtdb/query_test.clj[query tests] and the suite of benchmarks maintained in the `bench` sub-project.
