= Datalog Transactions
:page-aliases: 1.23.0@reference::transactions.adoc

Transactions are how you insert and modify data within XTDB.

Transactions are atomic, and comprised of a sequence of operations to be performed.

If the transaction contains pre-conditions, all pre-conditions must pass, or the entire transaction is aborted.
This processing happens at each node during indexing, and not when submitting the transaction.

[tabs]
====
Java::
+
--
A transaction is performed by calling `.submitTx` on an `IXtdbSubmitAPI` with a `Transaction` object.

The `Transaction` object can be created by either using `Transaction.Builder` directly or using a `Consumer`.

If using the `Consumer` approach, we recommend importing `xtdb.api.tx.Transaction.buildTx` statically for brevity.

[source,java]
----
include::example$test/xtdb/docs/examples/transactions/TransactionsTest.java[tags=creating-0,indent=0]

include::example$test/xtdb/docs/examples/transactions/TransactionsTest.java[tags=creating-1,indent=0]

include::example$test/xtdb/docs/examples/transactions/TransactionsTest.java[tags=creating-2,indent=0]

// To run the transaction:
include::example$test/xtdb/docs/examples/transactions/TransactionsTest.java[tags=using-0,indent=0]

// To run a transaction directly:
include::example$test/xtdb/docs/examples/transactions/TransactionsTest.java[tags=using-1,indent=0]
----
--

Clojure::
+
--
A transaction is performed by calling `xtdb.api/submit-tx` on a node with a list of transaction operations.

[source,clj]
----
(xt/submit-tx node
                [
                ;; Operations
                ])
----
--
====

[#operations]
== Operations

There are five transaction (write) operations:

.Write Operations
[cols="3,5,^2"]
|===
|Operation|Purpose|Pre-condition?

|<<#put, Put>>|Write a version of a document|
|<<#delete, Delete>>|Deletes a specific document|
|<<#match, Match>>|Check the document state against the given document|✓
|<<#evict, Evict>>|Evicts a document entirely, including all historical versions|
|<<#transaction-functions, Function>>|Runs a transaction function|✓
|===

[tabs]
====
Java::
+
--
You can add individual operations to the `Transaction.Builder` instance with their respective methods.
--

Clojure::
+
--
Transaction Operations are vectors which have their associated keyword as their first value.
--
====

[#put]
=== Put

Puts a <<#document, Document>> into XTDB.
If a document already exists with the same `id`, a new version of this document will be created at the supplied `valid time`.
See <<valid-time, Valid Time>> for more details.

[tabs]
====
Java::
+
--
[source,java]
----
include::example$test/xtdb/docs/examples/transactions/TransactionsTest.java[tags=put,indent=0]
----
<1> Putting a document as of now.
<2> Putting a document with a specific <<valid-time, valid time>>
<3> Putting a document with a <<valid-time, valid time>> and <<end-valid-time, end valid time>>
--

Clojure::
+
--
[source,clojure]
----
include::example$test/xtdb/docs/examples/transactions/transactions_test.clj[tags=put,indent=0]
----
<1> Document to add
<2> (optional) <<valid-time,`valid time`>>
<3> (optional) <<end-valid-time,`end valid time`>>
--
====

[#delete]
=== Delete

Deletes a <<#document, Document>> . See <<valid-time,Valid Time>> for details on how this interacts with multiple versions of the document.

[tabs]
====
Java::
+
--
[source,java]
----
include::example$test/xtdb/docs/examples/transactions/TransactionsTest.java[tags=delete,indent=0]
----

<1> Deletes as of now
<2> Deleting with a specific <<valid-time, valid time>>
<3> Deleting with a <<valid-time, valid time>> and <<end-valid-time, end valid time>>
--

Clojure::
+
--
[source,clojure]
----
include::example$test/xtdb/docs/examples/transactions/transactions_test.clj[tags=delete,indent=0]
----
<1> Document ID to be deleted
<2> (optional) <<valid-time,`valid time`>>
<3> (optional) <<end-valid-time,`end valid time`>>
--
====

[#match]
=== Match

Match checks the state of an entity - if the entity doesn't match the provided document, the transaction will not continue.

Use the `hasTxCommitted` (`tx-committed?`) API to check whether the transaction was successfully committed or not due to a failed match operation.

[tabs]
====
Java::
+
--
[source,java]
----
include::example$test/xtdb/docs/examples/transactions/TransactionsTest.java[tags=match,indent=0]
----

<1> Passes if `document1` is exactly present now
<2> Passes if `document2` is exactly present at <<valid-time,`validTime1`>>
<3> Passes if there is no document with the id `documentId1` present now
<4> Passes if there is no document with the id `documentId2` present at <<valid-time,`validTime2`>>
<5> Operation(s) to apply if all preconditions are met
--

Clojure::
+
--
[source,clojure]
----
include::example$test/xtdb/docs/examples/transactions/transactions_test.clj[tags=match,indent=0]
----

<1> ID to be matched (for an entity which may or may not exist)
<2> A specific document revision (or `nil`)
<3> (optional) <<valid-time,`valid time`>>
<4> Operation(s) to perform if the document is matched

If the document supplied is `nil`, the match only passes if there does not exist a document with the given ID.
--
====

[#evict]
=== Evict

Evicts a document from XTDB. Historical versions of the document will no longer be available.

[tabs]
====
Java::
+
--
[source,java]
----
include::example$test/xtdb/docs/examples/transactions/TransactionsTest.java[tags=evict,indent=0]
----
--

Clojure::
+
--
[source,clojure]
----
include::example$test/xtdb/docs/examples/transactions/transactions_test.clj[tags=evict,indent=0]
----
--
====

Evict is primarily used for GDPR Right to Erasure compliance.

It is important to note that Evict is the only operation which will have effects on the results returned when querying against an earlier Transaction Time.

[#transaction-functions]
=== Transaction Functions

Transaction functions are user-supplied functions, defined using Clojure, that will run on each individual node where a transaction is being ingested and processed after having been read from the transaction log.
They are conceptually similar to "stored procedures" in traditional databases, except they can only return new transaction operations.

Transaction functions can be used, for example, to safely check the current database state before applying a transaction, for integrity checks, or to patch an entity.

It is critical that transaction functions are "pure" - as in they only use the information passed to them via explicit arguments.
This is essential for deterministic operation.
Actions like generating UUIDs or accessing the system clock would be examples of impurity that can easily lead to non-determinism and break the transactional guarantees that XTDB offers.
XTDB will not attempt to analyse a transaction function for purity, and instead relies on users to take sufficient care to avoid all forms of impurity.
Side-effects should also be avoided unless strictly needed (e.g. debug logging).

[#transaction-functions-anatomy]
==== Anatomy
[source,clojure]
----
include::example$test/xtdb/docs/examples/transactions/transactions_test.clj[tags=fn-anatomy,indent=0]
----
<1> Transaction functions are passed a `context` parameter and any number of other parameters.
<2> The `context` parameter can be used to obtain a database value using `db` or `open-db`.
<3> Transaction functions should return a list of transaction operations or `false`

If a list of transaction operations is returned, these are indexed as part of the transaction.

If `false` is returned, or an exception is thrown, the whole transaction will roll back.

The `context` reflects the speculative accumulation of all transaction operations applied up to the current point in the processing.

There is a `xtdb.api/indexing-tx` API available which can be passed the `context` to return information about the current, in-flight transaction (such as the new `tx-time` and `tx-id`).

==== Creating / Updating

Transaction functions are created/updated by submitting a document to XTDB with the desired function.

[tabs]
====
Java::
+
--
You create a function document with `XtdbDocument.createFunction`.

It takes the ID for the function as well as a string consisting of the Clojure function to run.

[source,java]
----
include::example$test/xtdb/docs/examples/transactions/TransactionsTest.java[tags=fn-put,indent=0]
----
--

Clojure::
+
--
The document should use the `:xt/fn` key (note, not `::xt/fn`).

[source,clojure]
----
include::example$test/xtdb/docs/examples/transactions/transactions_test.clj[tags=fn-put,indent=0]
----
<1> Note that the function itself is quoted
--
====

==== Usage

When invoking a transaction function, you specify its ID and (optionally) other arguments

[tabs]
====
Java::
+
--
[source,java]
----
include::example$test/xtdb/docs/examples/transactions/TransactionsTest.java[tags=fn-use,indent=0]
----
--

Clojure::
+
--
Note that the transaction function operation `::xt/fn` is Clojure shorthand for `:xtdb.api/fn` (assuming the `xt` require alias is used) - be careful not to confuse this keyword with the `:xt/fn` keyword used inside the transaction function document.

[source,clojure]
----
include::example$test/xtdb/docs/examples/transactions/transactions_test.clj[tags=fn-use,indent=0]
----
<1> Function ID
<2> Parameter(s)
--
====

Transaction functions may return further transaction function invocation operations, which will in turn expand recursively until there are only primitive transaction operations remaining for the given transaction.

[#document]
== Documents

[tabs]
====
Java::
+
--
A `XtdbDocument` is created with an ID that must be of a <<#valid-ids,valid type>>.

The instance itself is immutable and plusing/minusing data yields a new instance of `XtdbDocument`.

Similarly to Transactions, you can use `XtdbDocument.Builder` directly or use the `Consumer` approach.
[source,java]
----
include::example$test/xtdb/docs/examples/transactions/TransactionsTest.java[tags=doc-builder,indent=0]

include::example$test/xtdb/docs/examples/transactions/TransactionsTest.java[tags=doc-consumer,indent=0]

// You can also chain creating new instances of the document,
// but this will be slow for larger documents.
include::example$test/xtdb/docs/examples/transactions/TransactionsTest.java[tags=doc-direct,indent=0]
----
--

Clojure::
+
--
A document is a map from keywords to values.

[source,clj]
----
{:xt/id :dbpedia.resource/Pablo-Picasso
 :name "Pablo"
 :last-name "Picasso"}
----

All documents must contain the `:xt/id` key.

Persistence of Clojure metadata is not supported (although is not currently rejected either) - we strongly recommend that all metadata should be removed from each document prior to submission to XTDB, to avoid potential equality checking issues (see https://github.com/xtdb/xtdb/issues/1510[here] for more details).
--
====

For operations containing documents, the id and the document are
hashed, and the operation and hash is submitted to the `tx-topic` in
the event log. The document itself is submitted to the `doc-topic`,
using its content hash as key. In Kafka, the `doc-topic` is compacted,
which enables later eviction of documents.

[#valid-ids]
=== Valid IDs

[tabs]
====
Java::
+
--
The following types of document IDs are allowed:

.Valid ID types (Java)
[cols="d,d"]
|===
|Type|Example

|Keyword|`Keyword.intern("my-id")`
|String|`"my-id"`
|Long|`42L`
|UUID|`UUID.randomUUID()`
|URI|`URI.create("mailto:hello@xtdb.com")`
|IPersistentMap|`PersistentArrayMap.EMPTY.assoc("foo", "bar")`
|===

``URL``s are valid IDs for historical reasons, but discouraged due to their `hashCode` depending on a DNS lookup.
--

Clojure::
+
--
The following types of `:xt/id` are allowed:

.Valid ID types (Clojure)
[cols="d,d"]
|===
|Type|Example

|Keyword|`:my-id` or `:dbpedia.resource/Pablo-Picasso`
|String|`"my-id"`
|Integers/Longs|`42`
|UUID|`#uuid "6f0232d0-f3f9-4020-a75f-17b067f41203"`
|URI|`(URI. "mailto:hello@xtdb.com")`
|Maps|`{:this :id-field}`
|===

``URL``s are valid IDs for historical reasons, but discouraged due to their `hashCode` depending on a DNS lookup.
--
====

[#indexing]
=== Indexing

XTDB automatically indexes the top-level fields across all documents as Entity-Attribute-Value triples. Vector and Set values are indexed as cardinality-many values, i.e. producing multiple EAVs.

[#transaction-time]
== Transaction Time

When you submit a transaction, the current time will be the Transaction Time.

You can override the transaction time for a transaction (e.g. for importing data into XTDB from another bitemporal database) so long as:

* the transaction time provided is no earlier than any other transaction currently in the system - i.e. transaction times must be increasing.
* the transaction time is no later than the clock on the transaction log (e.g. Kafka) - i.e. transactions cannot be inserted into the future.

[tabs]
====
Java::
+
[source,java]
----
buildTx(tx -> {
  tx.put(document);
  tx.withTxTime(txTime);
});
----

Clojure::
+
[source,clojure]
----
(xt/submit-tx node
              [[::xt/put {:xt/id :foo}]]
              {::xt/tx-time #inst "2020"})
----
====

[#valid-times]
== Valid Times

When an optional `valid time` is omitted from a transaction operation, the Transaction Time will be used as `valid time`.

[#valid-time]
=== Only Valid Time Provided

When `valid time` is used as a parameter for Put or Delete, it specifies the time from which the change is valid.

If there is a document, `A`, already present at the given `valid time`, the operation's effect is valid from `valid time` to the end of the current validity of `A`.

[#end-valid-time]
=== End Valid Time

When both `valid time` and `end valid time` are provided for Put or Delete, the operation's effect is valid from `valid time` (inclusive) to `end valid time` (exclusive).

[#await]
== Awaiting Transactions

After a transaction is submitted, it needs to be indexed before it is visible in XTDB DB snapshots.

The return value from submitting the transaction can be used to wait for the transaction to be indexed.

This return value holds both the ID of the transaction, and the Transaction Time

[tabs]
====
Java::
+
--
In Java, you receive a `TransactionInstant` from the `submitTx` call.

[source,java]
----
include::example$test/xtdb/docs/examples/transactions/TransactionsTest.java[tags=ti,indent=0]
----
--

Clojure::
+
--
In Clojure, you receive a map from `submit-tx` containing `::xt/tx-id` and `::xt/tx-time`

[source,clojure]
----
include::example$test/xtdb/docs/examples/transactions/transactions_test.clj[tags=ti,indent=0]
----
--
====

[#speculative-transactions]
== Speculative transactions

You can submit speculative transactions to XTDB, to see what the results of your queries would be if a new transaction were to be applied.
This is particularly useful for forecasting/projections or further integrity checks, without persisting the changes or affecting other users of the database.

You'll receive a new database value, against which you can make queries and entity requests as you would any normal database value.
Only you will see the effect of these transactions - they're not submitted to the cluster, and they're not visible to any other database value in your application.

[tabs]
====
Java::
+
--
You submit these transactions to an instance of IXtdbDatasource using `withTx`:

[source,java]
----
include::example$test/xtdb/docs/examples/transactions/TransactionsTest.java[tags=with-tx,indent=0]
----
--

Clojure::
+
--
You submit these transactions to a database value using `with-tx`:

[source,clojure]
----
include::example$test/xtdb/docs/examples/transactions/transactions_test.clj[tags=speculative-0,indent=0]
include::example$test/xtdb/docs/examples/transactions/transactions_test.clj[tags=speculative-1,indent=2]
include::example$test/xtdb/docs/examples/transactions/transactions_test.clj[tags=speculative-2,indent=2]
include::example$test/xtdb/docs/examples/transactions/transactions_test.clj[tags=speculative-3,indent=2]
----
--
====

The entities submitted by the speculative Put take their valid time (if not explicitly specified) from the valid time of the `db` from which they were forked.

[#dropping-the-database]
== Dropping the database

XTDB does not currently provide any API to perform a "drop" operation (physical deletion) of the entire database. To drop the database, you must first manually call the `close` method on the node(s), and then delete both the index-store directory and the relevant data (or directories) for the backend modules used for the transaction log and document store components (as per your configuration).

For testing purposes you can use `Files/createTempDirectory` or equivalent.
