---
title: Clojure Configuration Cookbook
---

This document provides examples for the EDN configuration of XTDB components, to be supplied to `xtdb.api/start-node`.

== Log

Main article: link:/config/log[Log]

[#in-memory-log]
=== In-Memory

Main article: link:/config/log#_in_memory[in-memory log]

This is the default, and can be omitted.

[source,clojure]
----
{:log [:in-memory
       {;; -- optional

        ;; :instant-src (java.time.InstantSource/system)
        }]}
----

[#local-log]
=== Local disk

Main article: link:/config/log#_local_disk[local-disk log]

[source,clojure]
----
{:log [:local
       {;; -- required
        ;; accepts `String`, `File` or `Path`
        :path "/tmp/log"

        ;; -- optional

        ;; accepts `java.time.InstantSource`
        ;; :instant-src (InstantSource/system)

        ;; :buffer-size 4096
        ;; :poll-sleep-duration "PT1S"
        }]}
----

[#kafka]
=== Kafka

Main article: link:/config/log/kafka[Kafka]

[source,clojure]
----
{:log [:kafka
       {;; -- required
        :bootstrap-servers "localhost:9092"
        :topic-name "xtdb-log"

        ;; -- optional

        ;; :create-topic? true
        ;; :poll-duration #xt/duration "PT1S"
        ;; :properties-file "kafka.properties"
        ;; :properties-map {}
        ;; :replication-factor 1
        ;; :topic-config {}
        }]}
----

== Storage

Main article: link:/config/storage[Storage]

[#in-memory-storage]
=== In-Memory

Main article: link:/config/storage#in-memory[in-memory storage]

This is the default, and should be omitted.

[#local-storage]
=== Local disk

Main article: link:/config/storage#local-disk[local-disk storage]

[source,clojure]
----
{:storage [:local
           {;; -- required

            ;; accepts `String`, `File` or `Path`
            :path "/var/lib/xtdb/storage"

            ;; -- optional

            ;; :max-cache-bytes 536870912
           }]}
----

[#remote-storage]
=== Remote

Main article: link:/config/storage#remote[remote storage]

[source,clojure]
----
{:storage [:remote {;; -- required 
                    
                    ;; Each object store implementation has its own configuration - 
                    ;; see below for some examples.
                    :object-store [:object-store-implementation {}]}]

 ;; -- required for remote storage
 ;; Local directory to store the working-set cache in.
 :disk-cache {;; -- required

              ;; accepts `String`, `File` or `Path`
              :path "/tmp/local-disk-cache"

              ;; -- optional
              ;; The maximum proportion of space to use on the filesystem for the diskCache directory
              ;; (overridden by maxSizeBytes, if set).
              :max-size-ratio 0.75

              ;; The upper limit of bytes that can be stored within the diskCache directory (unset by default).
              :max-size-bytes 107374182400}

 ;; -- optional - in-memory cache created with default config if not supplied
 ;; configuration for XTDB's in-memory cache
 ;; if not provided, an in-memory cache will still be created, with the default size
 :memory-cache {;; -- optional

                ;; The maximum proportion of the JVM's direct-memory space to use for the in-memory cache
                ;; (overridden by `:max-size-bytes`, if set).
                :max-size-ratio 0.5

                ;; unset by default
                :max-size-bytes 536870912}

}
----

[#s3]
=== S3

Main article: link:/ops/aws#storage[S3]

[source,clojure]
----
{:storage [:remote
           {:object-store [:s3
                           {;; -- required
                            :bucket "my-bucket"

                            ;; -- optional

                            ;; :prefix "my-xtdb-node"
                            ;; :configurator (reify S3Configurator
                            ;;                 ...)
                           }]}]}
----

[#azure]
=== Azure Blob Storage

Main article: link:/ops/azure#storage[Azure Blob Storage]

[source,clojure]
----
{:storage [:remote
           {:object-store [:azure
                           {;; -- required
                            ;; --- At least one of storage-account or storage-account-endpoint is required
                            :storage-account "storage-account"
                            ;; :storage-account-endpoint "https://storage-account.privatelink.blob.core.windows.net"
                            :container "xtdb-container"

                            ;; -- optional

                            ;; :prefix "my-xtdb-node"
                            ;; :user-managed-identity-client-id "user-managed-identity-client-id"
                           }]}]}
----


[#google-cloud]
=== Google Cloud Storage

Main article: link:/ops/google-cloud#storage[Google Cloud Storage]

[source,clojure]
----
{:storage [:remote
           {:object-store [:google-cloud
                           {;; -- required
                            :project-id "xtdb-project"
                            :bucket "xtdb-bucket"

                            ;; -- optional

                            ;; :prefix "my-xtdb-node"
                           }]}]}
----

