version: '3'
services:
  s3proxy:
    image: andrewgaul/s3proxy:4.1.1@sha256:87662b2a5afcdfa5f478a1c61650bae4c87bbd15f6ff2823236bcfd66ef7fe04
    ports:
      - "9000:9000"
    environment:
      - S3PROXY_ENDPOINT=http://0.0.0.0:9000
      - S3PROXY_IDENTITY=xtdb
      - S3PROXY_CREDENTIAL=xtdb-secret-key
    volumes:
      - s3proxy_data:/data

  # a service simply to create the bucket
  s3proxy-setup:
    image: amazon/aws-cli:2.37.1
    depends_on:
      s3proxy:
        condition: service_healthy
    environment:
      - AWS_ACCESS_KEY_ID=xtdb
      - AWS_SECRET_ACCESS_KEY=xtdb-secret-key
      - AWS_REGION=us-east-1
    entrypoint: >
      /bin/sh -c "
      aws --endpoint-url http://s3proxy:9000 s3api head-bucket --bucket xtdb-bucket 2>/dev/null ||
      aws --endpoint-url http://s3proxy:9000 s3api create-bucket --bucket xtdb-bucket"

  kafka:
    image: confluentinc/cp-kafka:7.7.1
    expose:
      - 9092
      - 9999
      - 29092
      - 29093
    ports:
      - 29092:29092
      - 29093:29093
    environment:
      CLUSTER_ID: "1"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: "1"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"
      KAFKA_LISTENERS: "PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"

  xtdb:
    image: ghcr.io/xtdb/xtdb-aws:edge
    depends_on:
      kafka:
        condition: service_started
      s3proxy-setup:
        condition: service_completed_successfully
    expose:
      - 8080
      - 5432
      - 3000
    ports:
      - 8081:8080
      - 5433:5432
      - 3000:3000
    environment:
      AWS_REGION: "aws-iso-global"
      AWS_S3_FORCE_PATH_STYLE: "true"
      AWS_S3_USE_VIRTUAL_HOSTING: "false"
      XTDB_NODE_ID: "xt-node-1"
      KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
      XTDB_LOG_TOPIC: "xt_log"
      XTDB_S3_BUCKET: "xtdb-bucket"
      XTDB_S3_ENDPOINT: "http://s3proxy:9000"
      ACCESS_KEY: "xtdb"
      SECRET_KEY: "xtdb-secret-key"
    command: ["-f", "/config/dc_config.yaml"]
    volumes:
      - ./dc_config.yaml:/config/dc_config.yaml

volumes:
  s3proxy_data:
