= Developing XTDB2

The top-level project ties all the other projects together for convenience whilst working within this repo.
All of the below commands should be run in the *root* of the XT2 repo.

== Links

* https://github.com/orgs/xtdb/projects/13/views/1[Kanban board^]
* https://github.com/xtdb/xtdb/actions[Github Actions (CI)^]
* link:GIT.adoc[Git practices in XTDB]

== Prerequisites

You will need at least JDK 17 installed.

== Getting started

XT2 uses https://gradle.org/[Gradle] - a JVM build tool that supports multi-module, polyglot projects.
You do not need to install Gradle to develop XT2 - there is a Gradle https://docs.gradle.org/current/userguide/gradle_wrapper.html[wrapper] in the repo.

* Java classes are (re-)compiled automatically when you (re-)start a REPL or run tests
* Start a REPL with `./gradlew :clojureRepl`
* Once you've connected to the REPL, in the `user` namespace, run:
** `(dev)` to require and go to the `dev` namespace.
** `(go)` to start up the dev node
** `(halt)` to stop it
** `(reset)` to stop it, reload changed namespaces, and restart it
** if you're using Emacs/CIDER, `cider-ns-refresh` will do all this for you - `C-c M-n M-r`, `, s x` in Spacemacs, `, n r` in Doom.
** Conjure users can use `ConjureRefresh`, see the https://github.com/Olical/conjure#mappings[docs] for bindings
** see https://github.com/weavejester/integrant-repl[Integrant REPL] for more details.
* You should now have a running XTDB node under `dev/node` - you can verify this by calling `(xt/status node)` (in the `dev` namespace).
* Most of the time, you shouldn't need to bounce the REPL, but:
** if you add a module, or change any of the dependencies of any of the modules, that'll require a REPL bounce.
** if you change any of the Java classes, that'll require a REPL bounce
** otherwise, `(dev/reset)` (or just `(reset)` if you're already in the `dev` ns) should be sufficient.
** Please don't put any more side-effecting top-level code in dev namespaces - you'll break this reload ability and make me sad.
** To run a single test file, run (e.g.) `./gradlew test --tests 'xtdb.api_test**'`
** Run `git config core.hooksPath .githooks` to add xtdb hooks to your local repo.

== Testing

* Test all with `./gradlew test`; `./gradlew integration-test` for longer tests
* Some tests have external dependencies which require `docker-compose`:
** `docker-compose up` (`docker-compose up <postgres|kafka>` etc for individual containers),
** `./gradlew jdbc-test` / `./gradlew kafka-test`
** `docker-compose down`

=== Auth for testing cloud based resources 

.*S3* (ensure all of the below are done on a consistent region):
* Need to ensure the `s3-stack` is setup via CloudFormation
** See the README for more info here.
* Need to log in to the AWS CLI - using `aws configure sso` 
* Need to assume the role on the CLI - `aws sts assume-role --role-arn <ARN of XTDBIamRole> --role-session-name <session-name> --profile <SSO profile>`
* Set `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` & `AWS_SESSION_TOKEN` from the output 
  of the above, then set AWS_REGION=<region for the cloudformation>
* Start the Gradle REPL and connect to it, to have all of the AWS creds available.

.*Azure*
* Ensure the Azure stack, `azure-resource-manager/azure-stack.json` stack is setup via the Azure deployment manager.
** See the README for more info here.
* Ensure a user/app registration is created with the create `xtdb-custom-role`.
* Create an access token for said user/app registration.
* Set `AZURE_CLIENT_ID` & `AZURE_CLIENT_SECRET` from the created access token. 
* Set `AZURE_TENANT_ID` based on the tenant id on which you created the user/app registration/  
* Set `AZURE_SUBSCRIPTION_ID` based on whichever subscription you created the stack on.
* Start the Gradle REPL and connect to it, to have all of the Azure creds available.

.*Google Cloud*
* Ensure the Google Cloud deployment, `cloud-deployment-manager/xtdb-object-store-stack.jinja`, is setup on the XTDB google cloud account.
** See the README for more info here.
* Ensure a https://console.cloud.google.com/iam-admin/serviceaccounts[Service Account] has been created for tests.
** Ensure the Service Account has the XTDB Custom Role created by the deployment above.
* Create a private key for the service account, saving a copy of the JSON credential file locally.
* Authenticate as the service account, using `gcloud auth activate-service-account <example-service-account@domain.com> --key-file <private-key.json>`
* Start the Gradle REPL and connect to it, to have all of the google cloud creds available.


== Profiling

To attach YourKit:

* Install YourKit (it's on the AUR, for Arch folks)
* `./gradlew :clojureRepl -Pyourkit`
+
This assumes YourKit is installed under `/opt/yourkit` (as it does from the AUR) - feel free to adapt the property (or even use its value) if you have it installed elsewhere.

== Releasing XT2

See link:RELEASING.adoc[].

== Arrow Fork

We maintain a fork of [Arrow](https://github.com/apache/arrow) to fix a couple of issues in `DenseUnionVector` - see [this diff](https://github.com/apache/arrow/compare/master...juxt:master) for more details.

To upgrade Arrow:

* Usual bump in `project.clj`
* Clone the [Arrow repo](https://github.com/apache/arrow), add the [JUXT fork](https://github.com/juxt/arrow) as a remote.
* Rebase `juxt/master` on the upstream tag.
* In xtdb2, `./bin/rebuild-forked-arrow-files.sh`
* Test
* Push (`--force-with-lease`) to JUXT fork, and commit to XT2.
