= Releasing Core2

We could automate more of this than we do, but here's a checklist in the meantime.

You can kick off a couple of these in parallel, but note the various 'await' items.

Version number is `Major.Minor.Patch`, e.g. `1.23.0`.
We use https://github.com/ptaoussanis/encore/blob/master/BREAK-VERSIONING.md[BreakVer].

== Git tag:

. find/replace `<previous-version>` -> `<next-version>`, commit
. `git tag --annotate --sign <next-version>` (magit `t -a -s t`), add release notes to tag.
. `git push origin master <next-version>`

== CircleCI

. Await https://app.circleci.com/pipelines/github/xtdb/core2[CircleCI build]

== Jars

To build the XTDB release artifacts locally and deploy them to Sonatype, run:

Build and deploy release jars

. `java -version` -> java-11-openjdk
. `git clean -dXf`
. `export CORE2_VERSION=1.23.0` (`set -x CORE2_VERSION=1.23.0` for the fish people)
. `./gradlew publish`

Release the artifacts to central

. Head over to https://s01.oss.sonatype.org, 'Log in', 'Staging Repositories'
. 'Close' the repo (performs validations)
. 'Release' the repo
. Check https://repo1.maven.org/maven2/com/xtdb to see when the artifacts have been mirrored across Maven Central.

It may be sensible to update `dev-SNAPSHOT` in response to the release, unless it is already ahead.

. `unset CORE2_VERSION` and deploy the new release as link:#releasing-snapshots[dev-SNAPSHOT]

== Docs:

NOTE: TODO: document deploying documentation site.

== Github release:

. Create a new milestone and ensure that all issues in the "Awaiting Release" column are updated
. Locate tag on https://github.com/xtdb/core2/releases[releases page], click 'Edit tag'
. Copy release notes into release description
. Await artifacts, upload artifacts to release
. Await JARs deploying, and ensure 'docs' section is complete - people get notified at this point.
. 'Publish release'
. 'Archive all cards' for the "Awaiting Release" column

== Publicise:

* Discourse
* Clojurians' Slack
* Zulip
* Twitter, if appropriate

[#releasing-snapshots]
== Building locally and releasing JAR snapshots:

.  (none of the above sections are required)
.  `java -version` → java-11-openjdk
.  `git clean -dXf`
.  `./gradlew publish`
.  (nothing to be done in Sonatype!)
.  Confirm snapshot is live at https://s01.oss.sonatype.org/content/repositories/snapshots/com/xtdb/labs/core2-core/dev-SNAPSHOT/
