= Releasing XTDB

We could automate more of this than we do, but here's a checklist in the meantime.

You can kick off a couple of these in parallel (particularly, `./lein-sub install && ./lein-sub do check, test` takes ~10 mins) but note the various 'await' items.

Version number is `Major.Minor.Patch`, e.g. `1.21.0`.
We use https://github.com/ptaoussanis/encore/blob/master/BREAK-VERSIONING.md[BreakVer].

## Git tag:

. find/replace `<previous-version>` -> `<next-version>`, commit
. `git tag --annotate --sign <next-version>` (magit `t -a -s t`), add release notes to tag.
. `git push origin main <next-version>`

## CircleCI

. Await https://app.circleci.com/pipelines/github/xtdb/xtdb[CircleCI build]
. Manually approve hold - this kicks off the Maven deploy, building the API docs, deploying Docker images etc.

If you're building XTDB locally, run:

. `git clean -dXf`
. `export XTDB_VERSION=1.21.0` (`set -x XTDB_VERSION=1.21.0` for the fish people)
. `./lein-sub install && ./lein-sub do check, test`
. `./lein-sub deploy`
. (in `labs/corda`): `./gradlew clean publish`

## JARs:

. Head over to https://s01.oss.sonatype.org, 'Log in', 'Staging Repositories'
. 'Close' the repo (performs validations)
. 'Release' the repo
. Check https://repo1.maven.org/maven2/com/xtdb to see when the artifacts have been mirrored across Maven Central.

## Artifacts:

. Await CircleCI.
. Await JAR upload (above) - required for Docker images.
. Retrieve artifacts from build: xtdb-builder.tar.gz, xtdb-in-memory.jar

## Docs:

. Await CircleCI.
. Create a `docs-v<next-release>` branch
. For each `docs/**/antora.yml`:
    a. Delete `prerelease: indeed`
    b. Delete `display_version: master` lines
    c. Replace `version: master` to `version: <next-release>`
    d. Commit
. For each `docs/**/*.adoc`: (Page Aliases Option 1)
    a. Replace `:page-alias: foo` with `:page-alias: <new-version>@foo`
. Alternatively: (Page Aliases Option 2)
    . Cherry pick the 'versioning page aliases' commit from the previous version's docs branch
    . Another version find/replace
    . Amend commit
. Commit, push branch to https://github.com/xtdb/xtdb
. Run `./bin/build.sh`. You should not get any errors.
. Run `./bin/deploy.sh`. You will need AWS credentials.

## Github release:

. Create a new milestone and ensure that all issues in the "Awaiting Release" column are updated
. Locate tag on https://github.com/xtdb/xtdb/releases[releases page], click 'Edit tag'
. Copy release notes into release description
. Await artifacts, upload artifacts to release
. Await JARs deploying, and ensure 'docs' section is complete - people get notified at this point.
. 'Publish release'
. 'Archive all cards' for the "Awaiting Release" column

## Publicise:

* Zulip
* Clojurians' Slack
* Discourse
* Twitter, if appropriate
