= Google Cloud Module

Within our XTDB node, we can make use of Google Cloud Services for certain purposes. Currently, we can:

* Use *Google Cloud Storage* as one of the XTDB Object Stores used by the remote storage module.

== Project Dependency 

In order to use any of the Google Cloud services, you will need to include a dependency on the `xtdb-google-cloud` module.

_deps.edn_
[source,clojure]
----
com.xtdb.labs/xtdb-google-cloud {:mvn/version "2.0.0-SNAPSHOT"}
----

_pom.xml_
[source,xml]
----
<dependency>
    <groupId>com.xtdb.labs</groupId>
    <artifactId>xtdb-google-cloud</artifactId>
    <version>2.0.0-SNAPSHOT</version>
</dependency>
----

== Authentication

Authentication for both the document store and checkpoint store components within the module is handled via Google’s "Application Default Credentials" - see the https://github.com/googleapis/google-auth-library-java/blob/main/README.md#application-default-credentials[*relevant documentation*] to get set up.
You will need to setup authentication using any of the methods listed within the documentation to be able to make use of the operations inside the modules.

Whatever method used to authenticate, you will need to ensure it has the correct permissions.
Alongside the various bits of infrastructure required for the object store, we create a custom XDTB IAM role.
One can use this role to provide all necessary permissions for the object store and the resources it is using on Google cloud, otherwise you will need to ensure whichever credentials you are using to authenticate XTDB have the same level of permissions to the miscellaneous services.
See the custom role definition in the link:cloud-deployment-manager/xtdb-object-store-stack.jinja[Google Cloud Deployment Manager stack] for what exactly that includes.

== Google Cloud Storage Object Store

We can swap out the implementation of the object store with one based on Google Cloud Blob Storage.
To do so, we can add the `:google-cloud` object store and it's configuration map, within the remote storage module config for our node:

We can swap out the implementation of the object store with one based on Google Cloud Blob Storage.
To do so, we add a `:google-cloud` section within the Integrant config for our node, alongside any config:
```clojure
{:storage [:remote {:object-store [:google-cloud {:project-id "your-project-id"
                                                  :bucket "your-storage-bucket"}]
                    :local-disk-cache local-disk-cache}]}
```

Below follows the various parameters used by the module, and some notes around the provided <<deployment-manager, Google Cloud Deployment Manager configuration template>> which sets up all of the necessary infrastructure.

=== Parameters

These are the following parameters that can be passed within the config for the Google Cloud Storage object store:
[cols="1,1,2,1"]
|===
| *Name* | *Type* | *Description* | *Required?*
| `project-id`
| String
| The name of the GCP project that the bucket is contained within
| Yes

| `bucket`
| String 
| The https://cloud.google.com/storage/docs/buckets[Cloud Storage bucket] which the documents will be stored within
| Yes

|`prefix`
| String/File/Path 
| A file path to prefix all of your files with - for example, if "foo" is provided all xtdb files will be located under a "foo" directory
| No
|=== 

[#deployment-manager]
=== Google Cloud Deployment Manager Configuration

In order to handle the various bits of Google Cloud infrastructure required to use a Cloud Storage bucket as an XTDB object store, we provide a link:cloud-deployment-manager/xtdb-stack.yaml[Google Cloud Deployment Manager Configuration] to setup everything that you should need.
Read below for more details on what's required in your Google Cloud project, what the configuration sets up and how to customize it, and how to deploy the configuration.

==== Requirements in the Google Cloud Project

In order to use our configuration to create the infrastructure, we will need the following APIs active within the project:

* Cloud Storage API
* IAM API
* Cloud Deployment Manager API

Within the configuration, we create a custom IAM role for all of the necessary infrastructure. In order for **Cloud Deployment Manager** to create this, it will require IAM permissions to do so:

* See https://cloud.google.com/iam/docs/maintain-custom-roles-deployment-manager#grant_permissions["Grant permissions to the Google APIs service account"] on how to do this, and what permissions it requires.

==== Configurable Properties

Within our Google Cloud Deployment Manager Configuration, we use a https://cloud.google.com/deployment-manager/docs/configuration/templates/create-basic-template[**configurable template**] that takes a set of properties. We can use these to configure the created resources. 

The properties within the file are as follows:

* `object_store_bucketname` (default `xtdb-object-store`) - the name of the Cloud Storage bucket that will be created and used as our XTDB object store.
* `bucket_location_type` (default `region`) - the https://cloud.google.com/storage/docs/locations[location type] of the created bucket, this can be use either `region`, `dual-region`, or `multi-region`.
* `bucket_location` (default `EUROPE-WEST2`) - the https://cloud.google.com/storage/docs/locations[bucket location] of the created bucket. Available values depend on the `bucket_location_type` - see https://cloud.google.com/storage/docs/locations#available-locations["Available locations"] for more info.
* `custom_role_name` (default `xtdb_custom_role`) - the name of the custom XTDB role to create with all of the permissions it will need for the Cloud Storage buckets.
* `custom_role_additional_permissions`` (default `[]`) - a list of any extra IAM roles you want the custom XTDB role to have. Defaults to an empty list, and creates only the permissions we need for XTDB. 

==== Created Resources

Deploying configuration file will create the following resources within the specified project in Google Cloud:

* A Cloud Storage bucket
* A custom role for all of the necessary permissions for XTDB to use the bucket (get, create, delete, list, and update storage objects)

==== How to deploy the configuration

In the following example, we deploy the Cloud Deployment Manager configuration using the `gcloud` command line tool:

* See https://cloud.google.com/sdk[**here**] for more details. 
* Ensure that you are https://cloud.google.com/sdk/gcloud/reference/auth/login[authenticated with the CLI] and have sufficient permissions to use deployment manager.

Ensure you have the contents of the `cloud-deployment-manager` folder. Once you have configured the `xtdb-stack.yaml` file to your liking, run the following command:

```bash
gcloud deployment-manager deployments create <deployment-name> --config cloud-deployment-manager/xtdb-stack.yaml
```

Replace `deployment-name` with a user readable name for the deployment in Cloud Deployment Manager, such that you can easily find and update it if and when you need to.
