AWSTemplateFormatVersion: '2010-09-09'
Parameters: 
  Description: 
    Type: String
    Description: Description of your application for Elastic Beanstalk Resources
    Default: "Some Application"
  CNAMEPrefix:
    Type: String
    Description: Prefix to be used in the generated CNAME
Resources:
  BeanstalkInstanceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkMulticontainerDocker
  BeanstalkInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref BeanstalkInstanceRole
  Application:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      Description: !Ref Description
  ConfigurationTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName: !Ref Application
      Description: !Join [" ", [!Ref Description, "Configuration"]]
      OptionSettings:
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: IamInstanceProfile
        Value: !Ref BeanstalkInstanceProfile
      - Namespace: aws:autoscaling:asg
        OptionName: MinSize
        Value: '1'
      - Namespace: aws:autoscaling:asg
        OptionName: MaxSize
        Value: '1'
      - Namespace: aws:elasticbeanstalk:environment
        OptionName: EnvironmentType
        Value: LoadBalanced
      - Namespace: aws:elasticbeanstalk:cloudwatch:logs
        OptionName: StreamLogs
        Value: true
      SolutionStackName: 64bit Amazon Linux 2018.03 v2.8.2 running Java 8
  Environment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref Application
      Description: !Join [" ", [!Ref Description, "Environment"]]
      CNAMEPrefix: !Ref CNAMEPrefix
      TemplateName: !Ref ConfigurationTemplate
