= AWS Auctionmark Benchmark

Contained within this folder are a number of things for setting up & running a cluster of containerized auctionmark running worker tasks.

Within this README is the following:

* Instructions for setting up the docker image.
* How to setup the infra needed on AWS.
* How to push the docker image to ECR.

== Creating the Docker Image

Included within this folder is a script, `build-aws-bench.sh`, which does the following:

* Creates a Shadow JAR of the `cloud-benchmark:aws` project.
** This contains the compiled `cloud-benchmark` project, which has a main file that runs auctionmark & configures it with provided node config, and also any of the dependencies we require to run the AWS module.
* Creates a docker image, copying in the Shadow JAR and the `aws-config.yaml` file with the node config.
** If you want to set any JVM opts - do it by editing the Dockerfile's `ENTRYPOINT`.


It will build the local image as `xtdb-aws-bench:latest`.

== Setting up the AWS Infra

To setup the necessary infrastructure on AWS, we shall reuse some of the existing cloudformation config found within the `/cloudformation` folder.

* We have a guide for setting this up, see https://docs.xtdb.com/guides/starting-with-aws.html - though with the following Caveat:
** From here we will only use the first three stacks, ie:
*** `xtdb-vpc`: To set up a sample VPC to be used by the other infrastructure
*** `xtdb-s3`: To set up all S3 infrastructure & permissions that are required to be used for an XTDB Object Store
*** `xtdb-msk`: To set up an MSK Kafka cluster for use as the XTDB log (depends on `xtdb-vpc`)
** Follow the instructions in the above guide accordingly.

Once you have the above stacks setup, you can then proceed to setup the `xtdb-aws-bench.yaml` stack from this directory:

NOTE: We will initially set up the resources, and the ECS cluster with `0` desired tasks - we will scale these up AFTER we have uploaded the docker image to ECR.  

* Upload the cloudformation template, passing required parameters from the above stacks.
** See the link:https://docs.xtdb.com/guides/starting-with-aws.html#_setting_up_the_nodes_on_ecs["Setting up the nodes on ECS"] section of the "Starting with AWS" guide if you need help with where to find all of these. 
* This will set up the ECS cluster, EC2 instance, various IAM setup and the like. It will create a service with `0` tasks, by default. 
** It will output the ECR repository URL, which we will use to push the docker image to.
* **Push the docker image to ECR** before proceeding to the next step.
* OPTIONAL: You can also set a slack webhook URL to post successes/errors to a slack channel - you will need to update the value of the created SecretsManager secret `bench/secrets` to add the relevant `SLACK_WEBHOOK_URL`.
* You can now update the stack to set the desired number of tasks to run - along with any other config you may want to set - these will now be running under your service and you can observe the logs in CloudWatch.

Some notes about updating what is running/elements of the stack:

* If you are making changes to the project/contents of the docker image itself itself, you will need to push a new image to the ECR repository, and spin up new ECS tasks accordingly (pushes to fixed images such as `latest` are not propagated automatically and will only apply to newly created tasks). Some examples of changes that would require a new image push are:
** Changes to the `aws-config.yaml` file
** Changes to the `logback.xml` configuration
** Changes to the `cloud-benchmark` project
*** Updating any of the files (`run_auctionmark/main.clj`) or the dependencies
*** Ensure you build a new shadow JAR prior to building a new version of the docker image - the `build-aws-bench.sh` script will do this for you.
* If you want to update any of the Auctionmark cnfiguration, set up a slack webhook URL or change the desired running ECS task count, you can set appropriate parameters on the stack.
* If you want otherwise want to change any of the infra, you can update the `xtdb-aws-bench.yaml` config and upload the updated the stack on `cloudformation`. 

== Pushing the Docker Image to ECR

With the AWS infrastructure setup, we can now push the docker image to ECR - see the guide [here](https://docs.aws.amazon.com/AmazonECR/latest/userguide/docker-push-ecr-image.html)

In summary:

* Ensure you are configured/signed in on the AWS CLI with the correct account
* Login to ECR: `aws ecr get-login-password --region <region> | docker login --username AWS --password-stdin <account>.dkr.ecr.<region>.amazonaws.com`
* Tag the image: `docker tag xtdb-aws-bench:latest <ECR Repository URL>:latest`
* Push the image: `docker push <ECR Repository URL>:latest`
