---
title: Introducing XTQL
---

:test: ../src/test/clojure/xtdb/docs/xtql_walkthrough_test.clj
:example: ../src/test/resources/docs/xtql_tutorial_examples.yaml

XTDB is queryable using two query languages: **SQL** and **XTQL**.

XTQL is our new, data-oriented, composable query language:

* It is inspired by the strong theoretical bases of both **Datalog** and **relational algebra**.
  These two combine to create a joyful, productive, interactive development experience, with the ability to build queries iteratively, testing and debugging smaller parts in isolation.
* It is designed to be highly amenable to dynamic query generation - we believe that our industry has spent more than enough time trying to generate SQL strings (not to mention the concomitant https://owasp.org/www-community/attacks/SQL_Injection[security vulnerabilities^]).

== Querying XTQL

XTQL can either be queried within an SQL query, or via the Clojure API.

To query XTQL within a SQL query, you can either execute it:

* as a top-level query (like SQL's `VALUES`): `XTQL &dollar;&dollar; <query> &dollar;&dollar;`:
+
[source,sql]
----
XTQL $$
  (-> (from :users [first-name last-name])
      ...)
$$
----
* or within a wider SQL query:
+
[source,sql]
----
SELECT ...
FROM (XTQL $$
  (-> (from :users [first-name last-name])
      ...)
$$) u
ORDER BY u.last_name DESC, u.first_name DESC
LIMIT 10
----

[#operators_and_relations]
== 'Operators' and 'relations'

XTQL is built up of small, composable 'operators', which combine together using 'pipelines' into larger queries.

* 'Source' operators (e.g. 'read from a table') each yield a 'relation' - an unordered bag of rowsfootnote:[rows ... which themselves are otherwise known as 'maps', 'structs', 'records' or 'dictionaries' depending on your persuasion 😄].
* 'Tail' operators (e.g. 'filter a relation', 'calculate extra fields') transform a relation into another relation.

From these simple operators, we can build arbitrarily complex queries.

Our first operator is `from`:

=== `from`

The `from` operator allows us to read from an XTDB table.
In this first example, we're reading the first-name and last-name fields from the `users` table - i.e. `SELECT first_name, last_name FROM users`:

[source,clojure]
----
(from :users [first-name last-name])
----

It's in the `from` operator that we specify the temporal filter for the table.
By default, this shows the table at the current time, but it can be overridden:

* to view the table at another point in time
* to view the changes to the table within a given range
* to view the entire history of the table

[source,clojure]
----
(from :users {:bind [first-name last-name]

              ;; at another point in time
              :for-valid-time (at #inst "2023-01-01")

              ;; within a given range
              :for-valid-time (in #inst "2023-01-01", #inst "2024-01-01")
              :for-valid-time (from #inst "2023-01-01")
              :for-valid-time (to #inst "2024-01-01")

              ;; for all time
              :for-valid-time :all-time

              ;; and all of the above :for-system-time too.
              })
----

In the `from` operator, we can also rename columns, and filter rows based on field values:

* We rename a column using a binding map:
+
[source,clojure]
----
include::{test}[tags=bo-xtql-1,indent=0]
----
+
[source,sql]
----
include::{example}[tags=bo-sql-1,indent=0]
----
+
* We can look up a single user-id by specifying a literal in the binding map:
+
[source,clojure]
----
include::{test}[tags=bo-xtql-2,indent=0]
----
+
[source,sql]
----
include::{example}[tags=bo-sql-2,indent=0]
----

Another source operator is `rel`, which allows you to specify an inline relation.

You can check out the link:/reference/main/xtql/queries.html#_source_operators[source operators reference] for more details.

=== Pipelines

We can then transform the rows in a table using tail operators, which we pass in an operator 'pipeline'.
Pipelines consist of a single source operator, and then arbitrarily many tail operators.

Here, we demonstrate `SELECT first_name, last_name FROM users ORDER BY last_name, first_name LIMIT 10`, introducing the 'order by' and 'limit' operators:

In Clojure, we use `+->+` to denote a pipeline - in a similar vein to the threading macro in Clojure 'core' footnote:[although XTQL's `+->+` isn't technically macro-expanded - it's just data.], we take one source operator and then pass it through a series of transformations.

[source,clojure]
----
(-> (from :users [first-name last-name])
    (order-by last-name first-name)
    (limit 10))
----

By building queries using pipelines, we are now free to build these up incrementally, trivially re-use parts of pipelines in different queries, or temporarily disable some operators to test parts of the pipeline in isolation.

Other tail operators include `where` (to filter rows), `return` (to specify the columns to output), `with` (to add additional columns based on the existing ones), and `aggregate` (grouping rows - counts, sums, etc).
For a full list, see the link:/reference/main/xtql/queries.html#_tail_operators[tail operators reference].

[#unify]
=== Multiple tables - introducing `unify`

Joining multiple tables in XTQL is achieved using Datalog-based 'unification'.

We introduce the `unify` source operator, which takes an unordered bag of input relations and joins them together using 'unification constraints' (similar to join conditions).

Each input relation (e.g. `from`) defines a set of 'logic variables' in its bindings.
If a logic variable appears more than once within a single unify clause, the results are constrained such that the logic variable has the same value everywhere it’s used.
This has the effect of imposing 'join conditions' over the inputs.

* In this case, we re-use the `user-id` logic variable to indicate that the `:xt/id` from the `:users` table should be matched with the `:author-id` of the `:articles` table.
+
[source,clojure]
----
include::{test}[tags=joins-xtql-1,indent=0]
----
+
[source,sql]
----
include::{example}[tags=joins-sql-1,indent=0]
----

+
* For non-equality cases, we can use a link:../reference/main/xtql/queries.html#_where[`where`] clause (where we have a full SQL-inspired expression standard library at our disposal)
+
[source,clojure]
----
;; 'find me all the users who are the same age'
include::{test}[tags=joins-xtql-2,indent=0]
----
+
[source,sql]
----
include::{example}[tags=joins-sql-2,indent=0]
----
+
* We can specify that a certain match is optional using link:/reference/main/xtql/queries.html#_joins[`left-join`]:
+
[source,clojure]
----
include::{test}[tags=joins-xtql-3,indent=0]
----
+
[source,sql]
----
include::{example}[tags=joins-sql-3,indent=0]
----
+
Here, we're asking to additionally return customers who haven't yet any orders (for which the order-table columns will be absent in the results).
* Or, we can specify that we only want to return customers who _don't_ have any orders, using link:/reference/main/stdlib/predicates.html#_boolean_functions[`not`] link:/reference/main/xtql/queries.html#_subqueries[`exists?`]:
+
[source,clojure]
----
include::{test}[tags=joins-xtql-4,indent=0]
----
+
[source,sql]
----
include::{example}[tags=joins-sql-4,indent=0]
----

The `unify` operator accepts 'unify clauses' - e.g. `from`, `where`, `with`, `join`, `left-join` - a full list of which can be found in the link:/reference/main/xtql/queries.html#_unify_clauses[unify clause reference guide].

=== Projections

* We can create new columns from old ones using link:../reference/main/xtql/queries.html#_with[`with`]:
+
[source,clojure]
----
include::{test}[tags=proj-xtql-1,indent=0]
----
+
[source,sql]
----
include::{example}[tags=proj-sql-1,indent=0]
----
+
We can also use link:../reference/main/xtql/queries.html#_with[`with`] within link:../reference/main/xtql/queries.html#_unify[`unify`] - this creates new logic variables which we can then unify in the same way.
+
* Where link:../reference/main/xtql/queries.html#_with[`with`] adds to the available columns, link:../reference/main/xtql/queries.html#_return[`return`] only yields the specified columns to the next operation:
+
[source,clojure]
----
include::{test}[tags=proj-xtql-2,indent=0]
----
+
[source,sql]
----
include::{example}[tags=proj-sql-2,indent=0]
----
* Where we don't need any additional projections, we can use link:../reference/main/xtql/queries.html#_without[`without`]:
+
[source,clojure]
----
include::{test}[tags=proj-xtql-3,indent=0]
----
+
[source,sql]
----
include::{example}[tags=proj-sql-3,indent=0]
----

=== Aggregations

To count/sum/average values, we use link:../reference/main/xtql/queries.html#_aggregate[`aggregate`]:

[source,clojure]
----
include::{test}[tags=aggr-xtql-1,indent=0]
----

[source,sql]
----
include::{example}[tags=aggr-sql-1,indent=0]
----

=== Set Operations

XTQL provides powerful set operations that allow you to combine, intersect, and compare results from multiple queries. These operations treat query results as mathematical sets and follow standard relational algebra principles.

Set operations are particularly useful when you need to:

* Combine data from different tables or sources
* Find commonalities between datasets
* Identify differences between query results
* Remove duplicates from complex queries

==== Basic Set Operations

The most common set operations are `union`, `intersect`, and `except`:

[source,clojure]
----
;; Combine customers and suppliers (removing duplicates)
(union
  (from :customers [{:name name, :city city}])
  (from :suppliers [{:name company-name, :city location}]))

;; Find cities that have both customers and suppliers
(intersect
  (-> (from :customers [{:city city}]) (return {:location city}))
  (-> (from :suppliers [{:city city}]) (return {:location city})))

;; Find customers who haven't placed orders
(except
  (from :customers [{:customer-id customer-id, :name name}])
  (-> (from :orders [{:customer-id customer-id}])
      (return {:customer-id customer-id, :name ""}))) ; simplified example
----

Each operation has an `-all` variant that preserves duplicates according to set theory rules:

[source,clojure]
----
;; union-all: preserves all rows, including duplicates
(union-all
  (from :sales-q1 [{:product product, :region region}])
  (from :sales-q2 [{:product product, :region region}]))

;; intersect-all: returns minimum count from each side
(intersect-all
  (from :inventory-a [{:product product}])
  (from :inventory-b [{:product product}]))

;; except-all: subtracts right-side count from left-side
(except-all
  (from :ordered-items [{:product product}])
  (from :shipped-items [{:product product}]))
----

==== Set Operations in Pipelines

Set operations can also be used as tail operators within pipelines, combining the current pipeline result with another query:

[source,clojure]
----
;; Find all engineering staff (employees + contractors)
(-> (from :employees [{:name name, :dept dept}])
    (where (= dept "Engineering"))
    (union (from :contractors [{:name name, :dept dept}])))

;; Find featured products that are also high-priced
(-> (from :products [{:category category, :price price}])
    (where (> price 100))
    (intersect (from :featured-products [{:category category, :price price}])))

;; Remove duplicates from a combined dataset
(-> (from :orders [customer-id])
    (union-all (from :quotes [customer-id]))
    (distinct))
----

==== Advanced Set Operations

You can nest set operations to create more complex queries:

[source,clojure]
----
;; Find products that are either (in category A or B) AND (high-demand or featured)
(intersect
  (union
    (from :products [{:product product, :category "A"}])
    (from :products [{:product product, :category "B"}]))
  (union
    (from :high-demand-products [{:product product}])
    (from :featured-products [{:product product}])))
----

Set operations integrate seamlessly with other XTQL features like aggregation and parameters:

[source,clojure]
----
;; Combine quarterly sales and calculate totals
(-> (union-all
      (from :sales-q1 [{:region region, :amount amount}])
      (from :sales-q2 [{:region region, :amount amount}]))
    (aggregate region {:total-sales (sum amount)}))

;; Parameterized set operation
(fn [target-status]
  (except
    (-> (from :users [{:user-id user-id, :status status}])
	(where (= status target-status)))
    (from :suspended-users [{:user-id user-id, :status status}])))
----

For complete details on set operations, including multiplicity handling and schema compatibility requirements, see the link:/reference/main/xtql/queries.html#_set_operations[Set Operations reference guide].

=== 'Pull'

When we've found the documents we're interested in, it's common to then want a tree of related information.
For example, if a user is reading an article, we might also want to show them details about the author as well as any comments.

(Users of existing EDN Datalog databases may already be familiar with link:../reference/main/xtql/queries.html#_subqueries['pull'] - in XTQL, because subqueries are a first-class concept, we rely extensively on these to express a more powerful/composable behaviour.)

[source,clojure]
----
include::{test}[tags=pull-xtql-1,indent=0]

;; => [{:title "...", :content "...",
;;      :author {:first-name "...", :last-name "..."}
;;      :comments [{:comment "...", :name "..."}, ...]}]

----

[source,sql]
----
-- using XTDB's 'NEST_ONE'/'NEST_MANY'

include::{example}[tags=pull-sql-1,indent=0]
----

In this example, we use link:../reference/main/xtql/queries.html#_subqueries[`pull`] to pull back a single map - we know that there's only one author per article (in our system).
When it's a one-to-many relationship, we use link:../reference/main/xtql/queries.html#_subqueries[`pull*`] - this returns any matches in a vector.

Also note that, because we have the full power of subqueries, we can express requirements like 'only get me the most recent 10 comments' using ordinary query operations, without any support within link:../reference/main/xtql/queries.html#_subqueries[`pull`] itself.

== Bitemporality

It wouldn't be XTDB without bitemporality, of course - indeed, some may be wondering how I've gotten this far without mentioning it!

(I'll assume you're roughly familiar with bitemporality for this section.
 If not, forgive me - we'll follow this up with more XTDB 2.x bitemporality content soon!)

* In XTDB 1.x, queries had to be 'point-in-time' - you had to pick a single valid/transaction time for the whole query.
+
In XTQL, while there are sensible defaults set for the whole query, you can override this on a per-link:../reference/main/xtql/queries.html#_from[`from`] basis by wrapping the table name in a vector and providing temporal parameters:
+
[source,clojure]
----
include::{test}[tags=bitemp-xtql-1,indent=0]

include::{test}[tags=bitemp-xtql-2,indent=0]
----
+
[source,sql]
----
include::{example}[tags=bitemp-sql-1,indent=0]

include::{example}[tags=bitemp-sql-2,indent=0]
----
+
** You can also specify `(from <time>)`, `(to <time>)` or `(in <from-time> <to-time>)`, to give fine-grained, in-query control over the history returned for the given rows.
** System time (formerly 'transaction time', renamed for consistency with SQL:2011) is filtered in the same map with `:for-system-time`.
* This means that you can (for example) query the same table at two points-in-time in the same query - 'who worked here in both 2018 and 2023':
+
[source,clojure]
----
include::{test}[tags=bitemp-xtql-3,indent=0]
----

== For more information

Congratulations - this is the majority of the theory behind XTQL!
You now understand the fundamentals behind how to construct XTQL queries from its simple building blocks - from here, it's much more about incrementally learning what each individual operator does, and how to work with it via edn.

You can:

* check out the reference guides for XTQL link:/reference/main/xtql/queries[queries] and link:/reference/main/xtql/txs[transactions].

We're very much in **listening mode** right now - as a keen early adopter, we'd love to hear your first impressions, thoughts and opinions on where we're headed with XTQL.
Please do get in touch via the link:/intro/community.html#oss-community[usual channels]!
