---
title: Configuration
---
:icon: /images/icons
:clojure: /drivers/clojure/getting-started#_in_process
:kotlin: /drivers/kotlin/getting-started.html#_in_process
:java: /drivers/java/getting-started.html#_in_process
:clojure-file-config: /drivers/clojure/codox/xtdb.node.html#var-start-node
:kotlin-file-config: /drivers/kotlin/kdoc/xtdb-core/xtdb.api/-xtdb/open-node.html


== Components 

An XTDB node consists of a number of components. 

For information on how to configure these and switch out implementations, see their reference documents:

* link:config/tx-log[Transaction Log]
* link:config/storage[Storage]
* link:config/modules[Optional Modules]

== Starting a node in process

[.lang-icons.right]
image:{icon}/clojure.svg[Clojure,link={clojure}]
image:{icon}/kotlin.svg[Kotlin,link={kotlin}]
image:{icon}/java.svg[Java,link={java}]

To start a node in-process within the various drivers, see the following:

== Configuring using YAML

Currently, all of the examples within the reference docs are in YAML. Config for the components is done at the top level of the file, i.e. you can specify the following keys, not nested under anything else: `storage`, `txLog`, `modules`.

[.lang-icons.right]
image:{icon}/clojure.svg[Clojure,link={clojure-file-config}]
image:{icon}/kotlin.svg[Kotlin,link={kotlin-file-config}]

Within the drivers, we offer the ability to provide and configure the node by passing the path to a YAML config file:

=== Using `!Env`

For certain keys, we allow the use of environment variables - typically, the keys where we allow this are things that may change *location* across environments. Generally, they are either "paths" or "strings". 

When specifying a key, you can use the `!Env` tag to reference an environment variable. As an example:

[source,yaml]
----
storage: !Local
  path: !Env XTDB_STORAGE_PATH
----

Any key that we allow the use of `!Env` will be documented as such.
