= Auctionmark (WIP)

Auctionmark runs in some capacity currently, this guide describes the requirements and steps to use the get-user query as a performance benchmark. Full auctionmark benchmark may or may not be working. Currently the auctionmark dataset is commited to the codebase so you can skip straight to the instructions in xtdb.bench2.xtdb.clj

- Set up AWS CLI credentials (skip)
- Run AWS_PROFILE=<profile_name_containing_above_creds> bin/download-dataset.sh --auctionmark (skip)
- See comments at bottom of xtdb.bench2.xtdb.clj for further instructions.

=== Creating a C1 vs C2 comparison report

The following setup assumes that you have `2.x` checked out and another directory at `../xtdb` which can checkout the `auctionmark` branch of C1.
Make sure there is nothing to be stashed on your (presumably C1) working branch.
The following script will first run a C1 auctionmark on your machine followed by a C2 run and finally creates a report for comparison. It assumes you are placed at the root of the `modules/bench` directory.
`./bin/auctionmark-compare.clj --load-phase true --run-duration "PT30S"`
For subsequent runs one can potentially skip the load-phase.


= (Deprecated) Bench

A rudimentary bench adapted from XTDB 1.x. It currently only runs TPC-H, and only runs it ad-hoc (on Fargate) - it doesn't have any of the daily scheduling.

Dependencies:

- AWS CLI (Arch: `aws-cli` or `aws-cli-v2-bin` from the AUR) + credentials set up

All run through scripts in `./bin`:

- `run-cloudformation.sh` - updates the CloudFormation stack (`./cloudformation/bench.yml`)
- `ecr-login.sh` - logs you in to ECR so that you can push the Docker image
- `build-docker.sh` - builds the bench Docker image
- `push-docker.sh` - pushes the bench Docker image
- `run-bench.sh tpch [--scale-factor 0.01] [--count 1]` - kicks off an ECS job.
- `run-bench.sh ts-devices [--size <small|med|big>] [--count 1]` - kicks off an ECS job.

You can also run it locally with (e.g.) `clojure -Mxtdb:4gb:bench-tpch --scale-factor 0.05` from the top-level of the core2 repo.
