= Bench

== Running from Gradle

(from the root of the repo, values given are defaults)

TPC-H::
`./gradlew tpch -PscaleFactor=0.01`

AuctionMark::
`./gradlew auctionmark -Pduration=PT30S -Pthreads=8 -PscaleFactor=0.1`

Products::
`./gradlew products`

== Running from Docker

. From the root of the repo:
.. Create the standalone JAR: `./gradlew shadowJar`
.. Create the Docker image: `docker buildx bake bench`
.. Push it (optional): `docker push ghcr.io/xtdb/xtdb-bench`
. Running it: `docker run --rm ghcr.io/xtdb/xtdb-bench <benchmark-type> <opts...>`.
+
--
TPC-H::
[source,bash]
----
docker run --rm ghcr.io/xtdb/xtdb-bench tpch \
  --scale-factor 0.01
----
AuctionMark::
[source,bash]
----
docker run --rm ghcr.io/xtdb/xtdb-bench auctionmark \
  --duration PT30S \
  --scale-factor 0.1 \
  --threads 8
----
Products::
[source,bash]
----
# ensure you've either downloaded the products dataset
# from S3 to datasets/products.transit.msgpack.gz,
# or your process has permissions to do so

docker run --rm ghcr.io/xtdb/xtdb-bench products
----
--

== Prometheus and Grafana

For local node monitoring, bring up a Prometheus and Grafana instance via `docker-compose up`.
By default the node serves Prometheus metrics under `localhost:8080/metrics` which Prometheus scrapes every 2 seconds.
If the metrics are not exposed under `localhost:8080` you need to tweak the `.config/prometheus.yaml` config accordingly.

Under `localhost:3001` you are able to access the Grafana UI (`admin` for user and password).
The XTDB node datasource should be setup, and there should be a dashboard available with some basic metrics.
If you tweak the dashboard or add a new one, save the changes in the corresponding file in `.config/dashboards/dashboard_name.json`.

== Auctionmark (WIP)

Auctionmark runs in some capacity currently - this guide describes the requirements and steps to use the get-user query as a performance benchmark.
Full auctionmark benchmark may or may not be working.
Currently the auctionmark dataset is committed to the codebase so you can skip straight to the instructions in `xtdb/bench/xtdb2.clj`

- Set up AWS CLI credentials (skip)
- Run `AWS_PROFILE=<profile_name_containing_above_creds> bin/download-dataset.sh --auctionmark` (skip)
- See comments at bottom of `xtdb/bench/xtdb2.clj` for further instructions.



Add a YourKit snapshot with `-Pyourkit` - you should see a snapshot appear in your snapshot directory (default `~/Snapshots`) when the application shuts down.

