= Azure Module

Within our XTDB node, we can make use of Azure Services for certain purposes. Currently, we can:

* Use *Azure Blob Storage* as the XTDB Object Store.
* Use *Azure Eventhubs* as the Log.

== Project Dependency 

In order to use any of the Azure services, you will need to include a dependency on the xtdb.azure module.

_deps.edn_
```
com.xtdb.labs/xtdb-azure {:mvn/version "2.0.0-SNAPSHOT"}
```

_pom.xml_
```
<dependency>
    <groupId>com.xtdb.labs</groupId>
    <artifactId>xtdb-azure</artifactId>
    <version>2.0.0-SNAPSHOT</version>
</dependency>
```

== Authentication

Authentication for the components in the module is done via the https://learn.microsoft.com/en-us/java/api/com.azure.identity.defaultazurecredential?view=azure-java-stable[*DefaultAzureCredential*] class - you will need to setup authentication using any of the methods listed within the Azure documentation to be able to make use of the operations inside the modules.

Whatever method used to authenticate, you will need to ensure it has the correct permissions. Alongside the various bits of infrastructure required for the object store, we create a custom XDTB IAM role. One can use this role to provide all necessary permissions for the object store and the resources it is using on Azure, otherwise you will need to ensure whichever credentials you are using to authenticate XTDB have the same level of permissions to the miscellaneous services.
See the custom role definition in the link:azure-resource-manager/azure-stack.json[Resource Manager stack] for what exactly that includes.

== Azure Blob Storage Object Store

We can swap out the implementation of the object store with one based on Azure Blob Storage. To do so, we add the `xtdb.azure/blob-object-store` key within the integrant config for our node, alongside any config:
```clojure
{
  ...
  {:xtdb.azure/blob-object-store {:storage-account "xtdbstorageaccount"
                                  :container "xtdb-object-store"
                                  :servicebus-namespace "xtdb-storage-account-eventbus"
                                  :servicebus-topic-name "xtdb-storage-bus-topic"}}
  ...
}
```

Alongside the storage account container, we require an eventgrid topic and service bus topic to pass around file changes to the container, such that we can keep a local copy of files on Azure, saving on expensive/lengthy operations to list objects. Below follows the various parameters used by the module, and some notes around the provided <<resource-manager, Azure Resource Manager template>> which sets up all of the necessary extra infrastructure. Even if this isn't used, we will require a similar setup to track file changes on whichever storage account/container you are using, and relevant permissions to use all of the services. 

=== Parameters

These are the following parameters that can be passed within the config for our `xtdb.azure/blob-object-store`:
[cols="1,1,2,1"]
|===
| *Name* | *Type* | *Description* | *Required?*
| `storage-account`
| String
| The https://learn.microsoft.com/en-us/azure/storage/common/storage-account-overview[storage account] that has the container to use as an object store
| Yes

| `container`
| String 
| The name of the https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blobs-introduction#containers[container] to use an an object store
| Yes

| `servicebus-namespace`
| String
| The name of the https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-messaging-overview#namespaces[Service Bus namespace] which contains the topic collecting notifications from the container 
| Yes

| `servicebus-topic-name`
| String
| The name of the https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-queues-topics-subscriptions#topics-and-subscriptions[Service Bus topic] which contains is collecting notifications from the container
| Yes

|`prefix`
| String 
| A string to prefix all of your files with - for example, if "foo" is provided all xtdb files will be located under a "foo" directory
| No
|===

[#resource-manager]
=== Azure Resource Manager Stack

In order to handle the various bits of Azure infrastructure required to use Azure Blob Storage as an XTDB object store, we provide a link:azure-resource-manager/azure-stack.json[parameterized 'Azure Resource Manager' stack] to setup everything that you should need.

==== Inputs to the stack

The paramaterized stack expects the following to be provided:

* The location to build the resources -- Defaults to the location of the resource group you're deploying the template in.
* The name of the storage account to create -- Defaults to `xtdbstorageaccount`
* The pricing tier/type of storage account to use -- Defaults to `Standard_LRS`
* The name of the storage container to use as the XTDB object store (and used by associated resources) -- Defaults to `xtdb-object-store`
* The name of the EventGrid system topic we use for container events -- Defaults to `xtdb-storage-account-system-topic`
* The name to use for the Service Bus namespace -- Defaults to `xtdb-storage-account-eventbus`
* The name to use for the Service Bus topic created in the namespace above -- Defaults to `xtdb-storage-bus-topic`
* The name of the custom XTDB role to create with permissions for the created resources -- Defaults to `xtdb-role`

==== Created Resources

The Azure Resource Manager stack will create the following resources within the specified resource group in Azure:

* An https://learn.microsoft.com/en-us/azure/storage/common/storage-account-overview[Azure Storage Account]
* A https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blobs-introduction#containers[Storage Account Container] within said storage account to use as the object store.
* An https://learn.microsoft.com/en-us/azure/event-grid/system-topics[EventGrid System Topic], subscribed to blob creation/deletion events on the container.
* A `standard` tier https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-messaging-overview#namespaces[Service Bus Namespace]:
** A https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-queues-topics-subscriptions#topics-and-subscriptions[Service Bus Topic] for the Service Bus namespace.
* An https://learn.microsoft.com/en-us/azure/event-grid/concepts#event-subscriptions[Event Subscription] on the EventGrid System Topic for the Service Bus Topic.
* A https://learn.microsoft.com/en-us/azure/role-based-access-control/custom-roles[custom role definition] for all of the necessary permissions for XTDB to use the above:
** Using the created storage container (Get, Put, Delete and List).
** Reading messages sent to EventGrid.
** Creating subscriptions on the Service Bus topic.

== Azure EventHub Log

We can swap out the implementation of the log with one based on Azure Eventhubs. To do so, we add the `xtdb.azure/event-hub-log` key within the integrant config for our node, alongside any config:
```clojure
{
  ...
  {::azure/event-hub-log {:namespace "eventhub-namespace"
                          :resource-group-name "resource-group-name"
                          :event-hub-name "example-event-hub"
                          :create-event-hub? true
                          :retention-period-in-days 60}}
  ...
}
```

=== Parameters

These are the following parameters that can be passed within the config for our `xtdb.azure/event-hub-log`:
[cols="1,1,2,1"]
|===
| *Name* | *Type* | *Description* | *Required?*
| `namespace`
| String
| The Event Hubs namespace of the EventHub. 
| Yes

| `event-hub-name`
| String
| The name of the EventHub that you wish to use a log.
| Yes

| `max-wait-time`
| Duration
| A duration representing the max amount of time to wait when reading data from the log - can be provided as a Java Duration or passed as a https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html#parse-java.lang.CharSequence-[duration string] or int representing a time in milliseconds. 
| No - defaults to "PT1S"

| `poll-sleep-duration`
| Duration
| A duration representing the time to sleep between reads of the log - can be provided as a Java Duration or passed as a https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html#parse-java.lang.CharSequence-[duration string] or int representing a time in milliseconds. 
| No - defaults to "PT1S"

| `create-event-hub?`
| Boolean
| Whether or not XTDB should create an eventhub for you within the specified namespace. See "<<Creating the Event Hub Automatically>>" for more info.
| No - defaults to false. 

| `resource-group-name`
| String
| The name of the resource group that the eventhub namespace belongs to.
| Only if `create-event-hub?` is true

| `retention-period-in-days`
| Long
| The retention period of the Event Hub for the Log - the maximum period determined by the tier of eventhub namespace you are using, see the https://learn.microsoft.com/en-us/azure/event-hubs/event-hubs-features#event-retention[Azure Docs].
| No - only needed if creating Event Hub automatically, and defaults to "7".

|=== 

=== Using Event Hubs 

Some things to note when setting up Event Hubs for XTDB:

* When using EventHubs as a log - you will require a pre-existing Event Hubs namespace, see the https://learn.microsoft.com/en-us/azure/event-hubs/event-hubs-create#create-an-event-hubs-namespace[Azure docs].
* As a bare minimum, whichever credentials you use to authenticate to Azure for the app will require two roles on the namespace - *Azure Event Hubs Data sender* and *Azure Event Hubs Data receiver*. 

#### Creating the Event Hub Manually

When creating an eventhub manually to use as an XTDB log, there are a few properties to consider:

* Partition count should be set to *1* - XTDB will only ever use a single partition within it's implementations of Log as they are required to be *totally ordered*.
* The retention period is configurable - you will likely wish to set this to as high as you reasonably can given the pricing tier of your Event Hubs namespace. 

==== Creating the Event Hub Automatically

If `create-event-hub?` is set to `true`, XTDB will attempt to create an Event Hub on your behalf - some notes on this:

* If `create-event-hub?` is set, a number of other pieces of configuration must be done to allow your application to manage Event Hubs on your behalf:
** Whichever credentials you use to authenticate to Azure for the app will require one extra roles for the namespace - *Azure Event Hubs Data Owner*.
** Within your XTDB integrant config, you will need to directly specify the resource group the Event Hub namespace belongs to within the `resource-group-name` parameter.
** The application will require two Azure related environment variables to be set - `AZURE_SUBSCRIPTION_ID` & `AZURE_TENANT_ID`. See the https://learn.microsoft.com/en-us/azure/azure-portal/get-subscription-tenant-id[Azure docs] for more info.
* The Event Hub will only be created if the `event-hub-name` in the configuartion doesn't already exist in the given namespace - it will not start a new Event Hub every time the node restarts.
* The created Event Hub will have a single partition, and the retention period will be set based on the `retention-period-in-days` parameter (this defaults to 7 days - the maximum retention period of the 'basic' namespace pricing tier)
