= Azure Module

Within our XTDB node, we can make use of Azure Services for certain purposes. Currently, we can:

* Use *Azure Blob Storage* as one of the XTDB Object Stores used by the remote storage module.

== Project Dependency 

In order to use any of the Azure services, you will need to include a dependency on the xtdb.azure module.

_deps.edn_
```
com.xtdb.labs/xtdb-azure {:mvn/version "2.x-SNAPSHOT"}
```

_pom.xml_
```
<dependency>
    <groupId>com.xtdb.labs</groupId>
    <artifactId>xtdb-azure</artifactId>
    <version>2.x-SNAPSHOT</version>
</dependency>
```

== Authentication

Authentication for the components in the module is done via the https://learn.microsoft.com/en-us/java/api/com.azure.identity.defaultazurecredential?view=azure-java-stable[*DefaultAzureCredential*] class - you will need to setup authentication using any of the methods listed within the Azure documentation to be able to make use of the operations inside the modules.

Whatever method used to authenticate, you will need to ensure it has the correct permissions. Alongside the various bits of infrastructure required for the object store, we create a custom XDTB IAM role. One can use this role to provide all necessary permissions for the object store and the resources it is using on Azure, otherwise you will need to ensure whichever credentials you are using to authenticate XTDB have the same level of permissions to the miscellaneous services.
See the custom role definition in the link:azure-resource-manager/azure-stack.json[Resource Manager stack] for what exactly that includes.

== Azure Blob Storage Object Store

We can swap out the implementation of the object store with one based on Azure Blob Storage.
To do so, we can add the `:azure` object store and it's configuration map, within the remote storage module config for our node:

```clojure
{:storage [:remote {:object-store [:azure {:storage-account "xtdbstorageaccount"
                                           :container "xtdb-object-store"}]}]
 :disk-cache {:path "local-disk-cache"}}
```

Below follows the various parameters used by the module, and some notes around the provided <<resource-manager, Azure Resource Manager template>> which sets up all of the necessary infrastructure.

=== Parameters

These are the following parameters that can be passed within the config for our `xtdb.azure/blob-object-store`:
[cols="1,1,2,1"]
|===
| *Name* | *Type* | *Description* | *Required?*
| `storage-account`
| String
| The https://learn.microsoft.com/en-us/azure/storage/common/storage-account-overview[storage account] that has the container to use as an object store
| Yes

| `container`
| String 
| The name of the https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blobs-introduction#containers[container] to use an an object store
| Yes


|`prefix`
| String/File/Path 
| A file path to prefix all of your files with - for example, if "foo" is provided all xtdb files will be located under a "foo" directory
| No
|===

[#resource-manager]
=== Azure Resource Manager Stack

In order to handle the various bits of Azure infrastructure required to use Azure Blob Storage as an XTDB object store, we provide a link:azure-resource-manager/azure-stack.json[parameterized 'Azure Resource Manager' stack] to setup everything that you should need.

==== Inputs to the stack

The paramaterized stack expects the following to be provided:

* The location to build the resources -- Defaults to the location of the resource group you're deploying the template in.
* The name of the storage account to create -- Defaults to `xtdbstorageaccount`
* The pricing tier/type of storage account to use -- Defaults to `Standard_LRS`
* The name of the storage container to use as the XTDB object store (and used by associated resources) -- Defaults to `xtdb-object-store`
* The name of the custom XTDB role to create with permissions for the created resources -- Defaults to `xtdb-role`

==== Created Resources

The Azure Resource Manager stack will create the following resources within the specified resource group in Azure:

* An https://learn.microsoft.com/en-us/azure/storage/common/storage-account-overview[Azure Storage Account]
* A https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blobs-introduction#containers[Storage Account Container] within said storage account to use as the object store.
* A https://learn.microsoft.com/en-us/azure/role-based-access-control/custom-roles[custom role definition] for all of the necessary permissions for XTDB to use created storage container (Get, Put, Delete and List).
