= Core2 Plan

== Must, 2022 Q4, Solidify the Core for Single Node PoC Deployment.

* Full nested SQL and Arrow type support in expression engine.
* Strict SQL: all comparisons, casts and operations needs to make sense, but can throw clear errors (UX).
* Time-as-state, single source of time with microsecond precision, see current_timestamp_as_db_state.adoc document.
* Arrow-native driver with full type system, ie. FlightSQL with JDBC/ADBC/ODBC.
* Better SQL UX and error messages tying back to documentation, think Rust.
* Boot up DBaaS team and analysis in parallel.
* Baseline of production logging and metrics.
* Minimal authentication via SSL.
* Basic INFORMATION_SCHEMA support (FlightSQL overlap), can be done as objects and not introduce SQL schema.
* Keep pgwire working, but we make clear it's not the supported driver.
* Documentation and web.

== Should, 2023 Q1, DBaaS, Scaling and Separate Storage and Compute.

* Deployment to AWS with basic monitoring, ie. Cloud Watch. (AWS marketplace?)
* DBaaS on AWS. Exactly what this means is out-of-scope for this core plan, but relies on capabilities listed here.
* HTAP benchmarks to guide work. https://github.com/cmu-db/benchbase
* Rudimentary planner that deals with join orders, like collapsing neighbouring joins into the multi-join operator. Needs RnD.
* Predictive caching, doesn't need to be any fancy ML. Needs RnD.
* New temporal index that scales, non-monolithic, could be per table as well. Needs RnD.
* Ability to split tables physically in storage.
* Lax SQL: reasonable coercion for operators instead of throwing errors.
* Minimum discoverability, like row access to mitigate select star: SELECT u FROM users u. Needs RnD.
* Support for MISSING vs NULL, related to select star. Needs RnD.
* Distributed in-memory caches to avoid object store access.
* Basic ability to feed metrics from the running clusters back to allow tuning across all clients.
* ARROW_TABLE extended to support Parquet, JSON etc.
* HTTP API.

== Could, 2023 Q2, Continuous Delivery of (SQL) Features to DBaaS.

* Controlled scaling of compute, different categories of compute and caches, protecting OLTP from OLAP (if needed).
* Deterministic transaction budgets.
* Azure and GCP object stores.
* Data migration from Core1. Can mainly be grown via existing Core1 projects. Build up helper repo.
* Bespoke consoles and dashboards. Needs analysis before embarking on, work sits under DBaaS team.
* CREATE VIEW.
* CREATE ASSERTION.
* CREATE TRIGGER.
* WINDOW functions.
* MERGE DML.
* Advanced OLAP features, grouping sets, roll up etc.
* WITH RECURSIVE.
* Light and Adaptive Indexing. Good caching is step one, this is the next step.
* More planner work, will be incremental and on-going.
* Add non-Kafka transaction logs.
* Object store erasure.
* "CREATE ROLE" - may not use SQL standard, but authorisation inside the DB. Needs RnD.

== Won't, 2023 Q3 and beyond

* Deployment to GCP and Azure with their basic "native" monitoring.
* Views with gradual schema to interface with tooling.
* CREATE FUNCTION.
* Consensus-based transaction log, removing the need for all nodes to redo all work.
* SQL:2023/PGQ: property graph queries.
* Distributed queries.
* Other query languages, ie. Datalog.
