= SQL

XTDB 2.x supports a significant subset of the SQL:2011 standard.

== Getting started

First, follow the link:./getting-started.adoc[Getting Started] guide.

[source,clojure]
----
(require '[xtdb.sql :as xt])

(with-open [node ...]
  ;; submit some data
  (xt/submit-tx node
                [[:sql "INSERT INTO users (id, first_name) VALUES (?, ?)"
                  [["jms", "James"]
                   ["jdt", "Jeremy"]]]])

  ;; run a SQL query

  (xt/q node "SELECT u.id, u.first_name FROM users u")
  ;; => [{:id "jms", :first_name "James"}, {:id "jdt", :first_name "Jeremy"}]

  )
----

== Bitemporality

XTDB 2.x supports SQL:2011's bitemporality syntax in its DQL and DML.

For example:
* to update a document for a subset of valid time: `UPDATE users FOR PORTION OF APPLICATION_TIME FROM TIMESTAMP '2023-04-01' TO TIMESTAMP '2023-05-01' SET name = ? WHERE id = ?`
* (in an extension to the spec) to query a table as at a valid time: `SELECT u.id, u.first_name FROM users u FOR APPLICATION_TIME AS OF TIMESTAMP '2023-04-15'`.

== Notes for SQL regulars

* XTDB 2.x's SQL doesn't require any DDL - just `INSERT` some data to get going.
* Not (yet) implemented (amongst other things):
** For now, it's necessary to qualify all column references - e.g. `SELECT id, first_name FROM users` -> `SELECT u.id, u.first_name FROM users u`
** `SELECT *` (coming soon)
