{
 "title": "XTDB: Monitoring Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "xtdbnode", "label": "XTDB Node", "query": { "query": "label_values(node_id)" } }
  ]
 },
 "panels": [
  {
   "title": "# Nodes",
   "type": "stat",
   "description": "How many current active XTDB nodes are there?",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(jvm_threads_live_threads{node_id=~\".*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction Lag",
   "type": "timeseries",
   "description": "How far behind is each node on it's indexing? Ie - id of last-submitted transaction - id of last-completed-transaction?",
   "gridPos": { "h": 5, "w": 9, "x": 3, "y": 0 },
   "targets": [
    { "expr": "node_tx_lag_TxId", "legendFormat": "{{node_id}}" }
   ]
  },
  {
   "title": "Max Transaction Latency (Over Time)",
   "type": "stat",
   "description": "What's the highest transaction latency over the time period?",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(tx_op_timer_seconds_max[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Query Latency (Over Time)",
   "type": "stat",
   "description": "What's the Max Query latency over the current time period?",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(query_timer_seconds_max[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Transactions",
   "type": "timeseries",
   "description": "How many transactions are taking place per second?",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Ops/Second" } },
   "targets": [
    {
     "expr": "sum(rate(tx_op_timer_seconds_count[30s]))",
     "legendFormat": "Cluster Rate"
    }
   ]
  },
  {
   "title": "Cluster Transactions Latencies",
   "type": "timeseries",
   "description": "How long are transactions taking, on average, across the cluster?",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.5, tx_op_timer_seconds)",
     "legendFormat": "Cluster Average"
    },
    {
     "expr": "quantile(0.99, tx_op_timer_seconds)",
     "legendFormat": "Cluster 99%"
    }
   ]
  },
  {
   "title": "Cluster Transaction Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(tx_error_total)", "legendFormat": "$xtdbnode" }
   ]
  },
  {
   "title": "Cluster Queries",
   "type": "timeseries",
   "description": "How many Queries are taking place per second?",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Ops/Second" } },
   "targets": [
    {
     "expr": "sum(rate(query_timer_seconds_count[30s]))",
     "legendFormat": "Cluster Rate"
    }
   ]
  },
  {
   "title": "Cluster Query Latencies",
   "type": "timeseries",
   "description": "How long are queries taking, on average, across the cluster?",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.5, query_timer_seconds)",
     "legendFormat": "Cluster Average"
    },
    {
     "expr": "quantile(0.99, query_timer_seconds)",
     "legendFormat": "Cluster 99%"
    }
   ]
  },
  {
   "title": "Cluster Query Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(query_error_total)", "legendFormat": "$xtdbnode" }
   ]
  },
  {
   "title": "Cluster PGWire Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(pgwire_active_connections)", "legendFormat": "$xtdbnode" }
   ]
  },
  {
   "title": "Cluster PGWire Total Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(pgwire_connections_total)", "legendFormat": "$xtdbnode" }
   ]
  },
  {
   "title": "Cluster Buffer Pool Network Write",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(buffer_pool_network_write_total)",
     "legendFormat": "$xtdbnode"
    }
   ]
  },
  {
   "title": "Cluster Buffer Pool Network Read",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(buffer_pool_network_read_total)",
     "legendFormat": "$xtdbnode"
    }
   ]
  },
  { "title": "$xtdbnode - Node Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }, "repeat": "xtdbnode" },
  {
   "title": "Transactions",
   "type": "timeseries",
   "description": "How many transactions are taking place per second?",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Ops/Second" } },
   "targets": [
    {
     "expr": "sum(rate(tx_op_timer_seconds_count{node_id=\"$xtdbnode\"}[30s]))",
     "legendFormat": "$xtdbnode - rate"
    }
   ]
  },
  {
   "title": "Transactions Latencies",
   "type": "timeseries",
   "description": "How long are transactions taking, on average, across the cluster?",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.5, tx_op_timer_seconds{node_id=\"$xtdbnode\"})",
     "legendFormat": "$xtdbnode - Average"
    },
    {
     "expr": "quantile(0.99, tx_op_timer_seconds{node_id=\"$xtdbnode\"})",
     "legendFormat": "$xtdbnode - 99%"
    }
   ]
  },
  {
   "title": "Transaction Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "tx_error_total{node_id=\"$xtdbnode\"}",
     "legendFormat": "$xtdbnode"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "timeseries",
   "description": "How many Queries are taking place per second?",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Ops/Second" } },
   "targets": [
    {
     "expr": "sum(rate(query_timer_seconds_count{node_id=\"$xtdbnode\"}[30s]))",
     "legendFormat": "$xtdbnode - Rate"
    }
   ]
  },
  {
   "title": "Query Latencies",
   "type": "timeseries",
   "description": "How long are queries taking, on average, across the cluster?",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.5, query_timer_seconds{node_id=\"$xtdbnode\"})",
     "legendFormat": "$xtdbnode - Average"
    },
    {
     "expr": "quantile(0.99, query_timer_seconds{node_id=\"$xtdbnode\"})",
     "legendFormat": "$xtdbnode - 99%"
    }
   ]
  },
  {
   "title": "Query Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "query_error_total{node_id=\"$xtdbnode\"}",
     "legendFormat": "$xtdbnode"
    }
   ]
  },
  {
   "title": "PGWire Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pgwire_active_connections{node_id=\"$xtdbnode\"}",
     "legendFormat": "$xtdbnode"
    }
   ]
  },
  {
   "title": "PGWire Total Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pgwire_connections_total{node_id=\"$xtdbnode\"}",
     "legendFormat": "$xtdbnode"
    }
   ]
  },
  {
   "title": "Buffer Pool Network Write",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "buffer_pool_network_write_total{node_id=\"$xtdbnode\"}",
     "legendFormat": "$xtdbnode"
    }
   ]
  },
  {
   "title": "Buffer Pool Network Read",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "buffer_pool_network_read_total{node_id=\"$xtdbnode\"}",
     "legendFormat": "$xtdbnode"
    }
   ]
  },
  {
   "title": "Current CPU Usage",
   "type": "gauge",
   "description": "Current Percentage of CPU used by JVM process of the XTDB nodes. \n",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "CPU Usage over Time",
   "type": "timeseries",
   "description": "Percentage of CPU used by JVM process of the XTDB node over time.\n",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_cpu_usage{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "JVM Heap Memory Usage",
   "type": "timeseries",
   "description": "Heap memory used by the JVM process of each node over time.\n",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(node_id) (jvm_memory_used_bytes{node_id=\"$xtdbnode\", area=\"heap\"})",
     "legendFormat": "{{node_id}} - used memory"
    },
    {
     "expr": "sum by(node_id) (jvm_memory_committed_bytes{node_id=\"$xtdbnode\", area=\"heap\"})",
     "legendFormat": "{{node_id}}  - committed memory"
    },
    {
     "expr": "max(sum by(node_id) (jvm_memory_max_bytes{node_id=\"$xtdbnode\", area=\"heap\"}))",
     "legendFormat": "Max Heap Size"
    }
   ]
  }
 ]
}
{
 "title": "XTDB: Node Debugging Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "xtdbnode", "label": "XTDB Node", "query": { "query": "label_values(node_id)" } }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\", node_id=\"$xtdbnode\"})",
     "legendFormat": "JVM Heap Used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{area=\"heap\", node_id=\"$xtdbnode\"})",
     "legendFormat": "JVM Heap Committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{area=\"heap\", node_id=\"$xtdbnode\"})",
     "legendFormat": "JVM Heap Max"
    }
   ]
  },
  { "title": "XTDB - Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Transactions - Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "tx_op_timer_seconds_count{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Transactions - Timer (Max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "tx_op_timer_seconds_max{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Transactions - Timer (Quantiles)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "tx_op_timer_seconds{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} - {{quantile}} quantile"
    }
   ]
  },
  { "title": "XTDB - Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Query - Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "query_timer_seconds_count{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Query - Timer (Max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "query_timer_seconds_max{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Query - Timer",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "query_timer_seconds{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} - {{quantile}} quantile"
    }
   ]
  },
  { "title": "XTDB - JVM Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "JVM - Heap Usage (Average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by(node_id) (jvm_memory_committed_bytes{node_id=\"$xtdbnode\"})",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "JVM - Heap Usage (Max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by(node_id) (jvm_memory_committed_bytes{node_id=\"$xtdbnode\"})",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "JVM - Buffer Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(node_id) (jvm_buffer_memory_used_bytes{node_id=\"$xtdbnode\"})",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "JVM - Live Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "JVM - Thread States",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "jvm_threads_states_threads{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} - {{state}}"
    }
   ]
  },
  { "title": "XTDB - Direct Allocated Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "XTDB - Buffer Pool Allocated Memory",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "memory_cache_evictableBytes_bytes{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} evictable bytes"
    },
    {
     "expr": "memory_cache_freeBytes_bytes{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} free bytes"
    },
    {
     "expr": "memory_cache_pinnedBytes_bytes{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} pinned bytes"
    }
   ]
  },
  {
   "title": "XTDB - Compactor Allocated Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "compactor_allocator_allocated_memory_bytes{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "XTDB - Indexer Allocated Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "indexer_allocator_allocated_memory_bytes{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "XTDB - Live Index Allocated Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "live_index_allocator_allocated_memory_bytes{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "XTDB - Log Watcher Allocated Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "watcher_allocator_allocated_memory_bytes{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Netty Allocated Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_netty_bytes{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} - netty used memory"
    }
   ]
  },
  {
   "title": "Direct Allocated Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_direct_bytes{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} - direct used memory"
    }
   ]
  },
  { "title": "XTDB - Memory Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  {
   "title": "Memory Cache - Record Batch count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "targets": [
    {
     "expr": "memory_cache_metaFiles_sliceCount{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} Meta Record Batches"
    },
    {
     "expr": "memory_cache_dataFiles_sliceCount{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} - Data Record Batches"
    }
   ]
  },
  {
   "title": "Memory Cache - Weights",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "memory_cache_metaFiles_weightBytes_bytes{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} - Meta Record Batches weight"
    },
    {
     "expr": "memory_cache_dataFiles_weightBytes_bytes{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} - Data Record Batches weight"
    }
   ]
  },
  {
   "title": "Memory Cache - Pinned vs Unpinned",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "targets": [
    {
     "expr": "memory_cache_metaFiles_pinned{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} - Meta pinned"
    },
    {
     "expr": "memory_cache_metaFiles_unpinned{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} - Meta unpinned"
    },
    {
     "expr": "memory_cache_dataFiles_pinned{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} - Data pinned"
    },
    {
     "expr": "memory_cache_dataFiles_unpinned{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} - Data unpinned"
    }
   ]
  },
  {
   "title": "Memory Cache - Cache misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "targets": [
    {
     "expr": "rate(memory_cache_misses_total{node_id=\"$xtdbnode\"}[1m])",
     "legendFormat": "{{node_id}} Memory Cache Misses 1min"
    },
    {
     "expr": "rate(disk_cache_misses_total{node_id=\"$xtdbnode\"}[1m])",
     "legendFormat": "{{node_id}} - Disk Cash Misses 1min"
    },
    {
     "expr": "rate(record_batch_requests_total{node_id=\"$xtdbnode\"}[1m])",
     "legendFormat": "{{node_id}} - Record Batch Requests 1min"
    },
    {
     "expr": "avg_over_time(rate(memory_cache_misses_total{node_id=\"$xtdbnode\"}[1m])[5m:])",
     "legendFormat": "{{node_id}} Memory Cache Misses 5min avg"
    },
    {
     "expr": "avg_over_time(rate(record_batch_requests_total{node_id=\"$xtdbnode\"}[1m])[5m:])",
     "legendFormat": "{{node_id}} - Record Batch Requests 5min avg"
    },
    {
     "expr": "avg_over_time(rate(record_batch_requests_total{node_id=\"$xtdbnode\"}[1m])[5m:])",
     "legendFormat": "{{node_id}} - Record Batch Requests 5min avg"
    }
   ]
  },
  {
   "title": "Buffer Pool - Record Batch requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
   "targets": [
    {
     "expr": "rate(record_batch_requests_total{node_id=\"$xtdbnode\"}[1m])",
     "legendFormat": "{{node_id}} - Record Batch requests 1min"
    },
    {
     "expr": "avg_over_time(rate(record_batch_requests_total{node_id=\"$xtdbnode\"}[1m])[5m:])",
     "legendFormat": "{{node_id}} - Record Batch requests 5min avg"
    }
   ]
  },
  { "title": "XTDB - Compactor Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 122 } },
  {
   "title": "Available Compaction Jobs",
   "type": "timeseries",
   "description": "Number of currently available compactor jobs.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
   "targets": [
    {
     "expr": "compactor_jobs_available{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} - Available Compactor Jobs"
    }
   ]
  },
  {
   "title": "Compaction Job Timer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(node_id) (compactor_job_timer_seconds{node_id=\"$xtdbnode\"})",
     "legendFormat": "{{node_id}} - Average"
    },
    {
     "expr": "compactor_job_timer_seconds{quantile=\"0.99\", node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} - 99%"
    },
    {
     "expr": "compactor_job_timer_seconds_max{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} - Max"
    }
   ]
  }
 ]
}