= crux-kafka-connect

This project contains `crux.kafka.connect.CruxSinkConnector` which is
an implementation of `org.apache.kafka.connect.sink.SinkConnector`.

Reads JSON and posts it to a Crux node using `crux-http-client`.

See also: https://kafka.apache.org/documentation/#connect

Download Kafka from https://kafka.apache.org/downloads

Building and installing the sink connector:
```
export KAFKA_HOME=...
lein uberjar
cp target/*-standalone.jar $KAFKA_HOME/libs
cp test-resources/*.properties $KAFKA_HOME/config
```

Steps to get running:

Start a local Crux node with embedded Kafka in the REPL and create the
test topic (from `crux-dev`):

```
(dev)
(start)
(k/create-topic (:admin-client node) "connect-test" 1 1 nil)
```

Beware of the `/tmp/connect.offsets` file when restarting the Kafka cluster from scratch.

== Sink

Start the Connect worker, which will connect to the embedded Kafka:

```
(cd $KAFKA_HOME; ./bin/connect-standalone.sh config/connect-standalone.properties config/connect-file-source.properties config/local-crux-sink.properties)
```

Write a line of JSON to `test.txt` file source:

```
echo '{"crux.db/id": "415c45c9-7cbe-4660-801b-dab9edc60c84", "value": "baz"}' >> test.txt
```

Verify the entity was transacted in the REPL:

```
(crux/entity (crux/db node) "415c45c9-7cbe-4660-801b-dab9edc60c84")
;=> {:crux.db/id #crux/id "415c45c9-7cbe-4660-801b-dab9edc60c84", :value "baz"}
```

The connector can also use the message key as id. In this case, a key
with nil value acts as a deletion of the entity in Crux, similar to
how compaction in Kafka works.


== Source

Start the Connect worker, which will connect to the embedded Kafka:

```
(cd $KAFKA_HOME; ./bin/connect-standalone.sh config/connect-standalone.properties config/local-crux-source.properties config/connect-file-sink.properties)
```

Transact an entity in the REPL:
```
(crux/submit-tx node [[:crux.tx/put {:crux.db/id #crux/id "415c45c9-7cbe-4660-801b-dab9edc60c84", :value "baz"}]])
```

Check it was submitted to the topic:
```
tail $KAFKA_HOME/test.sink.txt
```

Should output:
```
[[:crux.tx/put {:crux.db/id #crux/id "415c45c9-7cbe-4660-801b-dab9edc60c84", :value "baz"}]]
```
