= 6. Temporal data

Date: 2021-09-09

== Status

Accepted

== Context

XTDB is a temporal database that needs to support temporal query capabilities beyond time-slice queries.
Range queries across both transaction and valid time must be supported.

== Decision

We will support https://sigmodrecord.org/publications/sigmodRecord/1209/pdfs/07.industry.kulkarni.pdf[SQL:2011 temporal semantics] under the hood.
Advanced temporal queries should be possible, but not necessarily highly optimised.
Time-slice queries must still be competitive.

Internally, we will base the temporal data model on the https://www2.cs.arizona.edu/~rts/pubs/ISDec94.pdf[Bitemporal Conceptual Data Model] from Jensen, Soo and Snodgrass.

== Consequences

Requires us to implement an advanced temporal index alongside the columnar chunks and expose this indirectly to the query engine.

We should consider starting to use SQL:2011 terminology instead of Snodgrass everywhere for consistency:

* Transaction time - system time.
* Valid time - application time.
