= 9. Transactions

Date: 2021-09-09

== Status

Proposed

== Context

XTDB is a deterministic, dynamic document database.
A transaction is proposed asynchronously onto a central, totally ordered log.
The transaction might get rejected during processing.
Transactions must be fully deterministic as all nodes needs to reach the same conclusion and also share the same object store.

A transaction is composed of a series of operations executed in order.

Options:

. EDN (classic): put/delete/evict and integrity checks via match + find.
. SQL DML: insert/update/delete/evict and integrity checks via select.

Operations also need to be able to do bitemporal corrections.
SQL:2011 always assumes start/end time for corrections, while classic supports calculating the end time if not given.

== Decision

We will continue to use the existing single-writer log based model.
Pragmatically, we will support EDN-style transactions to start, either in EDN, JSON or raw Arrow.
It won't (for the foreseeable future) support interactive transactions.

As per the link:0002-data-model.adoc[data model], the transactions are converted to Arrow client side before submitted.

Integrity checks are done via queries and transaction functions should not be supported by default.

The core needs to support both start/end time and just start time for corrections.

We will later (before public release) move to SQL DML and remove support for EDN-style transactions.
