= 27. SQL basic DML

Date: 2021-10-06

== Status

Proposed

== Context

XTDB needs a simple way to manipulate data from SQL even if we don’t initially support full SQL DML.
This is so a user can use XTDB with SQL only end to end.

We want to support the basic `INSERT`, `UPDATE` and `DELETE` statements.
`MERGE` can provide some level of conditional processing.
We probably want to introduce an `EVICT` statement as well.

What constitutes a table will be defined in link:0025-sql-tables.adoc[SQL Tables].

=== Option A: Firehose and SQL DML

* We split ingest into two layers, SQL and firehose.
* Queries, general logic etc. are available at the SQL layer.
* Firehose layer has the current operations: put/delete/evict. There's no logic at this layer.
* SQL layer takes slightly more control - like the begin/end Transaction API in XTDB 1.x - and generates put/delete/evict but may also rollback and fail for logic reasons.
* Assertions (constraint checks) are run pre-commit, and triggers post-commit at the SQL layer. At the firehose layer is also a possibility, there are some pros cons (like it having to know about SQL).
* Log archiving into object store use the firehose layer as currently.
* Firehose layer might also be seen / used as a CDC feature between clusters.
* Firehose takes raw Arrow, with adapters for EDN, JSON etc.

== Decision

== Consequences
