= 40. Core2/PGWire transaction behaviour

Date: 2022-08-01

== Status

Proposed

== Context

We've implemented a PGWire adapter as an initial driver for Core2.
Currently this supports read-only queries, but we'd like to extend this to DML too.

=== General Core2 requirements

There are three main considerations here:

. In Core2, read-only and write transactions follow different paths:
  * Read-only transactions can be sent to any node, and return a synchronous result (similar to Postgres).
    Write transactions, though, are fundamentally asynchronous - they need to be sent to the tx-log (usually Kafka), and are then consumed asynchronously by each node.
  * This means that write transactions are http://jepsen.io/consistency/models/strict-serializable['strictly serialized'] - happy days.
    Read-only transactions are merely http://jepsen.io/consistency/models/serializable['serialized'] - but this isolation level allows for read-only transactions to be executed at any point in time (including, pathologically, before any write transactions!).
  * By default, read-only transactions execute against the latest transaction the node in question has indexed - so, in order for a user to reliably read their own writes in such a system (given the node may not have indexed their transaction yet), they must somehow ensure that their write transaction has been included.
. Separately, we value referentially transparent, 'repeatable' queries - the same query, executed with exactly the same parameters, should return the same resultset regardless of when it's executed.
  Specifically, it shouldn't matter how many subsequent transactions the queried node has indexed, nor the current wall-clock time of the querying or queried node.
. That said, in practice, users likely expect the same simple query run multiple times to include new results as they come in.

SQL:2011 does allow a lot of control over the temporal characteristics of the query, using either `FROM <table> FOR SYSTEM TIME ...` or `WHERE app_time OVERLAPS PERIOD(...)` etc.
However, even this is not strong enough for the above properties:

* By default, SQL:2011 doesn't filter application time - it returns the whole application timeline for each entity.
  We'll likely be recommending liberal use of `CURRENT_TIMESTAMP` to restrict results - e.g. `WHERE app_time CONTAINS CURRENT_TIMESTAMP`.
`CURRENT_TIMESTAMP` is obviously a co-effect so, if we're to preserve referential transparency, it needs to be a parameter to the query.
* If the user doesn't specify a system time constraint on a given table, the SQL semantics specify that this should be filtered to system time intervals containing the current time of the queried node.
  We could use the same `CURRENT_TIMESTAMP` query argument, but this isn't quite sufficient, because nodes consume the tx-log asynchronously.
+
Consider a node that's half an hour behind the tx-log: at 16:00, `SELECT * FROM foo FOR SYSTEM TIME AS OF 15:45` wouldn't reflect a transaction from 15:40 - once the node caught up, it would.

So, there are two necessarily distinct co-effect parameters here:

'current timestamp'::
If it is not explicitly supplied, it defaults to the current time on the submitting node.
We use the submitting node's clock for `CURRENT_TIMESTAMP` on both write transactions and queries because of https://github.com/xtdb/xtdb/issues/1665[this Core1 issue] - this guarantees that transactions submitted by a node that use `CURRENT_TIMESTAMP` are then included in a later `CURRENT_TIMESTAMP` query filter submitted by that node, regardless of which node the transaction and query are executed on.
+
'transaction basis'::
This provides an upper bound on the transactions that are visible to a given query - in addition to any restrictions in the query itself.
This also provides a lower bound on the visible transactions, so that a user can read their writes - the node must block until it's indexed this transaction to execute the query.
(In practice, we also advise the user supply a 'basis timeout' to limit how long the node will block.)
+
If it is not supplied, this defaults to the latest completed transaction (as opposed to the current time, because of the above note regarding asynchronous consumption of the tx-log).

== Problem statements

The adoption of some kind of transaction semantics is in service of solving one or more of the following problems:

  There exists in pgwire no means to provide a stable read basis across some sequence of queries, such that you can avoid data races with concurrent writers

  There exists no support in pgwire for DML statements (inserts, updates and deletes)

  Given the asynchronous nature of the tx-log, it is unclear how to map traditional SQL transaction semantics to core2 in a way that is well-defined, reliable and performant. e.g traditional read-after-write, multi-statement atomicity, interactive transactions.

== SQL spec

Much of the SQL spec is not necessarily in scope here such as save points, local transactions and co-operation with external transaction managers, multi-server transactions and so on. So we will ignore those for now (hopefully this is a reasonable core)

=== Transaction isolation

It is important to note the traditional isolation levels are not necessarily meaningful to core2, and may be misleading to try and approximate, as they apply to a totally different target architecture which has room for different policies. In core2, the log architecture seemingly prescribes the concurrency semantics across the board, and so it may not make sense for users to change or specify an isolation level.

=== Transaction access mode (e.g `READ ONLY`)

The access mode parameter is intended to reflect whether certain classes of statement are permitted within a session or transaction.

Like with many of the transactional behaviour parameters, access mode can be defined for a single transaction, or as a default for all subsequent transactions on the session (e.g `SET SESSION CHARACTERISTICS`).

Its default value in the spec is `READ WRITE`.

== PGWire concerns

The pgwire server represents an experimental interface to XT, as such we need not necessarily bend to meet it at the expense of clarity or quality of the core, however it is also important to not burn our bridges with it - as there is a non-zero probability that we do end up supporting it in the long term.

There are then a couple of concerns one should keep in mind as we explore options for solving the above problems

- Postgres clients have expectations on how postgres behaves, some provide helpers for transactions for example that write the SQL for you.
- There seems to be assumptions made by postgres clients of the transaction defaults on the server (such as default access mode) in some cases.
- Transaction access mode is often set on `BEGIN`, so session variables such as READ ONLY are often simulated by client i.e no session `SET` statement is issued to the postgres server when the variable changes.
- Some (most likely at a higher level) may have expectations on read-after-write or postgres specific dml semantics that we cannot reasonably meet (e.g insert returning ids).

I would not put too much weight at this stage on meeting postgres, but as session / transactional semantics are likely to be accessible only via pgwire early on, we should keep this in mind.

== Options

=== A: single statements

One path which allows us to avoid making certain decisions right away is to say that transactions may or may not establish a read basis at some point, and be extended to read-write or async batching. but we will not permit any kind of DML within a transaction for now - i.e. so we can leave transaction behaviour undefined for the time being.

An argument for leaving transactions undefined is simply the difficulty in finding appropriate semantics, If we pull apart the problem statement we see that there are a few dimensions to consider, all with their own challenges.

- repeatable read
- dml support even in principle given our constraints (tx-log, async, atomic only for single put)
- read-after-write support, given our constraints
- desire for a mechanism for submitting multiple dml ops that is sympathetic to the constraints of our atomicity model (async put to tx-log)

There is the so far unmentioned but perhaps relevant desire to see interactive read-write transactions at some point. Though this is certainly out of scope for now.

Another issue is the friction caused by our constraints around asynchronicity and atomicity being in conflict with typical expectations of a SQL database (such as what is imposed upon our postgres server).

Given the challenge, it might be wise to buy as much time as possible to improve our chances of a successful and clear fitting of core2's semantics to our postgres server (If pgwire sticks around!).

So given no transactions, we only support single statements for now, ignore `BEGIN`/`COMMIT`/etc, and behave as if auto-commit is enabled (like postgres).

* If the driver detects that any one of the statements is a write, it will submit the transaction, and synchronously await it before returning to the user.
  If none of the statements are writes, it will execute the query synchronously, as it does currently.
* We'll likely want to support multiple semicolon-delimited statements, in order to preserve the transactional atomicity of a collection of statements.
* Initially, we might decide to not support specifying the co-effect arguments, as the defaults would be quite reasonable if the connection synchronously awaited write transactions.
* Later, we might decide to use session parameters to specify these arguments, although their extent may not be clear without a transaction scope - would the user expect them to apply to just the next query, or to the rest of the session (or until they were changed again)?

=== B: scoped transactions with buffered writes

We use session parameters to specify bases, which are then naturally scoped to the transaction block. Writes are buffered for write transactions, being committed to the tx-log as a single operation on `COMMIT`.

* `START TRANSACTION` (SQL:2011 ยง17.1, p1035) optionally accepts a `<transaction access mode> ::= READ ONLY | READ WRITE` characteristic.
  In the SQL:2011 spec, the `<transaction access mode>` defaults to `READ WRITE`; however, in Postgres, it defaults to the `default_transaction_read_only` configuration parameter.
  We could consider defaulting to `READ ONLY`, which would then require users to explicitly specify `READ WRITE` in order to mutate the database.

Because postgres and the spec default to `READ WRITE`, and due to the assumptions and behaviour of typical postgres clients, it may be somewhat unreliable and brittle to depend on client libraries sending session characteristics hints to the server as required to get the correct semantics described.

The recommendation is to require users to explicitly denote the READ WRITE status of the transaction in SQL. The statement `SET TRANSACTION` (SQL:2011 $17.2, p1037) may be useful for this, as it explicitly changes the access mode of the next transaction only (avoiding issues where you must remember to 'reset' the session characteristics after each transaction).

To be clear a READ WRITE transaction in this world would imply that DML is buffered until commit, each DML op would not execute until committed, to preserve atomicity of the transaction. This implies novel behaviour of our postgres server and as such may itself cause some surprise. Though it is important to stress again the sense in which there needs to be a compromise in the sympathy to and transparency toward core2's actual TX model and the expectations of SQL clients & users.

In https://github.com/seancorfield/next-jdbc[next.jdbc] it would look like this:

[source,clojure]
----
(jdbc/execute! conn ["SET TRANSACTION READ WRITE"])
(jdbc/with-transaction [tx conn]
  ...)
----

In Java:

[source,java]
----
// pretty standard Java SQL connection transaction shenanigans, AFAICT.
Connection conn = ...;
boolean oldReadOnly = conn.getReadOnly();
try (Statement stmt = conn.createStatement()) {
    stmt.executeQuery("SET TRANSACTION READ WRITE");
}
conn.setAutoCommit(false);
...
conn.commit();
----

The intention is by this transaction will only allow DML statements, and they will be executed asynchronously as a single tx-log transaction on `commit`. In that way the desired atomicity of update operations can be achieved.

==== B addendum: flipped defaults

A variation on this approach has been discussed which chooses a `READ WRITE` default for the transaction access mode, but otherwise behaves the same way.

- One advantage of this is that it would mean you do not necessarily need to send a `SET TRANSACTION READ WRITE` to write to the database.
- It also aligns with the spec and postgres default policy, which means configuration defaults are more likely to work out of the box.

However, it does raise questions about query permissibility

- Queries perhaps outside of transactions can be permitted regardless of the access mode policy, to me this provides a pain-free read UX outside repeatable reads
- One option inside transactions is that queries are only permitted in a READ ONLY transaction
- Another could be that reads are permitted until one makes a single write, at which point the transaction refuses any more reads, this although perhaps practical but of course comes with clarity concerns, makes things a little more implicit and even more contextual.
- Another option is the wild west of simply allowing mixed read and writes and being clear in docs of the semantics until there is some interactive transaction support.


== Decision

For ease of implementation, we will initially lean towards implementing option B.

We will later re-consider option A as a sugar atop option B once we have landed option B, and are more familiar with the tradeoffs and nuances involved.
