---
title: Configuration Cookbook
---

This document provides examples for the EDN configuration of XTDB components, to be supplied to `xtdb.api/start-node`.

== Transaction Log 

Main article: link:/config/tx-log[Transaction Log]

[#in-memory-log]
=== In-Memory

Main article: link:/config/tx-log#_in_memory[in-memory transaction log]

This is the default, and can be omitted.

[source,clojure]
----
{:log [:in-memory
       {;; -- optional

        ;; :instant-src (java.time.InstantSource/system)
        }]}
----

[#local-log]
=== Local disk

Main article: link:/config/tx-log#_local_disk[local-disk transaction log]

[source,clojure]
----
{:log [:local
       {;; -- required
        ;; accepts `String`, `File` or `Path`
        :path "/tmp/tx-log"

        ;; -- optional

        ;; accepts `java.time.InstantSource`
        ;; :instant-src (InstantSource/system)

        ;; :buffer-size 4096
        ;; :poll-sleep-duration "PT1S"
        }]}
----

[#kafka]
=== Kafka

Main article: link:/config/tx-log/kafka[Kafka]

[source,clojure]
----
{:log [:kafka
       {;; -- required
        :bootstrap-servers "localhost:9092"
        :topic-name "xtdb-log"

        ;; -- optional

        ;; :create-topic? true
        ;; :poll-duration #xt.time/duration "PT1S"
        ;; :properties-file "kafka.properties"
        ;; :properties-map {}
        ;; :replication-factor 1
        ;; :topic-config {}
        }]}
----

== Storage

Main article: link:/config/storage[Storage]

[#in-memory-storage]
=== In-Memory

Main article: link:/config/storage#in-memory[in-memory storage]

This is the default, and should be omitted.

[#local-storage]
=== Local disk

Main article: link:/config/storage#local-disk[local-disk storage]

[source,clojure]
----
{:storage [:local
           {;; -- required

            ;; accepts `String`, `File` or `Path`
            :path "/var/lib/xtdb/storage"

            ;; -- optional

            ;; :max-cache-bytes 1024
            ;; :max-cache-entries 536870912
           }]}
----

[#remote-storage]
=== Remote

Main article: link:/config/storage#remote[remote storage]

[source,clojure]
----
{:storage [:remote {;; -- required 
                    
                    ;; Each object store implementation has its own configuration - 
                    ;; see below for some examples.
                    :object-store [:object-store-implementation {}]

                    ;; accepts `String`, `File` or `Path`
                    :local-disk-cache "/tmp/local-disk-cache"

                    ;; -- optional
                    ;; :max-cache-entries 1024
                    ;; :max-cache-bytes 536870912
                    }]}
----

[#s3]
=== S3

Main article: link:/config/storage/s3[S3]

[source,clojure]
----
{:storage [:remote
           {:object-store [:s3
                           {;; -- required
                            :bucket "my-bucket"
                            :sns-topic-arn "arn:aws:sns:region:account-id:my-sns-topic"

                            ;; -- optional

                            ;; :prefix "my-xtdb-node"
                            ;; :configurator (reify S3Configurator
                            ;;                 ...)
                           }]}]}
----

[#azure]
=== Azure Blob Storage

Main article: link:/config/storage/azure[Azure Blob Storage]

[source,clojure]
----
{:storage [:remote
           {:object-store [:azure
                           {;; -- required
                            :storage-account "storage-account"
                            :container "xtdb-container"
                            :service-bus-namespace "xtdb-service-bus"
                            :service-bus-topic-name "xtdb-service-bus-topic"

                            ;; -- optional

                            ;; :prefix "my-xtdb-node"
                           }]}]}
----


[#google-cloud]
=== Google Cloud Storage

Main article: link:/config/storage/google-cloud[Google Cloud Storage]

[source,clojure]
----
{:storage [:remote
           {:object-store [:google-cloud
                           {;; -- required
                            :project-id "xtdb-project"
                            :bucket "xtdb-bucket"
                            :pubsub-topic "xtdb-bucket-topic"

                            ;; -- optional

                            ;; :prefix "my-xtdb-node"
                           }]}]}
----

== Optional Modules

[#http-server]
=== HTTP Server

Main article: link:/config/modules/http-server[HTTP Server]

[source,clojure]
----
{:http-server {;; -- optional

               ;; :port 3000
              }}
----
