---
title: SQL Transactions
---

For examples on how to submit SQL transactions in each client library, see the link:/drivers[individual driver documentation].

[#tx-ops]
== Transaction operations

=== `INSERT`

Inserts documents into a table.

[railroad]
----
const insertIntoTable = rr.Sequence("INSERT", "INTO", "<table name>")
const colNames = rr.Sequence("(", rr.OneOrMore("<column name>", ","), ")")
const doc = rr.Sequence("(", rr.OneOrMore("<value>", ","), ")")
const docs = rr.OneOrMore(doc, ",")
const values = rr.Sequence(colNames, "VALUES", docs)
const objs = rr.OneOrMore(rr.Choice(0, "<object>", "<param>"), ",")
const records = rr.Sequence(rr.Optional(colNames, "skip"), "RECORDS", objs)
const selectQuery = rr.Sequence(rr.Optional(colNames, "skip"), "<select query>")
return rr.Diagram(rr.Stack(insertIntoTable, rr.Choice(0, values, records, selectQuery)))
----

* Documents must contain an `_id` column.
* By default, the document will be inserted for valid-time between now and end-of-time.
  This can be overridden by including `_valid_from` and/or `_valid_to` columns in the document.
* If the document already exists, 'insert' behaves like an upsert - it will overwrite the existing document for the valid-time range specified (or now -> end-of-time if not provided).


=== `UPDATE`

Updates documents in a table, optionally for a period of valid-time.

[railroad]
----
const updateTable = rr.Sequence("UPDATE", "<table name>")
const portionOf = rr.Optional(rr.Sequence("PORTION", "OF"), "skip")
const forValidTime = rr.Choice(0,
  rr.Sequence("FOR", portionOf, "VALID_TIME", "FROM", "<timestamp>", rr.Optional(rr.Sequence("TO", "<timestamp>"), 'skip')),
  rr.Sequence("FOR", "ALL", "VALID_TIME"),
  rr.Sequence("FOR", "VALID_TIME", "ALL"))
const setClause = rr.Sequence("SET", rr.OneOrMore(rr.Sequence("<column>", "=", "<value>"), ","))
const predicate = rr.Optional(rr.Sequence("WHERE", "<predicate>"), "skip")
return rr.Diagram(rr.Stack(updateTable, rr.Optional(forValidTime, "skip"), rr.Sequence(setClause, predicate)))
----

* If the valid-time range is not provided, the effective valid-time range of the update will be from now to the end of time.
  (SQL:2011 specifies that updates without this clause should be effective for all valid time; the now->end-of-time default is an XTDB deviation.)
* The `_id` column cannot be updated - instead, users should delete this document and re-insert a new one.
* The valid-time columns cannot be updated outside of the for-valid-time clause (i.e. not in the `SET` clause).

=== `PATCH`

Patches documents already in a table with the given document - updating those that exist, inserting any that don't (an 'upsert') - optionally for a period of valid-time.

[railroad]
----
const patchTable = rr.Sequence("PATCH", "INTO", "<table name>")
const portionOf = rr.Optional(rr.Sequence("PORTION", "OF"), "skip")
const forValidTime = rr.Optional(
  rr.Sequence("FOR", portionOf, "VALID_TIME", "FROM", "<timestamp>", rr.Optional(rr.Sequence("TO", "<timestamp>"), 'skip')))
const objs = rr.OneOrMore(rr.Choice(0, "<object>", "<param>"), ",")
const records = rr.Sequence("RECORDS", objs)
return rr.Diagram(rr.Stack(patchTable, rr.Optional(forValidTime, "skip"), records))
----

* If the valid-time range is not provided, the effective valid-time range of the update will be from now to the end of time.
* The `_id` column cannot be patched - instead, users should delete this document and re-insert a new one.
* The valid-time columns cannot be updated outside of the for-valid-time clause (i.e. not in the records themselves).
* Documents are currently merged at the granularity of individual keys - e.g. if a key is present in the patch document, it will override the same key in the database document; if a key is absent or null, the key from the document already in the database will be preserved.

=== `DELETE`

Deletes documents from a table, optionally for a period of valid-time.

[railroad]
----
const deleteTable = rr.Sequence("DELETE", "FROM", "<table name>")
const portionOf = rr.Optional(rr.Sequence("PORTION", "OF"), "skip")
const forValidTime = rr.Choice(0,
  rr.Sequence("FOR", portionOf, "VALID_TIME", "FROM", "<timestamp>", rr.Optional(rr.Sequence("TO", "<timestamp>"), 'skip')),
  rr.Sequence("FOR", "ALL", "VALID_TIME"),
  rr.Sequence("FOR", "VALID_TIME", "ALL"))
const predicate = rr.Optional(rr.Sequence("WHERE", "<predicate>"), "skip")
return rr.Diagram(rr.Stack(deleteTable, rr.Optional(forValidTime, "skip"), predicate))
----

* If the valid-time clause is not provided, the effective valid-time range of the delete will be from now to the end of time.
  (SQL:2011 specifies that deletes without this clause should be effective for all valid time; the now->end-of-time default is an XTDB deviation.)

=== `ERASE`

Irrevocably erases documents from a table, for all valid-time, for all system-time.

While XTDB is immutable, in some cases it is legally necessary to irretrievably delete data (e.g. for a GDPR request).
This operation removes data such that even queries as of a previous system-time no longer return the erased data.

[railroad]
----
const eraseTable = rr.Sequence("ERASE", "FROM", "<table name>")
const predicate = rr.Optional(rr.Sequence("WHERE", "<predicate>"), "skip")
return rr.Diagram(rr.Stack(eraseTable, predicate))
----

=== `ASSERT`

Rolls back the transaction if the provided predicate is false.

This is used to enforce constraints on the data in a concurrent environment, such as ensuring that a document with a given ID does not already exist.

[railroad]
----
return rr.Diagram("ASSERT", "<predicate>", rr.Optional("<message>"))
----

If the optional message string is provided, it replaces the default error message text “Assert failed”, should the predicate fail.

* We check to see whether the email address already exists in the database - if not, we can insert the new user.
+
[source,sql]
----
ASSERT NOT EXISTS (SELECT 1 FROM users WHERE email = 'james@example.com'), 'Email already exists!'

INSERT INTO users (_id, name, email) VALUES ('james', 'James', 'james@example.com')
----
* Check the `xt.txs` table for the transaction result to see if the assertion failed.
+
[source,sql]
SELECT * FROM xt.txs;
+
[source,text]
----
 _id  | committed |            error              |          system_time
------+-----------+-------------------------------+-------------------------------
    0 | t         | null                          | "2024-06-25T16:45:16.492255Z"
    1 | t         | null                          | "2024-06-25T16:45:26.985539Z"
    2 | f         | ... "Precondition failed" ... | "2024-06-25T16:45:32.577224Z"
(3 rows)
----

=== `COPY`

Copies data directly into an XTDB table - usually significantly more efficiently than the equivalent `INSERT`s.

[railroad]
----
const formatOpt = rr.Sequence("FORMAT", rr.Optional('=', 'skip'), rr.Choice(0, "'transit-json'", "'transit-msgpack'"))

return rr.Diagram(rr.Stack(
  rr.Sequence("COPY", "<table name>", "FROM", "STDIN"),
  rr.Sequence("WITH", "(", rr.ZeroOrMore(rr.Choice(0, formatOpt), ',', 'skip'), ")")
))
----

* A single `COPY` will atomically insert all of its documents within one transaction - if you're using Kafka, we recommend you split your documents into batches of ~1-10k so as not to exceed Kafka's message size limits.
* If you're using `psql` (or a similar tool) to connect to XTDB, those tools also support other sources in addition to `STDIN` - please see their own documentation for more details.
  For example, `psql` has a link:https://www.postgresql.org/docs/current/app-psql.html#APP-PSQL-META-COMMANDS-COPY[`\copy`^] command which supports loading from a file.
* Currently, there are two accepted formats: `'transit-json'` and `'transit-msgpack'`.
  For more details on the Transit format, see the https://github.com/cognitect/transit-format?tab=readme-ov-file#implementations[available libraries^] for your language.
* On the JVM, you can use Postgres's link:https://jdbc.postgresql.org/documentation/publicapi/org/postgresql/copy/CopyManager.html[`CopyManager`^] with an XTDB connection by calling `conn.unwrap(PGConnection.class).getCopyAPI()`.
* In the Clojure API, `:put-docs` uses `COPY` commands on your behalf.
