---
title: AWS
---

XTDB provides modular support for AWS environments, including a pre-built Docker image, integrations for **S3 storage** and **CloudWatch metrics**, and configuration options for deploying onto AWS infrastructure.

NOTE: For more information on setting up an XTDB cluster on AWS, see the link:guides/starting-with-aws["Getting Started with AWS"^] guide.

== Required infrastructure

In order to run an AWS based XTDB cluster, the following infrastructure is required:

* An **S3 bucket** for remote storage.
* A **Kafka cluster** for the message log.
** Within AWS, you can use the https://aws.amazon.com/msk/[Amazon Managed Streaming for Apache Kafka (MSK)^] service.
** For more information on setting up Kafka for usage with XTDB, see the link:config/log/kafka[Kafka configuration^] docs.
* IAM policies which grant XTDB permission to the S3 bucket and Kafka cluster.
* XTDB nodes configured to communicate with the Kafka cluster and S3 bucket.

[#terraform]
== Terraform Templates

To set up a basic version of the required infrastructure, we provide a set of Terraform templates specifically designed for AWS.

These can be fetched from the XTDB repository using the following command:

```bash
terraform init -from-module github.com/xtdb/xtdb.git//aws/terraform
```

=== Resources

By default, running the templates will deploy the following infrastructure:

* TODO

=== Configuration

In order to customize the deployment, we provide a number of pre-defined variables within the `terraform.tfvars` file.
These variables can be modified to tailor the infrastructure to your specific needs.

For more advanced usage, the Terraform templates themselves can be modified to suit your specific requirements.

'''

[#helm]
== `xtdb-aws` Helm Charts

For setting up a production-ready XTDB cluster on AWS, we provide a **Helm** chart built specifically for AWS environments.

=== Installation

The Helm chart can be installed directly from the link:https://github.com/xtdb/xtdb/pkgs/container/helm-xtdb-aws[**Github Container Registry** releases]. 

This will use the default configuration for the deployment, setting any required values as needed:  

```bash
helm install xtdb-aws oci://ghcr.io/xtdb/helm-xtdb-aws \
  --version 2.0.0-snapshot \
  --namespace xtdb-deployment \
  --set TODO
```

We provide a number of parameters for configuring numerous parts of the deployment, see the link:https://github.com/xtdb/xtdb/tree/main/aws/helm[`values.yaml` file] or call `helm show values`:

```bash
helm show values oci://ghcr.io/xtdb/helm-xtdb-aws \
  --version 2.0.0-snapshot 
```

=== Resources

By default, the following resources are deployed by the Helm chart:

* A `StatefulSet` containing a configurable number of XTDB nodes, using the link:#docker-image[**xtdb-aws** docker image]
* A `PersistentVolumeClaim` for each member of the `StatefulSet` (default size of 50 GiB, default storage class of TODO)
* A `LoadBalancer` Kubernetes service to expose the XTDB cluster to the internet.
* A `ClusterIP` service for exposing the **Prometheus** metrics from the nodes.
* A `ServiceAccount` used for authenticating the XTDB nodes with the S3 Bucket (TODO).

=== Pulling the Chart Locally

The chart can also be pulled from the **Github Container Registry**, allowing further configuration of the templates within:

```bash
helm pull oci://ghcr.io/xtdb/helm-xtdb-aws \
  --version 2.0.0-snapshot \
  --untar
```

'''

[#docker-image]
== `xtdb-aws` Docker Image

The https://github.com/xtdb/xtdb/pkgs/container/xtdb-aws[**xtdb-aws**^] image is optimized for running XTDB in AWS environments, and is deployed on every release to XTDB. 

By default, it will use **S3** for storage and **Kafka** for the message log, including dependencies for both.

=== Configuration

The following environment variables are used to configure the `xtdb-aws` image:

[cols="2,3", options="header"]
|===
| Variable              | Description

| `KAFKA_BOOTSTRAP_SERVERS`
| Kafka bootstrap server containing the XTDB topics.

| `XTDB_LOG_TOPIC`
| Kafka topic to be used as the XTDB log.

| `XTDB_S3_BUCKET`
| Name of the S3 bucket used for remote storage.

| `XTDB_NODE_ID`
| Persistent node id for labelling Prometheus metrics.

|===

You can also link:/ops/troubleshooting#loglevel[set the XTDB log level] using environment variables.

=== Using a Custom Node Configuration

For advanced usage, XTDB allows the above YAML configuration to be overridden to customize the running node's system/modules.

In order to override the default configuration:

. Mount a custom YAML configuration file to the container.
. Override the `COMMAND` of the docker container to use the custom configuration file, ie:
+
[source, bash]
----
CMD ["-f", "/path/to/custom-config.yaml"]
----

[#storage]
== S3 Storage

https://aws.amazon.com/s3/[**Amazon S3**^] can be used as a shared object-store for XTDB's link:config/storage#remote[remote storage^] module.

=== Infrastructure Requirements

[NOTE]
====
We provide a https://github.com/xtdb/xtdb/blob/main/modules/aws/cloudformation/s3-stack.yml[parameterized CloudFormation stack^] to help set up everything that you need.

The stack accepts the (globally unique) name of an S3 bucket as an input - this will be created, and referenced in associated resources - to be used in your XTDB configuration.
====

To use S3 as the object store, the following infrastructure is required:

. An **S3 bucket**.
. **IAM policies** which grant XTDB permission to the S3 bucket:
+
[source,yaml]
----
Statement:
- Effect: Allow
  Action:
    - 's3:GetObject'
    - 's3:PutObject'
    - 's3:DeleteObject'
    - 's3:ListBucket'
    - 's3:AbortMultipartUpload'
    - 's3:ListBucketMultipartUploads'
  Resource:
    - !Ref S3BucketArn
    - !Join [ '', [ !Ref S3BucketArn, '/*'] ]
----

=== Authentication

XTDB uses AWS SDK for Authentication, relying on the default AWS credential provider chain.
See the https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/credentials-chain.html[AWS documentation^] for setup instructions.

=== Configuration

To use the S3 module, include the following in your node configuration:

[source,yaml]
----
storage: !Remote
  objectStore: !S3
    ## -- required

    ## The name of the S3 bucket to use for the object store
    ## (Can be set as an !Env value)
    bucket: "my-s3-bucket" 

    ## -- optional

    ## A file path to prefix all of your files with
    ## - for example, if "foo" is provided, all XTDB files will be located under a "foo" sub-directory
    ## (Can be set as an !Env value)
    # prefix: my-xtdb-node

    ## Basic credentials for AWS.
    ## If not provided, will default to AWS's standard credential resolution.
    ## see: https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/credentials-chain.html
    # credentials:
    #   accessKey: "..."
    #   secretKey: "..."

    ## Endpoint URI
    ## If not provided, will default to the standard S3 endpoint for the resolved region.
    # endpoint: "https://..."

  localDiskCache: /var/cache/xtdb/object-store
----

If configured as an in-process node, you can also specify an `S3Configurator` instance - this is used to modify the requests sent to S3.

[#monitoring]
== CloudWatch Monitoring

XTDB supports reporting metrics to https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/WhatIsCloudWatch.html[**AWS Cloudwatch**^] for performance and health monitoring.

=== Configuration

To report XTDB node metrics to CloudWatch, include the following in your node configuration:

[source,yaml]
----
modules:
  - !CloudWatch
----

Authentication is handled via the AWS SDK, using the default AWS credential provider chain.
See the https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/credentials-chain.html[AWS documentation^] for setup instructions.

The associated credentials must have permissions to write metrics to a pre-configured `CloudWatch` namespace.

