---
title: AWS
---

XTDB has a range of AWS support, providing modules for using S3 for storage, CloudWatch for metrics reporting, and a standard Docker image for use in AWS environments.

See the link:guides/starting-with-aws["Getting Started with AWS"] guide for more information on setting up an XTDB cluster on AWS.

[#storage]
== S3 Storage

S3 can be used as a shared object-store for XTDB's remote storage module.

=== Infrastructure

[NOTE]
====
We provide a https://github.com/xtdb/xtdb/blob/main/modules/aws/cloudformation/s3-stack.yml[parameterized CloudFormation stack] to help set up everything that you need.

The stack accepts the (globally unique) name of an S3 bucket as an input - this will be created, and referenced in associated resources - to be used in your XTDB configuration.
====

To use S3 as the object store, the following infrastructure is required:

. An **S3 bucket**.
. **IAM policies** which grant XTDB permission to the S3 bucket:
+
[source,yaml]
----
Statement:
- Effect: Allow
  Action:
    - 's3:GetObject'
    - 's3:PutObject'
    - 's3:DeleteObject'
    - 's3:ListBucket'
    - 's3:AbortMultipartUpload'
    - 's3:ListBucketMultipartUploads'
  Resource:
    - !Ref S3BucketArn
    - !Join [ '', [ !Ref S3BucketArn, '/*'] ]
----

=== Authentication

Authentication is done via the AWS SDK, using the default AWS credential provider chain.
See the https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/credentials-chain.html[AWS documentation] for setup instructions.

=== Configuration

To use the S3 module, include the following in your node configuration:

[source,yaml]
----
storage: !Remote
  objectStore: !S3
    ## -- required

    ## The name of the S3 bucket to use for the object store
    ## (Can be set as an !Env value)
    bucket: "my-s3-bucket" 

    ## -- optional

    ## A file path to prefix all of your files with
    ## - for example, if "foo" is provided, all XTDB files will be located under a "foo" sub-directory
    ## (Can be set as an !Env value)
    # prefix: my-xtdb-node

    ## Basic credentials for AWS.
    ## If not provided, will default to AWS's standard credential resolution.
    ## see: https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/credentials-chain.html
    # credentials:
    #   accessKey: "..."
    #   secretKey: "..."

    ## Endpoint URI
    ## If not provided, will default to the standard S3 endpoint for the resolved region.
    # endpoint: "https://..."

  localDiskCache: /var/cache/xtdb/object-store
----

If configured as an in-process node, you can also specify an `S3Configurator` instance - this is used to modify the requests sent to S3.

[#monitoring]
== CloudWatch Monitoring

To report XTDB node metrics to **AWS CloudWatch**, we can the `!CloudWatch` module as follows:

[source,yaml]
----
modules:
  - !CloudWatch
----

Authentication is handled via the AWS SDK, using the default AWS credential provider chain.
See the https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/credentials-chain.html[AWS documentation] for setup instructions.

The associated credentials must have permissions to write metrics to a pre-configured `CloudWatch` namespace.


== `xtdb-aws` Docker Image

The `xtdb-aws` image is optimized for running XTDB in AWS environments, and is deployed on every release to XTDB.

[source,bash]
----
xtdb/xtdb-aws:2.0.0-beta4
----

By default, it will use S3 for storage and Kafka for transaction logs, including dependencies for both.

=== Required infrastructure

To run the `xtdb-aws` image with the default configuration, the following infrastructure is required:

. An **S3 bucket** for remote storage.
. A **Kafka cluster** for transaction logs.
.. Within AWS, you can use the https://aws.amazon.com/msk/[Amazon Managed Streaming for Apache Kafka (MSK)] service.
. IAM policies which grant XTDB permission to the S3 bucket and Kafka cluster.

=== Standard Configuration

The following YAML configuration is included with and used by default in the `xtdb-aws` image:

[source,yaml]
----
txLog: !Kafka
  bootstrapServers: !Env KAFKA_BOOTSTRAP_SERVERS
  txTopic: !Env XTDB_TX_TOPIC
  filesTopic: !Env XTDB_FILES_TOPIC

storage: !Remote
  objectStore: !S3
    bucket: !Env XTDB_S3_BUCKET
    prefix: "xtdb-object-store"
  localDiskCache: /var/lib/xtdb/buffers

healthz:
  port: 8080

modules:
- !HttpServer
  port: 3000
----

The following environment variables are used to configure the image:

[cols="2,3", options="header"]
|===
| Variable              | Description

| `KAFKA_BOOTSTRAP_SERVERS`
| Kafka bootstrap servers for transaction logs.

| `XTDB_TX_TOPIC`
| Kafka topic used as the XTDB transaction log.

| `XTDB_FILES_TOPIC`
| Kafka topic used for publishing/subscribing to XTDB file notifications.

| `XTDB_S3_BUCKET`
| Name of the S3 bucket used for remote storage.

|===

=== Overriding the default configuration

For advanced usage, XTDB allows the above YAML configuration to be overridden by mounting a custom configuration file to the container.

To override the default configuration:
- Mount a custom YAML configuration file to the container.
- Override the `COMMAND` of the docker container to use the custom configuration file, ie `-f /path/to/custom-config.yaml`.

