---
title: Configuration
---

== Components

An XTDB node consists of a number of components.

For information on how to configure these and switch out implementations, see their reference documents:

* link:config/log[Log]
* link:config/storage[Storage]
* link:config/modules[Optional Modules]

== Configuring using YAML

Currently, all of the examples within the reference docs are in YAML.
Config for the components is done at the top level of the file, i.e. you can specify the following keys, not nested under anything else: `storage`, `log`, `modules`.

Within the drivers, we offer the ability to provide and configure the node by passing the path to a YAML config file.

=== Using `!Env`

For certain keys, we allow the use of environment variables - typically, the keys where we allow this are things that may change *location* across environments. Generally, they are either "paths" or "strings".

When specifying a key, you can use the `!Env` tag to reference an environment variable. As an example:

[source,yaml]
----
storage: !Local
  path: !Env XTDB_STORAGE_PATH
----

Any key that we allow the use of `!Env` will be documented as such.

=== Monitoring & Observability

XTDB provides a suite of tools & templates to facilitate monitoring and observability. See link:config/monitoring[Monitoring & Observability].

=== Authentication

The pg-wire server and the http-server both support authentication which can be configured via authentication rules.
See link:config/authentication[Authentication].

=== Other configuration:

XTDB nodes accept other optional configuration, as follows:

[source,yaml]
----
server:
  # Host on which to start a read-write Postgres wire-compatible server.
  #
  # Default is "localhost", which means the server will only accept connections on the loopback interface.
  # Set to '*' to accept connections on all interfaces.
  host: localhost

  # Port on which to start a read-write Postgres wire-compatible server.
  #
  # Default is 0, to have the server choose an available port.
  # (In the XTDB Docker images, this is defaulted to 5432.)
  # Set to -1 to not start a read-write server.
  port: 0

  # Port on which to start a read-only Postgres wire-compatible server.
  #
  # The server on this port will reject any attempted DML/DDL,
  # regardless of whether the user would otherwise have the permission to do so.
  #
  # Default is -1, to not start a read-only server.
  # Set to 0 to have the server choose an available port.
  readOnlyPort: -1

compactor:
  # Number of threads to use for compaction.

  # Defaults to min(availableProcessors / 2, 1).
  # Set to 0 to disable the compactor.
  threads: 4
----

=== CLI flags

The following flags can be passed, either directly to the CLI or via Docker's arguments:

* `--compactor-only`: runs a compactor-only node.
