= Contributing
:page-aliases: about::contributing.adoc

== Thanks

Crux would not exist without the community of vibrant open source projects on which it depends, and we hope that the Crux community will serve to extend and reflect our gratitude.

[#github-info]
== GitHub

We currently use GitHub Issues to work on near-term changes to the Crux codebase and documentation.
Please see the issues labelled with https://github.com/xtdb/xtdb/labels/good%20first%20issue["good first issue"] if you are looking for ideas to help push Crux forward.

PRs with fixes and improvements to these docs are very welcome.

[#commits]
== Commits

Please strive to follow the best-practices for commit messages which are outlined https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html[here].

[#cla]
== CLA

A Contributor License Agreement (CLA) is necessary for us to ensure that we can support a healthy Crux ecosystem over the indefinite future.
Please complete the very short `.rtf` template linked below and email it to us, crux@juxt.pro, along with a reference to your current PR on GitHub.

https://raw.githubusercontent.com/xtdb/xtdb/master/docs/open-crux-individual-contributor-license-agreement-cla.rtf[Open Crux CLA]
