---
title: Troubleshooting
---

If you encounter any issues, it is recommended to raise a ticket at link:https://github.com/xtdb/xtdb/issues[XTDB Issues].
Additionally, check if someone else has already experienced and resolved a similar issue.

[#loglevel]
== Increasing the Log Level
If you face issues with XTDB and the logs (`INFO` by default) do not provide any specific information about the problem,
you can try increasing the log level to `DEBUG` or `TRACE`.

Example `logback.xml`:
[source,xml]
----
<configuration>
    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
    </appender>
    <root level="WARN">
        <appender-ref ref="STDOUT" />
    </root>
    <logger name="xtdb" level="TRACE" />
</configuration>
----

You can then pass the `logback.xml` configuration file to the Docker container using the following command:

`docker run --volume .:/config --env JDK_JAVA_OPTIONS='-Dlogback.configurationFile=/config/logback.xml' ...`

=== Setting Log Level via Environment Variables

We provide the ability to set the root XTDB log level using the `XTDB_LOGGING_LEVEL` environment variable:

`docker run --env XTDB_LOGGING_LEVEL='DEBUG' ...`

We also provide the ability to configure the log level for specific namespaces/components using `XTDB_LOGGING_LEVEL_<namespace>`. For example, to set the `compactor` namespace to `DEBUG`;

`docker run --env XTDB_LOGGING_LEVEL_COMPACTOR='DEBUG' ...`

[#ingestion-stopped]
== Ingestion Stopped

As XTDB is a deterministic system (every node must index transactions in exactly the same way),
it is crucial to ensure that everything written to disk is deterministic.
This is a strict requirement because inconsistencies in node states can lead to various issues later.

If you encounter an `Ingestion Stopped: ... some cause ...` error, it means we were unable to guarantee this
requirement and had to stop ingestion.
Please raise an issue with the full stack trace at link:https://github.com/xtdb/xtdb/issues[XTDB Issues].

// === Skipping Transactions

// When encountering a deterministic ingestion stopping issue, we provide `XTDB_SKIP_TXS` as a mechanism to move ingestion past particular errant/erroneous transactions.

// WARNING: This should _only_ be done if you are entirely certain that the issue is deterministic and causes all nodes to stop ingestion at the same point. This change _must_ be applied atomically - ie, all nodes must be stopped, the change applied, and then all nodes restarted. We _cannot_ risk  one node committing a transaction and another rolling the same transaction back.

// The process of using `XTDB_SKIP_TXS` is as follows:

// . Verify that ingestion stops at the same transaction on all nodes - identify this errant transaction. This is available within the logs.
// . Scale down all nodes within the XTDB cluster.
// . Set `XTDB_SKIP_TXS="<txId>,<txId2>..."` as an environment variable on all of the nodes.
// . Restart all nodes within the XTDB cluster.
// . When the errant transaction has been skipped, you will see a `WARN` Log within the node's logs.
// .. "Skipping transaction offset 2109 - within XTDB_SKIP_TXS"
// . Once the next block has been written, you will see a `INFO` Log from `xtdb.indexer.live-index`:
// .. "All XTDB_SKIP_TXS have been skipped and block has been finished - it is safe to remove the XTDB_SKIP_TXS environment variable."
// . Once it is safe to remove the `XTDB_SKIP_TXS` environment variable, scale down all nodes within the XTDB cluster.
// . Remove the `XTDB_SKIP_TXS` environment variable from all nodes.
// . Restart all nodes within the XTDB cluster.

