= Datalog
:page-aliases: reference::transactions.adoc reference::queries.adoc

TODO: This document is currently broken, as "Transactions" and its children are all at the H2 level.
(Same with "Queries".) If we put those at the H1 level, Antora navigation breaks.

* xref:_transaction[Transactions]
* xref:_queries[Queries]

== Transactions

Transactions are how you insert and modify data within XTDB.

Transactions are atomic, and comprised of a sequence of operations to be performed.

If the transaction contains pre-conditions, all pre-conditions must pass, or the entire transaction is aborted.
This processing happens at each node during indexing, and not when submitting the transaction.

[tabs]
====
Java::
+
--
A transaction is performed by calling `.submitTx` on an `IXtdbSubmitAPI` with a `Transaction` object.

The `Transaction` object can be created by either using `Transaction.Builder` directly or using a `Consumer`.

If using the `Consumer` approach, we recommend importing `xtdb.api.tx.Transaction.buildTx` statically for brevity.

[source,java]
----
include::example$test/xtdb/docs/examples/transactions/TransactionsTest.java[tags=creating-0,indent=0]

include::example$test/xtdb/docs/examples/transactions/TransactionsTest.java[tags=creating-1,indent=0]

include::example$test/xtdb/docs/examples/transactions/TransactionsTest.java[tags=creating-2,indent=0]

// To run the transaction:
include::example$test/xtdb/docs/examples/transactions/TransactionsTest.java[tags=using-0,indent=0]

// To run a transaction directly:
include::example$test/xtdb/docs/examples/transactions/TransactionsTest.java[tags=using-1,indent=0]
----
--

Clojure::
+
--
A transaction is performed by calling `xtdb.api/submit-tx` on a node with a list of transaction operations.

[source,clj]
----
(xt/submit-tx node
                [
                ;; Operations
                ])
----
--
====

[#operations]
== Operations

There are five transaction (write) operations:

.Write Operations
[cols="3,5,^2"]
|===
|Operation|Purpose|Pre-condition?

|<<#put, Put>>|Write a version of a document|
|<<#delete, Delete>>|Deletes a specific document|
|<<#match, Match>>|Check the document state against the given document|✓
|<<#evict, Evict>>|Evicts a document entirely, including all historical versions|
|<<#transaction-functions, Function>>|Runs a transaction function|✓
|===

[tabs]
====
Java::
+
--
You can add individual operations to the `Transaction.Builder` instance with their respective methods.
--

Clojure::
+
--
Transaction Operations are vectors which have their associated keyword as their first value.
--
====

[#put]
=== Put

Puts a <<#document, Document>> into XTDB.
If a document already exists with the same `id`, a new version of this document will be created at the supplied `valid time`.
See <<valid-time, Valid Time>> for more details.

[tabs]
====
Java::
+
--
[source,java]
----
include::example$test/xtdb/docs/examples/transactions/TransactionsTest.java[tags=put,indent=0]
----
<1> Putting a document as of now.
<2> Putting a document with a specific <<valid-time, valid time>>
<3> Putting a document with a <<valid-time, valid time>> and <<end-valid-time, end valid time>>
--

Clojure::
+
--
[source,clojure]
----
include::example$test/xtdb/docs/examples/transactions/transactions_test.clj[tags=put,indent=0]
----
<1> Document to add
<2> (optional) <<valid-time,`valid time`>>
<3> (optional) <<end-valid-time,`end valid time`>>
--
====

[#delete]
=== Delete

Deletes a <<#document, Document>> . See <<valid-time,Valid Time>> for details on how this interacts with multiple versions of the document.

[tabs]
====
Java::
+
--
[source,java]
----
include::example$test/xtdb/docs/examples/transactions/TransactionsTest.java[tags=delete,indent=0]
----

<1> Deletes as of now
<2> Deleting with a specific <<valid-time, valid time>>
<3> Deleting with a <<valid-time, valid time>> and <<end-valid-time, end valid time>>
--

Clojure::
+
--
[source,clojure]
----
include::example$test/xtdb/docs/examples/transactions/transactions_test.clj[tags=delete,indent=0]
----
<1> Document ID to be deleted
<2> (optional) <<valid-time,`valid time`>>
<3> (optional) <<end-valid-time,`end valid time`>>
--
====

[#match]
=== Match

Match checks the state of an entity - if the entity doesn't match the provided document, the transaction will not continue.

Use the `hasTxCommitted` (`tx-committed?`) API to check whether the transaction was successfully committed or not due to a failed match operation.

[tabs]
====
Java::
+
--
[source,java]
----
include::example$test/xtdb/docs/examples/transactions/TransactionsTest.java[tags=match,indent=0]
----

<1> Passes if `document1` is exactly present now
<2> Passes if `document2` is exactly present at <<valid-time,`validTime1`>>
<3> Passes if there is no document with the id `documentId1` present now
<4> Passes if there is no document with the id `documentId2` present at <<valid-time,`validTime2`>>
<5> Operation(s) to apply if all preconditions are met
--

Clojure::
+
--
[source,clojure]
----
include::example$test/xtdb/docs/examples/transactions/transactions_test.clj[tags=match,indent=0]
----

<1> ID to be matched (for an entity which may or may not exist)
<2> A specific document revision (or `nil`)
<3> (optional) <<valid-time,`valid time`>>
<4> Operation(s) to perform if the document is matched

If the document supplied is `nil`, the match only passes if there does not exist a document with the given ID.
--
====

[#evict]
=== Evict

Evicts a document from XTDB. Historical versions of the document will no longer be available.

[tabs]
====
Java::
+
--
[source,java]
----
include::example$test/xtdb/docs/examples/transactions/TransactionsTest.java[tags=evict,indent=0]
----
--

Clojure::
+
--
[source,clojure]
----
include::example$test/xtdb/docs/examples/transactions/transactions_test.clj[tags=evict,indent=0]
----
--
====

Evict is primarily used for GDPR Right to Erasure compliance.

It is important to note that Evict is the only operation which will have effects on the results returned when querying against an earlier Transaction Time.

[#transaction-functions]
=== Transaction Functions

Transaction functions are user-supplied functions, defined using Clojure, that will run on each individual node where a transaction is being ingested and processed after having been read from the transaction log.
They are conceptually similar to "stored procedures" in traditional databases, except they can only return new transaction operations.

Transaction functions can be used, for example, to safely check the current database state before applying a transaction, for integrity checks, or to patch an entity.

[#transaction-functions-anatomy]
==== Anatomy
[source,clojure]
----
include::example$test/xtdb/docs/examples/transactions/transactions_test.clj[tags=fn-anatomy,indent=0]
----
<1> Transaction functions are passed a `context` parameter and any number of other parameters.
<2> The `context` parameter can be used to obtain a database value using `db` or `open-db`.
<3> Transaction functions should return a list of transaction operations or `false`

If a list of transaction operations is returned, these are indexed as part of the transaction.

If `false` is returned, or an exception is thrown, the whole transaction will roll back.

The `context` reflects the speculative accumulation of all transaction operations applied up to the current point in the processing.

==== Creating / Updating

Transaction functions are created/updated by submitting a document to XTDB with the desired function.

[tabs]
====
Java::
+
--
You create a function document with `XtdbDocument.createFunction`.

It takes the ID for the function as well as a string consisting of the Clojure function to run.

[source,java]
----
include::example$test/xtdb/docs/examples/transactions/TransactionsTest.java[tags=fn-put,indent=0]
----
--

Clojure::
+
--
The document should use the `:xt/fn` key (note, not `::xt/fn`).

[source,clojure]
----
include::example$test/xtdb/docs/examples/transactions/transactions_test.clj[tags=fn-put,indent=0]
----
<1> Note that the function itself is quoted
--
====

==== Usage

When invoking a transaction function, you specify its ID and (optionally) other arguments

[tabs]
====
Java::
+
--
[source,java]
----
include::example$test/xtdb/docs/examples/transactions/TransactionsTest.java[tags=fn-use,indent=0]
----
--

Clojure::
+
--
Note that the transaction function operation `::xt/fn` is Clojure shorthand for `:xtdb.api/fn` (assuming the `xt` require alias is used) - be careful not to confuse this keyword with the `:xt/fn` keyword used inside the transaction function document.

[source,clojure]
----
include::example$test/xtdb/docs/examples/transactions/transactions_test.clj[tags=fn-use,indent=0]
----
<1> Function ID
<2> Parameter(s)
--
====

Transaction functions may return further transaction function invocation operations, which will in turn expand recursively until there are only primitive transaction operations remaining for the given transaction.

[#document]
== Documents

[tabs]
====
Java::
+
--
A `XtdbDocument` is created with an ID that must be of a <<#valid-ids,valid type>>.

The instance itself is immutable and plusing/minusing data yields a new instance of `XtdbDocument`.

Similarly to Transactions, you can use `XtdbDocument.Builder` directly or use the `Consumer` approach.
[source,java]
----
include::example$test/xtdb/docs/examples/transactions/TransactionsTest.java[tags=doc-builder,indent=0]

include::example$test/xtdb/docs/examples/transactions/TransactionsTest.java[tags=doc-consumer,indent=0]

// You can also chain creating new instances of the document,
// but this will be slow for larger documents.
include::example$test/xtdb/docs/examples/transactions/TransactionsTest.java[tags=doc-direct,indent=0]
----
--

Clojure::
+
--
A document is a map from keywords to values.

[source,clj]
----
{:xt/id :dbpedia.resource/Pablo-Picasso
 :name "Pablo"
 :last-name "Picasso"}
----

All documents must contain the `:xt/id` key.

Persistence of Clojure metadata is not supported (although is not currently rejected either) - we strongly recommended that all metadata should be removed from each document prior to submission to XTDB, to avoid potential equality checking issues (see https://github.com/xtdb/xtdb/issues/1510[here] for more details).
--
====

For operations containing documents, the id and the document are
hashed, and the operation and hash is submitted to the `tx-topic` in
the event log. The document itself is submitted to the `doc-topic`,
using its content hash as key. In Kafka, the `doc-topic` is compacted,
which enables later eviction of documents.

[#valid-ids]
=== Valid IDs

[tabs]
====
Java::
+
--
The following types of document IDs are allowed:

.Valid ID types (Java)
[cols="d,d"]
|===
|Type|Example

|Keyword|`Keyword.intern("my-id")`
|String|`"my-id"`
|Long|`42L`
|UUID|`UUID.randomUUID()`
|URI|`URI.create("mailto:hello@xtdb.com")`
|URL|`new URL("https://github.com/xtdb/xtdb")`
|IPersistentMap|`PersistentArrayMap.EMPTY.assoc("foo", "bar")`
|===
--

Clojure::
+
--
The following types of `:xt/id` are allowed:

.Valid ID types (Clojure)
[cols="d,d"]
|===
|Type|Example

|Keyword|`:my-id` or `:dbpedia.resource/Pablo-Picasso`
|String|`"my-id"`
|Integers/Longs|`42`
|UUID|`#uuid "6f0232d0-f3f9-4020-a75f-17b067f41203"`
|URI|`#xtdb/id "mailto:hello@xtdb.com"`
|URL|`#xtdb/id "https://github.com/xtdb/xtdb"`
|Maps|`{:this :id-field}`
|===

The `#xtdb/id` reader literal will take URI/URL strings and attempt to coerce them into valid IDs.

URIs and URLs are interpreted using Java classes (java.net.URI and java.net.URL respectively) and therefore you can also use these directly.
--
====

[#transaction-time]
== Transaction Time

When you submit a transaction, the current time will be the Transaction Time.

[#valid-times]
== Valid Times

When an optional `valid time` is omitted from a transaction operation, the Transaction Time will be used as `valid time`.

[#valid-time]
=== Only Valid Time Provided

When `valid time` is used as a parameter for Put or Delete, it specifies the time from which the change is valid.

If there is a document, `A`, already present at the given `valid time`, the operation's effect is valid from `valid time` to the end of the current validity of `A`.

[#end-valid-time]
=== End Valid Time

When both `valid time` and `end valid time` are provided for Put or Delete, the operation's effect is valid from `valid time` (inclusive) to `end valid time` (exclusive).

[#await]
== Awaiting Transactions

After a transaction is submitted, it needs to be indexed before it is visible in XTDB DB snapshots.

The return value from submitting the transaction can be used to wait for the transaction to be indexed.

This return value holds both the ID of the transaction, and the Transaction Time

[tabs]
====
Java::
+
--
In Java, you receive a `TransactionInstant` from the `submitTx` call.

[source,java]
----
include::example$test/xtdb/docs/examples/transactions/TransactionsTest.java[tags=ti,indent=0]
----
--

Clojure::
+
--
In Clojure, you receive a map from `submit-tx` containing `::xt/tx-id` and `::xt/tx-time`

[source,clojure]
----
include::example$test/xtdb/docs/examples/transactions/transactions_test.clj[tags=ti,indent=0]
----
--
====

[#speculative-transactions]
== Speculative transactions

You can submit speculative transactions to XTDB, to see what the results of your queries would be if a new transaction were to be applied.
This is particularly useful for forecasting/projections or further integrity checks, without persisting the changes or affecting other users of the database.

You'll receive a new database value, against which you can make queries and entity requests as you would any normal database value.
Only you will see the effect of these transactions - they're not submitted to the cluster, and they're not visible to any other database value in your application.

[tabs]
====
Java::
+
--
You submit these transactions to an instance of IXtdbDatasource using `withTx`:

[source,java]
----
include::example$test/xtdb/docs/examples/transactions/TransactionsTest.java[tags=with-tx,indent=0]
----
--

Clojure::
+
--
You submit these transactions to a database value using `with-tx`:

[source,clojure]
----
include::example$test/xtdb/docs/examples/transactions/transactions_test.clj[tags=speculative-0,indent=0]
include::example$test/xtdb/docs/examples/transactions/transactions_test.clj[tags=speculative-1,indent=2]
include::example$test/xtdb/docs/examples/transactions/transactions_test.clj[tags=speculative-2,indent=2]
include::example$test/xtdb/docs/examples/transactions/transactions_test.clj[tags=speculative-3,indent=2]
----
--
====

The entities submitted by the speculative Put take their valid time (if not explicitly specified) from the valid time of the `db` from which they were forked.

[#dropping-the-database]
== Dropping the database

XTDB does not currently provide any API to perform a "drop" operation (physical deletion) of the entire database. To drop the database, you must first manually `.stop` the node(s), then delete the underlying index-store directory, and then delete the relevant data (or directories) for the backend modules used for the transaction log and document store components.

For testing purposes you can use `Files/createTempDirectory` or equivalent.

== Queries

[#intro]
== Introduction

XTDB is a schemaless document database that provides you with a comprehensive means of traversing and querying across all of your documents.
XTDB automatically indexes the top-level fields in all documents, supporting efficient ad-hoc joins and retrievals.
XTDB is both _immutable_ and _bitemporal_, which are both required characteristics for a safe schemaless database.

XTDB is also a graph database.
The central characteristic of a graph database is that it can support arbitrary-depth graph queries (recursive traversals) very efficiently by default, without any need for schema-level optimisations.
Graph queries are possible through the XTDB dialect of the Datalog query language.

=== SQL

XTDB 1.x supports both Datalog and SQL, but SQL support is provided through a module.
To query XTDB using SQL, read the xref:reference::sql.adoc[SQL module documentation].

=== Datalog

Extensible Data Notation (edn) is a simple data format that is used to describe XTDB Datalog queries.
To understand how edn works, read the brief description at http://edn-format.org/[http://edn-format.org].

To understand how Datalog works, read the _Learn XTDB Datalog Today_ tutorial from the https://www.xtdb.com/tutorials/[Tutorials page].

////
Can we remove these 3 paragraphs? -sd

A Datalog query consists of a set of variables and a set of clauses.
The result of running a query is a result set of the possible combinations of values that
satisfy all of the clauses at the same time.
These combinations of values are referred to as "tuples".

The possible values within the result tuples are derived from your database of
documents. The documents themselves are represented in the database indexes as
"entity–attribute–value" (EAV) facts. For example, a single document
`{:xt/id :myid :color "blue" :age 12}` is transformed into two facts
`[[:myid :color "blue"][:myid :age 12]]`.

In the most basic case, a Datalog query works by searching for "subgraphs" in
the database that match the pattern defined by the clauses. The values within
these subgraphs are then returned according to the list of return variables
requested in the `:find` vector within the query.
////

[#structure]
=== Basic Structure

A query in XTDB is performed by calling `xt/q` on an XTDB database snapshot with a quoted map and, optionally, additional arguments.

[source,clojure]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=anatomy,indent=0]
----
<1> Database value. Usually the snapshot view comes from calling `xt/db` on an XTDB node
<2> Query map or vector (ex. `[:find ...etc... ]`, as found in other Datalog databases)
<3> Argument(s) supplied to the `:in` relations

The query map accepts the following Keywords

.Query Keys
[cols="3,3,8"]
|===
|Key|Type|Purpose

|<<#find,`:find`>>|Vector|Specify values to be returned
|<<#where,`:where`>>|Vector|Restrict the results of the query
|<<#in,`:in`>>|Vector|Specify external arguments
|<<#ordering-and-pagination,`:order-by`>>|Vector|Control the result order
|<<#ordering-and-pagination,`:limit`>>|Int|Specify how many results to return
|<<#ordering-and-pagination,`:offset`>>|Int|Specify how many results to discard
|<<#rules,`:rules`>>|Vector|Define powerful statements for use in `:where` clauses
|<<#timeout,`:timeout`>>|Int|Specify maximum query run time in ms
|===

[#find]
== Find

The find clause of a query specifies what values to be returned. These will be returned as a list.

[#find-logic-variable]
=== Logic Variable

You can directly specify a logic variable from your query.
The following will return all last names bound to the logic variable `n`.

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=triple,indent=0]
----

[#find-aggregate]
=== Aggregates

You can specify an aggregate function to apply to at most one logic variable.

.Built-in Aggregate Functions
[cols="3,.^8"]
|===
|Usage|Description
|`(sum ?lvar)`| Accumulates as a single value via the Clojure https://clojuredocs.org/clojure.core/+[`&#43;`] function
|`(min ?lvar)` .2+| Return a single value via the Clojure https://clojuredocs.org/clojure.core/compare[`compare`] function which may operate on many types (integers, strings, collections etc.)
|`(max ?lvar)`
|`(count ?lvar)`| Return a single count of all values including any duplicates
|`(avg ?lvar)`| Return a single value equivalent to `sum / count`
|`(median ?lvar)` .3+| Return a single value corresponding to the statistical definition
|`(variance ?lvar)`
|`(stddev ?lvar)`
|`(rand N ?lvar)`| Return a vector of exactly N values, where some values may be duplicates if N is larger than the range
|`(sample N ?lvar)`| Return a vector of at-most N distinct values
|`(distinct ?lvar)`| Return a set of distinct values
|===

==== Example:

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=query-aggregates,indent=0]

include::example$test/xtdb/docs/examples/query_test.clj[tags=query-aggregates-r,indent=0]
----

Note there is always implicit grouping across aggregates due to how XTDB performs the aggregation lazily _before_ turning the result tuples into a set.

=== Custom Aggregates

Custom (user-defined) aggregates are supported by adding a new method (via Clojure `defmethod`) for `xtdb.query/aggregate`.
This method takes a single (ignored) parameter and returns a multi-arity function which accepts zero parameters, an accumulator, or an accumulator and a single entity.
For example:

[source,clojure]
----
(defmethod xtdb.query/aggregate 'sort-reverse [_]
  (fn
    ([] [])
    ([acc] (vec (reverse (sort acc))))
    ([acc x] (conj acc x))))
----

[#pull]
=== Pull

XTDB queries support a `pull` syntax, allowing you to decouple specifying which entities you want from what data you'd like about those entities in your queries.
XTDB's support is based on the excellent https://edn-query-language.org/eql/1.0.0/what-is-eql.html[EDN Query Language (EQL)^] library.

To specify what data you'd like about each entity, include a `(pull ?logic-var projection-spec)` entry in the `:find` clause of your query:

[source,clojure]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=pull-query-1,indent=0]
include::example$test/xtdb/docs/examples/query_test.clj[tags=pull-query-1-r,indent=0]

include::example$test/xtdb/docs/examples/query_test.clj[tags=pull-query-2,indent=0]
include::example$test/xtdb/docs/examples/query_test.clj[tags=pull-query-2-r,indent=0]
----

You can quickly grab the whole document by specifying `*` in the projection spec:

[source,clojure]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=pull-query-6,indent=0]
include::example$test/xtdb/docs/examples/query_test.clj[tags=pull-query-6-r,indent=0]
----

If you have the entity id(s) in hand, you can call `pull` or `pull-many` directly:

[source,clojure]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=pull-many-query-1]
include::example$test/xtdb/docs/examples/query_test.clj[tags=pull-many-query-1-r]
include::example$test/xtdb/docs/examples/query_test.clj[tags=pull-many-query-2]
include::example$test/xtdb/docs/examples/query_test.clj[tags=pull-many-query-2-r]
----

We can navigate to other entities (and hence build up nested results) using joins.
Joins are specified in `{}` braces in the projection-spec - each one maps one join key to its nested spec:

[source,clojure]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=pull-query-3,indent=0]
include::example$test/xtdb/docs/examples/query_test.clj[tags=pull-query-3-r,indent=0]

include::example$test/xtdb/docs/examples/query_test.clj[tags=pull-query-4,indent=0]
include::example$test/xtdb/docs/examples/query_test.clj[tags=pull-query-4-r,indent=0]
----

We can also navigate in the reverse direction, looking for entities that refer to this one, by prepending `_` to the attribute name:

[source,clojure]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=pull-query-5,indent=0]
include::example$test/xtdb/docs/examples/query_test.clj[tags=pull-query-5-r,indent=0]
----

==== Attribute parameters

XTDB `pull` syntax supports a handful of custom https://edn-query-language.org/eql/1.0.0/specification.html#_parameters[EQL parameters], specified by wrapping the `:attribute` key in a pair: `(:attribute {:param :value, ...})`.

* `:as` - to rename attributes in the result, wrap the attribute in `(:source-attribute {:as :output-name})`:
+
[source,clojure]
----
{:find [(pull ?profession [:profession/name
                           {(:user/_profession {:as :users}) [:user/id :user/name]}])]
 :where [[?profession :profession/name]]}

;; => [{:profession/name "Doctor",
;;      :users [{:user/id 1, :user/name "Ivan"},
;;              {:user/id 3, :user/name "Petr"}]},
;;     {:profession/name "Lawyer",
;;      :users [{:user/id 2, :user/name "Sergei"}]}]
----
* `:limit` - limit the amount of values returned under the given property/join: `(:attribute {:limit 5})`
* `:default` - specify a default value if the matched document doesn't contain the given attribute: `(:attribute {:default "default"})`
* `:into` - specify the collection to pour the results into: `(:attribute {:into #{}})`
+
[source,clojure]
----
{:find [(pull ?profession [:profession/name
                           {(:user/_profession {:as :users, :into #{}})
                           [:user/id :user/name]}])]
 :where [[?profession :profession/name]]}

;; => [{:profession/name "Doctor",
;;      :users #{{:user/id 1, :user/name "Ivan"},
;;               {:user/id 3, :user/name "Petr"}}},
;;     {:profession/name "Lawyer",
;;      :users #{{:user/id 2, :user/name "Sergei"}}}]
----
* `:cardinality` (reverse joins) - by default, reverse joins put their values in a collection - for many-to-one/one-to-one reverse joins, specify `{:cardinality :one}` to return a single value.

For full details on what's supported in the projection-spec, see the https://edn-query-language.org/eql/1.0.0/specification.html[EQL specification^]

[#return-maps]
=== Returning maps
To return maps rather than tuples, supply the map keys under `:keys` for keywords, `:syms` for symbols, or `:strs` for strings:

[source,clojure]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=return-maps,indent=0]
include::example$test/xtdb/docs/examples/query_test.clj[tags=return-maps-r,indent=0]
----

[#where]
== Where

The `:where` section of a query limits the combinations of possible results by satisfying all clauses and rules in the supplied vector against the database (and any `:in` relations).

.Valid Clauses
[cols="1,4"]
|===
|Name|Description
|<<#clause-triple, triple clause>>| Restrict using EAV indexes
|<<#clause-pred, predicate>>| Restrict with any predicate
|<<#clause-range, range predicate>>| Restrict with any of `<` `+<=+` `>=` `>` `=`
|<<#clause-unification, unification predicate>>| Unify two distinct logic variables with `!=` or `==`
|<<#clause-not, not rule>>| Negate a list of clauses
|<<#clause-not-join, not-join rule>>| Not rule with its own scope
|<<#clause-or, or rule>>| Restrict on at least one matching clause
|<<#clause-or-join, or-join rule>>| Or with its own scope
|<<#clause-rule, defined rule>>| Restrict with a user-defined rule
|===

// TODO
// get-attr ?

[#clause-inputs]
=== Clause Inputs

Clauses may refer to combinations of literal values and logic variables as inputs.
Identical logic variables used across multiple clauses unify automatically (with the exception of `or-join` or `not-join` scoping).

A literal set containing literal values (e.g. `#{"val-1" "val-2"}`) will be interpreted as an input relation of distinct values, and can be used in place of any literal input (e.g. a set of entity IDs in the first position of a triple clause).

[#clause-triple]
=== Triple

A triple clause is a vector of (1) a literal entity ID or a logic variable, (2) a hard-coded attribute keyword (top-level key in a document), and (3) optionally, a value which can be a literal or a logic variable.

It restricts results by matching EAV facts

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=double,indent=0]

include::example$test/xtdb/docs/examples/query_test.clj[tags=triple-2,indent=0]

include::example$test/xtdb/docs/examples/query_test.clj[tags=triple-3,indent=0]
----
<1> This matches all entities, `p`, which have a `:name` field.
<2> This matches all entities, `p`, which have a `:name` of `"Ivan"`.
<3> This matches all entities, `p`, which have a `:name` which match the `:last-name` of `q`.

Note that the keyword attribute must always be specified and therefore you cannot use a logic variable in the attribute position.
You can however enumerate combinations of known attributes using rules, or execute independent queries efficiently using `openDB` (`open-db`).
A list of all known attributes is available via the `attributeStats` (`attribute-stats`) API.

[#clause-pred]
=== Predicates

Any fully qualified Clojure function that returns a boolean can be used as a "filter" predicate clause.

Predicate clauses must be placed in a clause, i.e. with a surrounding vector.

[source,clojure]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=query-with-pred-1,indent=0]
----

This matches all entities, `p` which have an odd `:age`.

[#where-subqueries]
=== Subqueries

You can nest a subquery with a `:where` clause to bind the result for further use in the query.

==== Binding results as a scalar

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=sub-query-example-1,indent=0]
----

In the above query, we perform a subquery doing some arithmetic operations and returning the result - and bind the resulting relation as a scalar.

Result set:

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=sub-query-example-1-r,indent=0]
----

==== Binding results as a tuple

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=sub-query-example-2,indent=0]
----

Similar to the previous query, except we bind the resulting relation as a tuple.

Result set:

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=sub-query-example-2-r,indent=0]
----

In this example, we bind the results of a subquery and use them to return another result.

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=sub-query-example-3,indent=0]
----

Result set:

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=sub-query-example-3-r,indent=0]
----

Any fully qualified Clojure function can also be used to return relation bindings in this way, by returning a list, set or vector.

[#clause-range]
=== Range Predicate

A `range predicate` is a vector containing a list of a range operator and then two logic variables or literals.

Allowed range operators are `<`, `+<=+`, `>=`, `>`, and `=`.

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=range-1,indent=0]

include::example$test/xtdb/docs/examples/query_test.clj[tags=range-2,indent=0]

include::example$test/xtdb/docs/examples/query_test.clj[tags=range-3,indent=0]
----
<1> Finds any entity, `p`, with an `:age` which is greater than 18
<2> Finds any entity, `p`, with an `:age` which is greater than the `:age` of any entity
<3> Finds any entity, `p`, for which 18 is greater than `:age` of `p`

[#clause-unification]
=== Unification Predicate

Use a unification predicate, either `==` or `!=`, to constrain two independent logic variables. Literals (and sets of literals) can also be used in place of one of the logic variables.

[source,clj]
----
;; Find all pairs of people with the same age:

[[p :age a]
 [p2 :age a2]
 [(== a a2)]]

;; ...is approximately equivalent to...

[[p :age a]
 [p2 :age a]]

;; Find all pairs of people with different ages:

[[p :age a]
 [p2 :age a2]
 [(!= a a2)]]

;; ...is approximately equivalent to...

[[p :age a]
 [p2 :age a2]
 (not [(= a a2]])]
----

[#clause-not]
=== Not

The `not` clause rejects a graph if all the clauses within it are true.

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=not-data,indent=0]

include::example$test/xtdb/docs/examples/query_test.clj[tags=not-2,indent=0]

include::example$test/xtdb/docs/examples/query_test.clj[tags=not-2-r,indent=0]
----
<1> Data
<2> Query
<3> Result

This will match any document which does not have a `:name` of "Ivan" _and_ a `:last-name` of "Ivanov".

[#clause-not-join]
=== Not Join

The `not-join` rule allows you to restrict the possibilities for logic variables by asserting that there does not exist a match for a given sequence of clauses.

You declare which logic variables from outside the `not-join` scope are to be used in the join.

Any other logic variables within the not-join are scoped only for the join.

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=not-join-data,indent=0]

include::example$test/xtdb/docs/examples/query_test.clj[tags=not-join,indent=0]

include::example$test/xtdb/docs/examples/query_test.clj[tags=not-join-r,indent=0]
----
<1> Data
<2> Declaration of which logic variables need to unify with the rest of the query
<3> Clauses
<4> Result

This will match any entity, `p`, which has different values for the `:name` and `:last-name` field.

Importantly, the logic variable `n` is unbound outside the `not-join` clause.

[#clause-or]
=== Or

An `or` clause is satisfied if any of its legs are satisfied.

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=or-data,indent=0]

include::example$test/xtdb/docs/examples/query_test.clj[tags=or-1,indent=0]

include::example$test/xtdb/docs/examples/query_test.clj[tags=or-1-r,indent=0]
----
<1> Data
<2> Query
<3> Result

This will match any document, `p`, which has a `:last-name` of "Ivanov" or "Ivannotov".

When within an `or` rule, you can use `and` to group clauses into a single leg (which must all be true).

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=or-2,indent=0]
----

Whenever the query engine complains that each leg in the `or` or `or-join` clause requires the "same logic variables", you can add a no-op predicate clause like `[(any? e)]` within `and` clauses for each of the missing variables in the various legs.
You need to add such no-op predicates until each leg contains the same set of variables.

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=or-3,indent=0]
----

Hypothetically, XTDB could automatically detect these cases and insert no-op predicates on the user's behalf, but that would be a deviation from the essential semantics of Datalog.
Note that `clojure.core/any?` is a function that always returns `true`.

[#clause-or-join]
=== Or Join

The `or-join` clause is satisfied if any of its legs are satisfied.

You declare which logic variables from outside the `or-join` scope are to be used in the join.

Any other logic variables within the `or-join` are scoped only for the join.

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=or-join-data,indent=0]

include::example$test/xtdb/docs/examples/query_test.clj[tags=or-join,indent=0]

include::example$test/xtdb/docs/examples/query_test.clj[tags=or-join-r,indent=0]
----
<1> Data
<2> Declaration of which logic variables need to unify with the rest of the query
<3> Clauses
<4> Result

This will match any document, `p` which has an `:age` greater than or equal to 18 _or_ has a `:name` of "Ivan".

Importantly, the logic variable `a` is unbound outside the `or-join` clauses.

[#clause-rule]
=== Rules

<<#rules, See Rules>>

[#in]
== In

XTDB queries can take a set of additional arguments, binding them to variables under the `:in` key within the query.

`:in` supports various kinds of binding.

=== Scalar binding

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=query-with-arguments1,indent=0]
----

In the above query, we parameterize the `first-name` symbol, and pass in "Ivan" as our input, binding "Ivan" to `first-name` in the query.

Result Set:
[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=query-with-arguments1-r,indent=0]
----

=== Collection binding

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=query-with-arguments2,indent=0]
----

This query shows binding to a collection of inputs - in this case, binding `first-name` to all of the different values in a collection of first-names.

Result Set:
[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=query-with-arguments2-r,indent=0]
----

=== Tuple binding

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=query-with-arguments3,indent=0]
----

In this query we are binding a set of variables to a single value each, passing in a collection as our input. In this case, we are passing a collection with a `first-name` followed by a `last-name`.

Result Set:
[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=query-with-arguments3-r,indent=0]
----

=== Relation binding

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=query-with-arguments4,indent=0]
----

Here we see how we can extend the parameterisation to match using multiple fields at once by passing and destructuring a relation containing multiple tuples.

Result Set:
[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=query-with-arguments4-r,indent=0]
----

[#ordering-and-pagination]
== Ordering and Pagination

A Datalog query naturally returns a result set of tuples, however, the tuples
can also be consumed as a sequence and therefore you will always have an
implicit order available. Ordinarily this implicit order is undefined (i.e. not
meaningful), because the join order and result order are unlikely to correlate.

The `:order-by` option is available for use in the query map to explicitly
control the result order.

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=order-and-pagination-1,indent=0]
----

Use of `:order-by` will require that results are fully-realised by the query
engine, however this happens transparently and it will automatically spill to
disk when sorting large numbers of results.

Basic `:offset` and `:limit` options are supported however typical pagination
use-cases will need a more comprehensive approach because `:offset` will
naively scroll through the initial result set each time.

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=order-and-pagination-2,indent=0]
----

Ordered results are returned as bags, not sets, so you may want to deduplicate
consecutive identical result tuples (e.g. using `clojure.core/dedupe` or
similar).

`:limit` may be used in isolation, without `:order-by`, and will also return a
bag of results that can contain duplicates.

To use `:order-by` with an aggregate, simply restate the aggregate element exactly as it is written in your `:find` vector.

More powerful ordering and pagination features may be provided in the future.
Feel free to open an issue or get in touch to discuss your ordering
requirements, e.g. see https://github.com/xtdb/xtdb/discussions/1514[#1514]

[#rules]
== Rules
Rules are defined by a rule head and then clauses as you would find in a `:where` statement.

They can be used as a shorthand for when you would otherwise be repeating the same restrictions in your `:where` statement.

[source,clojure]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=rules-1,indent=0]
----
<1> Rule usage clause (i.e. invocation)
<2> Rule head (i.e. signature)
<3> Rule body containing one or more clauses

The above defines the rule named `adult?` which checks that the supplied entity has an `:age` which is `>=` 18

Multiple rule bodies may be defined for a single rule name (i.e. using matching rule heads) which works in a similar fashion to an `or-join`.

The clauses within Rules can also be further Rule invocation clauses. This allows for the recursive traversal of entities and more.

[source,clojure]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=rules-2,indent=0]
----

This example finds all entities that the entity with `:name` "Smith" is connected to via `:follow`, even if the connection is via intermediaries.

=== Bound arguments

To improve the performance of a rule you can specify that certain arguments in the rule head must be "bound" logic variables (i.e. there must be known values for each argument at the point of evaluation) by enclosing them in a vector in the first argument position. Any remaining arguments will be treated as regular "free" logic variables.

As an analogy, bound variables are input arguments to a function, and free variables are the destructured return values from that function.

Changes are only necessary in the rule head(s) - no changes are required in the body or the usage clauses. Rule heads must always match.

For example, the following query and rule set will work and return the correct results.

[source,clojure]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=rules-3,indent=0]
----

However, specifying that the `p` variable should be bound before the rule can be evaluated will improve the evalution time by many orders-of-magnitude for large data sets.

[source,clojure]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=rules-4,indent=0]
----

[#timeout]
== Timeout

`:timeout` sets the maximum run time of the query (in milliseconds).

If the query has not completed by this time, a `java.util.concurrent.TimeoutException` is thrown.

[#valid-time-travel]
== Valid Time travel

When performing a query, `xt/q` is called on a database snapshot.

To query based on a different Valid Time, create this snapshot by specifying the desired Valid Time when we call `db` on the node.

[source,clojure]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=query-at-t-d1,indent=0]

include::example$test/xtdb/docs/examples/query_test.clj[tags=query-at-t-d2,indent=0]
----

Here, we have `put` different documents in XTDB with different Valid Times.

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=query-at-t-q1,indent=0]
----

Here, we have defined a query, `q` to find all entities with a `:name` of "Malcolma" and `:last-name` of "Sparks"

We can run the query at different Valid Times as follows

[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=query-at-t-q1-q,indent=0]

include::example$test/xtdb/docs/examples/query_test.clj[tags=query-at-t-q2-q,indent=0]
----

The first query will return an empty result set (`#{}`) because there isn't a document with the `:name` "Malcolma" valid at `#inst "1986-10-23"`

The second query will return `#{[:malcolm]}` because the document with `:name` "Malcolma" _is_ valid at the current time.
This will be the case so long as there are no newer versions (in the valid time axis) of the document that affect the current valid time version.

[#joins]
== Joins

=== Query: "Join across entities on a single attribute"

Given the following documents in the database
[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=join-d,indent=0]
----

We can run a query to return a set of tuples that satisfy the join on the attribute `:name`
[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=join-q,indent=0]
----

Result Set:
[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=join-r,indent=0]
----

Note that every person joins once, plus 2 more matches.

=== Query: "Join with two attributes, including a multi-valued attribute"

Given the following documents in the database
[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=join2-d,indent=0]
----

We can run a query to return a set of entities that `:follows` the set of entities with the `:name` value of `"Ivan"`
[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=join2-q,indent=0]
----

Result Set:
[source,clj]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=join2-r,indent=0]
----

Note that because XTDB is schemaless there is no need to have elsewhere declared that the `:follows` attribute may take a value of edn type `set`.

[#streaming-queries]
== Streaming Queries

Query results can also be streamed, particularly for queries whose results may
not fit into memory. For these, we use `xtdb.api/open-q`, which returns a
`Closeable` sequence. Note that results are returned as bags, not sets, so you
may wish to deduplicate consecutive identical result tuples (e.g. using
`clojure.core/dedupe` or similar).

We'd recommend using `with-open` to ensure that the sequence is closed properly.
Additionally, ensure that the sequence (as much of it as you need) is eagerly
consumed within the `with-open` block - attempting to use it outside (either
explicitly, or by accidentally returning a lazy sequence from the `with-open`
block) will result in undefined behaviour.

[source,clj,indent=0]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=streaming-query,indent=0]
----

[#history-api]
== History API

[#history-full-document-history]
=== Full Entity History
XTDB allows you to retrieve all versions of a given entity:
[source,clj]
----
include::example$test/xtdb/docs/examples_test.clj[tags=history-full,indent=0]
----

=== Retrieving previous documents
When retrieving the previous versions of an entity, you have the option to additionally return the documents associated with those versions (by using `:with-docs?` in the additional options map)
[source,clj]
----
include::example$test/xtdb/docs/examples_test.clj[tags=history-with-docs,indent=0]
----

[#history-document-history-range]
=== Document History Range
Retrievable entity versions can be bounded by four time coordinates:

* valid-time-start
* tx-time-start
* valid-time-end
* tx-time-end

All coordinates are inclusive. All coordinates can be null.
[source,clj]
----
include::example$test/xtdb/docs/examples_test.clj[tags=history-range,indent=0]
----

=== Lazy Iteration
See the `open-entity-history` (Clojure) and `openEntityHistory` (Java) APIs.

[#clojure-tips]
== Clojure Tips

=== Quoting

Logic variables used in queries must always be quoted in the `:find` and
`:where` clauses, which in the most minimal case could look like the following:

[source,clj]
----
(xt/q db
  {:find ['?e]
   :where [['?e :event/employee-code '?code]]}))
----

However it is often convenient to quote entire clauses or even the entire query
map rather than each individual use of every logic variable, for instance:

[source,clj]
----
(xt/q db
  '{:find [?e]
    :where [[?e :event/employee-code ?code]]}))
----

Note that use of Clojure's syntax quoting may cause confusion and is therefore not recommended. This is because Datalog built-ins like range predicates, unification predicates and rules (`or`, `not` etc.) will be mistakenly coerced into corresponding Clojure core functions (`clojure.core/or`, `clojure.core/==` etc.) and produce invalid queries.

=== Maps and Vectors in data

Say you have a document like so and you want to add it to an XTDB db:
[source,clj]
----
{:xt/id :me
 :list ["carrots" "peas" "shampoo"]
 :pockets {:left ["lint" "change"]
           :right ["phone"]}}
----

XTDB breaks down vectors into individual components so the query engine is able
see all elements on the base level. As a result of this the query engine is not
required to traverse any structures or any other types of search algorithm
which would slow the query down. The same thing should apply for maps so
instead of doing `:pocket {:left thing :right thing}` you should put them under
a namespace, instead structuring the data as `:pocket/left thing :pocket/right
thing` to put the data all on the base level. Like so:

[source,clj]
----
(xt/submit-tx
  node
  [[::xt/put
    {:xt/id :me
     :list ["carrots" "peas" "shampoo"]
     :pockets/left ["lint" "change"]
     :pockets/right ["phone"]}]
   [::xt/put
    {:xt/id :you
     :list ["carrots" "tomatoes" "wig"]
     :pockets/left ["wallet" "watch"]
     :pockets/right ["spectacles"]}]])
----

To query inside these vectors the code would be:

[source,clj]
----
(xt/q (xt/db node) '{:find [e l]
                     :where [[e :list l]]
                     :in [l]}
                   "carrots")
;; => #{[:you "carrots"] [:me "carrots"]}

(xt/q (xt/db node) '{:find [e p]
                     :where [[e :pockets/left p]]
                     :in [p]}
                   "watch")
;; => #{[:you "watch"]}
----

Note that `l` and `p` is returned as a single element as XTDB decomposes the
vector

[#datascript-differences]
== DataScript Differences

This list is not necessarily exhaustive and is based on the partial re-usage of
DataScript's query test suite within XTDB's query tests.

XTDB does not support:

- vars in the attribute position, such as `[e ?a "Ivan"]` or `[e _ "Ivan"]`

XTDB does _not yet_ support:

- `ground` (you can use alternatively use `identity`)
- `get-else` (see https://github.com/xtdb/xtdb/blob/e2f51ed99fc2716faa8ad254c0b18166c937b134/test/test/xtdb/query_test.clj#L1054[`get-attr`] which returns a relation instead)
- `get-some`
- `missing?` (however, instead of `[(missing? $ ?e :height)]` you can use `(not-join [?e] [?e :height])`)
- reverse attribute syntax in triple clauses (i.e. `[?child :example/_child ?parent]`), however reverse attribute joins (like `:example/_child`) are supported in `pull`

[#custom-functions]
== Custom Functions and Advanced Examples

Many advanced query requirements can be addressed using custom predicate function calls since you can reference any function that is loaded (and available on the classpath) by using its fully qualified name in a Datalog clause, e.g. `[(clojure.core/+ x y) z)]`.
These custom functions can be passed the `db` query context using the `$` argument convention for sophisticated nesting of queries and other lookups. Destructuring the results of a function as a relation is also supported, similarly to `:in` bindings.
The suite of functions in the `clojure.core` namespace may be referred to without the fully qualified prefix, including `clojure.core/eval`, however an xref:reference::query-configuration.adoc#fn-allowlist[allowlist feature] is available to help maintain security (particularly relevant when the HTTP server is being used).

These functions can be used, for example, to access data that is deeply nested with a given top-level value.

[source,clojure]
----
include::example$test/xtdb/docs/examples/query_test.clj[tags=get-in-data,indent=0]

include::example$test/xtdb/docs/examples/query_test.clj[tags=get-in,indent=0]

include::example$test/xtdb/docs/examples/query_test.clj[tags=get-in-2,indent=0]

include::example$test/xtdb/docs/examples/query_test.clj[tags=get-in-r,indent=0]
----
<1> Data
<3> Usage of `clojure.core/get-in` function with literal vector of keys
<3> Usage of `clojure.core/vector` function to construct intermediate vector value
<4> Result

Be aware during development that query compilation internalizes function definitions and this means that subsequent re-definitions of your custom functions may not be reflected until the query is modified and therefore re-compiled. During development, you can introduce a dummy predicate clause like `[(any? 1)]` (which always evaluates to `true` and has no effect on the query) and increment the integer when needed to bypass the effects of query caching.

Many examples of advanced queries are showcased across the https://github.com/xtdb/xtdb/blob/main/test/test/xtdb/query_test.clj[query tests] and the suite of benchmarks maintained in the `bench` sub-project.
