= Crux-in-a-Box (on RocksDB)
:page-subtitle: The simplest possible Crux setup
:page-author: Steven Deobald
:page-header: aurora-1197753_1920.jpg
:page-published: 2021-03-10T22:55Z
:thumbnail: crux-in-a-box

== Introduction

This guide will show you how to set up Crux with the following properties:

. Disk: Records persist to disk
. One node: Only one Crux node is configured
. Storage: RocksDB is used for all 3 stores (tx-log, doc-store, and index-store)

This guide will not discuss high-availability, failover/clustering/replication, or backups. You can use this simple RocksDB configuration in production and back it up as you would any other volume. If you want more advanced features, however, you should consider the xref:reference::kafka.adoc[Kafka] and/or xref:reference::jdbc.adoc[JDBC] modules.

All the code from this guide is compiled into minimal (working) project examples for Clojure and Java you can see in the https://github.com/deobald/crux-in-a-box[crux-in-a-box] GitHub repo.

== Steps

=== 1. Install Dependencies

Ensure you are using Java 8 or higher:

[source,shell]
----
java -version
----

Add Crux to your Clojure or Java project:

[tabs]
====
deps.edn::
+
[source,clojure,subs=attributes+]
----
com.xtdb/xtdb-core {:mvn/version "{crux_version}"}
com.xtdb/xtdb-rocksdb {:mvn/version "{crux_version}"}
----
project.clj::
+
[source,clojure,subs=attributes+]
----
[com.xtdb/xtdb-core "{crux_version}"]
[com.xtdb/xtdb-rocksdb "{crux_version}"]
----
pom.xml::
+
[source,xml,subs=attributes+]
----
<dependency>
    <groupId>com.xtdb</groupId>
    <artifactId>xtdb-core</artifactId>
    <version>{crux_version}</version>
</dependency>
<dependency>
    <groupId>com.xtdb</groupId>
    <artifactId>xtdb-rocksdb</artifactId>
    <version>{crux_version}</version>
</dependency>
----
====

[NOTE]
====

**A Note on Logging**

Ignore this note if you just want to get up and running quickly. It's completely optional, but nice to have.

Without setting up logging, you will see a `SLF4J: Defaulting to no-operation (NOP) logger implementation` message on STDOUT from Crux. This is harmless, but in a real application you will want to configure `Logback` with the http://www.slf4j.org[SLF4J] API to see INFO messages from Crux.

To do this in Clojure:

. https://github.com/deobald/crux-in-a-box/blob/4998db33d866a695c7d10049eb28fdada88a46fd/clj/project.clj#L10[Add Logback, SLF4J, and `tools.logging` as dependencies]
. Set the https://github.com/deobald/crux-in-a-box/blob/4998db33d866a695c7d10049eb28fdada88a46fd/clj/project.clj#L20[`clojure.tools.logging.factory`] JVM option
. Create a https://github.com/deobald/crux-in-a-box/blob/4998db33d866a695c7d10049eb28fdada88a46fd/clj/resources/logback.xml[`crux-in-a-box/resources/logback.xml`] file

To do this in Java:

. https://github.com/deobald/crux-in-a-box/blob/1ba9ed4d85bd15e90adec46b19523b262f8480ae/java/pom.xml#L25[Add Logback, SLF4J, and `tools.logging` as dependencies]
. Set the https://github.com/deobald/crux-in-a-box/blob/1ba9ed4d85bd15e90adec46b19523b262f8480ae/java/Makefile#L8[`clojure.tools.logging.factory` JVM option]
. Create a https://github.com/deobald/crux-in-a-box/blob/1ba9ed4d85bd15e90adec46b19523b262f8480ae/java/src/main/resources/logback.xml[`crux-in-a-box/src/main/resources/logback.xml`] file
====

=== 2. Configure Crux

This guide gets you up and running quickly by hard-coding configuration values. Store these configuration values with your favourite configuration library. In Clojure, you might use  https://github.com/juxt/aero[Aero].

This guide also does not make any assumptions about how you manage stateful services. Crux is a stateful service, however, and you should store the Crux node in your favourite state management library. In Clojure, you might use https://github.com/tolitius/mount[Mount].

[tabs]
====
Clojure::
+
[source,clojure,subs=attributes+]
----
(ns crux-in-a-box.db
  (:require [clojure.java.io :as io]
            [xtdb.api :as xt]))

(defn start-crux! []
  (letfn [(kv-store [dir]
            {:kv-store {:xt/module 'xtdb.rocksdb/->kv-store
                        :db-dir (io/file dir)
                        :sync? true}})]
    (xt/start-node
     {:xt/tx-log (kv-store "data/dev/tx-log")
      :xt/document-store (kv-store "data/dev/doc-store")
      :xt/index-store (kv-store "data/dev/index-store")})))

(def crux-node (start-crux!))

(defn stop-crux! []
  (.close crux-node))

----
Java::
+
[source,java,subs=attributes+]
----
package cruxinabox;

import java.io.File;
import java.io.IOException;
import xtdb.api.Crux;
import xtdb.api.IXtdb;

class Box {
    public static void main(String[] args) {
        try(IXtdb xtdbNode = IXtdb.startNode(new File("config.json"))) {
            System.out.println("Crux Started.");
        }
        catch (IOException e) {
            // ...
        }
    }
}

----
config.json::
+
[source,json,subs=attributes+]
----
{
  "xt/index-store": {
    "kv-store": {
      "xt/module": "xtdb.rocksdb/->kv-store",
      "db-dir": "data/index-store"
    }
  },
  "xt/document-store": {
    "kv-store": {
      "xt/module": "xtdb.rocksdb/->kv-store",
      "db-dir": "data/doc-store"
    }
  },
  "xt/tx-log": {
    "kv-store": {
      "xt/module": "xtdb.rocksdb/->kv-store",
      "db-dir": "data/tx-log"
    }
  },
  "xtdb.lucene/lucene-store": {
    "db-dir": "data/dev/lucene-dir"
  },
  "xtdb.http-server/server": {
    "port": 9999
  }
}

----
====

=== 3. Take it for a test drive

Time to play with your new Crux node. Try inserting some data, query it back out, and then shut down your node. This guide is not meant to teach you Datalog, the Crux API, or Crux query semantics -- you can look through the Tutorial and Reference Docs to dig deeper. But you should note that Crux is _asynchronous by default_. That means `submit-tx` returns immediately, even if your document hasn't been indexed yet. It's unlikely your query will come back empty, but don't be shocked if it does. Just try it again.

[tabs]
====
Clojure REPL::
+
[source,clojure,subs=attributes+]
----
crux-in-a-box.db> (xt/submit-tx crux-node [[:xt/put
                                              {:xt/id "hi2u"
                                               :user/name "zig"}]])
;; => #:xt{:tx-id 0, :tx-time #inst "2021-03-11T02:27:09.176-00:00"}
crux-in-a-box.db> (xt/q (xt/db crux-node) '{:find [e]
                                                :where [[e :user/name "zig"]]} )
;; => #{["hi2u"]}
crux-in-a-box.db> (stop-crux!)
;; => nil
----
Java::
+
[source,java,subs=attributes+]
----
/* include these imports in addition to those you used to configure crux: */
import java.util.HashMap;
import java.util.List;

import xtdb.api.IXtdbDatasource;
import xtdb.api.ICursor;
import xtdb.api.XtdbDocument;
import xtdb.api.TransactionInstant;
import xtdb.api.tx.Transaction;

/* submitTx example: */
HashMap<String, Object> data = new HashMap<>();
data.put("user/name", "zig");
XtdbDocument document = XtdbDocument.create("hi2u", data);
TransactionInstant transaction = node.submitTx(Transaction.buildTx(tx -> {
    tx.put(document);
}));
System.out.println(data.toString());

/* query example: */
node.awaitTx(transaction, null);
String query = "{:find [e] :where [[e :user/name \"zig\"]]}";
IXtdbDatasource db = node.db();
ICursor<List<?>> results = db.openQuery(query);
if (results.hasNext()) {
    List<?> result = results.next();
    System.out.println(result.toString());
}
db.close();
node.close();
----
====

== Considerations

This is a simple Crux setup with a small footprint. You could use this setup to build a small greenfield project or replace an existing Postgres, MySQL, or MongoDB installation which currently supports CRUD or reference data. With Crux, that database can grow with you. When it eventually requires streaming, replication, or high availability, you can migrate from RocksDB to Kafka or JDBC. But you don't need to involve those modules up-front unless you're sure you need them.
