= crux-blobs

This Crux module allows you to use Azure Blob Storage Service (blobs) as Crux's 'document store'.

== Getting started

First, include `[juxt/crux-blobs "RELEASE"]` in your project.clj, or `{juxt/crux-blobs {:mvn/version "RELEASE"}}` in your deps.edn.

Then, include `'crux.blobs/blobs-doc-store` in your topology - for example:

[source,clojure]
----
{:crux.node/topology '[crux.kafka/topology
                       crux.blobs/blobs-doc-store]
 :crux.blobs/storage-account "your-storage-account"
 :crux.blobs/container "your-container"}
----

== Configuration

In addition to the above configuration, you need to create a SAS token for the Blob container you're using. You create this using the Azure portal [TODO: More info/screenshots etc.].

You simply add the SAS token to your environment, using the following environment variable:
`CRUX_BLOBS_SAS_TOKEN`.

Currently documents are stored as EDN. TODO: Use nippy https://github.com/ptaoussanis/nippy[Nippy].

== Bugs/PRs

Please submit these through Github in the usual way - thanks!

Help is available through our usual channels - https://juxt-oss.zulipchat.com/#narrow/stream/194466-crux[Zulip] and http://clojurians.net/[#crux on Clojurians Slack].
