---
title: Introducing XTQL
---

:test: ../src/test/clojure/xtdb/docs/xtql_walkthrough_test.clj
:example: ../src/test/resources/docs/xtql_tutorial_examples.yaml

In Clojure, XTDB is queryable using two query languages: **SQL** and **XTQL**.

XTQL is our new, data-oriented, composable query language, inspired by the strong theoretical bases of both **Datalog** and **relational algebra**.
These two combine to create a joyful, productive, interactive development experience, with the ability to build queries iteratively, testing and debugging smaller parts in isolation.

* It is designed to be highly amenable to dynamic query generation - we believe that our industry has spent more than enough time trying to generate SQL strings (not to mention the concomitant https://owasp.org/www-community/attacks/SQL_Injection[security vulnerabilities^]).
* It can be used for both link:#operators_and_relations[queries] and link:#dml[transactions].

Let's start with XTQL queries:

[#operators_and_relations]
== 'Operators' and 'relations'

XTQL is built up of small, composable 'operators', which combine together using 'pipelines' into larger queries.

* 'Source' operators (e.g. 'read from a table') each yield a 'relation' - an unordered bag of rowsfootnote:[rows ... which themselves are otherwise known as 'maps', 'structs', 'records' or 'dictionaries' depending on your persuasion 😄].
* 'Tail' operators (e.g. 'filter a relation', 'calculate extra fields') transform a relation into another relation.

From these simple operators, we can build arbitrarily complex queries.

Our first operator is `from`:

=== `from`

The `from` operator allows us to read from an XTDB table.
In this first example, we're reading the first-name and last-name fields from the `users` table - i.e. `SELECT first_name, last_name FROM users`:

[source,clojure]
----
(from :users [first-name last-name])
----

It's in the `from` operator that we specify the temporal filter for the table.
By default, this shows the table at the current time, but it can be overridden:

* to view the table at another point in time
* to view the changes to the table within a given range
* to view the entire history of the table

[source,clojure]
----
(from :users {:bind [first-name last-name]

              ;; at another point in time
              :for-valid-time (at #inst "2023-01-01")

              ;; within a given range
              :for-valid-time (in #inst "2023-01-01", #inst "2024-01-01")
              :for-valid-time (from #inst "2023-01-01")
              :for-valid-time (to #inst "2024-01-01")

              ;; for all time
              :for-valid-time :all-time

              ;; and all of the above :for-system-time too.
              })
----

In the `from` operator, we can also rename columns, and filter rows based on field values:

* We rename a column using a binding map:
+
[source,clojure]
----
include::{test}[tags=bo-xtql-1,indent=0]
----
+
[source,sql]
----
include::{example}[tags=bo-sql-1,indent=0]
----
+
* We can look up a single user-id by specifying a literal in the binding map:
+
[source,clojure]
----
include::{test}[tags=bo-xtql-2,indent=0]
----
+
[source,sql]
----
include::{example}[tags=bo-sql-2,indent=0]
----

Another source operator is `rel`, which allows you to specify an inline relation.

You can check out the link:/reference/main/xtql/queries.html#_source_operators[source operators reference] for more details.

=== Pipelines

We can then transform the rows in a table using tail operators, which we pass in an operator 'pipeline'.
Pipelines consist of a single source operator, and then arbitrarily many tail operators.

Here, we demonstrate `SELECT first_name, last_name FROM users ORDER BY last_name, first_name LIMIT 10`, introducing the 'order by' and 'limit' operators:

In Clojure, we use `+->+` to denote a pipeline - in a similar vein to the threading macro in Clojure 'core' footnote:[although XTQL's `+->+` isn't technically macro-expanded - it's just data.], we take one source operator and then pass it through a series of transformations.

[source,clojure]
----
(-> (from :users [first-name last-name])
    (order-by last-name first-name)
    (limit 10))
----

By building queries using pipelines, we are now free to build these up incrementally, trivially re-use parts of pipelines in different queries, or temporarily disable some operators to test parts of the pipeline in isolation.

Other tail operators include `where` (to filter rows), `return` (to specify the columns to output), `with` (to add additional columns based on the existing ones), and `aggregate` (grouping rows - counts, sums, etc).
For a full list, see the link:/reference/main/xtql/queries.html#_tail_operators[tail operators reference].

[#unify]
=== Multiple tables - introducing `unify`

Joining multiple tables in XTQL is achieved using Datalog-based 'unification'.

We introduce the `unify` source operator, which takes an unordered bag of input relations and joins them together using 'unification constraints' (similar to join conditions).

Each input relation (e.g. `from`) defines a set of 'logic variables' in its bindings.
If a logic variable appears more than once within a single unify clause, the results are constrained such that the logic variable has the same value everywhere it’s used.
This has the effect of imposing 'join conditions' over the inputs.

* In this case, we re-use the `user-id` logic variable to indicate that the `:xt/id` from the `:users` table should be matched with the `:author-id` of the `:articles` table.
+
[source,clojure]
----
include::{test}[tags=joins-xtql-1,indent=0]
----
+
[source,sql]
----
include::{example}[tags=joins-sql-1,indent=0]
----

+
* For non-equality cases, we can use a link:../reference/main/xtql/queries.html#_where[`where`] clause (where we have a full SQL-inspired expression standard library at our disposal)
+
[source,clojure]
----
;; 'find me all the users who are the same age'
include::{test}[tags=joins-xtql-2,indent=0]
----
+
[source,sql]
----
include::{example}[tags=joins-sql-2,indent=0]
----
+
* We can specify that a certain match is optional using link:../reference/main/xtql/queries.html#_joins[`left-join`]:
+
[source,clojure]
----
include::{test}[tags=joins-xtql-3,indent=0]
----
+
[source,sql]
----
include::{example}[tags=joins-sql-3,indent=0]
----
+
Here, we're asking to additionally return customers who haven't yet any orders (for which the order-table columns will be absent in the results).
* Or, we can specify that we only want to return customers who _don't_ have any orders, using link:../reference/main/stdlib/predicates.html#_boolean_functions[`not`] link:../reference/main/xtql/queries.html#_subqueries[`exists?`]:
+
[source,clojure]
----
include::{test}[tags=joins-xtql-4,indent=0]
----
+
[source,sql]
----
include::{example}[tags=joins-sql-4,indent=0]
----

The `unify` operator accepts 'unify clauses' - e.g. `from`, `where`, `with`, `join`, `left-join` - a full list of which can be found in the link:/reference/main/xtql/queries.html#_unify_clauses[unify clause reference guide].

=== Projections

* We can create new columns from old ones using link:../reference/main/xtql/queries.html#_with[`with`]:
+
[source,clojure]
----
include::{test}[tags=proj-xtql-1,indent=0]
----
+
[source,sql]
----
include::{example}[tags=proj-sql-1,indent=0]
----
+
We can also use link:../reference/main/xtql/queries.html#_with[`with`] within link:../reference/main/xtql/queries.html#_unify[`unify`] - this creates new logic variables which we can then unify in the same way.
+
* Where link:../reference/main/xtql/queries.html#_with[`with`] adds to the available columns, link:../reference/main/xtql/queries.html#_return[`return`] only yields the specified columns to the next operation:
+
[source,clojure]
----
include::{test}[tags=proj-xtql-2,indent=0]
----
+
[source,sql]
----
include::{example}[tags=proj-sql-2,indent=0]
----
* Where we don't need any additional projections, we can use link:../reference/main/xtql/queries.html#_without[`without`]:
+
[source,clojure]
----
include::{test}[tags=proj-xtql-3,indent=0]
----
+
[source,sql]
----
include::{example}[tags=proj-sql-3,indent=0]
----

=== Aggregations

To count/sum/average values, we use link:../reference/main/xtql/queries.html#_aggregate[`aggregate`]:

[source,clojure]
----
include::{test}[tags=aggr-xtql-1,indent=0]
----

[source,sql]
----
include::{example}[tags=aggr-sql-1,indent=0]
----

=== 'Pull'

When we've found the documents we're interested in, it's common to then want a tree of related information.
For example, if a user is reading an article, we might also want to show them details about the author as well as any comments.

(Users of existing EDN Datalog databases may already be familiar with link:../reference/main/xtql/queries.html#_subqueries['pull'] - in XTQL, because subqueries are a first-class concept, we rely on extensively on these to express a more powerful/composable behaviour.)

[source,clojure]
----
include::{test}[tags=pull-xtql-1,indent=0]

;; => [{:title "...", :content "...",
;;      :author {:first-name "...", :last-name "..."}
;;      :comments [{:comment "...", :name "..."}, ...]}]

----

[source,sql]
----
-- using XTDB's 'NEST_ONE'/'NEST_MANY'

include::{example}[tags=pull-sql-1,indent=0]
----

In this example, we use link:../reference/main/xtql/queries.html#_subqueries[`pull`] to pull back a single map - we know that there's only one author per article (in our system).
When it's a one-to-many relationship, we use link:../reference/main/xtql/queries.html#_subqueries[`pull*`] - this returns any matches in a vector.

Also note that, because we have the full power of subqueries, we can express requirements like 'only get me the most recent 10 comments' using ordinary query operations, without any support within link:../reference/main/xtql/queries.html#_subqueries[`pull`] itself.

== Bitemporality

It wouldn't be XTDB without bitemporality, of course - indeed, some may be wondering how I've gotten this far without mentioning it!

(I'll assume you're roughly familiar with bitemporality for this section.
 If not, forgive me - we'll follow this up with more XTDB 2.x bitemporality content soon!)

* In XTDB 1.x, queries had to be 'point-in-time' - you had to pick a single valid/transaction time for the whole query.
+
In XTQL, while there are sensible defaults set for the whole query, you can override this on a per-link:../reference/main/xtql/queries.html#_from[`from`] basis by wrapping the table name in a vector and providing temporal parameters:
+
[source,clojure]
----
include::{test}[tags=bitemp-xtql-1,indent=0]

include::{test}[tags=bitemp-xtql-2,indent=0]
----
+
[source,sql]
----
include::{example}[tags=bitemp-sql-1,indent=0]

include::{example}[tags=bitemp-sql-2,indent=0]
----
+
** You can also specify `(from <time>)`, `(to <time>)` or `(in <from-time> <to-time>)`, to give fine-grained, in-query control over the history returned for the given rows.
** System time (formerly 'transaction time', renamed for consistency with SQL:2011) is filtered in the same map with `:for-system-time`.
* This means that you can (for example) query the same table at two points-in-time in the same query - 'who worked here in both 2018 and 2023':
+
[source,clojure]
----
include::{test}[tags=bitemp-xtql-3,indent=0]
----

[#dml]
== DML

XTQL can also be used to write to XTDB using XTQL DML.

It uses the same query language as above, with a small wrapper for each of the operations.
We're hoping that a reasonable proportion of use-cases that previously required transaction functions to be installed and invoked can now submit DML operations instead.

=== Insert

We submit link:../reference/main/xtql/txs.html#_insert_into[`insert-into`] operations to link:../reference/main/xtql/txs.html[`xt/submit-tx`].
link:../reference/main/xtql/txs.html#_insert_into[`insert-into`] accepts a query that inserts every result into the given table:


[source,clojure]
----
include::{test}[tags=DML-Insert-xtql,indent=0]
----

[source,sql]
----
-- we omit the submission boilerplate in the SQL equivalents

include::{example}[tags=DML-Insert-sql,indent=0]
----

Here we're preserving the valid-from and valid-to of the rows we're copying, but we could just as easily specify/calculate a different value.
Naturally, substitute your query of choice from above for the link:../reference/main/xtql/queries.html#_from[`from`] (link:../reference/main/xtql/queries.html#_unify[`unify`], for example) for an arbitrarily powerful XTQL command.

(As in XT2 SQL, XTQL link:../reference/main/xtql/txs.html#_insert_into[`insert-into`] behaves more like an upsert - if a document with that `xt/id` already exists, it will be overwritten for the specified period of valid-time.)

=== Delete

We can delete documents using queries as well.

* For example, to delete all of the comments on a given post, we can submit the following XTQL:
+
[source,clojure]
----
include::{test}[tags=DML-Delete-xtql,indent=0]
----
+
[source,sql]
----
include::{example}[tags=DML-Delete-sql,indent=0]
----
+
Here, we're passing a dynamic parameter to specify the post to delete.
+
* link:../reference/main/xtql/txs.html#[`delete`] can also take a collection of extra link:../reference/main/xtql/queries.html#_unify[`unify`] clauses.
Let's say instead we wanted to delete all comments on posts by a certain author - we can do that as follows:
+
[source,clojure]
----
include::{test}[tags=DML-Delete-additional-unify-clauses-xtql,indent=0]
----
+
[source,sql]
----
include::{example}[tags=DML-Delete-additional-unify-clauses-sql,indent=0]
----
+
Additional clauses passed to link:../reference/main/xtql/txs.html#[`delete`] in this way are unified, in the same way variables within a link:../reference/main/xtql/queries.html#_unify[`unify`] are.
In this case, because we've re-used the `pid` logic variable, XT implicitly joins the two values - the `post-id` from the `comments` table with the `xt/id` on the `posts` table.
* We can specify a valid-time range to delete using `for-valid-time`, in a similar manner to the link:../reference/main/xtql/queries.html#_from[`from`] clause.
+
For example, if we want to take down all Christmas promotions on the 26th December (but we don't want to be in the office to actually delete them), we could run the following:
+
[source,clojure]
----
include::{test}[tags=DML-Delete-bitemporal-xtql,indent=0]
----
+
[source,sql]
----
include::{example}[tags=DML-Delete-bitemporal-sql,indent=0]
----
+
* Finally, we can delete every entry in a table by omitting any `:bind` predicates:
+
[source,clojure]
----
include::{test}[tags=DML-Delete-everything-xtql,indent=0]
----
+
[source,sql]
----
include::{example}[tags=DML-Delete-everything-sql,indent=0]
----

=== Update


* Update operations are almost exactly the same as deletes, except - well, they update the document rather than deleting it, obviously - but they additionally take a `set` clause.
+
[source,clojure]
----
include::{test}[tags=DML-Update-xtql,indent=0]
----
+
[source,sql]
----
include::{example}[tags=DML-Update-sql,indent=0]
----
+
* Like deletes, updates also accept `:for-valid-time` and extra sub-queries to join from.
You can, for example, copy a value from another related table, or even update a denormalised value:
+
[source,clojure]
----
include::{test}[tags=DML-Update-bitemporal-xtql,indent=0]
----
+
[source,sql]
----
include::{example}[tags=DML-Update-bitemporal-sql-1,indent=0]

include::{example}[tags=DML-Update-bitemporal-sql-2,indent=0]
----

This is the operation that we envisage replacing a lot of XT1 transaction functions - it makes it trivial to patch a single value within a document, for example.

=== Erase

We can irretrievably erase a document using an link:../reference/main/xtql/txs.html#_erase_from[`erase`] query.

* Erases also look the same as deletes, but these don't support `:for-valid-time`:
+
[source,clojure]
----
include::{test}[tags=DML-Erase-xtql,indent=0]
----
+
[source,sql]
----
include::{example}[tags=DML-Erase-sql,indent=0]
----

=== Assert

link:../reference/main/xtql/txs.html#asserts[`assert-exists`] and link:../reference/main/xtql/txs.html#asserts[`assert-not-exists`] can be used to assert the state of the database during a transaction.
If an assertion fails, the whole transaction rolls back.
This can be used to check pre-conditions, for example.

This query asserts that no user has the email `james@example.com` before inserting a user that does:

[source,clojure]
----
include::{test}[tags=DML-Assert-xtql,indent=0]
----

[source,sql]
----
-- not implemented yet
include::{example}[tags=DML-Assert-sql,indent=0]
----

You can check the `xt/txs` table to see whether and why a transaction failed:

[source,clojure]
----
include::{test}[tags=DML-Assert-query,indent=0]

;; =>

include::{test}[tags=DML-Assert-query-result,indent=0]
----

Those familiar with XT1 might recognise this as `::xt/match` - albeit more powerful because you have the full query language available rather than just matching a whole document.

== For more information

Congratulations - this is the majority of the theory behind XTQL!
You now understand the fundamentals behind how to construct XTQL queries from its simple building blocks - from here, it's much more about incrementally learning what each individual operator does, and what it looks like in your client language.

You can:

* check out the reference guides for XTQL link:/reference/main/xtql/queries[queries] and link:/reference/main/xtql/txs[transactions].

We're very much in **listening mode** right now - as a keen early adopter, we'd love to hear your first impressions, thoughts and opinions on where we're headed with XTQL.
Please do get in touch via the link:/intro/community.html#oss-community[usual channels]!
