---
title: SQL over HTTP
---

Assuming you have successfully started an XTDB server, this tutorial walks through basic HTTP API usage and showcases a few of the novel features of XTDB. The examples should be easily translatable to any language (or you could use one of the many supported link:/drivers[client drivers]), and cURL commands are also provided for convenience.

== Status

To confirm XTDB is running:

`GET` to `localhost:3000/status`

If that returns, everything should be up and running.

== Transact

To run your first transaction, send the following:

`POST` to `localhost:3000/tx`

[source,json]
----
{
  "txOps": [{"sql": "INSERT INTO people (xt$id, name) VALUES (6, 'fred')"}]
}
----

Note that the `people` doesn't have to be defined beforehand - the table is created dynamically during the INSERT along with any supplied columns and types.

(TODO cURL tabs)

Transactions are durable and processed asynchronously. If you wait a few milliseconds for the processing to finish, you can query then that data.

== Query

`POST` to `localhost:3000/query`

[source,json]
----
{
  "query": {"sql": "SELECT * FROM people"}}
}
----

You can also ensure that the query reflects our transaction (after it has been either committed or aborted) by supplying the 'basis' map returned from our transations to the `queryOpts`:

`POST` to `localhost:3000/query`

[source,json]
----
{
  "query": {"sql": "SELECT * FROM people"},
  "queryOpts": {"basis": {"txId": 7806,
                          "systemTime":"2024-03-04T14:31:03.728415Z"}}
}
----

== Working with documents

XTDB is designed to work with JSON-like nested data as a first-class concept. Which means you can send the following transaction:

`POST` to `localhost:3000/tx`

[source,json]
----
{
  "txOps": [{"sql": "INSERT INTO people (xt$id, name, info)
                     VALUES (6, 'fred', {'height': 172,
                                         'age': 29,
                                         'likes': ['apples'])"}]
}
----

== Basis allows you to re-run queries

Re-run the previous query with the basis map supplied and see that the results are the same:

`POST` to `localhost:3000/query`

[source,json]
----
{
  "query": {"sql": "SELECT * FROM people"},
  "queryOpts": {"basis": {"txId": 7806,
                          "systemTime":"2024-03-04T14:31:03.728415Z"}}
}
----

A basis map is like a pointer to a snapshot of a previous version of the entire database state, except unlike snapshots in other systems there is no copying or explicit snapshot creation required.

If you re-run the previous query with the previous basis (returned by the first transaction), you _won't_ see the new version of Fred's record.

A basis is stable and allows you to re-run unmodified queries indefinitely. This is useful for debugging, auditing, and exposing application data for processing in downstream systems (generating reports, analytics etc.)


== System-Time Columns

...