= Crux Corda

A https://opencrux.com[Crux] library that allows you to pipe verified https://www.corda.net/[Corda] transactions into a Crux node, to then query using Crux's bitemporal Datalog query engine.

.build.gradle.kts
[source,kotlin]
----
// Main library
implementation("pro.juxt.crux-labs", "crux-corda", "NOT RELEASED YET")

// Library for inclusion in contract JARs
implementation("pro.juxt.crux-labs", "crux-corda-state", "NOT RELEASED YET")
----

.pom.xml
[source,xml]
----
<dependency>
    <groupId>pro.juxt.crux-labs</groupId>
    <artifactId>crux-corda</artifactId>
    <version><!-- NOT RELEASED YET --></version>
</dependency>

<!-- Library for inclusion in contract JARs -->
<dependency>
    <groupId>pro.juxt.crux-labs</groupId>
    <artifactId>crux-corda-state</artifactId>
    <version><!-- NOT RELEASED YET --></version>
</dependency>
----

// TODO
User documentation will live on the https://opencrux.com/reference[Crux documentation site].

== Developing `crux-corda`


* Testing: `./gradlew test`
* REPL: `./gradlew clojureRepl`
* Entry points:
** `crux-corda/src/main/kotlin/crux/corda/CruxCorda.kt` - entry point for the Crux driver, adds extension functions to `AppServiceHub`
** `crux-corda/src/main/clojure/crux/corda.clj` - the implementation of the Crux driver
** `crux-corda-state/src/main/kotlin/crux/corda/state/CruxState.kt` - interface that Corda states should implement to be included in Crux
* Example user app:
** `examples/iou-contract/src/main/kotlin/com/example/contract/IOUState.kt` - example of a Corda state with a Crux mapping
** `examples/iou-workflow/src/main/kotlin/com/example/service/CruxService.kt` - example of a CordaService that starts a Crux node
** `examples/iou-workflow/src/test/kotlin/com/example/workflow/IOUFlowTests.kt` - E2E test for the IOU app
