---
title: Getting started
---

XTDB can run in-process (in a JVM), or through traditional client-server connections.

== Client/Server

You can start an XTDB server using the 'standalone' Docker image:

[source,shell]
----
docker pull ghcr.io/xtdb/xtdb-standalone-ea

docker run -tip 3000:3000 ghcr.io/xtdb/xtdb-standalone-ea
----

This starts a server on http://localhost:3000.
By default, your data will be saved in a local directory in the Docker image, but you can also attach a host volume in the usual Docker way, to preserve your data on your host machine:

[source,sh]
----
docker run \
  -tip 3000:3000 \
  -v /path/to/host/dir:/var/lib/xtdb \
  ghcr.io/xtdb/xtdb-standalone-ea
----

=== Connecting through HTTP

You can then connect to your XTDB server using cURL, or similar tools.
For example, to check its status:

[source,shell]
----
curl http://localhost:3000/status
----

NOTE: currently only link:https://github.com/cognitect/transit-format[transit] (via `Content-Type: application/transit+json`) is enabled for use, however a more universal JSON encoding is coming very soon!

From here, check out the link:/sdks/openapi/index.html[OpenAPI docs] to see what else is available.

=== Connecting from JVM languages

If you're running on the JVM, you can use the JVM client library to connect to this node.

First, add the thin client link:/reference/main/sdks#_maven_artifacts_jvm[Maven coordinates] to your dependency manager of choice.

You can then open up an XTDB client by running:

.Kotlin
[%collapsible%open]
====
[source,kotlin]
----
import java.net.URL
import xtdb.api.XtdbClient

XtdbClient.openClient(URL("http://localhost:3000"))
    .use { client ->
        // ...

    }
----

From here, check out the link:/sdks/kotlin/index.html[Kotlin API docs^] to submit data and run queries.
====

.Java
[%collapsible%open]
====
[source,java]
----
import java.net.URL;
import xtdb.api.XtdbClient;

try (var client = XtdbClient.openClient(new URL("http://localhost:3000"))) {

    // ...

}
----

// TODO this currently links to the Kotlin docs until we've sorted out Dokka Javadoc
From here, check out the link:/sdks/kotlin/index.html[Java API docs^] to submit data and run queries.
====

.Clojure
[%collapsible]
====
Once you have a REPL (e.g. by running `clj`), you can connect to the XTDB node with:

[source,clojure]
----
(require '[xtdb.client :as xtc]
         '[xtdb.api :as xt])

(with-open [node (xtc/start-client "http://localhost:3000")]
  (xt/status node)

  ;; ...
  )
----

From here, check out the link:/sdks/clojure/index.html[Clojure API docs^] to submit data and run queries.
====

== In process (JVM/Clojure)

If you're running a JVM, you can also use XTDB directly, in-process.
In-process XTDB is particularly useful for testing and interactive development - you can start an in-memory node quickly and with little hassle, which makes it a great tool for unit tests and REPL experimentation.

First, ensure you are running JDK 17+ and then add the xtdb-core link:/reference/main/sdks#_maven_artifacts_jvm[Maven coordinates] to your dependency manager.

You'll also need to add the following JVM arguments to run Apache Arrow:

* `--add-opens=java.base/java.nio=ALL-UNNAMED`
* `-Dio.netty.tryReflectionSetAccessible=true"]}}}`

.Kotlin
[%collapsible%open]
====
[source,kotlin]
----
import xtdb.api.Xtdb

Xtdb.openNode()
    .use { xtdb ->
        // ...

    }
----

This node uses exactly the same API as the thin client - so, again, from here, check out the link:/sdks/kotlin/index.html[Kotlin API docs] to submit data and run queries.
====

.Java
[%collapsible%open]
====
[source,java]
----
import xtdb.api.Xtdb;

try(var xtdb = Xtdb.openNode()) {
    // ...
}
----

// TODO this currently links to the Kotlin docs until we've sorted out Dokka Javadoc
This node uses exactly the same API as the thin client - so, again, from here, check out the link:/sdks/kotlin/index.html[Java API docs] to submit data and run queries.
====

.Clojure
[%collapsible]
====
Once you have a REPL (started with `clj -A:xtdb`), you can create an in-memory XTDB node with:

[source,clojure]
----
(require '[xtdb.node :as xtn]
         '[xtdb.api :as xt])

(with-open [node (xtn/start-node {})]
  (xt/status node)

  ;; ...
  )
----

This node uses exactly the same API as the thin client - so, again, from here, check out the link:/sdks/clojure/index.html[Clojure API docs] to submit data and run queries.
====
