---
title: Quickstart
---
:icon: /images/icons
:clojure: /drivers/clojure/getting-started.html
:java: /drivers/java/getting-started.html
:kotlin: /drivers/kotlin/getting-started.html

== Try Online

If you want to avoid running your own XTDB server locally, you can instantly play with inserting data and querying XTDB right now using the link:https://fiddle.xtdb.com/[XT fiddle] website.

== Docker Install

XTDB is built for traditional client-server interactions over HTTP. You can start an XTDB server using the following Docker image:

[source,bash]
----
docker run --pull=always -tip 6543:3000 ghcr.io/xtdb/xtdb-standalone-ea
----

This starts a server on http://localhost:6543.
By default your data will only be stored transiently using a local directory within the Docker image, but you can attach a host volume to preserve your data across container restarts, e.g. by adding `-v /tmp/xtdb-data-dir:/var/lib/xtdb`.

You can then connect to your XTDB server using cURL, or similar tools.
For example, to check the status of the server:

[source,bash]
----
curl http://localhost:6543/status
----

== Run the `xtsql` interactive console

To work with XTDB interactively right away, you can run raw SQL commands using the `xtsql.py` terminal console:

[source,bash]
----
# any recent version of Python should work, no Python knowledge required
curl -s https://docs.xtdb.com/xtsql.py -O && \
  python xtsql.py --url=http://localhost:6543
----

=== Confirm connectivity

In addition to running SQL statements, `xtsql` supports a number of built-in commands, e.g. type 'status' and hit Enter to confirm XTDB is running and that you are connected:

[source,text]
----
-> status

| latestCompletedTx | latestSubmittedTx |
|-------------------|-------------------|
| NULL              | NULL              |
----

If that returns a table like the above, then everything should be up and running.

Next up, you probably want to start by inserting data, running your first queries, and learning about XTDB's novel capabilities:

link:/quickstart/insert-and-query[Let's INSERT some data]!

Note that `xtsql` is just a lightweight wrapper around XTDB's link:/drivers/http/getting-started[HTTP + JSON] API, and that link:/drivers[client drivers] are also provided for a range of languages to make working with XTDB more ergonomic than working with HTTP directly.