---
title: Getting started
---
:icon: /images/icons
:clojure: /drivers/clojure/getting-started.html
:java: /drivers/java/getting-started.html
:kotlin: /drivers/kotlin/getting-started.html

XTDB is built for traditional client-server interactions over HTTP. You can start an XTDB server using the 'standalone' Docker image:

[source,shell]
----
docker pull ghcr.io/xtdb/xtdb-standalone-ea

docker run -tip 3000:3000 ghcr.io/xtdb/xtdb-standalone-ea
----

This starts a server on http://localhost:3000.
By default, your data will be saved in a local directory in the Docker image, but you can also attach a host volume in the usual Docker way, to preserve your data on your host machine:

[source,sh]
----
docker run \
  -tip 3000:3000 \
  -v /path/to/host/dir:/var/lib/xtdb \
  ghcr.io/xtdb/xtdb-standalone-ea
----

You can then connect to your XTDB server using cURL, or similar tools.
For example, to check its status:

[source,shell]
----
curl http://localhost:3000/status
----

To learn how to use the HTTP API and discover a few of XTDB's novel capabilities, follow the link:/tutorials/sql-over-http[introductory tutorial].

You can also check out the link:/drivers/http/openapi/index.html[HTTP OpenAPI docs] to see all the options available.

== Connecting via a client driver

Official client drivers are provived for a range of languages to make working with XTDB more ergonomic than working directly with HTTP and JSON.

[.lang-icons.right]
image:{icon}/clojure.svg[Clojure,link={clojure}#_connecting_through_http]
image:{icon}/java.svg[Clojure,link={java}#_connecting_through_http]
image:{icon}/kotlin.svg[Clojure,link={kotlin}#_connecting_through_http]

For more details, check out the relevant instructions for your language:

More client drivers are link:/intro/roadmap.html[coming soon]!