---
title: What is XTDB?
---

XTDB is a 'bitemporal' and 'dynamic' relational database for handling regulated data. XTDB is a transactional system designed for powering applications while also being amenable to analytic querying thanks to its internal columnar architecture built on link:https://arrow.apache.org/[Apache Arrow]. XTDB is open source and runs on the JVM.

== Bitemporal

XTDB tracks both the *system time* when data is inserted (or `UPDATE`-d) into the database, and also the *valid time* periods that define exactly when a given row/record/document is considered *valid*/*effective* in your application. This combination of *system* and *valid* time dimensions is called "bitemporality" and in XTDB all data is bitemporal without having to think about storing or updating additional columns. All data is time-versioned automatically.

This system-maintained time-versioning allows application queries to easily access the correct state of the entire application history "as-at" any given moment, _and_ to trivially audit all changes to the database. In other words, this unlocks the complete history of data for rich analysis and allows applications to cope with link:https://tidyfirst.substack.com/p/eventual-business-consistency[out of order] arrival of information, including *corrections* to past data while maintaining a general sense of *immutability*.

XTDB’s approach to temporality is inspired by link:https://en.wikipedia.org/wiki/SQL:2011[SQL:2011], but makes it ubiquitous, practical and transparent during day-to-day development. All tables include 4 temporal columns by default which are maintained automatically. However queries are assumed to query 'now' unless otherwise specified. Non-valid historical data is filtered out during low-level processing at the heart of the internal design.

== Transactional columnar architecture

Unlike most transactional database systems, XTDB implements a columnar data architecture that "separates storage and compute" - this modern, Big-Data-inspired architecture is built around link:https://arrow.apache.org/[Apache Arrow] and commodity object storage (e.g. S3). Most importantly, this design reduces operational costs when retaining large volumes of historical data.

Transaction processing is strictly serial and strongly consistent, based on deterministic ordering of non-interactive transactions. The design implies a hard upper limit on transaction throughput (since all processing must ultimately happen via a single thread) but key advantage of this design is the concrete link:https://www.youtube.com/watch?v=Cym4TZwTCNU[information guarantees] about _exactly when, how & why_ data across the database has changed.

== Dynamic relational engine

The columnar engine within XTDB amenable to handling "documents" as wide rows in sparse tables, where any given value in a column may contain arbitrarily nested data without any need for upfront schema design. This enables developers to use XTDB either as a store of loosely structured documents, or as more traditional normalized database, or both at the same time.

Unlike typical SQL tables with row-oriented storage, XTDB's columnar tables are always 'sparse' (storing NULLs is cheap) and 'wide' (storing lots of columns is efficient).

== Both SQL *and* 'XTQL'

XTDB offers two interoperable query languages - one for reach (SQL) and one for developer productivity (link:/intro/what-is-xtql[XTQL]). SQL in XTDB is a first-class citizen, built to reflect the link:https://en.wikipedia.org/wiki/SQL:2011[SQL:2011] standard (which first introduced bitemporal capabilities to the SQL standard) and conforms to a broad suite of link:https://www.sqlite.org/sqllogictest/doc/trunk/about.wiki[SQLite Logic Tests].

link:/intro/what-is-xtql[XTQL] is a novel relational database language that extends the power of SQL and its standard library to a more composable format that can be written or generated by client libraries using a JSON API.

The two languages are able to interoperate with 100% parity, meaning application developers can use the APIs as they see fit without sacrificing analytical requirements or compromising on functionality.

== Feature Highlights

* Supports the full spectrum between normalized relational modeling and dynamic document-like storage without compromising data type fidelity (i.e. unlike JSONB).

* A native SQL dialect combined with a Datalog query language offers a more productive application development experience alongside rich data analysis (without ETL to another system).

* Strong data consistency built around linearized, single-writer transaction processing.

* Accurate and immutable temporal record versioning to mitigate the complexities of application logic and handle out-of-order data ingestion.

* Apache Arrow unlocks data for external integration.

* Advanced temporal querying allows you to analyze the evolution of your data.

* Deploy across your choice of cloud database services or on-premise to meet reliability and redundancy requirements.

Through each of these interconnected principles and features XTDB solves the link:/intro/why-xtdb[motivating problems] in a single, coherent system.
