{
 "title": "Auctionmark",
 "time": { "from": "2024-02-12T15:53:28.693Z", "to": "2024-02-12T16:03:23.413Z" },
 "panels": [
  {
   "title": "Transaction Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 0 },
   "targets": [
    { "expr": "get_item_seconds_count", "legendFormat": "get_item" },
    { "expr": "new_user_seconds_count", "legendFormat": "new_user" },
    { "expr": "new_bid_seconds_count", "legendFormat": "new_bid" },
    { "expr": "new_item_seconds_count", "legendFormat": "new_item" }
   ]
  },
  {
   "title": "get-item percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 10 },
   "targets": [
    { "expr": "get_item_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "new_item percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 10 },
   "targets": [
    { "expr": "new_item_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "new_user percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 18 },
   "targets": [
    { "expr": "new_user_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "new_bid percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 18 },
   "targets": [
    { "expr": "new_bid_seconds", "legendFormat": "__auto" }
   ]
  }
 ]
}