{
 "title": "XTDB v2 node metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Transaction Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "tx_op_timer_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Query percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "query_timer_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
   "targets": [
    { "expr": "tx_op_timer_seconds_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Queries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
   "targets": [
    { "expr": "query_timer_seconds_count", "legendFormat": "__auto" }
   ]
  }
 ]
}