= An Interactive Tale Of Time

= An Interactive Tale Of Time

For those readers whose learning ability is better when affections
are in place we're offering a short story writing experience
through database transactions and queries.


=== Table of contents

* Prerequisite knowledge
  ** EDN
  ** basic datalog
  ** basic clojrue
  ** bitemp

* Letting data in
  ** Basic transactions
  ** References                                             // missing in intro 1

* Looking Around (Queries)
  // Explore the present state of a world.
  ** schema exploration
  ** simple where and fields selection
  ** entity pull
       to observe characters and their relations structure
  ** and / or / in (1 2 3)
  ** joins                                                 // missing in intro 1

  ** changing data
     - cas
     - delete
     - evict

  ** main Clojure core functions at work
     or (arbitrary user functions)
  ** having                                                // requires a decorator [why do we call them decorators btw]?

* Domain evolution
  // Imagine we acquired a new datasource telling us about the past. We feed it in.
  // Characters should get more complex motivations.
  ** Who was where at valid-time year 1
  ** Who was where at valid-time year 20


== Setup
Assuming you have some basic knowledge of Clojure and you own a REPL.
All you need for this tale is add Crux dep.

[source,clj]
----
include::./deps.edn[tags=CruxDep]
----


Charles is a shopkeeper who possesses a truly magical artefact:
A Rather Cozy Mug.
When Mary and her fellow pirates steal the mug, Charles recruits the
assistance of Joe, a rogue traveller, to help recover it.


Fire up a repl and create a namespace
[source,clj]
----
include::./a_tale.clj[tags=a-tale/create-ns]
----


== Define a system

[source,clj]
----
include::./a_tale.clj[tags=a-tale/def-system]
----


== Letting data in
The year is 1740. We want to transact in our first character.


[source,clj]
----
include::./a_tale.clj[tags=a-tale/def-character]
----

Load the remaining part of the set

[source,clj]
----
include::./a_tale.clj[tags=a-tale/rest-of-set]
----


== Looking Around : Basic Queries
Get a database _value_ and read from it consistently

[source,clj]
----
include::./a_tale.clj[tags=a-tale/simple-queries]
----


== Balancing the world (delete and evict)

Ok yes magic beans once _were_ in the realm, and we want to remember that,
but following advice from our publisher we've decided to remove them from
the story for now. Charles won't know that they ever existed!

[source,clj]
----
include::./a_tale.clj[tags=a-tale/delete-query]
----


Sometimes people enter data which just doesn't belong there or that they no
longer have a legal right to store (GDPR, I'm looking at you, dear).
Lets completely wipe all traces of that laptop from the timelines.

[source,clj]
----
include::./a_tale.clj[tags=a-tale/evict-query]
----


Let's see what we got now
[source,clj]
----
include::./a_tale.clj[tags=a-tale/eviction-result]
----

== Some character development (db references)

Let's see how Crux handles references. Give our characters some artefacts

[source,clj]
----
include::./a_tale.clj[tags=a-tale/write-references]
----

****
Note that transactions in Crux will rewrite the whole entity, there're no
partial updates and no intentions to put them in the core as of yet.
This is because the core of Crux is intentionally slim, and
features like partial updates shall be kept in the upcoming convenience projects!
****

=== Who has what : basic joins


[source,clj]
----
include::./a_tale.clj[tags=a-tale/basic-joins]
----


=== A few convenience functions

[source,clj]
----
include::./a_tale.clj[tags=a-tale/convenience-functions]
----

== What was supposed to be a final
Mary steals The Mug in June

[source,clj]
----
include::./a_tale.clj[tags=a-tale/plot-final-1]
----

So for now we think we're done with the story.
We have a picture and we're all perfectly ready to blame Mary for
stealing a person's beloved mug.
Suddenly a revelation occurs when an _upstream data source_ kicks in.
We uncover a previously unknown piece of history.
It turns out the mug was Mary's family heirloom all along!

=== Write new upstream data into the past
[source,clj]
----
include::./a_tale.clj[tags=a-tale/new-upstream-data]
----

Note that with this particular data model we should also rewrite
all the artefacts transactions since 1715. But since it matches
the tale we can omit the labour for this time.
And if acts of ownership were separate documents, the labour
wouldn't be needed at all.


=== Fin
[source,clj]
----
include::./a_tale.clj[tags=a-tale/final-picture]
----
