[#about]
= About Crux

[#about-background]
== Background

JUXT has been working on Crux since 2017, following a set of experiences where bitemporality proved challenging to implement at-scale using existing off-the-shelf technologies. Crux has been built by a very small core team who have, by necessity, had to keep the requirements and implemented scope to a minimum. Crux represents a strong foundation for further research and development efforts and provides a basis on which JUXT can release and support a broad variety of open source software products.

[#about-vision]
== Vision

Crux ultimately aims to make the use of bitemporal modelling intuitive and accessible to as wide an audience as possible. Whilst bitemporality is only considered _absolutely essential_ for a small number of use-cases, we believe that broad usage bitemporality could significantly reduce the hidden complexity in our global information systems.

[#about-team]
== Team

See: https://github.com/juxt/crux/graphs/contributors

[#about-support]
== Support

Please contact us if you would like to discuss your support requirements: crux@juxt.pro

[#about-hosting]
=== Managed Hosting

JUXT offers a Managed Hosting service for Crux to accelerate your
development and provide you with a secure and reliable service.

[#about-software]
=== Software

JUXT currently offers bespoke support packages for Crux with SLAs that can be customised to meet your requirements.

[#about-reseller]
=== Reseller

Are you looking to implement Crux as part of a solution for your client(s)? JUXT can provide Software Support and Managed Hosting on your behalf. Please consider joining our reseller program.

[#about-deployment]
=== Deployment

Engage JUXT for Deployment Services Support if you need help with the initial process of installing and configuring Crux in your environment.

[#about-contributing]
== Contributing

include::contributing.adoc[leveloffset=+1]

[#about-releases]
=== Releases

For technical changes, see:https://github.com/juxt/crux/blob/master/CHANGELOG.md
