= About Crux

== Background

JUXT has been working on Crux since 2017, following a set of experiences where bitemporality proved challenging to implement at-scale using existing off-the-shelf technologies. Crux has been built by a very small core team who have, by necessity, had to keep the requirements and implemented scope to a minimum. Crux represents a strong foundation for further research and development efforts and provides a basis on which JUXT can release and support a broad variety of open source software products. 

== Vision

Crux ultimately aims to make the use of bitemporal modelling intuitive and accessible to as wide an audience as possible. Whilst bitemporality is only considered _absolutely essential_ for a small number of use-cases, we believe that broad usage bitemporality could significantly reduce the hidden complexity in our global information systems.

== Team

See: https://juxt.pro/team.html

== Product Roadmap
  
=== Long-term Direction

The Crux roadmap is not opaque and JUXT is open to community involvement in defining our objectives. We currently use a private Clubhouse instance to evaluate priorities and track long-term objectives, but we hope to migrate this information into an open forum in the near future. We expect that the majority of technical changes for the rest of 2019 will be in the layers of features that sit above the Crux core.

=== Enterprise Edition and Cloud Offering

JUXT is working to develop enterprise-level capabilities for operating Crux clusters and managing data across clusters. Crux can already be deployed to Kubernetes and we are aiming to provide self-service cloud instances to support production customer usage. JUXT currently offers flexible Managed Hosting for Crux. Please feel free to contact us: crux@juxt.pro

=== Community Contribution

Crux is an open source product that JUXT will support throughout its evolution. As the community continutes to grow we will incorporate quality community-led contributions into the core. However, because of Crux's unbundled architecture, we expect that sustantial contributions can be made outside of the core. JUXT aims to promote and help all community-led activities around Crux.

<<contributing.adoc#,Read more about contributing.>>


== Releases

For technical changes, see:https://github.com/juxt/crux/blob/master/CHANGELOG.md

=== crux-19.04 alpha

19 April 2019

This inaugural public alpha release serves to validate the API and overall
design with a wide audience of users and possible contributors.

