== (ns crux.api)
:toc: macro

`crux.api` exposes a union of methods from `ICruxNode` and `ICruxDatasource`,
with few lifecycle members added.

toc::[]

[#clojure-api-icruxnode]
=== ICruxNode

==== db

[source,clj]
----
  (db
    [node]
    [node ^Date valid-time]
    [node ^Date valid-time ^Date transaction-time]
    "When a valid time is specified then returned db value contains only those
     documents whose valid time is before the specified time.

     When both valid and transaction time are specified returns a db value as of
     the valid time and the latest transaction time indexed at or before the
     specified transaction time.

     If the node hasn't yet indexed a transaction at or past the given
     transaction-time, this throws NodeOutOfSyncException")
----

==== open-db

[source,clj]
----
  (open-db
    [node]
    [node ^Date valid-time]
    [node ^Date valid-time ^Date transaction-time]
    "When a valid time is specified then returned db value contains only those
     documents whose valid time is before the specified time.

     When both valid and transaction time are specified returns a db value as of
     the valid time and the latest transaction time indexed at or before the
     specified transaction time.

     If the node hasn't yet indexed a transaction at or past the given
     transaction-time, this throws NodeOutOfSyncException

     This DB opens up shared resources to make multiple requests faster - it must
     be `.close`d when you've finished using it (for example, in a `with-open`
     block)")
----

==== document

[source,clj]
----
  (document [node content-hash]
    "Reads a document from the document store based on its
    content hash.")
----

==== history

[source,clj]
----
  (history [node eid]
    "Returns the transaction history of an entity, in reverse
    chronological order. Includes corrections, but does not include
    the actual documents.")
----

=== history-range

[source,clj]
----
  (history-range [node eid
                  ^Date valid-time-start
                  ^Date transaction-time-start
                  ^Date valid-time-end
                  ^Date transaction-time-end]
    "Returns the transaction history of an entity, ordered by valid
    time / transaction time in chronological order, earliest
    first. Includes corrections, but does not include the actual
    documents.

    Giving null as any of the date arguments makes the range open
    ended for that value.")
----

=== status

[source,clj]
----
  (status [node]
    "Returns the status of this node as a map.")
----

=== submit-tx

[source,clj]
----
  (submit-tx [node tx-ops]
    "Writes transactions to the log for processing
     tx-ops datalog style transactions.
     Returns a map with details about the submitted transaction,
     including tx-time and tx-id.")
----

=== tx-committed?

[source,clj]
----
  (tx-committed? [node submitted-tx]
    "Checks if a submitted tx was successfully committed.
     submitted-tx must be a map returned from `submit-tx`.
     Returns true if the submitted transaction was committed,
     false if the transaction was not committed, and throws `NodeOutOfSyncException`
     if the node has not yet indexed the transaction.")
----

=== await-tx

[source,clj]
----
  (await-tx
    [node tx]
    [node tx ^Duration timeout]
    "Blocks until the node has indexed a transaction that is at or past the
  supplied tx. Will throw on timeout. Returns the most recent tx indexed by the
  node.")
----

=== await-tx-time

[source,clj]
----
  (await-tx-time
    [node ^Date tx-time]
    [node ^Date tx-time ^Duration timeout]
    "Blocks until the node has indexed a transaction that is past the supplied
  txTime. Will throw on timeout. The returned date is the latest index time when
  this node has caught up as of this call.")
----

=== sync

[source,clj]
----
 (sync
    [node]
    [node ^Duration timeout]
    "Blocks until the node has caught up indexing to the latest tx available at
  the time this method is called. Will throw an exception on timeout. The
  returned date is the latest transaction time indexed by this node. This can be
  used as the second parameter in (db valid-time, transaction-time) for
  consistent reads.

  timeout – max time to wait, can be nil for the default.
  Returns the latest known transaction time.")

----

=== tx-log

[source,clj]
----
(open-tx-log ^ICursor [this after-tx-id with-ops?]
  "Reads the transaction log. Optionally includes
  operations, which allow the contents under the :crux.api/tx-ops
  key to be piped into (submit-tx tx-ops) of another
  Crux instance.
  after-tx-id      optional transaction id to start after.
  with-ops?        should the operations with documents be included?
  Returns a cursor over the TxLog.")
  (attribute-stats [node]
    "Returns frequencies of indexed attributes")
----

=== attribute-stats

[source,clj]
----
  (attribute-stats [node]
    "Returns frequencies of indexed attributes")
----


[#clojure-api-icruxdatasource]
== ICruxDatasource
Represents the database as of a specific valid and transaction time.

=== entity

[source,clj]
----
  (entity [db eid]
    "queries a document map for an entity.
    eid is an object which can be coerced into an entity id.
    returns the entity document map.")
----

=== entity-tx

[source,clj]
----
  (entity-tx [db eid]
    "returns the transaction details for an entity. Details
    include tx-id and tx-time.
    eid is an object that can be coerced into an entity id.")
----

=== new-snapshot

[source,clj]
----
  (new-snapshot ^java.io.Closeable [db]
     "Returns a new implementation-specific snapshot allowing for multiple
     entity calls to share the same KV store snapshot.
     returns an implementation specific snapshot")
----

=== q

[source,clj]
----
  (q
    [db query]
    "q[uery] a Crux db.
    query param is a datalog query in map, vector or string form.
    Returns a vector of result tuples.")
----

=== open-q

[source,clj]
----
  (open-q
    [db query]
    "lazily q[uery] a Crux db.
      query param is a datalog query in map, vector or string form.

     This function returns a Closeable sequence of result tuples - once you've consumed
     as much of the sequence as you need to, you'll need to `.close` the sequence.
     A common way to do this is using `with-open`:

     (with-open [res (crux/open-q db '{:find [...]
                                       :where [...]})]
       (doseq [row res]
         ...))

     Once the sequence is closed, attempting to iterate it is undefined.
     ")
----

=== history-ascending

[source,clj]
----
  (history-ascending
    [db eid]
    "Retrieves entity history in chronological order from and including the
    valid time of the db while respecting transaction time. Includes the
    documents.")
----

=== open-history-ascending

[source,clj]
----
  (open-history-ascending
    [db eid]
    "Retrieves entity history lazily in chronological order from and including
    the valid time of the db while respecting transaction time. Includes the
    documents.")
----

=== history-descending

[source,clj]
----
  (history-descending
    [db eid]
    "Retrieves entity history in reverse chronological order from and including
    the valid time of the db while respecting transaction time. Includes the
    documents.")
----

=== open-history-descending

[source,clj]
----
  (open-history-descending
    [db eid]
    "Retrieves entity history lazily in reverse chronological order from and
    including the valid time of the db while respecting transaction time.
    Includes the documents.")
----

=== valid-time

[source,clj]
----
  (valid-time [db]
    "returns the valid time of the db.
    If valid time wasn't specified at the moment of the db value retrieval
    then valid time will be time of the latest transaction.")
----

=== transaction-time

[source,clj]
----
  (transaction-time [db]
    "returns the time of the latest transaction applied to this db value.
    If a tx time was specified when db value was acquired then returns
    the specified time."))
----


== Lifecycle members

=== start-node

[source,clj]
----
(defn start-node ^ICruxAPI [options])
----

NOTE: requires any dependendies on the classpath that the Crux modules may need.

Options:

[source,clj]
----
{:crux.node/topology ['crux.standalone/topology]}
----

Options are specified as keywords using their long format name, like
`:crux.kafka/bootstrap-servers` etc. See the individual modules used in the specified
topology for option descriptions.

returns a node which implements ICruxAPI and
java.io.Closeable. Latter allows the node to be stopped by
calling `(.close node)`.

throws IndexVersionOutOfSyncException if the index needs rebuilding.
throws NonMonotonicTimeException if the clock has moved backwards since
last run. Only applicable when using the event log.

=== new-api-client

[source,clj]
----
(defn new-api-client ^ICruxAPI [url])
----

Creates a new remote API client ICruxAPI. The remote client
requires valid and transaction time to be specified for all
calls to `db`.

NOTE: requires either clj-http or http-kit on the classpath,
see crux.remote-api-client/*internal-http-request-fn*
for more information.

Param `url` the URL to a Crux HTTP end-point.

Returns a remote API client.

=== new-ingest-client

[source,clj]
----
(defn new-ingest-client ^ICruxAsyncIngestAPI [options])
----

Starts an ingest client for transacting into Kafka without running a
full local node with index.

For valid options, see crux.kafka/default-options. Options are
specified as keywords using their long format name, like
:crux.kafka/bootstrap-servers etc.

Options:

[source,clj]
----
{:crux.kafka/bootstrap-servers "kafka-cluster-kafka-brokers.crux.svc.cluster.local:9092"
:crux.kafka/group-id           "group-id"
:crux.kafka/tx-topic           "crux-transaction-log"
:crux.kafka/doc-topic          "crux-docs"
:crux.kafka/create-topics      true
:crux.kafka/doc-partitions     1
:crux.kafka/replication-factor 1}
----

Returns a crux.api.ICruxIngestAPI component that implements
java.io.Closeable, which allows the client to be stopped by calling
close.
