= Configuration

== Systems

To start a Crux system, use the
https://juxt.pro/crux/docs/javadoc/index.html[Java API] or the Clojure
https://github.com/juxt/crux/blob/master/src/crux/api.clj[`crux.api`].

There are two main Crux systems: *cluster node* vs *standalone*. Use a
cluster node system when horizontal scalability is required or when
you want the guarantees that Kafka offers in terms of resiliency,
availabilty, and retention of data.

Multiple instances of a cluster node systems may participate in a
cluster using Kafka as the primary store and as the central means of
coordination.

The Standalone system is where a single Crux instance has everything
it needs locally. This is good for experimenting with Crux and
for small to medium sized deployments, where running a single instance
is permissable.

.Crux Systems
[#table-conversion%header,cols="d,d,d"]
|===
|Name|Transaction Log|Java API
|Cluster Node|Uses Kafka|`Crux.startClusterNode options;`
|Standalone|Uses local event log|`Crux.startStandaloneSystem options;`
|===

Crux systems implement the `ICruxAPI` interface and are the
starting point for making use of Crux. Systems also implement
`java.io.Closeable` and can therefore be lifecycle managed.

NOTE: To see an example of a Crux System being integrated into a
Clojure lifecycle management framework such as Integrant, see the
https://github.com/juxt/crux/blob/master/docs/example_standalone_integrantsystem.clj[example
Integrant system].

== Properties

Crux Systems will use the following properties:

.Systems Configuration
[#table-conversion%header,cols="d,d,d,d"]
|===
|System|Component|Property|Description
|Both|kv-store|`kv-backend`|Sets the K/V Store to use, e.g. `"crux.kv.rocksdb.RocksKv"`
|Both|kv-store|`db-dir`|Sets the data-directory to use, e.g. `"data/db-dir-1"`
|Standalone|tx-log|`bootstrap-servers`|Kafka Servers to connect to e.g. `"localhost:9092"`
|Standalone|http-server|`server-port`|Port for Crux HTTP Server e.g. `8080`
|===

[#standalone]
== Standalone System

Using the Crux standalone system is the best way to get started. Once
you've started a standalone Crux instance as described below, you can
then follow the <<get_started.adoc#,getting started
example>>.

=== Project Dependency

To add Crux as a project dependency:

[source,clj]
----
include::./deps.edn[tags=CruxDep]
----

=== Start the standalone system:

[source,clj]
----
include::./examples.clj[tags=start-system]
----

For the purposes of this Hello World, we are using the simplest
configuration of Crux, where all of the pluggable components are
in-memory. There is no Kafka or RocksDB to worry about.

You can later stop the system if you wish:

[source,clj]
----
include::./examples.clj[tags=close-system]
----

== Cluster Node System

When using Crux at scale it is recommended to use Crux as nodes
connecting to a Kafka cluster.

Add Crux as a project dependency:

[source,clj]
----
include::./deps.edn[tags=CruxDep]
----

And Kafka:

[source,clj,subs="normal"]
----
include::./deps.edn[tags=KafkaDeps]
----

Use the API to start a cluster node system, configuring it with the
`bootstrap-servers` property in order to connect to Kafka:

[source,clj]
----
include::./examples.clj[tags=start-cluster-node-system]
----

NOTE: If you don't specify `kv-backend` then by default the
cluster-node system will use RocksDB. You will need to <<#rocksdep,add RocksDB>> to
your list of project dependencies.

You can later stop the system if you wish:

[source,clj]
----
include::./examples.clj[tags=close-system]
----

== RocksDB

[#rocksdep]
=== Project Dependency

Add RocksDB as a project dependency:

[source,clj,subs="normal"]
----
include::./deps.edn[tags=RocksDeps]
----

=== Configuration

Set the following properties when configuring Crux systems:

.Rocks Configuration
[#table-conversion%header,cols="d,d"]
|===
|Property|Value
|`kv-backend`|`"crux.kv.rocksdb.RocksKv"`
|`db-dir`|i.e. `"data/db-dir-1"`
|===

For example when constructing the standalone system:

[source,clj]
----
include::./examples.clj[tags=start-standalone-with-rocks]
----

== Http

Crux can be used programmatically as a library, but Crux also ships
with an embedded HTTP server, that allows clients to use the API
remotely via REST.

Set the `server-port` configuration property on a Crux system to
expose a HTTP port that will accept REST requests.

Visit the guide on using the <<rest#rest,REST api>> for examples
of how to interact with Crux over HTTP.

== Extras

=== Embedded Kafka

Crux has an embedded Kafka that can be used.

Add Kafka and Zookeeper to your project dependencies:

[source,clj,subs="normal"]
----
include::./deps.edn[tags=KafkaDeps]
include::./deps.edn[tags=ZookeeperDeps]

----

See the below example code:

[source,clj]
----
include::./examples.clj[tags=ek-example]
----

You can later stop the Embedded Kafka if you wish:

[source,clj]
----
include::./examples.clj[tags=ek-close]
----
