== Kafka Nodes

When using Crux at scale it is recommended to use multiple Crux nodes connected
via a Kafka cluster.

image::local-cluster-mode.svg[Local Cluster Mode,width=70%,align="center"]

Kafka Cluster Nodes have the following properties:

.Cluster Node Configuration
[#table-conversion%header,cols="d,d,d"]
|===
|Property|Description|Default value
|`bootstrap-servers`|List of Kafka Servers to connect to|*localhost:9092*
|`tx-topic`|Name of Kafka topic to send transaction log|*crux-transaction-log*
|`doc-topic`|Name of Kafka topic to send documents|*crux-docs*
|`create-topics`|Option to automatically create Kafka topics if they do not already exist|*true*
|`doc-partitions`|Number of partitions for the document topic|*1*
|`replication-factor`|Number of times to replicate data on Kafka|*1*
|===

=== Project Dependencies

[source,clj]
----
include::./deps.edn[tags=CruxDep]
----

[source,clj,subs="normal"]
----
include::./deps.edn[tags=KafkaClientsDeps]
----

Use the API to start a cluster node, configuring it with the
`bootstrap-servers` property in order to connect to Kafka:

[source,clj]
----
include::./examples.clj[tags=start-cluster-node]
----

NOTE: If you don't specify `kv-backend` then by default the
cluster node will use RocksDB. You will need to <<#rocksdep,add RocksDB>> to
your list of project dependencies.

You can later stop the node if you wish:

[source,clj]
----
include::./examples.clj[tags=close-node]
----

=== Embedded Kafka

Crux is ready to work with an embedded Kafka for when you don't have a independently
running Kafka available to connect to (such as during development).

Add `crux-kafka-embedded` to your project dependencies:

[source,clj,subs="normal"]
----
include::./deps.edn[tags=KafkaEmbeddedDeps]
----

See the below example code:

[source,clj]
----
include::./examples.clj[tags=ek-example]
----

You can later stop the Embedded Kafka if you wish:

[source,clj]
----
include::./examples.clj[tags=ek-close]
----
