= Configuration

== Nodes

To start a Crux node, use the
https://juxt.pro/crux/docs/javadoc/index.html[Java API] or the Clojure
https://github.com/juxt/crux/blob/master/src/crux/api.clj[`crux.api`].

There are two types of Crux nodes: *cluster* and *standalone*. Use a
cluster node when horizontal scalability is required or when
you want the guarantees that Kafka offers in terms of resiliency,
availability, and retention of data.

Multiple cluster nodes participate in a cluster using Kafka as the primary
store and as the central means of coordination.

The Standalone node is where a single Crux instance has everything
it needs locally. This is good for experimenting with Crux and
for small to medium sized deployments, where running a single instance
is permissible.

.Crux Nodes
[#table-conversion%header,cols="d,d,d"]
|===
|Name|Transaction Log|Java API
|Cluster Node|Uses Kafka|`Crux.startClusterNode options;`
|Standalone|Uses local event log|`Crux.startStandaloneNode options;`
|===

Crux nodes implement the `ICruxAPI` interface and are the
starting point for making use of Crux. Nodes also implement
`java.io.Closeable` and can therefore be lifecycle managed.

NOTE: To see an example of a Crux Node being integrated into a
Clojure lifecycle management framework such as Integrant, see the
https://github.com/juxt/crux/blob/master/docs/example_standalone_integrant_node.clj[example
Integrant node].

== Properties

Crux Nodes will use the following properties:

.Nodes Configuration
[#table-conversion%header,cols="d,d,d,d"]
|===
|Node|Component|Property|Description
|Both|kv-store|`kv-backend`|Sets the K/V Store to use, e.g. `"crux.kv.rocksdb.RocksKv"`
|Both|kv-store|`db-dir`|Sets the data-directory to use, e.g. `"data/db-dir-1"`
|Standalone|tx-log|`bootstrap-servers`|Kafka Servers to connect to e.g. `"localhost:9092"`
|Standalone|http-server|`server-port`|Port for Crux HTTP Server e.g. `8080`
|===

[#standalone]
== Standalone Node

Using a Crux standalone node is the best way to get started. Once
you've started a standalone Crux instance as described below, you can
then follow the <<get_started.adoc#,getting started
example>>.

=== Project Dependency

To add Crux as a project dependency:

[source,clj]
----
include::./deps.edn[tags=CruxDep]
----

=== Start the standalone node:

[source,clj]
----
include::./examples.clj[tags=start-node]
----

For the purposes of this Hello World, we are using the simplest
configuration of Crux, where all of the pluggable components are
in-memory. There is no Kafka or RocksDB to worry about.

You can later stop the node if you wish:

[source,clj]
----
include::./examples.clj[tags=close-node]
----

== Cluster Nodes 

When using Crux at scale it is recommended to use multiple Crux nodes connected
via a Kafka cluster.

Add Crux as a project dependency:

[source,clj]
----
include::./deps.edn[tags=CruxDep]
----

And Kafka Clients:

[source,clj,subs="normal"]
----
include::./deps.edn[tags=KafkaClientsDeps]
----

Use the API to start a cluster node, configuring it with the
`bootstrap-servers` property in order to connect to Kafka:

[source,clj]
----
include::./examples.clj[tags=start-cluster-node]
----

NOTE: If you don't specify `kv-backend` then by default the
cluster node will use RocksDB. You will need to <<#rocksdep,add RocksDB>> to
your list of project dependencies.

You can later stop the node if you wish:

[source,clj]
----
include::./examples.clj[tags=close-node]
----

== RocksDB

[#rocksdep]
=== Project Dependency

Add RocksDB as a project dependency:

[source,clj,subs="normal"]
----
include::./deps.edn[tags=RocksDeps]
----

=== Configuration

Set the following properties when configuring Crux nodes:

.Rocks Configuration
[#table-conversion%header,cols="d,d"]
|===
|Property|Value
|`kv-backend`|`"crux.kv.rocksdb.RocksKv"`
|`db-dir`|i.e. `"data/db-dir-1"`
|`event-log-dir`|i.e. `"data/eventlog-1"`
|===

For example when constructing the standalone node:

[source,clj]
----
include::./examples.clj[tags=start-standalone-with-rocks]
----

== Http

Crux can be used programmatically as a library, but Crux also ships
with an embedded HTTP server, that allows clients to use the API
remotely via REST.

Set the `server-port` configuration property on a Crux node to
expose a HTTP port that will accept REST requests.

Visit the guide on using the <<rest#rest,REST api>> for examples
of how to interact with Crux over HTTP.

== Extras

=== Embedded Kafka

Crux is ready to work with an embedded Kafka.

Add Kafka and Zookeeper to your project dependencies:

[source,clj,subs="normal"]
----
include::./deps.edn[tags=KafkaDeps]
include::./deps.edn[tags=ZookeeperDeps]

----

See the below example code:

[source,clj]
----
include::./examples.clj[tags=ek-example]
----

You can later stop the Embedded Kafka if you wish:

[source,clj]
----
include::./examples.clj[tags=ek-close]
----
