= Deployment

== Kafka Cluster Modes

Use Kafka for transaction log and document log persistence.

=== Local Cluster

Embed the Crux node in your application:

image::local-cluster-mode.svg[Local Cluster Mode,width=70%,align="center"]

=== Remote Cluster

Use the Crux node over HTTP:

image::remote-cluster-mode.svg[Remote Cluster Mode,width=70%,align="center"]

== Standalone Modes

Use a second local KV instance for durable transaction log and document log
persistence. This is not recommended for production usage.

=== Local Standalone

Embed a fully independent instance of Crux in your application:

image::local-standalone-mode.svg[Local Standalone Mode,width=50%,align="center"]

=== Remote Standalone

Use a single standalone instance of Crux over HTTP:

image::remote-standalone-mode.svg[Remote Standalone Mode,width=50%,align="center"]

== Migration

You can rebuild nodes whenever needed as long as the transaction log and
document log is durably stored. Nodes will need rebuilding when index formats
have breaking changes. Migrating from a standalone node to a cluster node is
possible, to address evolving scaling and availability requirements.

== Security

Crux does not provide any native security features. It is important that you
carefully consider the security risks when deploying Crux in public
environments. Contact us if you would like to hear about JUXT's deployment
services for Crux: crux@juxt.pro 

== Managed Hosting

JUXT offers a Managed Hosting service for Crux to accelerate your development
and provide you with a secure and reliable service. We can deploy into any
environment. Contact us if you would like to hear about JUXT's Managed Hosting
service for Crux: crux@juxt.pro 

== Backup and Restore

Crux provides utility APIs for local backup and restore when you are using the
standalone mode (which is not recommended for production usage). For an example
of usage, see
https://github.com/juxt/crux/blob/e5e21352b7a466d20a7b57518e129770191de352/example/standalone_webservice/src/example_standalone_webservice/main.clj#L744[the
standalone web service example].

An additional example of backup and restore is provided that only applies to a stopped
standalone node
https://github.com/juxt/crux/tree/master/docs/example/backup-restore[here].

In a clustered deployment, only Kafka's
https://docs.confluent.io/current/kafka/post-deployment.html#backup-and-restoration[official
backup and restore] functionality should be relied on to provide safe
durability. The standalone mode's backup and restore operations can instead be
used for creating operational snapshots of a node's indexes for scaling
purposes. 
