= Design

== Introduction

Crux is an unbundled database, where parts are pluggable and can be
swapped out for alternative implementations. This document walks
through some of the noteworthy parts.

== ObjectStore

Crux contains an ObjectStore for storing and retreiving documents.

[source,clj]
----
include::../src/crux/db.clj[tags=ObjectStore]
----

The main implementation is `KvObjectStore` wrapped by
`CachedObjectstore`.

NOTE: Objects are stored against used their hashed value.

NOTE: The `KvObjectStore` wraps the lower-level `KvStore`

== KvStore

[source,clj]
----
include::../src/crux/kv.clj[tags=KvStore]
----

The `KvStore` exposes the operations Crux needs to use a Key Value store for
indexing purposes, and for storing Objects.

Implementations of the `KvStore` include:

.KvStores
[#table-conversion%header,cols="d,d"]
|===
|Implementation|Description
|`crux.kv.rocksdb/RocksKv`|Uses https://rocksdb.org/[RocksDB] and the standard Java API that ships with RocksDB
|`crux.kv.rocksdb.jnr/RocksJNRKv`|Uses https://rocksdb.org/[RocksDB] and a custom built JNR bridge
|`crux.kv.lmdb/LMDBKv`|Uses https://en.wikipedia.org/wiki/Lightning_Memory-Mapped_Database[LMBD]
|`crux.kv.memdb/MemKv`|An in-memory KvStore
|===

== TxLog

Crux uses a replayable transaction log that is used to derive indicies.

[source,clj]
----
include::../src/crux/db.clj[tags=TxLog]
----

The transaction log is used to write both transaction and documents to
an appendable transaction log.

.TxLogs
[#table-conversion%header,cols="d,d"]
|===
|Implementation|Description
|`crux.kafka.KafkaTxLog`|(default), using Kafka with separate Kafka topics for both documents and transactions
|`crux.tx.KvTxLog`|Uses the KvStore as the transaction log. This useful if Kafka isn't desired, and the topology of having distributed Crux nodes feeding of a centralised transacton log isn't required
|===

== Indexer

The indexer indexes documents and transactions for query
purposes. This might be on the back of subscriptions to Kafka topics,
or by direct calls made in a single node topological setup.

[source,clj]
----
include::../src/crux/db.clj[tags=Indexer]
----

The single implememention is `crux.tx.KvIndexer`, which makes use of
the `KvStore` to persist indices.

The Indexer writes to these indices when indexing _documents_:

.Crux Document Indices
[#table-conversion%header,cols="d,d"]
|===
|Implementation|Description
|`attribute+value+entity+content-hash-key`|For querying against attribute values
|`attribute+entity+value+entity+content-hash-key`|For querying against attribute values within entities
|===

The Indexer writes to these indices when indexing _transactions_:

.Crux Transaction Indices
[#table-conversion%header,cols="d,d"]
|===
|Implementation|Description
|`entity+valid-time+transaction-time+transaction-id`|Use for `as-of` document retrieval
|===
