= Get Started

== Recommended Reading

This guide contains simple steps showing how to transact data and run a simple
query. However, there are a few topics you might benefit from learning about
before you get too far with attempting to use Crux:

- *EDN* – the extensible data notation format used throughout
  the Crux APIs, see <<tutorials.adoc#_essential_edn_for_using_crux,Essential
EDN for Crux>>.

- The *Datalog* query language – Crux supports an EDN-flavoured version of
  Datalog. The <<queries.adoc#,Queries>> section within this documentation
provides a good overview. You can also find an interactive tutorial for
EDN-flavoured Datalog http://www.learndatalogtoday.org/chapter/1[here].

- *Clojure* – whilst a complete Java API is provided, a basic understanding of
  Clojure is recommended – Clojure is a succinct and pragmatic data-oriented
language with strong support for immutability and parallelism.
https://clojure.org/[See Clojure.org].

== Setting Up

If you want to start playing about, it is advised you run Crux in a
<<configuration.adoc#standalone,standalone configuration>> first.

Alternatively, if you just want to try using the REST API, follow https://github.com/juxt/crux/blob/master/example/standalone_webservice/README.md[these steps] to use a self-contained demonstration image from Docker Hub and refer to the <<rest.adoc#,REST API>> section.

*Docker way*.
See https://github.com/juxt/crux/tree/master/example/standalone_webservice[standalone webservice example]
for a demo Docker container.


== Transacting

[source,clj]
----
include::./examples.clj[tags=submit-tx]
----
Note that the ID for the Kafka transaction and the ID within the Crux document
must be the same. Restating the ID within the Crux document is currently necessary
although this may change in the future, as the standard API evolves.

== Querying

[source,clj]
----
include::./examples.clj[tags=query]
----

You should get:

[source,clj]
----
include::./examples.clj[tags=should-get]
----

An entity query would be:
[source,clj]
----
include::./examples.clj[tags=query-entity]
----
You should get:

[source,clj]
----
include::./examples.clj[tags=should-get-entity]
----

== Next Steps

Now you know the basics of how to interact with Crux you may want to dive into a https://juxt.pro/blog/posts/a-bitemporal-tale.html[tutorial] or continue on to read about the kinds of things you are able to do with <<queries.adoc#,Queries>>.
