= Get Started

==  Introduction

This guide contains simple steps showing how to transact data and run a simple
query. However, there are a few topics you might benefit from learning about
before you get too far with attempting to use Crux:

- *EDN* – the extensible data notation format used throughout
  the Crux APIs, see <<tutorials.adoc#_essential_edn_for_using_crux,Essential
EDN for Crux>>.

- The *Datalog* query language – Crux supports an EDN-flavoured version of
  Datalog. The <<queries.adoc#,Queries>> section within this documentation
provides a good overview. You can also find an interactive tutorial for
EDN-flavoured Datalog http://www.learndatalogtoday.org/chapter/1[here].

- *Clojure* – whilst a complete Java API is provided, a basic understanding of
  Clojure is recommended – Clojure is a succinct and pragmatic data-oriented
language with strong support for immutability and parallelism.
https://clojure.org/[See Clojure.org].

== Setting Up

If you want to start interacting with Crux in your environment then it is
advised you run Crux in a <<configuration.adoc#standalone,standalone
configuration>>.

Alternatively, if you simply want to experiment with Crux using a demo Docker
container from Docker Hub (no JVM/JDK/Clojure install required, only Docker!)
then please see the
https://github.com/juxt/crux/tree/master/docs/example/standalone_webservice[standalone
web service example]. You can also use this self-contained demonstration image to
experiment with the <<rest.adoc#,REST API>>.

== Transacting

[source,clj]
----
include::./examples.clj[tags=submit-tx]
----

== Querying

[source,clj]
----
include::./examples.clj[tags=query]
----

You should get:

[source,clj]
----
include::./examples.clj[tags=should-get]
----

An entity query would be:
[source,clj]
----
include::./examples.clj[tags=query-entity]
----
You should get:

[source,clj]
----
include::./examples.clj[tags=should-get-entity]
----

== Next Steps

Now you know the basics of how to interact with Crux you may want to dive into a https://juxt.pro/blog/posts/a-bitemporal-tale.html[REPL-based tutorial] (or use the interactive no-install browser-based https://nextjournal.com/crux/a-bitemporal-tale[Nextjournal edition]!). Otherwise, let's take a look at the kinds of things you are able to do with <<queries.adoc#,Queries>>.
