[#get-started]
== Get Started

===  Introduction

This guide contains simple steps showing how to transact data and run a simple
query. However, there are a few topics you might benefit from learning about
before you get too far with attempting to use Crux:

- *EDN* – the extensible data notation format used throughout
  the Crux APIs, see <<tutorials.adoc#tutorials-essential-edn,Essential
EDN for Crux>>.

- The *Datalog* query language – Crux supports an EDN-flavoured version of
  Datalog. The <<queries.adoc#,Queries>> section within this documentation
provides a good overview. You can also find an interactive tutorial for
EDN-flavoured Datalog http://www.learndatalogtoday.org/chapter/1[here].

- *Clojure* – whilst a complete Java API is provided, a basic understanding of
  Clojure is recommended – Clojure is a succinct and pragmatic data-oriented
language with strong support for immutability and parallelism.
https://clojure.org/[See Clojure.org].

[#get-started-setup]
=== Setting Up

Follow the below steps to quickly set yourself up a Crux playground:

=== Project Dependency

First add Crux as a project dependency:

[source,clj]
----
include::./deps.edn[tags=CruxDep]
----

=== Start a Crux node

[source,clj]
----
include::./src/docs/examples.clj[tags=include-crux-api]

include::./src/docs/examples.clj[tags=start-standalone-node]
----

For the purposes of this Hello World, we are using the simplest configuration of Crux, where all of the pluggable components are in-memory. There is no Kafka or RocksDB to worry about.

=== Transacting

[source,clj]
----
include::./src/docs/examples.clj[tags=submit-tx]
----

=== Querying

[source,clj]
----
include::./src/docs/examples.clj[tags=query]
----

You should get:

[source,clj]
----
include::./src/docs/examples.clj[tags=should-get]
----

An entity query would be:
[source,clj]
----
include::./src/docs/examples.clj[tags=query-entity]
----
You should get:

[source,clj]
----
include::./src/docs/examples.clj[tags=should-get-entity]
----

=== Next Steps

Now you know the basics of how to interact with Crux you may want to dive into our <<tutorials.adoc#, tutorials>>. Otherwise, let's take a look at the kinds of things you are able to do with <<queries.adoc#,Queries>>.
