= 'Pull' syntax

Crux queries support a 'pull' syntax, allowing you to decouple specifying which entities you want from what data you'd like about those entities in your queries.
Crux's support is based on the excellent https://edn-query-language.org/eql/1.0.0/what-is-eql.html[EDN Query Language (EQL)^] library.

To specify what data you'd like about each entity, include a `(pull ?logic-var pull-spec)` entry in the `:find` clause of your query:

[source,clojure]
----
;; with just 'query':
{:find [?uid ?name ?profession]
 :where [[?user :user/id ?uid]
         [?user :user/name ?name]
         [?user :user/profession ?profession]}
;; => [[1 "Ivan" :doctor] [2 "Sergei" :lawyer], [3 "Petr" :doctor]]

;; using `pull`:
{:find [(pull ?user [:user/name :user/profession]
 :where [[?user :user/id ?uid]]}

;; => [{:user/id 1, :user/name "Ivan", :user/profession :doctor},
;;     {:user/id 2, :user/name "Sergei", :user/profession :lawyer},
;;     {:user/id 3, :user/name "Petr", :user/profession :doctor}]
----

We can navigate to other entities (and hence build up nested results) using 'joins'.
Joins are specified in `{}` braces in the pull-spec - each one maps one join key to its nested spec:

[source,clojure]
----
;; with just 'query':
{:find [?uid ?name ?profession-name]
 :where [[?user :user/id ?uid]
         [?user :user/name ?name]
         [?user :user/profession ?profession]
         [?profession :profession/name ?profession-name]}
;; => [[1 "Ivan" "Doctor"] [2 "Sergei" "Lawyer"], [3 "Petr" "Doctor"]]

{:find [(pull ?user [:user/name {:user/profession [:profession/name]}]
 :where [[?user :user/id ?uid]]}

;; => [{:user/id 1, :user/name "Ivan", :user/profession {:profession/name "Doctor"}},
;;     {:user/id 2, :user/name "Sergei", :user/profession {:profession/name "Lawyer"}}
;;     {:user/id 3, :user/name "Petr", :user/profession {:profession/name "Doctor"}}]
----

We can also navigate in the reverse direction, looking for entities that refer to this one, by prepending `_` to the attribute name:

[source,clojure]
----
{:find [(pull ?profession [:profession/name {:user/_profession [:user/id :user/name]}]
 :where [[?profession :profession/name]]}

;; => [{:profession/name "Doctor",
;;      :user/_profession [{:user/id 1, :user/name "Ivan"},
;;                         {:user/id 3, :user/name "Petr"}]},
;;     {:profession/name "Lawyer",
;;      :user/_profession [{:user/id 2, :user/name "Sergei"}]}]
----

You can quickly grab the whole document by specifying `*` in the pull spec:

[source,clojure]
----
;; with just 'query':
{:find [(pull ?user [*]
 :where [[?user :user/id 1]]}

;; => [{:user/id 1, :user/name "Ivan", :user/profession :doctor, ...}]
----

For full details on what's supported in the pull-spec, see the https://edn-query-language.org/eql/1.0.0/specification.html[EQL specification^]
Crux does not (yet) support union queries or recursive queries.
