= Query

== Basic Query

[source,clj]
----
include::./examples.clj[tags=query]
----

== Rules

Crux query capability is easiest summarized via an example:

[source,clj]
----
(q/q db
    '{:find  [?e2]
      :where [(follow ?e1 ?e2)]
      :args [{:?e1 :1}]
      :rules [[(follow ?e1 ?e2)
              [?e1 :follow ?e2]]
             [(follow ?e1 ?e2)
              [?e1 :follow ?t]
              (follow ?t ?e2)]]})
----

The `db` is retrieved via a call to `crux.query/db` which optionally
takes business and transaction time. The call will block until the local
index has seen the transaction time, if provided. The `crux.query/q`
takes 2 or 3 arguments, `db` and `q` but also optionally a `snapshot`
which is already opened and managed by the caller (using `with-open` for
example). This version of the call returns a lazy sequence of the
results, while the other verision provides a set. A snapshot can be
retreived from a `kv` instance via `crux.kv-store/new-snapshot`.

The `:args` key contains a relation where each map is expected to have
the same keys. These keys are turned into logic variable symbols and the
relation is joined with the rest of the query. The elements must
implement `Comparable`.

Crux does not support variables in the attribute position. The entity
position is hard coded to mean the `:crux.db/id` field.
