= Query Guide

== Quick Reference

As a handy reference to Crux's query features:

* <<_a_very_basic_query>>
* <<_valid_time_travel>>
* <<_how_to_use_arguments,`:args`>>
* <<_a_very_basic_query,`or`>>
* <<_a_very_basic_query,Combining `or` with `and`>>
* <<_a_very_basic_query,`not`>>
* <<_joins,Joins>>
* <<_a_very_basic_query,Blanks>>
* <<_a_very_basic_query,`:rules`>>

== Introduction 

This page walks through many of the more interesting queries that run as part of Crux's default test suite. See `test/crux/query_test.clj` for the full suite of query tests and how each test listed below runs in the wider context.

Extensible Data Notation (edn) is used as the data format for the public Crux APIs. To gain an understanding of edn see <<resources.adoc#_essential_edn_for_using_crux>>.

== A very basic query

Our first query runs on a database that contains the following 3 documents which get broken apart and indexed as "entities":
[source,clj]
----
include::./query_test_examples.clj[tags=test-basic-query-d]
----

Note that `:ivan`, `:petr` and `:smith` are edn keywords, which may be used as document IDs in addition to UUIDs.

The following query has 3 clauses, represented as edn vectors within the `:where` vector which constrain the result set to match only the entities that satisfy all 3 clauses at once:

[source,clj]
----
include::./query_test_examples.clj[tags=test-basic-query-q]
----

Let's try to work out what these 3 clauses do...

`[p1 :name name]` is looking for all entities that have a value under the attribute of `:name` and then binds the corresponding entity ID to `p1` and the corresponding value to `name`. Since all 3 entites in our database have a `:name` attribute, this clause alone will simply return all 3 entities.

`[p1 :last-name name]` reuses the variable `name` from the previous clause which is significant because it constrains the query to only look for entities where the value of `:name` (from the first clause) is _equal to_ the value of `:last-name` (from the second clause). Looking at documents that were processed by our database there is only one possible entity that can be returned, because it has the same values `:name` and `:last-name`.

`[p1 :name "Smith"]` only serves to reinforce the conclusion from the previous two clauses which is that the variable `name` can only be matched against the string `"Smith"` within our database.

...so what is the actual result of the query? Well that is defined by the `:find` vector which states that only the values corresponding to `p1` should be returned, which in this case is simply `:smith` (the keyword database ID for the document relating to our protagonist "Smith Smith"). Results are returned as an edn set, which means duplicate results will not appear.

The edn result set only contains the value `:smith`

[source,clj]
----
include::./query_test_examples.clj[tags=test-basic-query-r]
----

== How to use arguments

For the next set of queries we will again use the same set of documents for our database as used in the previous section:

[source,clj]
----
include::./query_test_examples.clj[tags=query-with-arguments-d]
----

=== Query: "Match on entity ID and value"

[source,clj]
----
include::./query_test_examples.clj[tags=query-with-arguments1-q]
----

Our first query supplies two arguments to the query via a map within the `:args` vector. The effect of this is to make sure that regardless of whether other `:name` values in the database also equal `"Ivan"`, that only the entity with an ID matching our specific `ivan` ID is considered within the query. Use of arguments means we can avoid hard-coding values directly into the query clauses.


Result Set:
[source,clj]
----
include::./query_test_examples.clj[tags=query-with-arguments1-r]
----

=== Query: "Match entities with given values"

[source,clj]
----
include::./query_test_examples.clj[tags=query-with-arguments2-q]
----

This next query shows how multiple argument values can be mapped to a single field. This allows us to usefully parametise the input to a query such that we do not have to rerun a single query multiple times (which would be significantly less efficient!).

Result Set:
[source,clj]
----
include::./query_test_examples.clj[tags=query-with-arguments2-r]
----

=== Query: "Match entities with given value tuples"

[source,clj]
----
include::./query_test_examples.clj[tags=query-with-arguments3-q]
----

Here we see how we can extend the parametisation to match using multiple fields at once.

Result Set:
[source,clj]
----
include::./query_test_examples.clj[tags=query-with-arguments3-r]
----

=== Query: "Use predicates with arguments" 

[source,clj]
----
include::./query_test_examples.clj[tags=query-with-arguments4-q]
----

Something else we can do with arguments is apply predicates to them directly within the clauses. Predicates return either `true` or `false` but all predicates used in clauses must return `true` in order for the given combination of field values to be part of the valid result set. In this case only `:name "Ivan"` satisfies `[(re-find #"I" name)]` (which returns true for any values that begin with "I").

[source,clj]
----
include::./query_test_examples.clj[tags=query-with-arguments4-r]
----

=== Query: "Use range constraints with arguments" 

[source,clj]
----
include::./query_test_examples.clj[tags=query-with-arguments5-q]
----

Finally we can see how we can return an argument that passes all of the predicates by including it in the `:find` vector. This essentially bypasses any interaction with the data in our database. 

Result Set:
[source,clj]
----
include::./query_test_examples.clj[tags=query-with-arguments5-r]
----

== Valid time travel

Congratulations! You already know enough about queries to build a simple CRUD application with Crux. However, your manager has just told you that the new CRUD application you have been designing needs to backfill the historical document versions from the legacy CRUD application. Luckily Crux makes it easy for your application to both insert and retrieve these old versions.

Here we will sees how you are able to run queries at a given point in the valid time axis against, implicity, the most recent transaction time. 

First, we transact a very old document into the database with the ID `:malcolm` and the `:name` `"Malcolm"`, and specify the `valid time` instant at which this document became valid in the legacy system: `#inst "1986-10-22"`.

[source,clj]
----
include::./query_test_examples.clj[tags=query-at-t-d1]
----

Next we transact a slightly more recent (though still very old!) revision of that same document where the `:name` has been corrected to `"Malcolma"`, again using a historical timestamp extracted from the legacy system.

[source,clj]
----
include::./query_test_examples.clj[tags=query-at-t-d2]
----

We are then able to query at different points in the valid time axis to check for the validity of the correction.
[source,clj]
----
include::./query_test_examples.clj[tags=query-at-t-q]
----

Firstly we can verify that `"Malcolma"` was unknown at `#inst "1986-10-23"`.

[source,clj]
----
include::./query_test_examples.clj[tags=query-at-t-q1-q]
----

Result Set:
[source,clj]
----
include::./query_test_examples.clj[tags=query-at-t-q1-r]
----

We can then verify that `"Malcolma"` is the currently known `:name` for the entity with ID `:malcolm` by simply not specifying a valid time alongside the query. This will be the case so long as there are no newer versions (in the valid time axis) of the document that affect the current valid time version. 

[source,clj]
----
include::./query_test_examples.clj[tags=query-at-t-q2-q]
----

Result Set:
[source,clj]
----
include::./query_test_examples.clj[tags=query-at-t-q2-r]
----

== Joins

=== Query: "Join across entities on a single attribute" 

Given the following documents in the database
[source,clj]
----
include::./query_test_examples.clj[tags=join-d]
----

We can run a query to return a set of tuples that satisfy the join on the attribute `:name`
[source,clj]
----
include::./query_test_examples.clj[tags=join-q]
----

Result Set:
[source,clj]
----
include::./query_test_examples.clj[tags=join-r]
----

Note that every person joins once, plus 2 more matches.

=== Query: "Join with two attributes, including a multi-valued attribute"

Given the following documents in the database
[source,clj]
----
include::./query_test_examples.clj[tags=join2-d]
----

We can run a query to return a set of entities that `:follows` the set of entities with the `:name` value of `"Ivan"`
[source,clj]
----
include::./query_test_examples.clj[tags=join2-q]
----

Result Set:
[source,clj]
----
include::./query_test_examples.clj[tags=join2-r]
----

Note that because Crux is schemaless there is no need to have elsewhere declared that the `:follows` attribute may take a value of edn type `set`.

== DataScript Queries

== Bitemporal Queries

== Other Queries
