= XTDB Documentation

We use https://docs.antora.org/antora/2.3/[Antora] to build the XTDB documentation.

The full website build/deploy is available (to JUXTers) in the private https://github.com/xtdb/website-old[website-old] repo - for more details, see the README over there.

From here, though, you can build the documentation section in isolation, to check any changes.

== Install:

* Requires Node/NPM installed.

== Build:

* `./bin/build.sh`
** Troubleshooting: `npm install`
* `./bin/open-local-site.sh` to open up the built version of the site in your browser.
* `./bin/run-local-server.sh` to open the site if you require plugins (like Dark Reader) which work poorly with `file://` URLs.

== Versions:

The documentation site includes documentation for previous releases as well as the current main branch.
These are located by branch name convention - branches prefixed with `docs-v*` will be included.

=== Release checklist:

1. Create a `docs-v<new-version>` branch
2. Update docs/reference/antora.yml:
  a. Delete `prerelease: indeed` and `display-version: main` lines
  b. Update `version: master` to `version: <new-version>`
3. Commit, push branch to the main JUXT XTDB repo
4. Head over to `website-old` to deploy the docs.
