= XTDB Documentation

We use https://docs.antora.org/antora/2.3/[Antora] to build the XTDB documentation.

The full website build/deploy is available (to JUXTers) in the private https://github.com/xtdb/website[website] repo - for more details, see the README over there.

From here, though, you can build the documentation section in isolation, to check any changes.

== Install:

* Requires Node/NPM installed.

== Build:

* `./bin/build.sh`
** Troubleshooting: `npm install`
* `./bin/open-local-site.sh` to open up the built version of the site in your browser.
* `./bin/run-local-server.sh` to open the site if you require plugins (like Dark Reader) which work poorly with `file://` URLs.

== Versions:

The documentation site includes documentation for previous releases as well as the current main branch.
These are located by branch name convention - branches prefixed with `docs-v*` will be included.

=== Release checklist:

1. Create a `docs-v<new-version>` branch
2. Update `docs/**/antora.yml`:
  a. Delete `prerelease: indeed`
  b. Delete `display_version: master`
  c. Replace `version: master` with `version: <new-version>`
3. Update `docs/**/*.adoc`:
  a. Replace `:page-alias: zig` with `:page-alias: <new-version>@zig`
3. Commit, push branch to https://github.com/xtdb/xtdb
4. Run `./bin/build.sh`. You should not get any errors.
5. Run `./bin/deploy.sh`. You will need AWS credentials.
