= Building the website

To build the website we are using [Antora](https://docs.antora.org/antora/2.3/) to build the Asciidoctor files within the main Crux repository, and then uploading the built site into S3 (used, with CloudFront, to host the website).## DependenciesTo build the website, you will need:

== Install

* Node/NPM
* `npm i -g @antora/cli @antora/site-generator-default`
* AWS CLI to deploy

== Building

Build the site with `./bin/build.sh`:
* `--with-local-bundle` to use a local build of the ui-bundle (assuming you have `crux-site` checked out in the same directory as your `crux` repo)
* `--with-blog` will build the site with the blog section (assuming, as above, you have `crux-site` checked out in the same directory as your `crux` repo)

It's assumed that
* branches prefixed with `docs-v*` will be included as previous versions
  * When you release Crux, create one of these `docs-v*` branches on `origin`, and update the version in `reference/antora.yml`
  * To remove a version from the site, delete the branch
* you have `https://github.com/juxt/crux` as `origin` - so that if you don't have the `docs-v*` branches locally, Antora will still find them

== Deploying

Deploy a publicly-accessible preview

* Run `./bin/deploy.sh`
* By default this will deploy to `https://opencrux.com/_<whoami>/`
* Set `OPENCRUX_PREFIX` to default to something other than `whoami`

Deploy to the live site

* Run `./bin/deploy.sh /`
* Note that `/` implies the use of top-level domain routes
