= Roadmap

== GitHub Issues

We use GitHub Issues to capture and respond to questions about the roadmap and to work on near-term changes to Crux.

== Long-term Direction

The Crux roadmap is not opaque and we are open to community involvement in defining our objectives. We currently use a private Clubhouse instance to evaluate priorities and track long-term objectives. We expect that the majority of technical changes for the rest of 2019 will be in the layers of features that sit above the Crux core.

== Enterprise Edition & Cloud Offering

JUXT is working to develop enterprise-level capabilities for operating Crux clusters and managing data across clusters. Crux can already be easily deployed to Kubernetes and we are aiming to provide self-service cloud instances to support production customer usage. JUXT currently offers flexible Managed Hosting for Crux.

== Contribution

Crux is an open source product that JUXT will support throughout its evolution. As the community continutes to grow we will incorporate quality community-led contributions into the core. However, because of Crux's unbundled architecture, we expect that sustantial contributions can be made outside of the core. JUXT aims to promote and help all community-led activities around Crux.
