= Getting Started

== Introduction

There are two main Crux systems: *local node* vs *standalone*. Local
node is each Crux system instance being a node in a wider cluster,
using Kafka for the centralised event log.

Standalone is where a single Crux instance has everything it needs
locally.

.Crux Systems
[#table-conversion%header,cols="d,d"]
|===
|Name|Transaction Log
|Local Node|Uses Kakfa
|Standalone|Uses local event log
|===

The Standalone system is good for experimenting with Crux and
for small to medium sized deployments, where running a single instance
is permissable.

The Local Node is for when horizontal scalability of nodes is
required, and for the resiliency and availabilty guarantees that Kafka
offers.

[#standalone]
== Standalone System

Using the Crux standalone system is the best way to get started. Once
you've staredt a standalone Crux instance as described below, you can
then follow the <<user_guide#getting-started-example,getting started
example>>.

=== Project Dependency

To add Crux as a project dependency:

[source,clj]
----
include::./deps.edn[tags=CruxDep]
----

=== Start the standalone system:

[source,clj]
----
include::./examples.clj[tags=start-system]
----

For the purposes of this Hello World, we are using the simplest
configuration of Crux, where all the pluggable components are
in-memory constituents. There is no Kafka or RocksDB to worry about.

You can later stop the system if you wish:

[source,clj]
----
include::./examples.clj[tags=close-system]
----

== Local Node System

When using Crux at scale, it's recommended to use Crux as nodes
connecting to a Kakfa cluster.

Add Crux as a project dependency:

[source,clj]
----
include::./deps.edn[tags=CruxDep]
----

And Kafka:

[source,clj,subs="normal"]
----
include::./deps.edn[tags=KakfaDeps]
----

Use the API to start a local node system, configuring it with the
`bootstrap-servers` property in order to connect to Kafka:

[source,clj]
----
include::./examples.clj[tags=start-local-node-system]
----

Note: If you don't specify `kv-backend` then by default the
local-node system will use RocksDB. You will need to <<#rocksdep,add RocksDB>> to
your list of project dependencies.

== RocksDB

[#rocksdep]
=== Project Dependency

Add RocksDB as a project dependency:

[source,clj,subs="normal"]
----
include::./deps.edn[tags=RocksDeps]
----

=== Configuration

Set the following properties when configuring Crux systems:

.Rocks Configuration
[#table-conversion%header,cols="d,d"]
|===
|Property|Value
|`kv-backend`|`"crux.kv.rocksdb.RocksKv"`
|`db-dir`|i.e. `"data/db-dir-1"`
|===

For example when constructing the standalone system:

[source,clj]
----
include::./examples.clj[tags=start-standalone-with-rocks]
----

== Http

Crux can be used programmatically as a library, but Crux also ships
with an embedded http server, that allows clients to use the API
remotely via REST.

[source,clj]
----
include::./examples.clj[tags=http-setup]
----

Visit the guide on using the <<deployment#rest,REST api>> for examples
of how to interact with Crux over http.

Close the server:

[source,clj]
----
include::./examples.clj[tags=http-close]
----

== Embedded

To see an example of a wired up embedded Crux, see an
https://github.com/juxt/crux/blob/master/docs/example_system.clj[example
Integrant system].

NOTE: TODO, show how to actually use this system (transact and run
queries).

== Configuration

=== K/V Store

Supported KV stores are RocksDB, LMDB and an in-memory store.

== Embedded Kafka

Add Kafka and Zookeeper to your project dependencies:

[source,clj,subs="normal"]
----
include::./deps.edn[tags=KakfaDeps]
----

See the below example code:

[source,clj]
----
include::./examples.clj[tags=ek-example]
----

You can later stop the Embedded Kafka if you wish:

[source,clj]
----
include::./examples.clj[tags=ek-close]
----
