= Getting Started

== Systems

To start a Crux system, use the
https://juxt.pro/crux/docs/javadoc/index.html[Java API] or the Clojure
https://github.com/juxt/crux/blob/master/src/crux/api.clj[`crux.api`].

There are two main Crux systems: *local node* vs *standalone*. Use a
local node system for when horizontal scalability of nodes required,
and for guarantees Kafka makes on resiliency and
availabilty, and retention of data.

if you want Crux system instances to participate in
a cluster using Kafka for the centralised event log.

The Standalone system is where a single Crux instance has everything
it needs locally. This is good for experimenting with Crux and
for small to medium sized deployments, where running a single instance
is permissable.

.Crux Systems
[#table-conversion%header,cols="d,d,d"]
|===
|Name|Transaction Log|Java API
|Local Node|Uses Kakfa|`Crux.startLocalNode options;`
|Standalone|Uses local event log|`Crux.startStandaloneSystem options;`
|===

Crux systems implement the `ICruxSystem` interface and are the
starting point for making use of Crux. Systems also implement
`java.io.Closeable` and can therefore be lifecycle managed.

NOTE: To see an example of a Crux System being integrated into a
Clojure lifecycle management framework such as Integrant, see the
https://github.com/juxt/crux/blob/master/docs/example_standalone_integrantsystem.clj[example
Integrant system].

== Configuration

Crux Systems will use the following properties:

.Systems Configuration
[#table-conversion%header,cols="d,d,d,d"]
|===
|System|Component|Property|Description
|Both|kv-store|`kv-backend`|Sets the K/V Store to use, i.e. `"crux.kv.rocksdb.RocksKv"`
|Both|kv-store|`db-dir`|Sets the data-directory to use, i.e. `"data/db-dir-1"`
|Standalone|tx-log|`bootstrap-servers`|Kakfa Servers to connect to i.e. `"localhost:9092"`
|===

[#standalone]
== Standalone System

Using the Crux standalone system is the best way to get started. Once
you've staredt a standalone Crux instance as described below, you can
then follow the <<user_guide#getting-started-example,getting started
example>>.

=== Project Dependency

To add Crux as a project dependency:

[source,clj]
----
include::./deps.edn[tags=CruxDep]
----

=== Start the standalone system:

[source,clj]
----
include::./examples.clj[tags=start-system]
----

For the purposes of this Hello World, we are using the simplest
configuration of Crux, where all the pluggable components are
in-memory constituents. There is no Kafka or RocksDB to worry about.

You can later stop the system if you wish:

[source,clj]
----
include::./examples.clj[tags=close-system]
----

== Local Node System

When using Crux at scale, it's recommended to use Crux as nodes
connecting to a Kakfa cluster.

Add Crux as a project dependency:

[source,clj]
----
include::./deps.edn[tags=CruxDep]
----

And Kafka:

[source,clj,subs="normal"]
----
include::./deps.edn[tags=KakfaDeps]
----

Use the API to start a local node system, configuring it with the
`bootstrap-servers` property in order to connect to Kafka:

[source,clj]
----
include::./examples.clj[tags=start-local-node-system]
----

Note: If you don't specify `kv-backend` then by default the
local-node system will use RocksDB. You will need to <<#rocksdep,add RocksDB>> to
your list of project dependencies.

== RocksDB

[#rocksdep]
=== Project Dependency

Add RocksDB as a project dependency:

[source,clj,subs="normal"]
----
include::./deps.edn[tags=RocksDeps]
----

=== Configuration

Set the following properties when configuring Crux systems:

.Rocks Configuration
[#table-conversion%header,cols="d,d"]
|===
|Property|Value
|`kv-backend`|`"crux.kv.rocksdb.RocksKv"`
|`db-dir`|i.e. `"data/db-dir-1"`
|===

For example when constructing the standalone system:

[source,clj]
----
include::./examples.clj[tags=start-standalone-with-rocks]
----

== Http

Crux can be used programmatically as a library, but Crux also ships
with an embedded http server, that allows clients to use the API
remotely via REST.

[source,clj]
----
include::./examples.clj[tags=http-setup]
----

Visit the guide on using the <<deployment#rest,REST api>> for examples
of how to interact with Crux over http.

Close the server:

[source,clj]
----
include::./examples.clj[tags=http-close]
----

== Extras

=== Embedded Kafka

Crux has an embedded Kafka that can be used.

Add Kafka and Zookeeper to your project dependencies:

[source,clj,subs="normal"]
----
include::./deps.edn[tags=KakfaDeps]
include::./deps.edn[tags=ZookeeperDeps]

----

See the below example code:

[source,clj]
----
include::./examples.clj[tags=ek-example]
----

You can later stop the Embedded Kafka if you wish:

[source,clj]
----
include::./examples.clj[tags=ek-close]
----
