= Getting Started

== Introduction

Crux can be used in two main configurations: *local node* vs *standalone*. Local node is each Crux instance being a node in a wider cluster, using Kafka for the centralised event log. Standalone is where a single Crux instance has everything it needs locally.

.Crux Configurations
[#table-conversion%header,cols="d,d"]
|===
|Name|Transaction Log
|Local Node|Uses Kakfa
|Standalone|Uses local event log
|===

The Standalone coniguration is good for experimenting with Crux and
for small to medium sized deployments, where running a single instance
is permissable.

The Local Node is for when horizontal scalability of nodes is
required, and for the resiliency and availabilty guarantees that Kafka
offers.

[#standalone]
== Standalone

Using Crux standalone is the best way to get started. Once you've
staredt a standalone Crux instance as described below, you can then
follow the <<user_guide#getting-started-example,getting started
example>>.

=== Project Dependency

To add Crux as a project dependency:

[source,clj]
----
include::./deps.edn[tags=CruxDep]
----

=== Start the standalone system:

NOTE: TODO: rewrite this bit to use the Java API via Clojure interop

[source,clj]
----
include::./examples.clj[tags=start-system]
----

For the purposes of this Hello World, we are using the simplest
configuration of Crux, where all the pluggable components are
in-memory constituents. There is no Kafka or RocksDB to worry about.

The system will contain a `kv-store` that you can use for query purposes:

[source,clj]
----
(:kv-store system)
----

And a `tx-log` that you can use to transact data into Crux:

[source,clj]
----
(:tx-log system)
----

You can later stop the system if you wish:

[source,clj]
----
include::./examples.clj[tags=close-system]
----

== Kafka

When using Crux at scale, it's recommended to configure Crux to use
Kafka.

Crux will use Kafka as a replayable and consumable transaction log,
injesting the documents in order to build local query indices.

You can setup Kafka yourself to run outside of Crux, or Crux ships
with the option of running an embedded Kafka.

If you want to play around with Crux without using Kafka, you can try
using Crux <<#standalone,standalone>> which uses in-memory event logs.

NOTE: TODO Be more explicit local-node (kafka) vs standalone

=== Connecting to Kakfa

To connect to a running Kafka, simply configure the following property:

[source,clj]
----
:bootstrap-servers "localhost:9092"
----

An easy way to fire up a local Kafka and Zookeeper for testing
purposes is via
https://docs.confluent.io/current/installation/docker/docs/installation/single-node-client.html[Confluent's
'single node client' guide]. Note you will need to add an additional
argument when running the Kakfa container: `-p 9092:9092`, and edit
your hosts file with the entry `127.0.0.1 kafka`.

=== Embedded Kafka

Add Kafka and Zookeeper to your project dependencies:

[source,clj,subs="normal"]
----
include::./deps.edn[tags=KakfaDeps]
----

See the below example code:

[source,clj]
----
include::./examples.clj[tags=ek-example]
----

You can later stop the Embedded Kafka if you wish:

[source,clj]
----
include::./examples.clj[tags=ek-close]
----

== Crux Node

By default Crux uses RocksDB as the underlying Key/Value store, that
Crux nodes use to house their query indices.

Therefore, you'll need the Rocks dependency:

[source,clj,subs="normal"]
----
org.rocksdb/rocksdbjni {:mvn/version "5.17.2"}
----

[source,clj]
----
include::./examples.clj[tags=ln-example]
----

As per usual, you can close the local node when you're finished:

[source,clj]
----
include::./examples.clj[tags=ln-close]
----

NOTE: TODO: show how you'd use the in-mem KV to skip rocks, provide a
link in this intro.

== Http

Crux can be used programmatically as a library, but Crux also ships
with an embedded http server, that allows clients to use the API
remotely via REST.

[source,clj]
----
include::./examples.clj[tags=http-setup]
----

Visit the guide on using the <<deployment#rest,REST api>> for examples
of how to interact with Crux over http.

Close the server:

[source,clj]
----
include::./examples.clj[tags=http-close]
----

== Embedded

To see an example of a wired up embedded Crux, see an
https://github.com/juxt/crux/blob/master/docs/example_system.clj[example
Integrant system].

NOTE: TODO, show how to actually use this system (transact and run
queries).

== Configuration

=== K/V Store

Supported KV stores are RocksDB, LMDB and an in-memory store.
