[#getting-started-example]
== Getting Started

This guide contains simple steps showing how to transact data and run a
simple query. However, there are a few topics you might benefit from studying beforehand.

=== Recommended Prerequisites

- Familiarity with *EDN* – the extensible data notation. https://github.com/edn-format/edn[Link].

- A basic understanding of the *Datalog* query language. Crux supports an EDN-flavoured version of Datalog.
  You can find an interactive tutorial for EDN-flavoured Datalog http://www.learndatalogtoday.org/chapter/1[here].

- An understanding of temporality in databases and the significance of <<bitemp#bitemp-why,bitemporality>>.

- Basic understanding of *Clojure* – a succinct and pragmatic data-oriented
  language with strong support for immutability and paralellism. https://clojure.org/[More].


== Setting things up

First setup Crux. If you want to play about, it's advised you run Crux
in a <<setup#standalone,standalone configuration>> first.

=== Write a transaction:

[source,clj]
----
include::./examples.clj[tags=submit-tx]
----
Note that the ID for the Kafka transaction and the ID within the Crux document must be the same. Restating the ID within the Crux document is currently necessary although this may change in the future, as the standard API evolves.

=== Make a query:

[source,clj]
----
include::./examples.clj[tags=query]
----

You should get:

[source,clj]
----
include::./examples.clj[tags=should-get]
----

An entity query would be:
[source,clj]
----
include::./examples.clj[tags=query-entity]
----
You should get:

[source,clj]
----
include::./examples.clj[tags=should-get-entity]
----


== Query

Crux query syntax is that of Datalog using Clojure's EDN, inspired by
Datomic (later adopted by other DBs such as DataScript).

=== Basic Query

[source,clj]
----
include::./examples.clj[tags=query]
----

The `db` is retrieved via a call to `crux.api/db`.




=== Time Queries

`crux.api/db` optionally takes valid time and transaction time as
additional arguments. In the below example we query using valid time
only.

[source,clj]
----
include::./examples.clj[tags=query-valid-time]
----

In the next example we query using both valid time and transaction
time temporal coordinates. This call will block until the local index
has seen the transaction time

[source,clj]
----
include::./examples.clj[tags=query-tx-time]
----

NOTE: TODO: The above doesn't yeild a result

=== Lazy Queries

NOTE: TODO Make an example

The `crux.api/q` takes 2 or 3 arguments, `db` and `q` but also
optionally a `snapshot` which is already opened and managed by the
caller (using `with-open` for example). This version of the call
returns a lazy sequence of the results, while the other version
provides a set. A snapshot can be retreived from a `kv` instance via
`crux.kv-store/new-snapshot`.

=== Rules

Crux query capability is easiest summarized via an example:

[source,clj]
----
(q/q db
    '{:find  [?e2]
      :where [(follow ?e1 ?e2)]
      :args [{:?e1 :1}]
      :rules [[(follow ?e1 ?e2)
              [?e1 :follow ?e2]]
             [(follow ?e1 ?e2)
              [?e1 :follow ?t]
              (follow ?t ?e2)]]})
----

The `:args` key contains a relation where each map is expected to have
the same keys. These keys are turned into logic variable symbols and the
relation is joined with the rest of the query. The elements must
implement `Comparable`.

Crux does not support variables in the attribute position. The entity
position is hard coded to mean the `:crux.db/id` field.

== Transactions

The four transaction (write) operations are as follows:

[source,clojure]
----
[:crux.tx/put :http://dbpedia.org/resource/Pablo_Picasso
"090622a35d4b579d2fcfebf823821298711d3867"
#inst "2018-05-18T09:20:27.966-00:00"]

[:crux.tx/cas :http://dbpedia.org/resource/Pablo_Picasso
"090622a35d4b579d2fcfebf823821298711d3867"
"048ebba27e1da223ce97dded59d46e069ddf921b"
#inst "2018-05-18T09:21:31.846-00:00"]

[:crux.tx/delete :http://dbpedia.org/resource/Pablo_Picasso
#inst "2018-05-18T09:21:52.151-00:00"]

[:crux.tx/evict :http://dbpedia.org/resource/Pablo_Picasso
#inst "2018-05-18T09:21:52.151-00:00"]
----

The valid time is optional and defaults to transaction time, which is
taken from the Kafka log. Crux currently writes into the past at a
single point, so to overwrite several versions or a range in time, one
is required to submit a transaction containing several operations.
Eviction works a bit differently, and all versions at or before the
provided valid time are evicted.

The hashes are the SHA-1 content hash of the documents. Crux uses an
attribute `:crux.db/id` on the documents that has to line up with the id
it is submitted under.

A document looks like this:

[source,clj]
----
{:crux.db/id :http://dbpedia.org/resource/Pablo_Picasso
 :name "Pablo"
 :last-name "Picasso"}
----

In practice when using Crux, one calls `crux.db/submit-tx` with a set of
transaction operations as above, where the hashes are replaced with
actual documents:

[source,clj]
----
[[:crux.tx/put :http://dbpedia.org/resource/Pablo_Picasso
 {:crux.db/id :http://dbpedia.org/resource/Pablo_Picasso
  :name "Pablo"
  :last-name "Picasso"}
 #inst "2018-05-18T09:20:27.966-00:00"]]
----

For each operation the id and the document are hashed, and this version
is submitted to the `tx-topic` in Kafka. The document itself is
submitted to the `doc-topic`, using its content hash as key. This latter
topic is compacted, which enables later deletion of documents.

If the transaction contains CAS operations, all CAS operations must pass
their pre-condition check or the entire transaction is aborted. This
happens at the query node during indexing, and not when submitting the
transaction.

== API

Please consult the JavaDocs for the official Crux API.

https://juxt.pro/crux/docs/javadoc/index.html[API JavaDoc]
