= What is Crux?

Crux is an unbundled, distributed, bi-temporal graph database.

== Unbundled

Crux - to use Martin Kleppmann’s phrase -is is an _unbundled_
database. It's a database turned inside out, using:

* Apache Kafka for the primary store and semi-immutable log.
* RocksDB or LMDB to host indices for rich query support.

== Distributed

Nodes can come and go, with local indices stored in a Key/Value store
such as RocksDB, sharing the master data living in a master event-log
(Kafka is currently supported).

== Bitemporality

Crux is a bitemporal database, storing both valid and transaction
time. This enables corrections in valid time at a later transaction
time. <<bitemp.adoc#,Read more about Bitemporality in Crux.>>

== Query

Crux supports a Datalog query interface for reads. Queries are
executed so that the results are lazily streamed from the underlying
indices.

Crux is ultimately a store of versioned EDN documents. The attributes
of these documents are indexed, allowing for queries.

== Schemaless

Crux does not use a schema for the documents. One reason for this is
that the document data might come from many different places, and not
ultimately be owned by the system using Crux to query the data.

== Eviction

Crux supports eviction of past data, to play nicely with GDRP and
similar concerns.

The main transaction log contains only hashes and is immutable. The
content data itself is stored in a secondary document topic that can
be evicted by compaction.
