= XTQL Transactions

XTQL transactions are submitted through `xtdb.api/submit-tx` (`xtdb.api` aliased here as `xt`).

* `(xt/submit-tx <node> <tx-ops> <opts>?)`: returns the transaction key of the submitted transaction.
** `tx-ops`: vector of link:#tx-ops[transaction operations].
* `(xt/submit-tx& <node> <tx-ops> <opts>?)`: returns a `CompletableFuture` of the transaction key.

XT submit options are an optional map of the following keys:

* `system-time`: overrides system-time for the transaction, mustn't be earlier than any previous system-time.
* `default-tz`: overrides the default time zone for the transaction.

[#tx-ops]
== Transaction operations

=== `put`

Upserts a document into the given table, optionally during the given valid time period.

`(xt/put <table> <document>)`

* `table` (keyword).
* `document` (map): must contain `:xt/id`.

To specify a valid-time range:

* `(-> (xt/put <table> <document>) (xt/starting <from>))`
* `(-> (xt/put <table> <document>) (xt/until <to>))`
* `(-> (xt/put <table> <document>) (xt/during <from> <to))`

where:

* `from` (timestamp): may be `nil`.
    Defaults to the current time of the transaction if not provided.
* `to` (timestamp): may be `nil`.
    Defaults to the end-of-time if not provided.

=== `delete`

Deletes a document from the given table, optionally during the given valid time period.

`(xt/delete <table> <id>)`

See `put` for options.

=== `erase`

Irrevocably erase the document from the given table (including through system time), for all valid-time.

`(xt/erase <table> <id>)`

=== `call`

Call a transaction function.

`(xt/call <fn-id> <args>*)`

Transaction functions are defined using `put-fn`:

[source,clojure]
----
(xt/put-fn :increment
           '(fn [args...]
              ...
              ))
----

Transaction functions are evaluated with the Small Clojure Interpreter (https://github.com/babashka/sci[SCI^]).
They should return a vector of other transaction operations (including invoking other transaction functions).
If they return false, or throw an exception, the transaction will be rolled back.

There are a few functions available in scope during the transaction function:

* `(q <query> <opts>?)` runs an link:./queries[XTQL query]
* `(sql-q <query> <opts>?)`: runs a SQL query.
* `+*current-tx*+`: the current transaction being indexed.
