= Configuration
:toc: macro

toc::[]

[#nodes]
== Nodes

To start a Crux node, use the https://crux-doc.s3.eu-west-2.amazonaws.com/crux-javadoc/20.09-1.11.0/index.html[Java API] or the Clojure https://github.com/juxt/crux/blob/master/crux-core/src/crux/api.clj[`crux.api`].

Within Clojure, we call `start-node` from within `crux.api`, passing it a set of options for the node.
There are a number of different configuration options a Crux node can have, grouped into *topologies*.

=== Crux Topologies
[#table-conversion%header,cols="d,d,d"]
|===
|Name|Transaction Log|Topology
|xref:#standalone[Standalone]|Uses local event log|`:crux.standalone/topology`
|xref:kafka.adoc[Kafka]|Uses Kafka|`:crux.kafka/topology`
|xref:jdbc.adoc[JDBC]|Uses JDBC event log|`:crux.jdbc/topology`
|===

Use a Kafka node when horizontal scalability is required or when you want the guarantees that Kafka offers in terms of resiliency, availability and retention of data.

Multiple Crux nodes participate in a cluster with Kafka as the primary store and as the central means of coordination.

The JDBC node is useful when you don't want the overhead of maintaining a Kafka cluster.
Read more about the motivations of this setup https://juxt.pro/blog/posts/crux-jdbc.html[here].

The Standalone node is a single Crux instance which has everything it needs locally.
This is good for experimenting with Crux and for small to medium sized deployments, where running a single instance is permissible.

Crux nodes implement the `ICruxAPI` interface and are the starting point for making use of Crux.
Nodes also implement `java.io.Closeable` and can therefore be lifecycle managed.

[#properties]
== Properties

The following set of options are used by KV backend implementations, defined within `crux.kv`:

.`crux.kv` options
[#table-conversion%header,cols="d,d,d"]
|===
|Property|Description|Default Value
|`:crux.kv/db-dir` | Directory to store K/V files | *data*
|`:crux.kv/sync?`| Sync the KV store to disk after every write?| *false*
|===


[#standalone]
== Standalone Node

Using a Crux standalone node is the best way to get started.
Once you've started a standalone Crux instance as described below, you can then follow the xref:get-started.adoc[getting started example].

image::local-standalone-mode.svg?sanitize=true[Local Standalone Mode,450,220,align="center"]

.Standalone configuration
[#table-conversion%header,cols="d,d,d"]
|===
|Property|Description|Default Value
|`:crux.standalone/event-log-dir`| Directory used to store the event-log i.e. `"data/event-log-1"`| n/a
|`:crux.standalone/event-log-kv-store` | Key/Value store to use for standalone event-log persistence | *'crux.kv.memdb/kv*
|`:crux.standalone/event-log-sync?` | Sync the event-log backend KV store to disk after every write? | *true*
|===

[#standalone-dependency]
=== Project Dependency

[source,clj]
----
include::example$deps.edn[tags=CruxDep]
----
