= Corda

Development Status: Alpha

A Crux module that allows you to pipe verified https://www.corda.net/[Corda] transactions into a Crux node, to then query using Crux's bitemporal Datalog query engine.

NOTE: For an introduction to Corda, check out the  https://docs.corda.net/docs/corda-os/4.8/tutorials-index.html[tutorials on the Corda site].

== Setup

[tabs]
====
build.gradle.kts::
+
[source,kotlin,subs=attributes+]
----
// Main library
implementation("pro.juxt.crux-labs", "crux-corda", "1.18.2")

// Library for inclusion in contract JARs
implementation("pro.juxt.crux-labs", "crux-corda-state", "1.18.2")
----

pom.xml::
+
[source,xml,subs=attributes+]
----
<dependency>
    <groupId>pro.juxt.crux-labs</groupId>
    <artifactId>crux-corda</artifactId>
    <version>1.18.2</version>
</dependency>

<!-- Library for inclusion in contract JARs -->
<dependency>
    <groupId>pro.juxt.crux-labs</groupId>
    <artifactId>crux-corda-state</artifactId>
    <version>1.18.2</version>
</dependency>
----
====

=== Corda Service

To set up a Crux node within Corda, create a Corda Service:

[source,kotlin]
----
@CordaService
class CruxService(private val serviceHub: AppServiceHub) : SingletonSerializableAsToken() {
    val node = serviceHub.startCruxNode {
        withCordaTxLog { }
        ...
    }
}
----

This is a minimal configuration - see the main xref:configuration.adoc[Crux configuration] documentation for how to further configure the Crux node within the `startCruxNode` block.

== Mapping Corda documents into Crux

By default, any Corda states that implement `crux.corda.state.CruxState` will be indexed into Crux:

[source,kotlin]
----
@BelongsToContract(IOUContract::class)
data class IOUState(val value: Int,
                    val lender: Party,
                    val borrower: Party,
                    override val linearId: UniqueIdentifier = UniqueIdentifier()) :
    LinearState, CruxState {

    override val cruxId = linearId.id

    override val cruxDoc: Map<String, Any> = mapOf(
        "iou-state/value" to value,
        "iou-state/lender" to lender.name.toString(),
        "iou-state/borrower" to borrower.name.toString())
}
----

This mapping can be customised further by overriding the document mapping in the tx-log configuration - providing a function taking each Corda state and returning a collection of `CruxState` objects:

[source,kotlin]
----
@CordaService
class CruxService(private val serviceHub: AppServiceHub) : SingletonSerializableAsToken() {
    val node = serviceHub.startCruxNode {
        withCordaTxLog {
            // This replicates the default behaviour.
            withDocumentMapping { state ->
                if (state is CruxState) listOf(state)
                else null
            }
        }
    }
}
----

In the same way as each Corda node will only see a subset of transactions of the wider Corda network, the Crux node will only be able to index the transactions of its associated Corda node.

== Querying Crux

To access the standard Crux query API, you can make the Crux node available as a field on your Corda service (as above), and then query Crux xref:queries.adoc[as normal].

[source,kotlin]
----
val cruxNode = serviceHub.cordaService(CruxService::class.java).node

cruxNode.db().query("""
    {:find [?l ?b ?v]
     :where [[?iou :iou-state/lender ?l]
             [?iou :iou-state/borrower ?b]
             [?iou :iou-state/value ?v]]}
    """.trimIndent())
----
