= HTTP

Crux offers a REST API layer in the `crux-http-server` module that allows you to send transactions and run queries over HTTP.

image::remote-cluster-mode.svg?sanitize=true[Remote Cluster Mode,450,145,align="centre"]

Using Crux in this manner is a valid use-case but it cannot support all of the features and benefits that running the Crux node inside of your application provides, in particular the ability to efficiently combine custom code with multiple in-process Datalog queries.

Your application only needs to communicate with one Crux node when using the REST API.
Multiple Crux nodes can placed be behind a HTTP load balancer to spread the writes and reads over a horizontally-scaled cluster transparently to the application.
Each Crux node in such a cluster will be independently catching up with the head of the transaction log, and since different queries might go to different nodes, you have to be slightly conscious of read consistency when designing your application to use Crux in this way.
Fortunately, you can readily achieve read-your-writes consistency with the ability to query consistent point-in-time snapshots using specific temporal coordinates.

The REST API also provides an experimental endpoint for SPARQL 1.1 Protocol queries under `/_crux/sparql/`, rewriting the query into the Crux Datalog dialect.
Only a small subset of SPARQL is supported and no other RDF features are available.

[#start-http-server]
== Starting an HTTP Server

=== Project Dependency

[source,clojure, subs=attributes+]
----
juxt/crux-http-server {:mvn/version "{crux_version}-alpha"}
----

You can start up a *HTTP server* on a node by including `crux.http-server/server` in your node configuration, optionally passing the server port:

[tabs]
====
JSON::
+
[source,json]
----
{
  "crux.http-server/server": {
    "port": 3000,
    ...
  }
}
----

Clojure/EDN::
+
[source,clojure]
----
{:crux.http-server/server {:port 3000
                           ...}
----
====

// TODO Authorization section

=== Parameters

* `port` (int, default 3000)
* `read-only?` (boolean, default false): start the HTTP server in read-only mode
* `jwks` (string): https://jwt.io/[JSON Web Token] (JWT) key set to authorise requests against - `{"keys": [...]}`

=== Ring Handler

Crux also exposes a https://github.com/ring-clojure/ring[Ring] handler that you can include within your own Ring-compatible server, with parameters as above:

[source,clojure]
----
(crux.http-server/->crux-handler crux-node {...})
----

[#start-remote-client]
== Using a Remote API Client

In addition to calling the HTTP endpoints directly you can also use the remote API client, which implements the same interfaces/protocols as a local Crux node, where possible.

=== Project Dependency

[source,clojure, subs=attributes+]
----
juxt/crux-http-client {:mvn/version "{crux_version}-beta"}
----

To connect to a pre-existing remote node, you need a URL to the node and the above on your classpath.
We can then call `crux.api/new-api-client`, passing the URL.
If the node was started on `localhost:3000`, you can connect to it by doing the following:

[source,clojure]
----
include::example$src/docs/examples.clj[tags=start-http-client]
----

[#rest-api]
== Using the REST API

All of the REST endpoints return both `application/edn` and https://github.com/cognitect/transit-clj[`application/transit+json`].
Individual endpoints may return additional types - see their docs below.

[#status]
=== GET `/_crux/status`

Returns the current status information of the node.

[source,bash]
----
curl -X GET \
     -H "Content-Type: application/edn" \
     $CRUX_URL/_crux/status
----

[#entity]
=== GET `/_crux/entity`

Returns the document map for a particular entity.

[source,bash]
----
curl -X GET \
     -H "Content-Type: application/edn" \
     $CRUX_URL/_crux/entity?eid-edn=:tommy
----

==== Query Parameters

.*Required Parameters*
* One of the following:
** `eid-edn` (EDN formatted Crux ID)
** `eid` (String IDs)

.*Optional Parameters*
* `valid-time` (date, defaulting to now)
* `transaction-time` (date, defaulting to latest transaction time)

=== GET `/_crux/entity?history=true`

Returns the history of a particular entity.

[source,bash]
----
curl -X GET \
     -H "Content-Type: application/edn" \
     $CRUX_URL/_crux/entity?eid-edn=:tommy&history=true&sort-order=asc
----

==== Query Parameters

.*Required Parameters*
* One of the following:
** `eid-edn` (EDN formatted Crux ID)
** `eid` (String IDs)
* `sort-order` (either `asc` or `desc`)

.*Optional Parameters*
* `with-corrections` (boolean, default false): includes bitemporal corrections in the response, inline, orted by valid-time then transaction-time
* `with-docs` (boolean, default false): includes the documents in the response sequence, under the `:crux.db/doc` key
* `start-valid-time`, `start-transaction-time` (inclusive, default unbounded): bitemporal co-ordinates to start at
* `end-valid-time`, `end-transaction-time` (exclusive, default unbounded): bitemporal co-ordinates to stop at

[#entity-tx]
=== GET `/_crux/entity-tx`

Returns the transaction details for an entity - returns a map containing the tx-id and tx-time.

[source,bash]
----
curl -X GET \
     -H "Content-Type: application/edn" \
     $CRUX_URL/_crux/entity-tx?eid-edn=:tommy
----

==== Query Parameters

.*Required Parameters*
* One of the following:
** `eid-edn` (EDN formatted Crux ID)
** `eid` (String IDs)

.*Optional Parameters*
* `valid-time` (date, defaulting to now)
* `transaction-time` (date, defaulting to latest transaction time)

[#query]
=== GET `/_crux/query`

Takes a datalog query and returns its results. Results are also available in `text/csv` and `text/tsv` formats (can force negotiation of these by using the `/_crux/query.csv` and `/_crux/query.tsv` endpoints respectively).

[source,bash]
----
curl -g \
     -X GET \
     -H "Content-Type: application/edn" \
     $CRUX_URL/_crux/query?query={%3Afind+[e]+%3Awhere+[[e+%3Acrux.db/id+_]]}
----

==== Query Parameters

.*Required Parameters*
* `query` (URL encoded datalog query)

.*Optional Parameters*
* `valid-time` (date, defaulting to now)
* `transaction-time` (date, defaulting to latest transaction time)

[#query]
=== POST `/_crux/query`

Takes a datalog query and returns its results. Results are also available in `text/csv` and `text/tsv` formats (can force negotiation of these by using the `/_crux/query.csv` and `/_crux/query.tsv` endpoints respectively).

[source,bash]
----
curl -g \
     -X POST \
     -H "Content-Type: application/edn" \
     -d '{:query {:find [e] :where [[e :last-name "Petrov"]]}}' \
     $CRUX_URL/_crux/query?valid-time=2019-01-08T16:34:47.738-00:00
----

==== Parameters

===== Body Parameters

.*Required Parameters*
* `query` (URL encoded datalog query)

===== Query Parameters

.*Optional Parameters*
* `valid-time` (date, defaulting to now)
* `transaction-time` (date, defaulting to latest transaction time)


[#attribute-stats]
=== GET `/_crux/attribute-stats`

Returns frequencies of indexed attributes

[source,bash]
----
curl -X GET \
     -H "Content-Type: application/edn" \
     $CRUX_URL/_crux/attribute-stats
----

[#sync]
=== GET `/_crux/sync`

Wait until the Kafka consumer's lag is back to 0 (i.e. when it no longer has pending transactions to write).  Returns the transaction time of the most recent transaction.

[source,bash]
----
curl -X GET \
     -H "Content-Type: application/edn" \
     $CRUX_URL/_crux/sync?timeout=500
----

==== Query Parameters

.*Optional Parameters*
* `timeout` (integer): specified in milliseconds (defaulting to 10 seconds)

[#await-tx]
=== GET `/_crux/await-tx`

Waits until the node has indexed a transaction that is at or past the supplied tx-id. Returns the most recent tx indexed by the node.

[source,bash]
----
curl -X GET \
     -H "Content-Type: application/edn" \
     $CRUX_URL/_crux/await-tx?tx-id=1
----

==== Query Parameters

.*Required Parameters*
* `tx-id` (integer): tx-id of transaction to wait for

.*Optional Parameters*
* `timeout` (integer): specified in milliseconds (defaulting to 10 seconds)

[#await-tx-time]
=== GET `/_crux/await-tx-time`

Blocks until the node has indexed a transaction that is past the supplied tx-time. The returned date is the latest index time when this node has caught up as of this call.

[source,bash]
----
curl -X GET \
     -H "Content-Type: application/edn" \
     $CRUX_URL/_crux/await-tx-time?tx-time=2020-09-10T11%3A16%3A10.983Z
----

==== Query Parameters

.*Required Parameters*
* `tx-time` (date): tx-time of to wait for

.*Optional Parameters*
* `timeout` (integer): specified in milliseconds (defaulting to 10 seconds)

[#tx-log]
=== GET `/_crux/tx-log`

Returns a list of all transactions, from oldest to newest transaction time - optionally including documents.

[source,bash]
----
curl -X GET $CRUX_URL/_crux/tx-log
----

==== Query Parameters

.*Optional Parameters*
* `after-tx-id` (integer, default unbounded): transaction id to start after.
* `with-ops?` (boolean, defaults to false): should the operations with documents be included?

[#submit-tx]
=== POST `/_crux/submit-tx`

Takes a vector of transactions (any combination of `:put`, `:delete`, `:match`, and `:evict`) and executes them in order. This is the only "write" endpoint.

[source,bash]
----
curl -X POST \
     -H "Content-Type: application/edn" \
     -d '[[:crux.tx/put {:crux.db/id :ivan, :name "Ivan" :last-name "Petrov"}],
          [:crux.tx/put {:crux.db/id :boris, :name "Boris" :last-name "Petrov"}],
          [:crux.tx/delete :maria  #inst "2012-05-07T14:57:08.462-00:00"]]' \
     $CRUX_URL/_crux/submit-tx
----

=== GET `/_crux/tx-committed`

Checks if a submitted tx was successfully committed, returning a map with tx-committed and either `true` or `false` (or a `NodeOutOfSyncException` exception response if the node has not yet indexed the transaction).

[source,bash]
----
curl -X GET \
     -H "Content-Type: application/edn" \
     $CRUX_URL/_crux/tx-committed?tx-id=1
----

==== Query Parameters

.*Required Parameters*
* `tx-id` (integer): tx-id of transaction to check


=== GET `/_crux/latest-completed-tx`

Returns the latest transaction to have been indexed by this node.

[source,bash]
----
curl -X GET \
     -H "Content-Type: application/edn" \
     $CRUX_URL/_crux/latest-completed-tx
----

=== GET `/_crux/latest-submitted-tx`

Returns the latest transaction to have been submitted to this cluster.

[source,bash]
----
curl -X GET \
     -H "Content-Type: application/edn" \
     $CRUX_URL/_crux/latest-submitted-tx
----

=== GET `/_crux/active-queries`

Returns a list of currently running queries.

[source,bash]
----
curl -X GET \
     -H "Content-Type: application/edn" \
     $CRUX_URL/_crux/active-queries
----

=== GET `/_crux/recent-queries`

Returns a list of recently completed/failed queries.

[source,bash]
----
curl -X GET \
     -H "Content-Type: application/edn" \
     $CRUX_URL/_crux/recent-queries
----

=== GET `/_crux/slowest-queries`

Returns a list of slowest completed/failed queries ran on the node.

[source,bash]
----
curl -X GET \
     -H "Content-Type: application/edn" \
     $CRUX_URL/_crux/slowest-queries
----
