= Installation

Crux nodes can be xref:#embedded[embedded within your JVM application], or they can be started standalone through a xref:#uberjar[pre-built Crux JAR], via xref:#docker[Docker], or using xref:#clojure-cli[Clojure CLI tooling].

This guide will show you how to set up an in-memory node using the `crux-core` module.
You can then proceed to add further modules (eg for persistence) as required - see the documentation of the individual modules for more information.

[#project-dependency]
== Project dependency

Crux depends on Java 8+.

[tabs]
====
deps.edn::
+
[source,clojure, subs=attributes+]
----
pro.juxt.crux/crux-core {:mvn/version "{crux_version}"}
----
pom.xml::
+
[source,xml,subs=attributes+]
----
<dependency>
    <groupId>pro.juxt.crux</groupId>
    <artifactId>crux-core</artifactId>
    <version>{crux_version}</version>
</dependency>
----
====

[#embedded]
== Within your JVM application

First, add the `crux-core` module as a project dependency.
We can then start up an in-memory Crux node with:

[tabs]
====
Clojure::
+
[source,clojure]
----
(require '[crux.api :as crux])

(crux/start-node {})
----

Java::
+
[source,java]
----
include::example$test/crux/docs/Install.java[tag=imports]

include::example$test/crux/docs/Install.java[tag=main-0,indent=0]
include::example$test/crux/docs/Install.java[tag=main-1,indent=0]
----

Kotlin::
+
[source,kotlin]
----
include::example$test/crux/docs/Install.kt[tag=imports]

include::example$test/crux/docs/Install.kt[tag=main,indent=0]
----
====

[#uberjar]
== Using a pre-built Crux JAR

You can start a standalone Crux node, accessible through HTTP, using a pre-built Crux JAR.
Crux pre-built JARs can be found on the relevant https://github.com/juxt/crux/releases[GitHub releases,window=_blank] page - we'll use `crux-in-memory.jar`.

Start it in the usual way, with `java -jar crux-in-memory.jar`.
This will open an HTTP port with a console UI on port 3000 - open http://localhost:3000[window=_blank] in your favourite browser.

// TODO crux-build needs its own pages in the main docs, not just a blog
You can also build custom Crux JARs with your choice of modules - see the https://juxt.pro/blog/crux-build[Crux build,window=_blank] blog for more details.

[#docker]
== Via Docker

You can also start a standalone Crux node using Docker, using:

`docker run -p 3000:3000 juxt/crux-in-memory:1.18.2`

Again, this opens up an HTTP server at http://localhost:3000[window=_blank].

Likewise, you can build custom Crux Docker images - see the https://juxt.pro/blog/crux-build[Crux build,window=_blank] blog for more details.

[#clojure-cli]
== Clojure CLI tooling

Similarly, to start Crux using Clojure's CLI tooling:

[tabs]
====
deps.edn::
+
[source,clojure, subs=attributes+]
----
{:deps {org.clojure/clojure {:mvn/version "1.10.3"}

        pro.juxt.crux/crux-core {:mvn/version "{crux_version}"}
        pro.juxt.crux/crux-http-server {:mvn/version "{crux_version}"}}}
----
====

[tabs]
====
crux.edn::
+
[source,clojure]
----
{:crux.http-server/server {:port 3000}}
----
====

Then, start the node with `clojure -m crux.main`.

You can get a listing of CLI flags using `clojure -m crux.main -h`.
