= Installation

Crux nodes can be xref:#embedded[embedded within your JVM application], or they can be started standalone through a xref:#uberjar[pre-built Crux JAR], via xref:#docker[Docker], or using xref:#clojure-cli[Clojure CLI tooling].


This guide will show you how to set up an in-memory node using the `crux-core` module.
You can then proceed to add further modules (eg for persistence) as required - see the documentation of the individual modules for more information.

[#project-dependency]
== Project dependency

Crux depends on Java 8+.

.deps.edn
[source,clojure]
----
include::example$deps.edn[tags=CruxDep,indent=0]
----

.pom.xml
[source,xml]
----
include::example$maven.xml[indent=0]
----

[#embedded]
== Within your JVM application

First, add the `crux-core` module as a project dependency.
We can then start up an in-memory Crux node with:

.Clojure
[source,clojure]
----
(require '[crux.api :as crux])

(crux/start-node {})
----

.Java
[source,java]
----
include::example$src/docs/Install.java[tags=imports]

include::example$src/docs/Install.java[tags=main,indent=0]
----

[#uberjar]
== Using a pre-built Crux JAR

You can start a standalone Crux node, accessible through HTTP, using a pre-built Crux JAR.
Crux pre-built JARs can be found on the relevant https://github.com/juxt/crux/releases[GitHub releases,window=_blank] page - we'll use `crux-in-memory.jar`.

Start it in the usual way, with `java -jar crux-in-memory.jar`.
This will open an HTTP port with a console UI on port 3000 - open http://localhost:3000[window=_blank] in your favourite browser.

// TODO crux-build needs its own pages in the main docs, not just a blog
You can also build custom Crux JARs with your choice of modules - see the https://juxt.pro/blog/crux-build[Crux build,window=_blank] blog for more details.

[#docker]
== Via Docker

You can also start a standalone Crux node using Docker, using:

`docker run -p 3000:3000 juxt/crux-in-memory:20.09-1.11.0`

Again, this opens up an HTTP server at http://localhost:3000[window=_blank].

Likewise, you can build custom Crux Docker images - see the https://juxt.pro/blog/crux-build[Crux build,window=_blank] blog for more details.

[#clojure-cli]
== Clojure CLI tooling

Similarly, to start Crux using Clojure's CLI tooling:

.deps.edn
[source,clojure]
----
{:deps {org.clojure/clojure {:mvn/version "1.10.1"}

        juxt/crux-core {:mvn/version "20.09-1.11.0-beta"}
        juxt/crux-http-server {:mvn/version "20.09-1.11.0-alpha"}}}
----

.crux.edn
[source,clojure]
----
{:crux.http-server/server {:port 3000}}
----

Then, start the node with `clojure -m crux.main`.

You can get a listing of CLI flags using `clojure -m crux.main -h`.
