= JDBC Nodes

Crux nodes can use JDBC databases to store their transaction logs and/or document stores.

image::jdbc-modes.svg?sanitize=true[Local Cluster Mode,450,480,align="center"]

== Project Dependencies

[tabs]
====
deps.edn::
+
[source,clojure, subs=attributes+]
----
juxt/crux-jdbc {:mvn/version "{crux_version}-beta"}
----

pom.xml::
+
[source,xml, subs=attributes+]
----
<dependency>
    <groupId>juxt</groupId>
    <artifactId>crux-jdbc</artifactId>
    <version>{crux_version}-beta</version>
</dependency>
----
====

== Example configuration

JDBC transaction logs and document stores depend on a 'connection pool' component - if you use both, they can share the same connection pool.

Connection pools require a JDBC 'dialect' - out of the box, Crux supports the following:

[#dialects]
* H2: `+crux.jdbc.h2/->dialect+`
* MySQL: `+crux.jdbc.mysql/->dialect+`
* Microsoft SQL Server: `+crux.jdbc.mssql/->dialect+`
* Oracle: `+crux.jdbc.oracle/->dialect+`
* PostgreSQL: `+crux.jdbc.psql/->dialect+`
* SQLite: `+crux.jdbc.sqlite/->dialect+`

Each of these also require an additional dependency to pull in the relevant JDBC driver - see the Crux JDBC https://github.com/juxt/crux/blob/master/crux-jdbc/project.clj[project.clj] for our latest dependencies.

[#db-spec]
The connection pool also requires a `db-spec` - a map containing either a full `jdbcUrl` or its component parts, including `dbtype` (provided by the dialect by default), `host`, `port`, `dbname`.
Any other attributes supplied (`user`, `password`, say) are appended to the URL as query parameters - see your individual JDBC driver for full details.

[#pool-opts]
Crux uses https://github.com/brettwooldridge/HikariCP[HikariCP] to provide connection pools.
You can pass options directly to https://javadoc.io/static/com.zaxxer/HikariCP/3.2.0/com/zaxxer/hikari/HikariConfig.html[`HikariConfig`] via `pool-opts` - for example, to `setMaximumPoolSize`, add `maximumPoolSize` to your configuration.

=== JDBC as a Transaction Log

[tabs]
====
JSON::
+
[source,json]
----
{
  "crux/tx-log": {
    "crux/module": "crux.jdbc/->tx-log",
    "connection-pool": {
      "dialect": {
        "crux/module": "crux.jdbc.psql/->dialect"
      },
      "pool-opts": { ... },
      "db-spec": { ... }
    },

    "poll-sleep-duration": "PT1S"
  },

  ...
}
----

Clojure::
+
[source,clojure]
----
{:crux/tx-log {:crux/module 'crux.jdbc/->tx-log
               :connection-pool {:dialect {:crux/module 'crux.jdbc.psql/->dialect}
                                 :pool-opts { ... }
                                 :db-spec { ... }}
               :poll-sleep-duration (Duration/ofSeconds 1)}
 ...}
----

EDN::
+
[source,clojure]
----
{:crux/tx-log {:crux/module crux.jdbc/->tx-log
               :connection-pool {:dialect {:crux/module crux.jdbc.psql/->dialect}
                                 :pool-opts { ... }
                                 :db-spec { ... }}
               :poll-sleep-duration "PT1S"}
 ...}
----
====

=== JDBC as a Document Store

[tabs]
====
JSON::
+
[source,json]
----
{
  "crux/document-store": {
    "crux/module": "crux.jdbc/->document-store",
    "connection-pool": {
      "dialect": {
        "crux/module": "crux.jdbc.psql/->dialect"
      },
      "pool-opts": { ... },
      "db-spec": { ... }
    }
  },

  ...
}
----

Clojure::
+
[source,clojure]
----
{:crux/document-store {:crux/module 'crux.jdbc/->document-store
                       :connection-pool {:dialect {:crux/module 'crux.jdbc.psql/->dialect}
                                         :pool-opts { ... }
                                         :db-spec { ... }}}
 ...}
----

EDN::
+
[source,clojure]
----
{:crux/document-store {:crux/module crux.jdbc/->document-store
                       :connection-pool {:dialect {:crux/module crux.jdbc.psql/->dialect}
                                         :pool-opts { ... }
                                         :db-spec { ... }}}
 ...}
----
====

=== Sharing connection pools

If you use JDBC for both the transaction log and document store, you can share the same connection pool between the two modules as follows:

[tabs]
====
JSON::
+
[source,json]
----
{
  "crux.jdbc/connection-pool": {
    "dialect": {
      "crux/module": "crux.jdbc.psql/->dialect"
    },
    "pool-opts": { ... },
    "db-spec": { ... }
  },


  "crux/document-store": {
    "crux/module": "crux.jdbc/->document-store",
    "connection-pool": "crux.jdbc/connection-pool"
  },

  "crux/tx-log": {
    "crux/module": "crux.jdbc/->tx-log",
    "connection-pool": "crux.jdbc/connection-pool"
  },

  ...
}
----

Clojure::
+
[source,clojure]
----
{:crux.jdbc/connection-pool {:dialect {:crux/module 'crux.jdbc.psql/->dialect}
                             :pool-opts { ... }
                             :db-spec { ... }}
 :crux/tx-log {:crux/module 'crux.jdbc/->tx-log
               :connection-pool :crux.jdbc/connection-pool}
 :crux/document-store {:crux/module 'crux.jdbc/->document-store
                       :connection-pool :crux.jdbc/connection-pool}
 ...}
----

EDN::
+
[source,clojure]
----
{:crux.jdbc/connection-pool {:dialect {:crux/module crux.jdbc.psql/->dialect}
                             :pool-opts { ... }
                             :db-spec { ... }}
 :crux/tx-log {:crux/module crux.jdbc/->tx-log
               :connection-pool :crux.jdbc/connection-pool}
 :crux/document-store {:crux/module crux.jdbc/->document-store
                       :connection-pool :crux.jdbc/connection-pool}
 ...}
----
====

== Parameters

=== Connection pool (`+crux.jdbc/->connection-pool+`)

* `dialect` (dialect, required): JDBC xref:#dialects[dialect]
* `pool-opts` (map): see xref:#pool-opts[above]
* `db-spec` (map, required): see xref:#db-spec[above]


=== Transaction log (`+crux.jdbc/->tx-log+`)

* `connection-pool`
* `poll-sleep-duration` (string/`Duration`, default 100 milliseconds, `"PT0.1S"`): time to sleep between each poll, if the previous poll didn't yield any transactions.

=== Document store (`+crux.jdbc/->document-store+`)

* `connection-pool`
* `cache-size` (int): size of in-memory document cache
