= Lucene

Lucene module for Crux making use of https://lucene.apache.org/[Apache Lucene].

Note: This module is in alpha and likely to change.

== Setup

`crux-lucene` runs in-process as part of the Crux node as a Crux module.

First, add the `crux-lucene` dependency to your project:

[tabs]
====
deps.edn::
+
[source,clojure, subs=attributes+]
----
juxt/crux-lucene {:mvn/version "{crux_version}-alpha"}
----

pom.xml::
+
[source,xml, subs=attributes+]
----
<dependency>
    <groupId>juxt</groupId>
    <artifactId>crux-lucene</artifactId>
    <version>{crux_version}-alpha</version>
</dependency>
----
====


Add the following to your node configuration:

[tabs]
====
JSON::
+
[source,json]
----
{
  "crux.lucene/lucene-store": {
        "db-dir": "lucene",
  }
}
----

Clojure::
+
[source,clojure]
----
{...
 :crux.lucene/lucene-store {:db-dir "lucene-dir"}}
----

EDN::
+
[source,clojure]
----
{...
 :crux.lucene/lucene-store {:db-dir "lucene-dir"}}
----
====

== Querying

All text fields in a document will be automatically indexed. You can
then you use the in-built `text-search` fn in your datalog:

[source,clojure]
----
{:find '[?e]
 :where '[[(text-search :name "Ivan") [[?e]]]
 [?e :crux.db/id]]}
----

The destructuring available is `entity-id`, `matched-value` and
`score`. For example, to return the full search results tuple:

[source,clojure]
----
{:find '[?e ?v ?s]
 :where '[[(text-search :name "Ivan") [[?e ?v ?s]]]
 [?e :crux.db/id]]}
----

You can use standard Lucene search capabilities:

[source,clojure]
----
{:find '[?e]
 :where '[[(text-search :name "Iva*") [[?e]]]
 [?e :crux.db/id]]}
----

Will return all entities that with a `:name` that starts with
"Iva". See the Lucene documentation for more information.

You can search across all attributes:

[source,clojure]
----
{:find '[?e ?v ?a ?s]
 :where '[[(wildcard-text-search "Iva*") [[?e ?v ?a ?s]]]
 [?e :crux.db/id]]}
----

Will return all entities that have an attribute with a value that
matches "Iva". The destructured binding also contains `a` which is the
attribute.
