= AWS S3

You can use AWS's Simple Storage Service (S3) as XTDB's 'document store'.

== Project Dependency

In order to use S3 within XTDB, you must first add S3 as a project dependency:

[tabs]
====
deps.edn::
+
[source,clojure, subs=attributes+]
----
com.xtdb/xtdb-s3 {:mvn/version "{xtdb_version}"}
----

pom.xml::
+
[source,xml, subs=attributes+]
----
<dependency>
    <groupId>com.xtdb</groupId>
    <artifactId>xtdb-s3</artifactId>
    <version>{xtdb_version}</version>
</dependency>
----
====

== Using S3

Replace the implementation of the document store with `+xtdb.s3/->document-store+`

[tabs]
====
JSON::
+
[source,json]
----
{
  "xtdb/document-store": {
    "xtdb/module": "xtdb.s3/->document-store",
    "bucket": "your-bucket",
    ...
  },
}
----

Clojure::
+
[source,clojure]
----
{:xtdb/document-store {:xtdb/module 'xtdb.s3/->document-store
                       :bucket "your-bucket"
                       ...}}
----

EDN::
+
[source,clojure]
----
{:xtdb/document-store {:xtdb/module xtdb.s3/->document-store
                       :bucket "your-bucket"
                       ...}}
----
====

== Parameters

* `configurator` (xref:#configurator[`S3Configurator`])
* `bucket` (string, required)
* `prefix` (string): S3 key prefix
* `cache-size` (int): size of in-memory document cache

[#checkpoint-store]
== Checkpoint store

S3 can be used as a query index xref:checkpointing.adoc[checkpoint store].

Checkpoints aren't GC'd by XTDB - we recommend you set a lifecycle policy on your bucket to remove older checkpoints.

[source,clojure]
----
;; under :xtdb/index-store -> :kv-store -> :checkpointer
;; see the Checkpointing guide for other parameters
{:checkpointer {...
                :store {:xtdb/module 'xtdb.s3.checkpoint-store/->checkpoint-store
                        :configurator ...
                        :bucket "..."
                        :prefix "..."}}
----

=== Parameters

* `configurator` (xref:#configurator[`S3Configurator`])
* `bucket` (string, required)
* `prefix` (string): S3 key prefix

[#configurator]
== Configuring S3 requests

WARNING: This is unfortunately currently only accessible from Clojure - we plan to expose it outside of Clojure soon.

While the above is sufficient to get `xtdb-s3` working out of the box, there are a plethora of configuration options in S3 - how to get credentials, object properties, serialisation of the documents, etc.
We expose these via the https://github.com/xtdb/xtdb/blob/main/modules/s3/src/xtdb/s3/S3Configurator.java[`xtdb.s3.S3Configurator`] interface - you can supply an instance using the following in your node configuration.

Through this interface, you can supply an `S3AsyncClient` for xtdb-s3 to use, adapt the `PutObjectRequest`/`GetObjectRequest` as required, and choose the serialisation format.
By default, we get credentials through the usual AWS credentials provider, and store documents using https://github.com/ptaoussanis/nippy[Nippy].

[tabs]
====
Clojure::
+
[source,clojure]
----
{:xtdb/document-store {:xtdb/module 'xtdb.s3/->document-store
                       :configurator (fn [_]
                                       (reify S3Configurator
                                         ...)
                       ...}}
----
====
