= Transactions (Java)

[#overview]
== Overview

A transaction is performed by passing calling `.submitTx` on an `ICruxIngestAPI` with a `Transaction` object.

The `Transaction` object can be created by either using `Transaction.Builder` directly or using a `Consumer`.

If using the `Consumer` approach, we recommend importing `crux.api.tx.Transaction.buildTx` statically for brevity.

[source,java]
----
include::example$test/crux/docs/examples/transactions/TransactionsTest.java[tags=creating-0,indent=0]

include::example$test/crux/docs/examples/transactions/TransactionsTest.java[tags=creating-1,indent=0]

include::example$test/crux/docs/examples/transactions/TransactionsTest.java[tags=creating-2,indent=0]

// To run the transaction:
include::example$test/crux/docs/examples/transactions/TransactionsTest.java[tags=using-0,indent=0]

// To run a transaction directly:
include::example$test/crux/docs/examples/transactions/TransactionsTest.java[tags=using-1,indent=0]
----

If the transaction contains pre-conditions, all pre-conditions must pass, or the
entire transaction is aborted. This happens at the query node during indexing,
and not when submitting the transaction.

[#operations]
== Operations
There are five transaction (write) operations:

.Write Operations
[cols="3,5,^2"]
|===
|Operation|Purpose|Pre-condition?

|<<#put, Put>>|Write a version of a document|
|<<#delete, Delete>>|Deletes a specific document|
|<<#match, Match>>|Check the document state against the given document|✓
|<<#evict, Evict>>|Evicts a document entirely, including all historical versions|
|<<#function, Function>>|Runs a transaction function|✓
|===

[#put]
=== Put

Put's a <<#document, Document>> into Crux. If a document already exists with the same `id`, a new version of this document will be created at the supplied `valid time`. See <<transactions.adoc#valid-time, Valid Time>> for more details.

[source,java]
----
include::example$test/crux/docs/examples/transactions/TransactionsTest.java[tags=put,indent=0]
----
<1> Putting a document as of now.
<2> Putting a document with a specific <<transactions.adoc#valid-time, valid time>>
<3> Putting a document with a <<transactions.adoc#valid-time, valid time>> and <<transactions.adoc#end-valid-time, end valid time>>

[#delete]
=== Delete

Deletes a <<#document, Document>> . See <<transactions.adoc#valid-time,Valid Time>> for details on how this interacts with multiple versions of the document.

[source,java]
----
include::example$test/crux/docs/examples/transactions/TransactionsTest.java[tags=delete,indent=0]
----

<1> Deletes as of now
<2> Deleting with a specific <<transactions.adoc#valid-time, valid time>>
<3> Deleting with a <<transactions.adoc#valid-time, valid time>> and <<transactions.adoc#end-valid-time, end valid time>>

[#match]
=== Match

Match checks the state of an entity - if the entity doesn't match the provided doc, the transaction will not continue.

[source,java]
----
include::example$test/crux/docs/examples/transactions/TransactionsTest.java[tags=match,indent=0]
----

<1> Passes if `document1` is exactly present now
<2> Passes if `document2` is exactly present at <<valid-time,`validTime1`>>
<3> Passes if there is no document with the id `documentId1` present now
<4> Passes if there is no document with the id `documentId2` present at <<valid-time,`validTime2`>>
<5> Operation(s) to apply if all preconditions are met

[#evict]
=== Evict

Evicts a document from Crux. Historical versions of the document will no longer be available.

[source,java]
----
include::example$test/crux/docs/examples/transactions/TransactionsTest.java[tags=evict,indent=0]
----

Evict is primarily used for GDPR Right to Erasure compliance.

It is important to note that Evict is the only operation which will have effects on the results returned when querying against an earlier Transaction Time.

[#function]
=== Transaction Functions

Transaction functions are user-supplied functions that run on the individual Crux nodes when a transaction is being ingested.

Transaction functions can be used, for example, to safely check the current database state before applying a transaction, for integrity checks, or to patch an entity.

Currently, only functions written in Clojure are supported, although they can be created and used from Java.

==== Creating / Updating

Transaction functions are created/updated by submitting a CruxDocument created with `CruxDocument.createFunction`.

It takes the ID for the function as well as a string consisting of the Clojure function to run.

For information about creating these functions, see <<transactions-clojure#transaction-functions-anatomy, the Clojure docs entry>>.

[source,java]
----
include::example$test/crux/docs/examples/transactions/TransactionsTest.java[tags=fn-put,indent=0]
----

==== Usage

When invoking a transaction function, you specify its ID and (optionally) other arguments
[source,java]
----
include::example$test/crux/docs/examples/transactions/TransactionsTest.java[tags=fn-use,indent=0]
----

[#document]
== Documents

A `CruxDocument` is created with an ID that must be of a <<#valid-ids,valid type>>.

The instance itself is immutable and putting/removing data yields a new instance of `CruxDocument`.

Similarly to Transactions, you can use `CruxDocument.Builder` directly or use the `Consumer` approach.
[source,java]
----
include::example$test/crux/docs/examples/transactions/TransactionsTest.java[tags=doc-builder,indent=0]

include::example$test/crux/docs/examples/transactions/TransactionsTest.java[tags=doc-consumer,indent=0]

// You can also chain creating new instances of the document, but this will be slow for larger documents.
include::example$test/crux/docs/examples/transactions/TransactionsTest.java[tags=doc-direct,indent=0]
----

[#valid-ids]
=== Valid IDs

The following types of document IDs are allowed:

.Valid ID types
[cols="d,d"]
|===
|Type|Example

|Keyword|`Keyword.intern("my-id")`
|String|`"my-id"`
|Integer/Long|`42`
|UUID|`UUID.randomUUID()`
|URI|`URI.create("mailto:crux@juxt.pro")`
|URL|`new URL("https://github.com/juxt/crux")`
|IPersistentMap|`PersistentArrayMap.EMPTY.assoc("foo", "bar")`
|===

[#speculative-transactions]
== Speculative transactions

You can submit speculative transactions to Crux, to see what the results of your queries would be if a new transaction were to be applied.
This is particularly useful for forecasting/projections or further integrity checks, without persisting the changes or affecting other users of the database.

You'll receive a new database value, against which you can make queries and entity requests as you would any normal database value.
Only you will see the effect of these transactions - they're not submitted to the cluster, and they're not visible to any other database value in your application.

We submit these transactions to a database value using `withTx`:

[source,java]
----
include::example$test/crux/docs/examples/transactions/TransactionsTest.java[tags=with-tx,indent=0]
----

The entities submitted by the speculative Put take their valid time (if not explicitly specified) from the valid time of the `db` from which they were forked.